/* ---------- the Grounds (the Grid) ---------- */
function pitchOutline(opts={}){const ball=opts.ball&&!RM?`<g class="ball"><ellipse rx="16" ry="10" transform="rotate(-25)"/><animateMotion dur="7s" repeatCount="indefinite" begin="${opts.delay||0}s" path="M60 300 Q 250 90 440 300"/></g>`:'';
  return `<svg viewBox="0 0 500 500" aria-hidden="true" preserveAspectRatio="xMidYMid meet" class="pitch-o">${pitchLines()}${ball}</svg>`;}
/* one pitch, drawn from the same lines everywhere: goal lines at 68 and 432, 22s at 148 and 352, 10s dashed, halfway at 250 */
function pitchLines(tintL,tintR){return `<rect class="fld" x="20" y="135" width="460" height="230" rx="6"/><rect class="ig" x="20" y="135" width="48" height="230"${tintL?` style="fill:${tintL};opacity:.16"`:''}/><rect class="ig" x="432" y="135" width="48" height="230"${tintR?` style="fill:${tintR};opacity:.16"`:''}/><g class="ln">${[68,148,219,250,281,352,432].map(x=>`<line x1="${x}" y1="139" x2="${x}" y2="361"${x===219||x===281?' stroke-dasharray="8 8"':''}${x===250?' class="half"':''}/>`).join('')}<rect x="20" y="135" width="460" height="230" rx="6" class="edge"/></g><g class="posts"><path d="M68 190v120M46 190v120M46 262h22"/><path d="M432 190v120M454 190v120M432 262h22"/></g>`;}
function groundModel(){const ms=eraMatches();const m={};for(const r of ms){if(!r.recorded)continue;let c=m[r.stadium]||(m[r.stadium]={cid:r.stadium,count:0,first:r.year,last:r.year,wins:{},name:groundName(r.stadium),country:GROUNDS[r.stadium].country,place:GROUNDS[r.stadium].city});c.count++;c.first=Math.min(c.first,r.year);c.last=Math.max(c.last,r.year);if(r.winner)c.wins[r.winner]=(c.wins[r.winner]||0)+1;}
  return Object.values(m).map(c=>({...c,top:Object.entries(c.wins).sort((a,b)=>b[1]-a[1])[0]?.[0]||null}));}
function drawGrid(){const list=groundModel();const q=state.gridFind.trim().toLowerCase();const unrec=eraMatches().filter(m=>!m.recorded).length;let shown=list.filter(c=>(q||c.count>=state.gridMin)&&(!q||(c.name+' '+c.country+' '+c.place).toLowerCase().includes(q)));
  const sorters={count:(a,b)=>b.count-a.count||a.name.localeCompare(b.name),name:(a,b)=>a.name.localeCompare(b.name),country:(a,b)=>a.country.localeCompare(b.country)||b.count-a.count,recent:(a,b)=>b.last-a.last||b.count-a.count};shown.sort(sorters[state.gridSort]);
  const bigN=state.gridSort==='count'&&!q?6:0;
  $('#gridLede').textContent=`${list.length} grounds have staged a Test in ${eraLabel().replace(' · ',', ')}${unrec?`; ${unrec.toLocaleString('en')} more matches have no ground recorded`:''}. Each carries the colour of the nation that has won there most; the largest cards are the grounds Test rugby has returned to most often.${shown.length<list.length&&!q?` Showing ${shown.length} with ${state.gridMin}+ Tests.`:''}`;
  $('#circuits').innerHTML=shown.map((c,i)=>`<button type="button" class="circ flat${i<bigN?' big':''}" data-cid="${esc(c.cid)}" style="${c.top?teamVar(c.top):'--team:#8b9099'}" title="${esc(c.name)} · ${c.count} Tests · ${c.first}–${c.last}${c.top?' · most wins: '+esc(c.top):''}"><span class="ct">${esc(c.country)}${c.place&&c.place!==c.country?' · '+esc(c.place):''}</span><span class="n">${c.count}</span><span class="nm">${esc(c.name)}</span><span class="yrs">${c.first}${c.last!==c.first?'–'+c.last:''}${c.top?' · <i style="background:var(--team)"></i>'+esc(c.top)+' '+c.wins[c.top]:''}</span></button>`).join('')||`<p class="muted">No ground matches.</p>`;}

/* ---------- Stage: tabs, era strip, era context ---------- */
const TABS=[['season','Season'],['match','Match'],['nations','Nations'],['players','Players'],['grounds','Grounds'],['coaches','Coaches'],['records','Records'],['barcode','Barcode'],['duel','Duel']];
function drawTabs(){$('#tabs').innerHTML=TABS.map(([id,l])=>`<button type="button" role="tab" data-tab="${id}" aria-pressed="${state.tab===id}">${l}</button>`).join('');
  $('#stageStatus').textContent=(state.tab==='season'||state.tab==='match')&&!state.whole?`${state.year} · ${eraOf(state.year)?.name||''}`:eraLabel();}
function drawEraStrip(preview){const strip=$('#eraStrip');if(!strip.children.length)strip.innerHTML=ERAS.map(e=>`<button type="button" style="--w:${e.to-e.from+1}" data-era="${e.id}" title="${esc(e.name)} · ${e.from}–${e.to}" aria-label="${esc(e.name)} ${e.from}–${e.to}"></button>`).join('');
  for(const b of strip.children){b.classList.toggle('on',state.era===b.dataset.era);b.classList.toggle('demo',preview===b.dataset.era);}
  const e=preview?ERAS.find(x=>x.id===preview):state.era==='all'?eraOf(state.year):ERAS.find(x=>x.id===state.era);
  $('#eraCaption').innerHTML=`<span><b>${esc(e.name)}</b> · ${e.from}–${e.to}</span><span class="dim">${state.era===e.id?'Lens on · click again to release':'Click a segment to focus the whole page on that era'}</span>`;
  const ctx=$('#eraContext');ctx.innerHTML=`<div class="era-car">${e.ball.svg}</div><div><p class="eyebrow">${state.era===e.id?'Era lens':preview?'Era':'Era of the selected season'} · ${e.from}–${e.to}</p><h3>${esc(e.name)}</h3><p>${esc(e.text)}</p><div class="chips">${e.ball.features.map(f=>`<span>${esc(f)}</span>`).join('')}</div><p class="small dim" style="margin:10px 0 0">${esc(e.ball.label)} · as applied by this archive’s scoring table; a value with an arrow changed inside the era</p></div>`;}
const tour={i:-1,timer:null,visible:false,stopped:RM};
function tourStep(){if(tour.stopped||!tour.visible)return;tour.i=(tour.i+1)%ERAS.length;const ctx=$('#eraContext');ctx.classList.add('swap');setTimeout(()=>{if(tour.stopped)return;drawEraStrip(ERAS[tour.i].id);ctx.classList.remove('swap');},260);tour.timer=setTimeout(tourStep,4200);}
function tourStart(){if(tour.stopped||tour.timer)return;tour.timer=setTimeout(tourStep,1800);}
function tourPause(){clearTimeout(tour.timer);tour.timer=null;}
function tourStop(){if(tour.stopped)return;tour.stopped=true;tourPause();$('#eraContext').classList.remove('swap');drawEraStrip();}

/* ---------- shared pieces ---------- */
const resClass=(m,side)=>m.draw?'D':m.winner===side?'W':'L';
const scoreOf=(m,side)=>side===m.home?`${m.hs}–${m.as}`:`${m.as}–${m.hs}`;
const compShort=m=>m.worldcup?`RWC ${m.worldcup}${m.stage?' · '+m.stage:''}`:m.competition==='Six / Five / Home Nations'?'Championship':m.competition==='Rugby Championship / Tri Nations'?'Rugby Championship':m.competition==='Lions series'?'Lions':m.competition==='Historical / Olympic'?'Historical':m.competition==='Nations Championship'?'Nations Championship':'Test';
function matchCard(m,on){const w=m.winner;return `<button type="button" class="cal${on?' on':''}" data-match="${m.id}" style="${w?teamVar(w):'--team:#5b616b'}"><div class="rd">${esc(dm(m.date))} · ${esc(compShort(m))}${m.historical?' †':''}</div><div class="sc"><span>${esc(code(m.home))}</span><b>${m.hs}–${m.as}</b><span>${esc(code(m.away))}</span></div><div class="nm">${esc(m.home)} v ${esc(m.away)}</div><div class="w">${w?esc(w)+' won':'drawn'}${m.recorded?' · '+esc(groundName(m.stadium)):''}</div></button>`;}
function natBars(rows,valOf,subOf,max,unit=''){return `<div class="board">${rows.map((a,i)=>`<button type="button" class="bar" data-nation="${esc(a.id)}" style="--i:${i};${teamVar(a.id)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(a.id)}<small> ${a.w}–${a.l}–${a.d}</small></span><small>${subOf(a)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*valOf(a)/(max||1))}%"></span></span></span><span class="val">${valOf(a)}${unit}</span></button>`).join('')}</div>`;}
function drawChart(el,series,n,labelOf,xl){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(200,box.height);const padL=34,padR=110,padT=14,padB=26;const max=Math.max(1,...series.flatMap(s=>s.pts));const x=i=>padL+(n?i*(W-padL-padR)/n:0),y=v=>padT+(H-padT-padB)*(1-v/max);
  let g='';const step=max>200?100:max>60?25:max>20?10:max>8?5:1;for(let v=0;v<=max;v+=step)g+=`<line class="gridl" x1="${padL}" x2="${W-padR}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}"/><text class="lb" x="${padL-6}" y="${(y(v)+3).toFixed(1)}" text-anchor="end">${v}</text>`;
  for(let i=0;i<n;i++){const l=xl(i);if(l)g+=`<text class="lb" x="${x(i+1).toFixed(1)}" y="${H-8}" text-anchor="middle">${esc(l)}</text>`;}
  const paths=series.map(s=>{const d=s.pts.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1)).join('');const last=s.pts[s.pts.length-1];return `<path class="ser" d="${d}" style="--c:${color(s.id)}"><title>${esc(labelOf(s.id))} · ${fmt(last)}</title></path><text class="end" x="${(x(n)+6).toFixed(1)}" y="${(y(last)+4).toFixed(1)}" style="--c:${color(s.id)}">${esc(labelOf(s.id))} ${fmt(last)}</text>`;}).join('');
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Cumulative wins">${g}${paths}</svg>`;}

/* ---------- Season ---------- */
function seasonView(){if(state.whole)return eraView();const s=byYear[state.year];const ms=s.matches;const st=natStats(ms);const maxP=Math.max(...st.map(a=>a.p));const ranked=st.filter(a=>a.p>=Math.min(3,maxP)).sort((a,b)=>b.rate-a.rate||b.w-a.w||b.margin-a.margin);const table=[...st].sort((a,b)=>b.rate-a.rate||b.w-a.w||b.margin-a.margin);
  const {best,cup}=champOf(s);const partial=String(s.year)===(A.through||'').slice(0,4);const nations=st.length,grounds=new Set(ms.filter(m=>m.recorded).map(m=>m.stadium)).size;
  const podium=ranked.slice(0,3);const order=[podium[1],podium[0],podium[2]];
  const head=`<div class="season-head"><div class="champ-card" style="${best?`--accent:${color(best.id)};--on-accent:${onColor(color(best.id))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${partial?'Season in progress · results through '+esc(day(A.through)):'Best record of the year'}</p><div class="yr">${s.year}</div>${best?`<div class="who"><small>${partial?'Leads the year':'Best record'} · ${best.w}–${best.l}–${best.d}</small>${esc(best.id)}</div><div class="team"><i></i>${esc(nat(best.id).nickname||nat(best.id).tag||'')}</div><div class="facts"><div><b>${best.rate}%</b>win rate</div><div><b>${best.p}</b>Tests</div><div><b>${ms.length}</b>Tests this year</div><div><b>${nations}</b>nations</div></div>`:'<div class="who">No results yet</div>'}${cup?`<p class="small" style="margin:18px 0 0;color:var(--ink);opacity:.85">World Cup: <b>${esc(cup.winner)}</b> beat ${esc(cup.final.loser)} ${esc(scoreOf(cup.final,cup.winner))} in the final</p>`:''}<p class="small dim" style="margin:${cup?6:18}px 0 0">Ranked by win rate, then wins, among sides with ${Math.min(3,maxP)}+ Tests in the year.</p></div>
  <div><div class="podium">${order.map((d,i)=>d?`<button type="button" class="step p${podium.indexOf(d)+1} bar" data-nation="${esc(d.id)}" style="--h:${Math.round(120+120*d.rate/100)}px;${teamVar(d.id)};display:flex"><span class="pos">${podium.indexOf(d)+1}</span><span class="nm">${esc(d.id)}</span><span class="pt">${d.w}–${d.l}–${d.d} · ${d.rate}% · ${d.p} Tests</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const cal=`<div class="h3"><span>The year’s Tests</span><small>${ms.length} matches · click one to open it</small></div><div class="calendar">${ms.map(m=>matchCard(m,state.match===m.id&&state.tab==='match')).join('')}</div>`;
  const big=[...ms].filter(m=>m.points&&!m.draw).sort((a,b)=>b.margin-a.margin||b.total-a.total).slice(0,10);
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Table of the year</span><small>every side that played · win rate, then wins</small></div>${natBars(table,a=>a.rate,a=>`${a.p} Tests · ${a.np?'avg margin '+(a.margin>0?'+':'')+a.margin:'goals era'}`,100,'%')}</div><div class="panel"><div class="h3"><span>Biggest wins of the year</span><small>by margin, points era</small></div><div class="board">${big.map((m,i)=>`<button type="button" class="bar" data-match="${m.id}" style="--i:${i};${teamVar(m.winner)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(m.winner)}<small> v ${esc(m.loser)}</small></span><small>${esc(dm(m.date))} · ${esc(compShort(m))}${m.recorded?' · '+esc(groundName(m.stadium)):''}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*m.margin/(big[0].margin||1))}%"></span></span></span><span class="val">${esc(scoreOf(m,m.winner))}</span></button>`).join('')||'<p class="muted small">No points-era results.</p>'}</div></div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>The year, Test by Test</span><small>cumulative wins, top ${Math.min(8,st.length)} sides</small></div><div class="chart" id="cumChart"></div></div>`;
  $('#view').innerHTML=head+cal+body;
  const top=[...st].sort((a,b)=>b.w-a.w||b.rate-a.rate).slice(0,8);const series=top.map(a=>({id:a.id,pts:[0]}));for(const m of ms)for(const sr of series)sr.pts.push(sr.pts[sr.pts.length-1]+(m.winner===sr.id?1:0));
  let lastMon='';drawChart($('#cumChart'),series,ms.length,x=>x,i=>{const mon=ms[i].date.slice(5,7);if(mon===lastMon)return '';lastMon=mon;return new Date(ms[i].date+'T12:00:00Z').toLocaleDateString('en-GB',{month:'short',timeZone:'UTC'});});}

/* ---------- Whole era, combined ---------- */
function eraView(){const seasons=eraSeasons();const ms=eraMatches();const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);const label=e?e.name:'All eras';const span=`${seasons[0].year}–${seasons[seasons.length-1].year}`;
  const st=natStats(ms);const ranked=st.filter(a=>a.p>=10).sort((a,b)=>b.rate-a.rate||b.w-a.w);const byWins=[...st].sort((a,b)=>b.w-a.w||b.rate-a.rate);
  const bests={};const roll=seasons.map(s=>{const c=champOf(s);if(c.best)bests[c.best.id]=(bests[c.best.id]||0)+1;return {year:s.year,d:c.best?.id,rec:c.best?`${c.best.w}–${c.best.l}–${c.best.d}`:'',cup:c.cup?.winner,n:s.matches.length};});
  const cups=ms.filter(m=>m.stage==='Final');const grounds=new Set(ms.filter(m=>m.recorded).map(m=>m.stadium)).size;
  const podium=ranked.slice(0,3);const order=[podium[1],podium[0],podium[2]];const top=ranked[0];
  const head=`<div class="season-head"><div class="champ-card" style="${top?`--accent:${color(top.id)};--on-accent:${onColor(color(top.id))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">Whole era, combined · ${seasons.length} seasons</p><div class="yr" style="font-size:clamp(44px,6vw,84px)">${span}</div><div class="who"><small>${esc(label)} · best record</small>${esc(top?top.id:'—')}</div><div class="team"><i></i>${top?`${top.w}–${top.l}–${top.d} · ${top.rate}% of ${top.p} Tests`:''}</div><div class="facts"><div><b>${fmt(ms.length)}</b>Tests</div><div><b>${st.length}</b>sides</div><div><b>${grounds}</b>grounds</div><div><b>${cups.length}</b>World Cup finals</div></div><p class="small" style="margin:18px 0 0;color:var(--ink);opacity:.85">Most wins: <b>${esc(byWins[0]?.id||'—')}</b> · ${byWins[0]?.w||0} Tests won${Object.keys(bests).length?`<br><span class="dim">Best record of the year most often: ${esc(Object.entries(bests).sort((a,b)=>b[1]-a[1])[0][0])} (${Object.entries(bests).sort((a,b)=>b[1]-a[1])[0][1]} years)</span>`:''}</p></div>
  <div><div class="podium">${order.map(d=>d?`<button type="button" class="step p${podium.indexOf(d)+1} bar" data-nation="${esc(d.id)}" style="--h:${Math.round(120+120*d.rate/100)}px;${teamVar(d.id)};display:flex"><span class="pos">${podium.indexOf(d)+1}</span><span class="nm">${esc(d.id)}</span><span class="pt">${d.rate}% · ${d.w}–${d.l}–${d.d}</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const rollHtml=`<div class="h3"><span>Best record, year by year</span><small>click a year to open it</small></div><div class="calendar">${roll.map(c=>`<button type="button" class="cal" data-year="${c.year}" style="${c.d?teamVar(c.d):'--team:#5b616b'}"><div class="rd">${c.year} · ${c.n} Tests</div><div class="nm" style="font-size:16px;margin-top:10px;color:var(--team)">${esc(c.d||'—')}</div><div class="w" style="color:var(--muted)">${c.rec}</div><div class="w">${c.cup?'⚑ '+esc(c.cup):''}</div></button>`).join('')}</div>`;
  const pl=PLAYERS.filter(p=>p.startYear<=seasons[seasons.length-1].year&&p.endYear>=seasons[0].year).sort((a,b)=>(b.caps||0)-(a.caps||0)).slice(0,20);
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Nations across the era</span><small>by wins · ${st.length} sides</small></div>${natBars(byWins.slice(0,20),a=>a.w,a=>`${a.rate}% of ${a.p} Tests`,byWins[0]?.w)}</div><div class="panel"><div class="h3"><span>Careers across the era</span><small>most caps among careers overlapping ${span}</small></div><div class="board">${pl.map((p,i)=>`<button type="button" class="bar" data-player="${esc(p.id)}" style="--i:${i};${teamVar(p.team)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(p.name)}<small> ${esc(p.team)}</small></span><small>${esc(p.span)}${p.tries?' · '+p.tries+' tries':''}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*p.caps/(pl[0]?.caps||1))}%"></span></span></span><span class="val">${p.caps}</span></button>`).join('')}</div></div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Wins, season by season</span><small>cumulative Test wins, top ${Math.min(8,byWins.length)} by wins</small></div><div class="chart" id="cumChart"></div></div>`;
  $('#view').innerHTML=head+rollHtml+body;
  const series=byWins.slice(0,8).map(a=>({id:a.id,pts:[0]}));for(const s of seasons)for(const sr of series){let w=0;for(const m of s.matches)if(m.winner===sr.id)w++;sr.pts.push(sr.pts[sr.pts.length-1]+w);}
  drawChart($('#cumChart'),series,seasons.length,x=>x,i=>seasons.length<=20||i%Math.ceil(seasons.length/14)===0?String(seasons[i].year).slice(2):'');}
function eraMatchesView(){const ms=eraMatches();$('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Every Test · ${esc(eraLabel())}</span><small>${fmt(ms.length)} matches · click one to open it</small></div><div class="tablewrap"><table><tr><th>Date</th><th>Home</th><th>Score</th><th>Away</th><th>Competition</th><th>Ground</th></tr>${ms.slice().reverse().slice(0,1200).map(m=>`<tr><td><a href="#" data-match="${m.id}" style="color:inherit">${esc(day(m.date))}</a></td><td><i class="dot" style="${teamVar(m.home)}"></i>${esc(m.home)}</td><td><b>${m.hs}–${m.as}</b>${m.scoreUnit==='goals'?' <span class="dim">goals</span>':''}</td><td><i class="dot" style="${teamVar(m.away)}"></i>${esc(m.away)}</td><td>${esc(compShort(m))}${m.historical?' †':''}</td><td>${m.recorded?`<a href="#" data-ground="${esc(m.stadium)}" style="color:inherit">${esc(groundName(m.stadium))}</a>`:'<span class="dim">not recorded</span>'}</td></tr>`).join('')}</table></div>${ms.length>1200?`<p class="small dim">Showing the most recent 1,200 of ${fmt(ms.length)}; narrow the era lens or open a season for the rest.</p>`:''}`;}
