/* ---------- Match: the sheet and the symbolic replay ---------- */
let replay=null;
function stopReplay(){if(replay){replay.timers.forEach(clearTimeout);replay=null;}}
function pitchEvents(m){const v=PTS(m.year);const mk=(side,off)=>{const ev=[];const push=(kind,n,pts)=>{for(let i=0;i<n;i++)ev.push({side,kind,pts});};if(m.scoring){const sc=m.scoring;push('try',sc[off],v.try);push('ptry',sc[off+5],v.ptry);push('con',sc[off+1],v.con);push('pen',sc[off+2],v.pen);push('drop',sc[off+3],v.drop);}
    else{/* no breakdown recorded: pace the scoreboard in plausible steps, drawn as plain marks */let rest=side==='home'?m.hs:m.as;while(rest>0){const step=rest>=v.try+v.con&&Math.random()<.6?v.try+v.con:rest>=v.try?v.try:rest>=v.pen?v.pen:rest;push('score',1,step);rest-=step;}}return ev;};
  const h=mk('home',0),a=mk('away',6);const out=[];let i=0,j=0;while(i<h.length||j<a.length){if(j>=a.length||(i<h.length&&i/h.length<=j/a.length))out.push(h[i++]);else out.push(a[j++]);}return out;}
function pitchSheet(m){const ev=pitchEvents(m);const hc=color(m.home),ac=color(m.away);let ch=0,ca=0,ih=0,ia=0;const known=!!m.scoring;
  const marks=ev.map((e,k)=>{const home=e.side==='home';const idx=home?ih++:ia++;const c=home?hc:ac;const y=150+((idx*37)%180);let x,shape;
    if(e.kind==='try'||e.kind==='ptry'){x=home?440+(idx*9)%30:60-(idx*9)%30;shape=`<ellipse cx="${x}" cy="${y}" rx="11" ry="7" fill="${e.kind==='ptry'?'none':c}" stroke="${c}" stroke-width="2.5" transform="rotate(-30 ${x} ${y})"/>`;}
    else if(e.kind==='con'){x=home?400-(idx*9)%40:100+(idx*9)%40;shape=`<path d="M${x} ${y+9}l7-18" stroke="${c}" stroke-width="3" fill="none"/><circle cx="${x+7}" cy="${y-9}" r="3" fill="${c}"/>`;}
    else if(e.kind==='pen'){x=home?330-(idx*13)%90:170+(idx*13)%90;shape=`<path d="M${x} ${y+10}v-20" stroke="${c}" stroke-width="3.5"/><path d="M${x-6} ${y-10}h12" stroke="${c}" stroke-width="3.5"/>`;}
    else if(e.kind==='drop'){x=home?370-(idx*15)%60:130+(idx*15)%60;shape=`<path d="M${x} ${y-9}l8 9-8 9-8-9z" fill="${c}"/>`;}
    else{x=home?250+40+(idx*23)%150:250-40-(idx*23)%150;shape=`<circle cx="${x}" cy="${y}" r="5" fill="${c}" opacity=".8"/>`;}
    if(home)ch+=e.pts;else ca+=e.pts;return `<g class="ev" data-k="${k}" data-h="${ch}" data-a="${ca}" style="animation-delay:${RM?0:k*.55+.4}s"><title>${esc(home?m.home:m.away)} · ${e.kind==='try'?'try':e.kind==='ptry'?'penalty try':e.kind==='con'?'conversion':e.kind==='pen'?'penalty goal':e.kind==='drop'?'drop goal':'score'} · +${e.pts}</title>${shape}</g>`;}).join('');
  return `<div class="replay" id="replay"><div class="hud"><div><h3>${esc(m.home)} v ${esc(m.away)}</h3><div class="sub">${esc(day(m.date))} · ${esc(compShort(m))}${m.recorded?' · '+esc(groundName(m.stadium)):''}</div></div><div class="whistle" aria-hidden="true">FT</div></div>
  <div class="track pitchwrap"><svg viewBox="0 120 500 260" class="pitch-o big" role="img" aria-label="Symbolic scoring map">${pitchLines(hc,ac)}<text x="26" y="357" class="igl">${esc(code(m.home))} in-goal</text><text x="474" y="357" class="igl" text-anchor="end">${esc(code(m.away))} in-goal</text><g id="pitchEvents">${marks}</g></svg></div>
  <div class="pitchscore"><span style="color:${hc}">${esc(m.home)}</span><b id="psH">0</b><i>–</i><b id="psA">0</b><span style="color:${ac}">${esc(m.away)}</span><button type="button" class="btn" id="pitchReplay">↻ Replay</button></div>
  <p class="small dim" style="margin:10px 0 0">${known?'A symbolic build of the scoreboard from the recorded breakdown — balls are tries (hollow: penalty tries), placed in the in-goal they were scored in; flags conversions, posts penalties, diamonds drop goals. The order of events is not recorded; the values are those of '+m.year+'.':'No scoring breakdown is recorded for this Test, so the scoreboard builds in symbolic steps of '+m.year+'’s values; the marks carry no meaning beyond pace.'}${m.scoreUnit==='goals'?' Scores before 1886 count goals.':''}</p></div>`;}
function runPitch(){stopReplay();const evs=$$('#pitchEvents .ev');const h=$('#psH'),a=$('#psA');if(!evs.length)return;const rp={timers:[]};replay=rp;const set=k=>{h.textContent=evs[k].dataset.h;a.textContent=evs[k].dataset.a;if(k===evs.length-1)$('#replay').classList.add('done');};
  const play=()=>{rp.timers.forEach(clearTimeout);rp.timers=[];$('#replay').classList.remove('done');evs.forEach(e=>{e.style.animation='none';e.offsetHeight;e.style.animation='';});h.textContent='0';a.textContent='0';evs.forEach((e,k)=>rp.timers.push(setTimeout(()=>set(k),RM?0:k*550+700)));};
  play();$('#pitchReplay').onclick=play;}
function h2hBefore(m){const ms=MATCHES.filter(x=>x.id<m.id&&plays(x,m.home)&&plays(x,m.away));const st=natStats(ms);const a=st.find(x=>x.id===m.home),b=st.find(x=>x.id===m.away);return {n:ms.length,a,b};}
function matchView(){if(state.whole)return eraMatchesView();const s=byYear[state.year];let m=byId[state.match];if(!m||m.year!==s.year)m=s.matches[s.matches.length-1];state.match=m.id;
  const nav=`<div class="chiplist" style="margin-top:20px">${s.matches.map(x=>`<button type="button" class="chip${x.id===m.id?' on':''}" data-match="${x.id}" style="${x.id===m.id?'border-color:var(--accent);color:var(--accent)':''}"><i style="--c:${x.winner?color(x.winner):'#444'}"></i>${esc(dm(x.date))} ${esc(code(x.home))}–${esc(code(x.away))}</button>`).join('')}</div>`;
  const line=side=>{const rows=(gamesByMatch[m.id]||[]).filter(x=>x.p.team===side).sort((p,q)=>(p.g.position==='Reserve')-(q.g.position==='Reserve')||p.p.name.localeCompare(q.p.name));if(!rows.length)return '';return `<div class="h3" style="margin-top:20px"><span>${esc(side)} · line-up</span><small>${rows.length} recorded appearances</small></div><div class="tower"><div class="th"><span>#</span><span></span><span>Player</span><span style="text-align:center"></span><span style="text-align:right"></span><span style="text-align:right">Tries</span><span style="text-align:right">Scoring</span></div>${rows.map((x,i)=>`<div class="tr" style="--i:${i};${teamVar(side)}"><span class="pos">${x.p.number||i+1}</span><span class="code">${esc(code(side))}</span><span class="name"><a href="#" data-player="${esc(x.p.id)}" style="color:inherit;text-decoration:none">${esc(x.p.name)}</a><small>${esc(x.g.position||'')}</small></span><span></span><span></span><span class="pts">${x.g.tries||''}</span><span class="st">${esc(x.g.scoring||'')}</span></div>`).join('')}</div>`;};
  const hh=h2hBefore(m);const form=side=>{const prev=MATCHES.filter(x=>x.id<m.id&&plays(x,side)).slice(-10);return `<div class="ribbon">${prev.map(x=>`<i class="${resClass(x,side)}" title="${esc(day(x.date))} v ${esc(x.home===side?x.away:x.home)} ${esc(scoreOf(x,side))}" data-match="${x.id}"></i>`).join('')}</div>`;};
  const side=`<div><div class="h3"><span>Before kick-off</span><small>the record between these two</small></div><div class="kpis" style="grid-template-columns:1fr 1fr"><div class="kpi" style="border-color:${color(m.home)}"><span>${esc(m.home)}</span><b>${hh.a?hh.a.w:0}</b><small>wins in ${hh.n} previous meetings${hh.a?' · form '+'':''}</small>${form(m.home)}</div><div class="kpi" style="border-color:${color(m.away)}"><span>${esc(m.away)}</span><b>${hh.b?hh.b.w:0}</b><small>wins in ${hh.n} previous meetings${hh.a&&hh.a.d?' · '+hh.a.d+' drawn':''}</small>${form(m.away)}</div></div><p class="small dim" style="margin:8px 0 0">Each side’s last ten Tests before this one: green won, red lost, grey drawn.</p>${line(m.home)}${line(m.away)}</div>`;
  const meta=`<div class="kpis" style="margin-top:18px"><div class="kpi"><span>Date</span><b style="font-size:22px">${esc(day(m.date))}</b><small>${m.dateUncertain?'date uncertain in source':esc(m.competitionRaw||'')}</small></div><div class="kpi"><span>Ground</span><b style="font-size:22px">${m.recorded?`<a href="#" data-ground="${esc(m.stadium)}" style="color:inherit;text-decoration:none">${esc(groundName(m.stadium))}</a>`:'Not recorded'}</b><small>${esc([m.city,m.country].filter(Boolean).join(', ')||'—')}</small></div><div class="kpi"><span>Competition</span><b style="font-size:22px">${esc(compShort(m))}</b><small>${esc(m.stage||m.competition)}${m.historical?' · historical recognition †':''}</small></div><div class="kpi"><span>Margin</span><b>${m.draw?'Draw':'+'+m.margin}</b><small>${m.draw?'':esc(m.winner)+' · '}${m.total} ${m.scoreUnit}</small></div><div class="kpi"><span>Nations</span><b style="font-size:22px"><a href="#" data-nation="${esc(m.home)}" style="color:inherit;text-decoration:none">${esc(code(m.home))}</a> · <a href="#" data-nation="${esc(m.away)}" style="color:inherit;text-decoration:none">${esc(code(m.away))}</a></b><small>open a nation</small></div></div>`;
  const links=`<p class="small dim" style="margin-top:14px">${(m.sources||[]).slice(0,3).map(u=>`<a href="${esc(u)}" target="_blank" rel="noopener">${esc(u.replace(/^https?:\/\//,'').split('/')[0])} ↗</a>`).join(' · ')}${m.notes&&m.notes.length?' · '+esc(m.notes.join(' ')):''}</p>`;
  $('#view').innerHTML=`${nav}<div class="race">${pitchSheet(m)}${side}</div>${meta}${links}`;runPitch();}

/* ---------- Nations ---------- */
function radar(el,axes,a,b){const W=260,H=260,cx=130,cy=130,R=96,n=axes.length;const pt=(i,v)=>{const ang=-Math.PI/2+i*2*Math.PI/n;return [cx+Math.cos(ang)*R*v,cy+Math.sin(ang)*R*v];};
  let g='';for(const k of [.25,.5,.75,1])g+=`<polygon class="ring" points="${axes.map((_,i)=>pt(i,k).map(v=>v.toFixed(1)).join(',')).join(' ')}"/>`;for(let i=0;i<n;i++){const [x,y]=pt(i,1);g+=`<line class="axis" x1="${cx}" y1="${cy}" x2="${x.toFixed(1)}" y2="${y.toFixed(1)}"/>`;const [lx,ly]=pt(i,1.24);g+=`<text class="lbl" x="${lx.toFixed(1)}" y="${(ly+3).toFixed(1)}">${esc(axes[i].label)}</text>`;}
  const poly=(vals,cls)=>`<polygon class="poly ${cls}" points="${vals.map((v,i)=>pt(i,Math.max(0,Math.min(1,v))).map(q=>q.toFixed(1)).join(',')).join(' ')}"/>`;el.innerHTML=`<svg viewBox="0 0 ${W} ${H}">${g}${poly(a,'a')}${b?poly(b,'b'):''}</svg>`;}
const AXES=[{k:'w',label:'Wins'},{k:'rate',label:'Win %'},{k:'p',label:'Tests'},{k:'ppm',label:'Pts / Test'},{k:'marginPos',label:'Margin'},{k:'homeRate',label:'Home %'},{k:'streak',label:'Best run'}];
function normAxes(list){const max={};for(const ax of AXES)max[ax.k]=Math.max(1,...list.map(a=>ax.k==='marginPos'?Math.max(0,a.margin):a[ax.k]));return a=>AXES.map(ax=>(ax.k==='marginPos'?Math.max(0,a.margin):a[ax.k])/max[ax.k]);}
function nationsView(){const ms=eraMatches();const list=natStats(ms);const lens=state.lens;const min=/rate|ppm|margin/.test(lens)?10:0;const rows=list.filter(a=>a.p>=min).sort((a,b)=>b[lens]-a[lens]||b.w-a.w).slice(0,30);const max=Math.max(1,...rows.map(a=>Math.abs(a[lens])));const q=(state.find2||'').toLowerCase();
  const found=q?list.filter(a=>a.id.toLowerCase().includes(q)).slice(0,12):[];
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Nations · ${esc(eraLabel())}</span><small>${list.length} sides · ${fmt(ms.length)} Tests</small></div><div class="panel"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:14px"><input type="search" id="find2" placeholder="Search a nation" value="${esc(state.find2||'')}" aria-label="Search"><select id="lens" aria-label="Lens">${Object.entries(LENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(LENSES[lens][1])}</span></div>${q?`<div class="chiplist" style="margin-bottom:14px">${found.map(a=>`<button type="button" class="chip" data-nation="${esc(a.id)}"><i style="--c:${color(a.id)}"></i>${esc(a.id)}</button>`).join('')||'<span class="muted small">No match.</span>'}</div>`:''}
  ${natBars(rows,a=>a[lens],a=>`${a.p} Tests · ${a.first}–${a.last}`,max,/rate/.test(lens)?'%':'')}</div>`;}
function seasonsTable(id){const out=[];for(const s of S){const ms=s.matches.filter(m=>plays(m,id));if(!ms.length)continue;const a=natStats(ms).find(x=>x.id===id);out.push({year:s.year,...a});}return out;}
function nationView(id){const ms=eraMatches();const all=natStats(ms);const a=all.find(x=>x.id===id);const back=`<button type="button" class="btn" data-tab="nations">← All nations</button>`;const t=nat(id);
  if(!a){$('#view').innerHTML=`<div style="margin-top:22px">${back}</div><p class="muted" style="margin-top:16px">${esc(id)} played no Test in ${esc(eraLabel())}. Change the era lens to see them.</p>`;return;}
  const mine=ms.filter(m=>plays(m,id));const norm=normAxes(all.filter(x=>x.p>=10));
  const ribbon=mine.map(m=>`<i class="${resClass(m,id)}" title="${esc(day(m.date))} v ${esc(m.home===id?m.away:m.home)} ${esc(scoreOf(m,id))}" data-match="${m.id}"></i>`).join('');
  const opp={};for(const m of mine){const o=m.home===id?m.away:m.home;let r=opp[o]||(opp[o]={id:o,p:0,w:0,d:0,l:0});r.p++;if(m.draw)r.d++;else if(m.winner===id)r.w++;else r.l++;}const opps=Object.values(opp).sort((a,b)=>b.p-a.p);
  const tbl=seasonsTable(id).filter(x=>inEraYear(x.year));const cups=mine.filter(m=>m.worldcup);const cupYears=[...new Set(cups.map(m=>m.worldcup))];const camp=cupYears.map(y=>{const cm=cups.filter(m=>m.worldcup===y);const last=cm[cm.length-1];const won=last.stage==='Final'&&last.winner===id;return {y,n:cm.length,w:cm.filter(m=>m.winner===id).length,last,won,exit:won?'Champions':last.stage==='Final'?'Runners-up':last.stage==='Bronze final'?(last.winner===id?'Third':'Fourth'):last.stage||'Pool'};});
  const coaches=COACHES.filter(c=>c.team===id&&c.endYear>=eraRange()[0]&&c.startYear<=eraRange()[1]);const players=PLAYERS.filter(p=>p.team===id&&p.endYear>=eraRange()[0]&&p.startYear<=eraRange()[1]).sort((a,b)=>(b.caps||0)-(a.caps||0)).slice(0,12);
  $('#view').innerHTML=`<div style="margin-top:22px;display:flex;gap:10px;flex-wrap:wrap;align-items:center">${back}<span class="small muted">${esc(eraLabel())}</span></div>
  <div class="card" style="margin-top:18px;${teamVar(id)}"><div class="panel"><div class="trace" id="trace"></div><p class="small dim" style="text-align:center;margin:8px 0 0">Form trace · each axis relative to the best side in this era lens (10+ Tests)</p></div>
  <div><p class="eyebrow">${t.ten?'Nation':'Opponent'} · ${a.first}–${a.last}${t.nickname?' · '+esc(t.nickname):''}</p><h2 class="display" style="font-size:clamp(40px,6vw,84px);margin:6px 0 0;color:var(--team);text-shadow:0 0 30px rgba(255,255,255,.18)">${esc(id)}</h2>${t.tag?`<p class="muted" style="margin:4px 0 0">${esc(t.tag)}${t.titles.length?' · world champions '+t.titles.join(', '):''}</p>`:''}
  <div class="kpis" style="margin-top:18px"><div class="kpi"><span>Tests</span><b>${a.p}</b><small>${a.w}–${a.l}–${a.d}</small></div><div class="kpi"><span>Win rate</span><b>${a.rate}%</b><small>draws count as not won</small></div><div class="kpi"><span>Points</span><b>${fmt(a.pf)}</b><small>${fmt(a.pa)} against · ${a.np} points-era Tests</small></div><div class="kpi"><span>Avg margin</span><b>${a.margin>0?'+':''}${a.margin}</b><small>per points-era Test</small></div><div class="kpi"><span>At home</span><b>${a.homeRate}%</b><small>${a.hw} of ${a.home} home Tests</small></div><div class="kpi"><span>Best run</span><b>${a.streak}</b><small>consecutive wins</small></div><div class="kpi"><span>World Cups</span><b>${a.cups}</b><small>${camp.length} campaign${camp.length===1?'':'s'} in lens</small></div></div>
  <div class="h3" style="margin-top:20px"><span>Every Test</span><small>green won · red lost · grey drawn · click to open</small></div><div class="ribbon">${ribbon}</div>
  ${coaches.length?`<div class="h3" style="margin-top:20px"><span>Coaches</span></div><div class="chiplist">${coaches.map(c=>`<button type="button" class="chip" data-coach="${esc(c.id)}"><i style="--c:${color(id)}"></i>${esc(c.name)} <span class="dim">${esc(c.tenure)}</span></button>`).join('')}</div>`:''}</div></div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Record by opponent</span><small>most met first</small></div>${natBars(opps.slice(0,16),r=>r.w,r=>`${r.p} Tests · ${pct(r.w,r.p)}% won`,Math.max(1,...opps.map(r=>r.w)))}</div><div class="panel">${players.length?`<div class="h3"><span>Careers</span><small>most caps · careers overlapping the lens</small></div><div class="board">${players.map((p,i)=>`<button type="button" class="bar" data-player="${esc(p.id)}" style="--i:${i};${teamVar(id)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(p.name)}<small> ${esc(p.position||'')}</small></span><small>${esc(p.span)}${p.tries?' · '+p.tries+' tries':''}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*p.caps/(players[0].caps||1))}%"></span></span></span><span class="val">${p.caps}</span></button>`).join('')}</div>`:''}${camp.length?`<div class="h3" style="margin-top:${players.length?16:0}px"><span>World Cup campaigns</span></div><div class="tablewrap"><table><tr><th>Year</th><th>Played</th><th>Won</th><th>Ended</th><th>Last match</th></tr>${camp.map(c=>`<tr><td>${c.y}</td><td>${c.n}</td><td>${c.w}</td><td>${c.won?'<b style="color:var(--gold)">Champions ★</b>':esc(c.exit)}</td><td><a href="#" data-match="${c.last.id}" style="color:inherit">${esc(scoreOf(c.last,id))} v ${esc(c.last.home===id?c.last.away:c.last.home)}</a></td></tr>`).join('')}</table></div>`:''}${!players.length&&!camp.length?'<p class="muted small">No career or World Cup records in this lens.</p>':''}</div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Season by season</span></div><div class="tablewrap"><table><tr><th>Year</th><th>P</th><th>W</th><th>D</th><th>L</th><th>Win %</th><th>For</th><th>Against</th><th>Best result</th></tr>${tbl.slice().reverse().map(x=>`<tr><td><a href="#" data-year="${x.year}" style="color:inherit">${x.year}</a></td><td>${x.p}</td><td>${x.w}</td><td>${x.d}</td><td>${x.l}</td><td>${x.rate}%</td><td>${x.np?x.pf:'—'}</td><td>${x.np?x.pa:'—'}</td><td>${x.big?`<a href="#" data-match="${x.big.id}" style="color:inherit">${esc(scoreOf(x.big,id))} v ${esc(x.big.home===id?x.big.away:x.big.home)}</a>`:'—'}</td></tr>`).join('')}</table></div></div>`;
  radar($('#trace'),AXES,norm(a));}

/* ---------- Players ---------- */
function playerPool(){if(state.era==='all')return PLAYERS;const [a,b]=eraRange();return PLAYERS.filter(p=>p.endYear>=a&&p.startYear<=b);}
function playersView(){const list=playerPool();const lens=state.plens;const rows=list.filter(p=>p[lens]!=null).sort((a,b)=>b[lens]-a[lens]||b.caps-a.caps).slice(0,40);const max=rows[0]?.[lens]||1;const q=(state.find2||'').toLowerCase();const found=q?list.filter(p=>p.name.toLowerCase().includes(q)).sort((a,b)=>b.caps-a.caps).slice(0,12):[];
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Players · ${esc(eraLabel())}</span><small>${list.length} careers overlapping the lens · ${PLAYERS.length} in the archive</small></div><div class="panel"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:14px"><input type="search" id="find2" placeholder="Search a player" value="${esc(state.find2||'')}" aria-label="Search"><select id="plens" aria-label="Lens">${Object.entries(PLENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(PLENSES[lens][1])} Career totals, not era totals: the lens selects careers by span.</span></div>${q?`<div class="chiplist" style="margin-bottom:14px">${found.map(p=>`<button type="button" class="chip" data-player="${esc(p.id)}"><i style="--c:${color(p.team)}"></i>${esc(p.name)}</button>`).join('')||'<span class="muted small">No match.</span>'}</div>`:''}
  <div class="board">${rows.map((p,i)=>`<button type="button" class="bar" data-player="${esc(p.id)}" style="--i:${i};${teamVar(p.team)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(p.name)}<small> ${esc(p.team)}${p.position?' · '+esc(p.position):''}</small></span><small>${esc(p.span)} · ${p.caps} caps</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*p[lens]/max)}%"></span></span></span><span class="val">${fmt(p[lens])}</span></button>`).join('')}</div><p class="small dim" style="margin:12px 0 0">Selected published career tables per nation, not every capped player; South Africa carries the fullest coverage.</p></div>`;}
function playerView(id){const p=playerBy[id];const back=`<button type="button" class="btn" data-tab="players">← All players</button>`;if(!p){$('#view').innerHTML=`<div style="margin-top:22px">${back}</div>`;return;}
  const games=p.games.map(g=>({...g,m:byId[g.mid]})).filter(g=>g.m);const inLens=games.filter(g=>inEraYear(g.m.year));const w=inLens.filter(g=>resClass(g.m,p.team)==='W').length;
  const byY={};for(const g of games){const y=g.m.year;byY[y]=byY[y]||{y,caps:0,tries:0,w:0};byY[y].caps++;byY[y].tries+=g.tries||0;if(resClass(g.m,p.team)==='W')byY[y].w++;}const years=Object.values(byY);const maxC=Math.max(1,...years.map(x=>x.caps));
  const opp={};for(const g of games){opp[g.opponent]=(opp[g.opponent]||0)+1;}const opps=Object.entries(opp).sort((a,b)=>b[1]-a[1]);
  $('#view').innerHTML=`<div style="margin-top:22px;display:flex;gap:10px;flex-wrap:wrap;align-items:center">${back}<span class="small muted">${esc(eraLabel())}</span></div>
  <div class="card" style="margin-top:18px;grid-template-columns:1fr;${teamVar(p.team)}"><div><p class="eyebrow">Player · <a href="#" data-nation="${esc(p.team)}" style="color:inherit">${esc(p.team)}</a> · ${esc(p.span)}</p><h2 class="display" style="font-size:clamp(40px,6vw,84px);margin:6px 0 0;color:var(--team);text-shadow:0 0 30px rgba(255,255,255,.18)">${esc(p.name)}</h2><p class="muted" style="margin:4px 0 0">${esc(p.fullName&&p.fullName!==p.name.split(' ')[0]?p.fullName+' '+p.name.split(' ').slice(1).join(' ')+' · ':'')}${esc(p.position||'')}${p.dob?' · born '+esc(p.dob):''}${p.birthplace?', '+esc(p.birthplace):''}${p.number?' · Springbok no. '+esc(p.number):''}</p>
  <div class="kpis" style="margin-top:18px"><div class="kpi"><span>Caps</span><b>${p.caps}</b><small>career, as published</small></div>${p.tries!=null?`<div class="kpi"><span>Tries</span><b>${fmt(p.tries)}</b><small>career</small></div>`:''}${p.points!=null?`<div class="kpi"><span>Points</span><b>${fmt(p.points)}</b><small>career</small></div>`:''}${p.first?`<div class="kpi"><span>First Test</span><b style="font-size:22px">${esc(day(p.first))}</b></div><div class="kpi"><span>Last Test</span><b style="font-size:22px">${esc(day(p.last))}</b></div>`:`<div class="kpi"><span>Career span</span><b style="font-size:22px">${esc(p.span)}</b><small>years, as published</small></div>`}${games.length?`<div class="kpi"><span>Linked Tests</span><b>${games.length}</b><small>${p.complete?'complete history':'partial history'} · ${pct(games.filter(g=>resClass(g.m,p.team)==='W').length,games.length)}% won</small></div>`:''}</div>
  ${games.length?`<div class="h3" style="margin-top:20px"><span>Every linked Test</span><small>green won · red lost · grey drawn · click to open</small></div><div class="ribbon">${games.map(g=>`<i class="${resClass(g.m,p.team)}" title="${esc(day(g.m.date))} v ${esc(g.opponent)} ${esc(scoreOf(g.m,p.team))}${g.tries?' · '+g.tries+' tr':''}" data-match="${g.m.id}"></i>`).join('')}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Caps by year</span></div><div class="board">${years.map((x,i)=>`<div class="bar" style="--i:${i};${teamVar(p.team)};cursor:default"><span class="rk">${x.y}</span><span><span class="lab"><span>${x.caps} cap${x.caps===1?'':'s'}<small> ${x.w} won${x.tries?' · '+x.tries+' tries':''}</small></span></span><span class="trk"><span class="fill" style="--w:${Math.round(100*x.caps/maxC)}%"></span></span></span><span class="val">${x.caps}</span></div>`).join('')}</div></div><div class="panel"><div class="h3"><span>Opponents faced</span></div><div class="chiplist">${opps.map(([o,n])=>`<button type="button" class="chip" data-nation="${esc(o)}"><i style="--c:${color(o)}"></i>${esc(o)} <span class="dim">${n}</span></button>`).join('')}</div></div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Matches</span></div><div class="tablewrap"><table><tr><th>Date</th><th>Opponent</th><th>Score</th><th>Position</th><th>Scoring</th><th>Ground</th></tr>${games.slice().reverse().map(g=>`<tr><td><a href="#" data-match="${g.m.id}" style="color:inherit">${esc(day(g.m.date))}</a></td><td><i class="dot" style="${teamVar(g.opponent)}"></i>${esc(g.opponent)}</td><td><b class="${resClass(g.m,p.team)}">${esc(scoreOf(g.m,p.team))}</b></td><td>${esc(g.position||'')}</td><td>${esc(g.scoring||'')}</td><td>${g.m.recorded?esc(groundName(g.m.stadium)):'—'}</td></tr>`).join('')}</table></div></div>`:(()=>{const span=MATCHES.filter(m=>plays(m,p.team)&&m.year>=p.startYear&&m.year<=p.endYear);const a=natStats(span).find(x=>x.id===p.team);return `<p class="small dim" style="margin-top:16px">No match-by-match history is captured for this career; the totals above are the published snapshot.</p>${a?`<div class="h3" style="margin-top:20px"><span>${esc(p.team)} across this career</span><small>the nation’s record ${p.startYear}–${p.endYear}, not the player’s appearances</small></div><div class="kpis"><div class="kpi"><span>Tests</span><b>${a.p}</b><small>${a.w}–${a.l}–${a.d}</small></div><div class="kpi"><span>Win rate</span><b>${a.rate}%</b></div><div class="kpi"><span>Avg margin</span><b>${a.margin>0?'+':''}${a.margin}</b></div><div class="kpi"><span>World Cups</span><b>${a.cups}</b><small>won in the span</small></div></div><div class="ribbon" style="margin-top:12px">${span.map(m=>`<i class="${resClass(m,p.team)}" title="${esc(day(m.date))} v ${esc(m.home===p.team?m.away:m.home)} ${esc(scoreOf(m,p.team))}" data-match="${m.id}"></i>`).join('')}</div>`:''}`;})()}
  <p class="small dim" style="margin-top:12px">${(p.sources||[]).slice(0,3).map(u=>`<a href="${esc(u)}" target="_blank" rel="noopener">${esc(u.replace(/^https?:\/\//,'').split('/')[0])} ↗</a>`).join(' · ')}</p></div></div>`;}

/* ---------- Coaches ---------- */
function coachPool(){if(state.era==='all')return COACHES;const [a,b]=eraRange();return COACHES.filter(c=>c.endYear>=a&&c.startYear<=b);}
function coachesView(){const list=coachPool();const rows=list.slice().sort((a,b)=>(b.reported?.n||0)-(a.reported?.n||0)||b.startYear-a.startYear);const max=Math.max(1,...rows.map(c=>c.reported?.n||0));
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Coaches · ${esc(eraLabel())}</span><small>${list.length} tenures overlapping the lens · ${COACHES.length} in the archive</small></div><div class="panel"><div class="board">${rows.map((c,i)=>{const r=c.reported||{};return `<button type="button" class="bar" data-coach="${esc(c.id)}" style="--i:${i};${teamVar(c.team)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(c.name)}<small> ${esc(c.team)} · ${esc(c.tenure)}</small></span><small>${r.n!=null?`${r.w}–${r.l}–${r.d} · ${pct(r.w,r.n)}% won`:'record not published'}${c.role&&c.role!=='Head coach'?' · '+esc(c.role):''}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*(r.n||0)/max)}%"></span></span></span><span class="val">${r.n??'—'}</span></button>`;}).join('')}</div><p class="small dim" style="margin:12px 0 0">Published records from each union’s coaching list; where the archive could link the matches, the linked record is shown on the coach’s page. Coverage starts at different years per nation.</p></div>`;}
function coachView(id){const c=coachBy[id];const back=`<button type="button" class="btn" data-tab="coaches">← All coaches</button>`;if(!c){$('#view').innerHTML=`<div style="margin-top:22px">${back}</div>`;return;}const r=c.reported||{},l=c.linkedRecord;const ms=c.matches;
  $('#view').innerHTML=`<div style="margin-top:22px;display:flex;gap:10px;flex-wrap:wrap;align-items:center">${back}<span class="small muted">${esc(eraLabel())}</span></div>
  <div class="card" style="margin-top:18px;grid-template-columns:1fr;${teamVar(c.team)}"><div><p class="eyebrow">${esc(c.role||'Coach')} · <a href="#" data-nation="${esc(c.team)}" style="color:inherit">${esc(c.team)}</a> · ${esc(c.tenure)}</p><h2 class="display" style="font-size:clamp(40px,6vw,84px);margin:6px 0 0;color:var(--team);text-shadow:0 0 30px rgba(255,255,255,.18)">${esc(c.name)}</h2>
  <div class="kpis" style="margin-top:18px"><div class="kpi"><span>Published record</span><b>${r.n!=null?`${r.w}–${r.l}–${r.d}`:'—'}</b><small>${r.n!=null?r.n+' Tests · '+pct(r.w,r.n)+'% won':'not published'}</small></div><div class="kpi"><span>Linked record</span><b>${l?`${l.w}–${l.l}–${l.d}`:'—'}</b><small>${l?l.n+' linked Tests':'no match linkage captured'}</small></div><div class="kpi"><span>Spells</span><b style="font-size:22px">${esc(c.spells.join(' · '))}</b></div><div class="kpi"><span>Method</span><b style="font-size:16px;font-style:normal;font-family:var(--body);font-weight:400;color:var(--muted)">${esc(c.method||'—')}</b></div></div>
  ${ms.length?`<div class="h3" style="margin-top:20px"><span>Every linked Test</span><small>green won · red lost · grey drawn</small></div><div class="ribbon">${ms.map(m=>`<i class="${resClass(m,c.team)}" title="${esc(day(m.date))} v ${esc(m.home===c.team?m.away:m.home)} ${esc(scoreOf(m,c.team))}" data-match="${m.id}"></i>`).join('')}</div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Matches</span></div><div class="tablewrap"><table><tr><th>Date</th><th>Opponent</th><th>Score</th><th>Competition</th><th>Ground</th></tr>${ms.slice().reverse().map(m=>`<tr><td><a href="#" data-match="${m.id}" style="color:inherit">${esc(day(m.date))}</a></td><td><i class="dot" style="${teamVar(m.home===c.team?m.away:m.home)}"></i>${esc(m.home===c.team?m.away:m.home)}</td><td><b class="${resClass(m,c.team)}">${esc(scoreOf(m,c.team))}</b></td><td>${esc(compShort(m))}</td><td>${m.recorded?esc(groundName(m.stadium)):'—'}</td></tr>`).join('')}</table></div></div>`:''}
  ${c.notes&&c.notes.length?`<p class="small muted" style="margin-top:12px">${esc(c.notes.join(' '))}</p>`:''}<p class="small dim" style="margin-top:12px">${(c.sources||[]).slice(0,2).map(u=>`<a href="${esc(u)}" target="_blank" rel="noopener">${esc(u.replace(/^https?:\/\//,'').split('/')[0])} ↗</a>`).join(' · ')}</p></div></div>`;}
