/* ---------- Grounds ---------- */
function groundsView(){const list=groundModel().sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));const unrec=eraMatches().filter(m=>!m.recorded).length;
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Grounds · ${esc(eraLabel())}</span><small>${list.length} venues${unrec?' · '+fmt(unrec)+' Tests without a recorded ground':''}</small></div><div class="tablewrap"><table><tr><th>Ground</th><th>City</th><th>Country</th><th>Tests</th><th>Years</th><th>Most wins</th></tr>${list.map(c=>`<tr><td><a href="#" data-ground="${esc(c.cid)}" style="color:inherit">${esc(c.name)}</a></td><td>${esc(c.place)}</td><td>${esc(c.country)}</td><td>${c.count}</td><td>${c.first}${c.last!==c.first?'–'+c.last:''}</td><td>${c.top?`<i class="dot" style="${teamVar(c.top)}"></i>${esc(c.top)} (${c.wins[c.top]})`:'—'}</td></tr>`).join('')}</table></div>`;}
function groundView(cid){const g=GROUNDS[cid];const ms=eraMatches().filter(m=>m.stadium===cid);const back=`<button type="button" class="btn" data-tab="grounds">← All grounds</button>`;
  if(!ms.length){$('#view').innerHTML=`<div style="margin-top:22px">${back}</div><p class="muted" style="margin-top:16px">${esc(g?.name||cid)} staged no Test in ${esc(eraLabel())}.</p>`;return;}
  const st=natStats(ms);const wins={};for(const m of ms)if(m.winner)wins[m.winner]=(wins[m.winner]||0)+1;const topW=Object.entries(wins).sort((a,b)=>b[1]-a[1]);const hostSide=st.filter(a=>ms.some(m=>isHomeFor(m,a.id))).sort((a,b)=>b.p-a.p)[0];
  const hi=[...ms].filter(m=>m.points).sort((a,b)=>b.total-a.total)[0];const big=[...ms].filter(m=>m.points&&!m.draw).sort((a,b)=>b.margin-a.margin)[0];const last=ms[ms.length-1];
  const ribbon=ms.map(m=>`<i style="--c:${m.winner?color(m.winner):'#333'}" title="${esc(day(m.date))} · ${esc(m.home)} ${m.hs}–${m.as} ${esc(m.away)}" data-match="${m.id}"></i>`).join('');
  $('#view').innerHTML=`<div style="margin-top:22px;display:flex;gap:10px;flex-wrap:wrap;align-items:center">${back}<span class="small muted">${esc(eraLabel())}</span></div>
  <div class="card" style="margin-top:18px;grid-template-columns:1fr;${topW[0]?teamVar(topW[0][0]):''}">
  <div><p class="eyebrow">Ground · ${esc([g.city,g.country].filter(Boolean).join(', '))}</p><h2 class="display" style="font-size:clamp(36px,5.6vw,76px);margin:6px 0 0">${esc(g.name)}</h2>
  <div class="kpis" style="margin-top:18px"><div class="kpi"><span>Tests</span><b>${ms.length}</b><small>${ms[0].year}–${last.year}</small></div><div class="kpi"><span>Home side</span><b style="font-size:22px">${hostSide?esc(hostSide.id):'—'}</b><small>${hostSide?`${hostSide.w}–${hostSide.l}–${hostSide.d} here · ${hostSide.rate}%`:'neutral or unrecorded'}</small></div><div class="kpi"><span>Most wins</span><b style="font-size:22px">${topW[0]?esc(topW[0][0]):'—'}</b><small>${topW[0]?topW[0][1]+' of '+ms.length:''}</small></div><div class="kpi"><span>Highest aggregate</span><b>${hi?hi.total:'—'}</b><small>${hi?esc(hi.home)+' '+hi.hs+'–'+hi.as+' '+esc(hi.away)+' · '+hi.year:''}</small></div><div class="kpi"><span>Biggest margin</span><b>${big?'+'+big.margin:'—'}</b><small>${big?esc(big.winner)+' v '+esc(big.loser)+' · '+big.year:''}</small></div><div class="kpi"><span>Sides</span><b>${st.length}</b><small>have played here</small></div></div>
  <div class="h3" style="margin-top:20px"><span>Winners, Test by Test</span><small>one block per match, in the winner’s colour</small></div><div class="ribbon">${ribbon}</div></div></div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Most wins here</span></div>${natBars(topW.slice(0,8).map(([id,n])=>({id,w:n,l:st.find(a=>a.id===id).l,d:st.find(a=>a.id===id).d})),a=>a.w,a=>`${st.find(x=>x.id===a.id).p} Tests here`,topW[0]?.[1])}</div><div class="panel"><div class="h3"><span>Records here</span><small>by win rate, 3+ Tests</small></div>${natBars(st.filter(a=>a.p>=3).sort((a,b)=>b.rate-a.rate||b.w-a.w).slice(0,8),a=>a.rate,a=>`${a.p} Tests`,100,'%')||''}</div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Every Test here</span></div><div class="tablewrap"><table><tr><th>Date</th><th>Home</th><th>Score</th><th>Away</th><th>Competition</th></tr>${ms.slice().reverse().map(m=>`<tr><td><a href="#" data-match="${m.id}" style="color:inherit">${esc(day(m.date))}</a></td><td><i class="dot" style="${teamVar(m.home)}"></i>${esc(m.home)}</td><td><b>${m.hs}–${m.as}</b></td><td><i class="dot" style="${teamVar(m.away)}"></i>${esc(m.away)}</td><td>${esc(compShort(m))}${m.historical?' †':''}</td></tr>`).join('')}</table></div></div>`;}

/* ---------- Records ---------- */
function recordsView(){const ms=eraMatches();const st=natStats(ms);const pl=playerPool();const pts=ms.filter(m=>m.points);const grounds=new Set(ms.filter(m=>m.recorded).map(m=>m.stadium)).size;const cups=ms.filter(m=>m.stage==='Final');
  const big=[...pts].filter(m=>!m.draw).sort((a,b)=>b.margin-a.margin||b.total-a.total).slice(0,8);const hi=[...pts].sort((a,b)=>b.total-a.total||b.margin-a.margin).slice(0,8);const one=[...pts].filter(m=>m.winner).sort((a,b)=>Math.max(b.hs,b.as)-Math.max(a.hs,a.as))[0];
  const streaks=[...st].sort((a,b)=>b.streak-a.streak||b.rate-a.rate).slice(0,5);const draws=ms.filter(m=>m.draw).length;const nil=pts.filter(m=>m.hs===0&&m.as===0).length;
  const top=(k,min)=>{const rows=st.filter(a=>a.p>=min).sort((a,b)=>b[k]-a[k]||b.w-a.w).slice(0,5);return natBars(rows,a=>a[k],a=>`${a.p} Tests`,Math.max(1,...rows.map(a=>Math.abs(a[k]))),/rate/.test(k)?'%':'');};
  const ptop=k=>{const rows=pl.filter(p=>p[k]!=null).sort((a,b)=>b[k]-a[k]).slice(0,5);const max=rows[0]?.[k]||1;return `<div class="board">${rows.map((p,i)=>`<button type="button" class="bar" data-player="${esc(p.id)}" style="--i:${i};${teamVar(p.team)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(p.name)}<small> ${esc(code(p.team))} · ${esc(p.span)}</small></span></span><span class="trk"><span class="fill" style="--w:${Math.round(100*p[k]/max)}%"></span></span></span><span class="val">${fmt(p[k])}</span></button>`).join('')}</div>`;};
  const mlist=(arr,lab)=>`<div class="board">${arr.map((m,i)=>`<button type="button" class="bar" data-match="${m.id}" style="--i:${i};${teamVar(m.winner||m.home)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(m.home)} ${m.hs}–${m.as} ${esc(m.away)}</span><small>${esc(day(m.date))} · ${esc(compShort(m))}${m.recorded?' · '+esc(groundName(m.stadium)):''}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*lab(m)/(lab(arr[0])||1))}%"></span></span></span><span class="val">${lab(m)}</span></button>`).join('')}</div>`;
  const rec=(t,v,sub)=>`<div class="kpi"><span>${t}</span><b style="font-size:24px">${v}</b><small>${sub}</small></div>`;
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Records · ${esc(eraLabel())}</span><small>${fmt(ms.length)} Tests</small></div>
  <div class="kpis"><div class="kpi"><span>Tests</span><b>${fmt(ms.length)}</b><small>${eraSeasons().length} seasons · ${grounds} grounds</small></div><div class="kpi"><span>Sides</span><b>${st.length}</b><small>${st.filter(a=>nat(a.id).ten).length} of the ten nations</small></div><div class="kpi"><span>World Cup finals</span><b>${cups.length}</b><small>${[...new Set(cups.map(m=>m.winner))].length} different champions</small></div><div class="kpi"><span>Draws</span><b>${draws}</b><small>${pct(draws,ms.length)}% of Tests${nil?' · '+nil+' scoreless':''}</small></div><div class="kpi"><span>Careers</span><b>${pl.length}</b><small>published, overlapping the lens</small></div></div>
  <div class="kpis" style="margin-top:12px">${big[0]?rec('Biggest win',`+${big[0].margin}`,`${esc(big[0].winner)} ${esc(scoreOf(big[0],big[0].winner))} ${esc(big[0].loser)} · ${big[0].year}`):''}${hi[0]?rec('Highest aggregate',hi[0].total,`${esc(hi[0].home)} ${hi[0].hs}–${hi[0].as} ${esc(hi[0].away)} · ${hi[0].year}`):''}${one?rec('Most points by one side',Math.max(one.hs,one.as),`${esc(one.winner)} v ${esc(one.loser)} · ${one.year}`):''}${streaks[0]?rec('Longest winning run',streaks[0].streak,`${esc(streaks[0].id)} · consecutive Tests in lens`):''}</div>
  <div class="three" style="margin-top:20px"><div class="panel"><div class="h3"><span>Wins</span><small>nations</small></div>${top('w',0)}<div class="h3" style="margin-top:16px"><span></span><small>win rate · 20+ Tests</small></div>${top('rate',20)}</div><div class="panel"><div class="h3"><span>Points</span><small>points per Test · 20+</small></div>${top('ppm',20)}<div class="h3" style="margin-top:16px"><span></span><small>average margin · 20+</small></div>${top('margin',20)}</div><div class="panel"><div class="h3"><span>Careers</span><small>caps</small></div>${ptop('caps')}<div class="h3" style="margin-top:16px"><span></span><small>tries</small></div>${ptop('tries')}<div class="h3" style="margin-top:16px"><span></span><small>points</small></div>${ptop('points')}</div></div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Biggest wins</span><small>by margin</small></div>${mlist(big,m=>m.margin)}</div><div class="panel"><div class="h3"><span>Highest-scoring Tests</span><small>aggregate points</small></div>${mlist(hi,m=>m.total)}</div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Longest winning runs</span><small>consecutive Test wins inside the lens</small></div>${natBars(streaks,a=>a.streak,a=>`${a.p} Tests · ${a.rate}% won`,streaks[0]?.streak)}</div>`;}

/* ---------- Barcode ---------- */
const HEATMETRICS={rate:['Win rate %','Wins divided by Tests that year.'],w:['Wins','Tests won that year.'],p:['Tests','Matches played that year.'],pf:['Points for','Points scored that year, points era only.'],margin:['Average margin','Points for minus against, per Test.']};
function barcodeView(){const seasons=eraSeasons();const metric=state.heat;const per={};for(const s of seasons){for(const a of natStats(s.matches)){const v=metric==='margin'?Math.max(0,a.margin):a[metric];per[a.id]=per[a.id]||{id:a.id,cells:{},total:0,p:0};per[a.id].cells[s.year]=v;per[a.id].total+=metric==='rate'?a.w:v;per[a.id].p+=a.p;}}
  const rows=Object.values(per).sort((a,b)=>b.p-a.p).slice(0,28);const max=Math.max(1,...rows.flatMap(r=>Object.values(r.cells)));const years=seasons.map(s=>s.year);
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Season barcode · ${esc(eraLabel())}</span><small>${rows.length} sides × ${years.length} seasons</small></div><div class="panel"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:14px"><select id="heatMetric">${Object.entries(HEATMETRICS).map(([k,v])=>`<option value="${k}" ${k===metric?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(HEATMETRICS[metric][1])} Brightness is the cell’s share of the brightest cell; colour is the nation’s. Rows ordered by Tests played.</span></div>
  <div class="barcode"><div class="bc-row"><span></span><span class="cells" style="gap:2px">${years.map(y=>`<i style="background:none;height:14px;font-size:8px;color:var(--dim);text-align:center;line-height:14px">${years.length<=30||y%10===0?String(y).slice(2):''}</i>`).join('')}</span><span></span></div>${rows.map(r=>`<div class="bc-row"><span class="lab" data-nation="${esc(r.id)}">${esc(r.id)}</span><span class="cells">${years.map(y=>{const v=r.cells[y];const a=v===undefined?0:Math.max(.12,v/max);return `<i style="--c:${v===undefined?'#0e1014':mixHex(color(r.id),'#12141a',a)}" title="${y} · ${esc(r.id)} · ${v===undefined?'no Test':fmt(v)+(metric==='rate'?'%':'')}"></i>`;}).join('')}</span><span class="tot">${fmt(Math.round(r.total))}</span></div>`).join('')}</div>
  <div class="bc-key"><span><i style="--c:#0e1014"></i>no Test</span><span><i style="--c:#2a2f39"></i>low</span><span><i style="--c:var(--accent)"></i>high, in the nation’s colour</span><span class="dim">· row total: ${metric==='rate'?'wins':HEATMETRICS[metric][0].toLowerCase()}</span></div></div>`;}

/* ---------- Duel ---------- */
function swingChart(ms,a,b){const W=800,H=180,padL=30,padR=30,padT=16,padB=22;let cum=0;const pts=ms.map(m=>{cum+=m.winner===a?1:m.winner===b?-1:0;return cum;});const max=Math.max(1,...pts.map(Math.abs));const x=i=>padL+(ms.length>1?i*(W-padL-padR)/(ms.length-1):(W-padL-padR)/2),y=v=>padT+(H-padT-padB)*(1-v/max)/2;
  const d=pts.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1)).join('');const zero=y(0);const area=`${d}L${x(ms.length-1).toFixed(1)} ${zero}L${x(0).toFixed(1)} ${zero}Z`;const cid='sw'+Math.random().toString(36).slice(2,7);
  return `<svg viewBox="0 0 ${W} ${H}" class="swing" role="img" aria-label="Cumulative lead in the rivalry"><defs><clipPath id="${cid}a"><rect x="0" y="0" width="${W}" height="${zero}"/></clipPath><clipPath id="${cid}b"><rect x="0" y="${zero}" width="${W}" height="${H-zero}"/></clipPath></defs><line x1="${padL}" x2="${W-padR}" y1="${zero}" y2="${zero}" stroke="#2e333d"/><text x="${padL}" y="${padT-4}" class="lb" fill="${color(a)}">${esc(a)} ahead</text><text x="${padL}" y="${H-6}" class="lb" fill="${color(b)}">${esc(b)} ahead</text><path d="${area}" fill="${color(a)}" opacity=".22" clip-path="url(#${cid}a)"/><path d="${area}" fill="${color(b)}" opacity=".22" clip-path="url(#${cid}b)"/><path d="${d}" fill="none" stroke="var(--ink)" stroke-width="1.6"/>${ms.map((m,i)=>`<circle cx="${x(i).toFixed(1)}" cy="${y(pts[i]).toFixed(1)}" r="3" fill="${m.winner?color(m.winner):'#8b9099'}" data-match="${m.id}" style="cursor:pointer"><title>${esc(day(m.date))} · ${esc(m.home)} ${m.hs}–${m.as} ${esc(m.away)}</title></circle>`).join('')}</svg>`;}
function duelView(){const by=state.duelBy;
  if(by==='p'){const pool=playerPool().sort((a,b)=>(b.caps||0)-(a.caps||0));if(!pool.find(p=>p.id===state.dA))state.dA=pool[0]?.id;if(!pool.find(p=>p.id===state.dB)||state.dB===state.dA)state.dB=pool.find(p=>p.id!==state.dA)?.id;const opt=v=>pool.map(p=>`<option value="${esc(p.id)}" ${p.id===v?'selected':''}>${esc(p.name)} (${esc(code(p.team))})</option>`).join('');const P1=playerBy[state.dA],P2=playerBy[state.dB];
    $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Head to head · ${esc(eraLabel())}</span><small>${pool.length} careers in lens</small></div><div class="panel"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:16px"><select id="duelBy"><option value="n">Nations</option><option value="p" selected>Players</option></select><select id="dA">${opt(state.dA)}</select><span class="eyebrow">vs</span><select id="dB">${opt(state.dB)}</select></div><div id="duelBody"></div></div>`;if(!P1||!P2)return;
    const rowsK=[['Caps','caps'],['Tries','tries'],['Points','points'],['First Test',null,p=>p.startYear],['Last Test',null,p=>p.endYear],['Linked Tests won %',null,p=>p.games.length?pct(p.games.filter(g=>byId[g.mid]&&resClass(byId[g.mid],p.team)==='W').length,p.games.length):null]];
    $('#duelBody').innerHTML=`<div class="two" style="gap:12px"><div class="kpi" style="border-color:${color(P1.team)}"><span>${esc(P1.name)}</span><b>${P1.caps}</b><small>caps · ${esc(P1.team)} · ${esc(P1.span)}</small></div><div class="kpi" style="border-color:${color(P2.team)}"><span>${esc(P2.name)}</span><b>${P2.caps}</b><small>caps · ${esc(P2.team)} · ${esc(P2.span)}</small></div></div>
    <div class="tablewrap" style="margin-top:14px"><table><tr><th style="text-align:right;color:${color(P1.team)}">${esc(P1.name)}</th><th></th><th style="color:${color(P2.team)}">${esc(P2.name)}</th></tr>${rowsK.map(([l,k,f])=>{const va=k?P1[k]:f(P1),vb=k?P2[k]:f(P2);const m=Math.max(va||0,vb||0,1);const bar=(v,c,right)=>v==null||/First|Last/.test(l)?'':`<span style="display:inline-block;height:8px;width:${Math.round(120*v/m)}px;background:${c};border-radius:2px;vertical-align:middle;margin-${right?'left':'right'}:8px"></span>`;return `<tr><td style="text-align:right">${bar(va,color(P1.team))}<b>${fmt(va)}</b></td><td style="text-align:center;color:var(--muted);font-size:10.5px;letter-spacing:.14em;text-transform:uppercase">${l}</td><td><b>${fmt(vb)}</b>${bar(vb,color(P2.team),true)}</td></tr>`;}).join('')}</table></div><p class="small dim" style="margin-top:10px">Career totals as published; the linked-Tests figure exists only where a match-by-match history is captured.</p>`;return;}
  const ms=eraMatches();const all=natStats(ms).filter(a=>a.p>=5).sort((a,b)=>b.p-a.p);if(!all.find(a=>a.id===state.dA))state.dA=all[0]?.id;if(!all.find(a=>a.id===state.dB)||state.dB===state.dA)state.dB=all.find(a=>a.id!==state.dA&&ms.some(m=>plays(m,state.dA)&&plays(m,a.id)))?.id||all.find(a=>a.id!==state.dA)?.id;
  const opt=v=>all.map(a=>`<option value="${esc(a.id)}" ${a.id===v?'selected':''}>${esc(a.id)}</option>`).join('');const NA=all.find(a=>a.id===state.dA),NB=all.find(a=>a.id===state.dB);
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Head to head · ${esc(eraLabel())}</span><small>${all.length} sides with 5+ Tests</small></div><div class="panel"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:16px"><select id="duelBy"><option value="n" selected>Nations</option><option value="p">Players</option></select><select id="dA">${opt(state.dA)}</select><span class="eyebrow">vs</span><select id="dB">${opt(state.dB)}</select></div><div id="duelBody"></div></div>`;if(!NA||!NB)return;
  const meet=ms.filter(m=>plays(m,NA.id)&&plays(m,NB.id));const aw=meet.filter(m=>m.winner===NA.id).length,bw=meet.filter(m=>m.winner===NB.id).length,dr=meet.length-aw-bw;const bigA=[...meet].filter(m=>m.winner===NA.id&&m.points).sort((a,b)=>b.margin-a.margin)[0],bigB=[...meet].filter(m=>m.winner===NB.id&&m.points).sort((a,b)=>b.margin-a.margin)[0];
  const norm=normAxes(all);const rowsK=[['Wins','w'],['Win rate %','rate'],['Tests','p'],['Points per Test','ppm'],['Average margin','margin'],['Home win %','homeRate'],['Best run','streak'],['World Cups','cups']];
  $('#duelBody').innerHTML=`<div class="card" style="grid-template-columns:300px 1fr;--team:${color(NA.id)};--team2:${color(NB.id)}"><div class="trace" id="duelTrace"></div><div>
  <div class="two" style="gap:12px"><div class="kpi" style="border-color:${color(NA.id)}"><span>${esc(NA.id)}</span><b>${aw}</b><small>wins in ${meet.length} meetings${dr?' · '+dr+' drawn':''}${bigA?' · best '+esc(scoreOf(bigA,NA.id))+' ('+bigA.year+')':''}</small></div><div class="kpi" style="border-color:${color(NB.id)}"><span>${esc(NB.id)}</span><b>${bw}</b><small>wins in ${meet.length} meetings${bigB?' · best '+esc(scoreOf(bigB,NB.id))+' ('+bigB.year+')':''}</small></div></div>
  ${meet.length?`<div class="h3" style="margin-top:16px"><span>The rivalry, meeting by meeting</span><small>cumulative lead · click a point to open the match</small></div><div class="swingwrap">${swingChart(meet,NA.id,NB.id)}</div><div class="ribbon" style="margin-top:8px">${meet.slice(-30).map(m=>`<i class="${m.draw?'D':m.winner===NA.id?'W':'L'}" title="${esc(day(m.date))} · ${esc(m.home)} ${m.hs}–${m.as} ${esc(m.away)}" data-match="${m.id}"></i>`).join('')}</div><p class="small dim" style="margin:6px 0 0">Last ${Math.min(30,meet.length)} meetings from ${esc(NA.id)}’s side.</p>`:`<p class="muted small" style="margin-top:14px">These two have not met in ${esc(eraLabel())}.</p>`}
  <div class="tablewrap" style="margin-top:14px"><table><tr><th style="text-align:right;color:${color(NA.id)}">${esc(NA.id)}</th><th style="text-align:center"></th><th style="color:${color(NB.id)}">${esc(NB.id)}</th></tr>${rowsK.map(([l,k])=>{const va=NA[k],vb=NB[k];const m=Math.max(Math.abs(va),Math.abs(vb),1);return `<tr><td style="text-align:right"><span style="display:inline-block;height:8px;width:${Math.round(120*Math.max(0,va)/m)}px;background:${color(NA.id)};border-radius:2px;vertical-align:middle;margin-right:8px"></span><b>${fmt(va)}${/rate|Rate/.test(k)?'%':''}</b></td><td style="text-align:center;color:var(--muted);font-size:10.5px;letter-spacing:.14em;text-transform:uppercase">${l}</td><td><b>${fmt(vb)}${/rate|Rate/.test(k)?'%':''}</b><span style="display:inline-block;height:8px;width:${Math.round(120*Math.max(0,vb)/m)}px;background:${color(NB.id)};border-radius:2px;vertical-align:middle;margin-left:8px"></span></td></tr>`;}).join('')}</table></div>
  <p class="small dim" style="margin-top:10px">Whole-lens figures for each side against everyone, not only against each other; the meetings count and the swing are head to head.</p></div></div>`;
  radar($('#duelTrace'),AXES,norm(NA),norm(NB));}

/* ---------- Sources & coverage ---------- */
function drawSources(){const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b><small>${s}</small></div>`;$('#sourcesBody').innerHTML=`<p class="eyebrow">Ten-nation edition / ${esc(day(A.asof))}</p><h2>One archive. Ten distinct records.</h2><div class="kpis">${kpi('Unique fixtures',fmt(A.matches.length),'shared records, each viewed from either side')}${kpi('Nations kept whole','10','every opponent remains in each archive')}${kpi('Player register',fmt(A.players.length),`${fmt((A.harvest||{}).sheetsAny||0)} Tests with a team sheet · ${fmt((A.harvest||{}).namedScorers||0)} with named scorers`)}${kpi('Match span',`${FIRST_YEAR}–${LAST_YEAR}`,'latest captured match: '+esc(day(A.through)))}</div>
<h3>Why these ten?</h3><p class="small muted">South Africa, New Zealand, Australia, Argentina, England, France, Ireland, Wales, Scotland and Italy are the longstanding nations of the Rugby Championship and Six Nations. This is an editorial cohort, not an official all-time top-ten ranking. Fiji, Samoa, Japan, the Lions and other sides are retained as opponents and appear throughout the atlas; only Tests involving at least one of the ten are in the archive.</p>
<h3>Match records</h3><ol><li><a href="https://rugbyarchive.github.io/about.html" target="_blank" rel="noopener">Nuck’s Rugby Archive · historical match research</a><p>The principal source for the expanded national-team archive. Its public dataset combines reference books, union records and reporting. Fixtures marked as full internationals involving the ten selected nations were imported, awarded/abandoned fixtures excluded, and its uncertainty flags preserved. This is a curated independent archive, not a certified complete record from each union; the source itself identifies ongoing verification work.</p></li><li><a href="https://bokhist.com/StatOpponentSummary.aspx" target="_blank" rel="noopener">Springbok Rugby History · preserved South African record</a><p>All 577 match records, all 270 player snapshots, the captured player histories and eight World Cup squad lists from the previous edition are retained. The three conflicting dates against the Lions (1903), Australia (1992) and Australia (2021) follow this reconciled record. France’s 1907 fixture is present only from France’s perspective because it is absent from the Springbok capped archive.</p></li><li><a href="https://www.lassen.co.nz/pickandgo.php" target="_blank" rel="noopener">Pick &amp; Go · public latest-results cross-check</a><p>Public recent-result tables provide an additional cross-check. No restricted subscription records are included.</p></li></ol>
<h3>Player records</h3><p class="small muted">${(()=>{const h=A.harvest||{};return `The register holds every entry of the published national player lists of the sides in the archive (${Object.keys(A.registers||{}).length} lists on Wikipedia, CC BY-SA 4.0), ${fmt(h.registerEntries)} entries in all, with the caps, tries and points each list gives when it gives them. Team sheets and named scorers were read from the Wikipedia match, tour and championship articles and, as factual cross-checks, from national unions’ own match records: ${fmt(h.sheetsAny)} Tests carry at least one team sheet, ${fmt(h.sheetsBoth)} both, ${fmt(h.namedScorers)} have named scorers, and ${fmt(h.scoringBreakdowns)} carry a scoring breakdown that reconciles to the recorded score under the values of the day. Dates of birth and death come from Wikidata (CC0) for the ${fmt(h.wikidataPeople)} people it could link by an exact Wikipedia sitelink. ${fmt(h.unresolvedNames)} names printed in a match source could not yet be linked to a register entry; they are kept as printed and marked for review, so a team sheet is never shortened. ${fmt(h.missingSheets)} team sheets are still missing. South African profiles keep their original detailed coverage from Springbok Rugby History.`;})()} A named replacement is not credited with an appearance unless the source confirms it; captured appearance counts are lower bounds, never career totals. Published figures can lag match results and different fields can have different cut-offs; they are not a current squad list. Unknown values stay unavailable. The era lens selects careers by span; the totals shown are always career totals.</p>${(A.harvestCorrections||[]).length?`<h3>Reviewed corrections</h3><p class="small muted">${A.harvestCorrections.map(c=>`${esc(c.field)} of match ${c.match} ${esc(c.before)} → ${esc(c.after)}${c.evidence?` (<a href="${esc(c.evidence)}" target="_blank" rel="noopener">evidence ↗</a>)`:''}`).join('; ')}. Each follows an official match record; the harvest’s note is kept on the match.</p>`:''}
<h3>Coaches</h3><p class="small muted">${Object.entries(A.coachCoverage).map(([n,c])=>`<b>${esc(n)}</b> from ${c.firstYear}, ${c.profiles} profiles, ${c.linked} linked matches. ${esc(c.note)}`).join(' ')} Coaching snapshot dated ${esc(day(A.coachAsOf))}.</p>
<h3>Recognition and early history</h3><p class="small muted">The archive includes source-classified internationals and retained historical capped fixtures; the latter are marked † in lists. Individual unions can recognise a match differently. France’s broader archive reaches the 1900 Olympics; its first standard Test is in 1906. The Springbok record includes 15 historical fixtures against South America, the NZ Cavaliers and World Invitation.</p>
<h3>Scores, eras and calculations</h3><p class="small muted">Win rate is wins divided by all matches, including draws. Before 1886 the archive’s numeric scores count goals; these fixtures contribute to results but are excluded from point sums, average margins and point-margin records. The River counts each Test win once, a draw as half to each side. “Best record of the year” ranks sides with at least three Tests that year (fewer only in the earliest years) by win rate, then wins, then average margin; it is a reading of the archive, not a title. Scoring values shown on the era card are those this atlas applies when it builds a symbolic scoreboard; historical changes in value are otherwise unadjusted. Grounds are recorded as the source gives them, so early fixtures often have none.</p>`;}

/* ---------- deep links: the address bar mirrors the state, so any view can be shared or opened from a static page ---------- */
let routeLock=false;
function writeRoute(){if(routeLock)return;const q=[];if(state.era!=='all')q.push('era='+encodeURIComponent(state.era));if(state.whole)q.push('whole=1');else q.push('season='+state.year);q.push('tab='+state.tab);if(state.tab==='match'&&!state.whole&&state.match!=null)q.push('match='+state.match);for(const k of ['nation','player','ground','coach']){if(state.tab===k+'s'&&state[k])q.push(k+'='+encodeURIComponent(state[k]));}const h='#'+q.join('&');if(location.hash!==h){try{history[location.hash?'pushState':'replaceState'](null,'',h);}catch(e){}}}
function readRoute(){const h=location.hash.replace(/^#\/?/,'');if(!h||/^static-/.test(h))return false;const p={};for(const kv of h.split('&')){const i=kv.indexOf('=');p[i<0?kv:kv.slice(0,i)]=i<0?'1':decodeURIComponent(kv.slice(i+1));}let any=false;
  if(p.era&&(p.era==='all'||ERAS.some(e=>e.id===p.era))){state.era=p.era;any=true;}
  if(p.match&&byId[+p.match]){state.match=+p.match;state.year=byId[+p.match].year;any=true;}else if(p.season&&byYear[+p.season]){state.year=+p.season;any=true;}
  if(state.era!=='all'&&!inEraYear(state.year)){if(p.season||p.match)state.era='all';else state.year=eraSeasons().slice(-1)[0].year;}
  state.whole=p.whole==='1';if(state.whole)any=true;
  if(p.tab&&TABS.some(t=>t[0]===p.tab)){state.tab=p.tab;any=true;}
  state.nation=p.nation&&NAT[p.nation]||p.nation&&MATCHES.some(m=>m.home===p.nation||m.away===p.nation)?p.nation:null;state.player=p.player&&playerBy[p.player]?p.player:null;state.ground=p.ground&&GROUNDS[p.ground]?p.ground:null;state.coach=p.coach&&coachBy[p.coach]?p.coach:null;
  if(!p.match||!byId[+p.match])state.match=byYear[state.year].matches.slice(-1)[0]?.id??null;
  return any;}
/* ---------- render, navigation, events ---------- */
function render(){stopReplay();drawTabs();if(tour.stopped||!tour.timer)drawEraStrip();const v={season:seasonView,match:matchView,nations:()=>state.nation?nationView(state.nation):nationsView(),players:()=>state.player?playerView(state.player):playersView(),grounds:()=>state.ground?groundView(state.ground):groundsView(),coaches:()=>state.coach?coachView(state.coach):coachesView(),records:recordsView,barcode:barcodeView,duel:duelView}[state.tab];try{v();}catch(e){$('#view').innerHTML=`<p class="muted">Something in this view could not be drawn: ${esc(e.message)}</p>`;console.error(e);}StageNav.draw();writeRoute();}
function go(tab,scroll=true){state.tab=tab;render();if(scroll)$('#stage').scrollIntoView({behavior:RM?'auto':'smooth',block:'start'});}
function ensureYearInLens(y){if(state.era!=='all'&&!inEraYear(y)){state.era='all';$('#eraSelect').value='all';drawGrid();}}
function setSeason(y,scroll){state.whole=false;ensureYearInLens(y);state.year=y;fillSeasons();state.match=byYear[y].matches.slice(-1)[0]?.id??null;applyTheme();drawRiver();if(state.tab!=='season'&&state.tab!=='match')state.tab='season';go(state.tab,scroll);}
function openMatch(id,scroll){const m=byId[id];if(!m)return;state.whole=false;ensureYearInLens(m.year);state.year=m.year;state.match=m.id;fillSeasons();applyTheme();drawRiver();go('match',scroll);}
function fillSeasons(){const sel=$('#season');const ss=eraSeasons();const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);sel.innerHTML=`<option value="era">${e?'Whole era':'All seasons'} · ${ss[0].year}–${ss[ss.length-1].year}</option>`+'<optgroup label="Newest first">'+ss.slice().reverse().map(s=>`<option value="${s.year}">${s.year}</option>`).join('')+'</optgroup>';sel.value=state.whole?'era':state.year;}
function setEra(id){tourStop();state.era=id;$('#eraSelect').value=id;if(id!=='all'){const e=ERAS.find(x=>x.id===id);if(!(state.year>=e.from&&state.year<=e.to)){state.year=eraSeasons().slice(-1)[0].year;state.match=byYear[state.year].matches.slice(-1)[0]?.id;}}fillSeasons();applyTheme();drawRiver();drawGrid();render();}
function init(){
  $('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.map(e=>`<option value="${e.id}">${esc(e.name)} · ${e.from}–${e.to}</option>`).join('');
  $('#theme').innerHTML=`<option value="champion">Best record’s colours</option>`+TEN.map(t=>`<option value="${esc(t.name)}">${esc(t.name)} · ${esc(t.nickname)}</option>`).join('');
  fillSeasons();
  const sides=new Set(MATCHES.flatMap(m=>[m.home,m.away])).size;
  $('#edition').innerHTML=`<span><span class="live"></span><b>${fmt(MATCHES.length)}</b> Test matches</span><span><b>${sides}</b> sides</span><span><b>${Object.keys(GROUNDS).length}</b> grounds</span><span><b>${PLAYERS.length}</b> careers</span><span><b>${COACHES.length}</b> coaches</span><span>through <b>${esc(day(A.through))}</b></span>`;
  $('#reading').open=false;state.match=byYear[state.year].matches.slice(-1)[0]?.id;
  const deep=readRoute();if(deep){tourStop();$('#eraSelect').value=state.era;fillSeasons();}
  drawSources();applyTheme();drawRiver();drawGrid();render();lightsOut();if(deep&&(state.tab!=='season'||state.whole||state.era!=='all'))setTimeout(()=>$('#stage').scrollIntoView({behavior:'auto',block:'start'}),60);
  addEventListener('hashchange',()=>{if(/^#static-/.test(location.hash)){$('#reading').open=true;return;}routeLock=true;try{if(readRoute()){tourStop();$('#eraSelect').value=state.era;fillSeasons();applyTheme();drawRiver();drawGrid();render();}}finally{routeLock=false;}});
  $('#eraSelect').addEventListener('change',e=>setEra(e.target.value));
  $('#season').addEventListener('change',e=>{if(e.target.value==='era'){state.whole=true;applyTheme();drawRiver();if(state.tab!=='season'&&state.tab!=='match')state.tab='season';go(state.tab,false);}else setSeason(+e.target.value,false);});
  $('#theme').addEventListener('change',applyTheme);
  $('#gridSort').addEventListener('change',e=>{state.gridSort=e.target.value;drawGrid();});
  $('#gridMin').addEventListener('change',e=>{state.gridMin=+e.target.value;drawGrid();});
  $('#gridFind').addEventListener('input',e=>{state.gridFind=e.target.value;drawGrid();});
  $('#eraStrip').addEventListener('click',e=>{const s=e.target.closest('[data-era]');if(s)setEra(state.era===s.dataset.era?'all':s.dataset.era);});
  $('#eraStrip').addEventListener('pointerenter',()=>{tourPause();},{passive:true});$('#eraStrip').addEventListener('pointerleave',()=>{if(!tour.stopped)tourStart();},{passive:true});
  $('#eraStrip').addEventListener('mouseover',e=>{const s=e.target.closest('[data-era]');if(s&&!tour.stopped){drawEraStrip(s.dataset.era);}});
  if('IntersectionObserver' in window){new IntersectionObserver(en=>{tour.visible=en[0].isIntersecting;if(tour.visible)tourStart();else tourPause();},{threshold:.2}).observe($('#eraStrip'));}else{tour.visible=true;tourStart();}
  $('#circuits').addEventListener('click',e=>{const b=e.target.closest('[data-cid]');if(b){state.ground=b.dataset.cid;go('grounds');}});
  const clear=t=>{if(t==='nations')state.nation=null;if(t==='players')state.player=null;if(t==='grounds')state.ground=null;if(t==='coaches')state.coach=null;};
  $('#tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;clear(b.dataset.tab);go(b.dataset.tab,false);});
  $('#view').addEventListener('click',e=>{const a=e.target.closest('[data-nation],[data-player],[data-ground],[data-coach],[data-match],[data-year],[data-tab]');if(!a)return;if(a.tagName==='A')e.preventDefault();
    if(a.dataset.tab){clear(a.dataset.tab);go(a.dataset.tab,false);return;}
    if(a.dataset.year){const y=+a.dataset.year;ensureYearInLens(y);state.whole=false;state.year=y;fillSeasons();applyTheme();drawRiver();state.match=byYear[y].matches.slice(-1)[0]?.id;go('season',false);return;}
    if(a.dataset.match){openMatch(+a.dataset.match,false);return;}
    if(a.dataset.nation){state.nation=a.dataset.nation;go('nations',false);return;}
    if(a.dataset.player){state.player=a.dataset.player;go('players',false);return;}
    if(a.dataset.ground){state.ground=a.dataset.ground;go('grounds',false);return;}
    if(a.dataset.coach){state.coach=a.dataset.coach;go('coaches',false);return;}});
  $('#view').addEventListener('change',e=>{const t=e.target;if(t.id==='lens'){state.lens=t.value;render();}else if(t.id==='plens'){state.plens=t.value;render();}else if(t.id==='heatMetric'){state.heat=t.value;render();}else if(t.id==='duelBy'){state.duelBy=t.value;state.dA=state.dB=null;render();}else if(t.id==='dA'){state.dA=t.value;render();}else if(t.id==='dB'){state.dB=t.value;render();}});
  $('#view').addEventListener('input',e=>{if(e.target.id==='find2'){state.find2=e.target.value;const pos=e.target.selectionStart;render();const f=$('#find2');if(f){f.focus();f.setSelectionRange(pos,pos);}}});
  const src=$('#sources');if(src)src.addEventListener('click',()=>{$('#sourcesBox').open=true;$('#sourcesBox').scrollIntoView({behavior:RM?'auto':'smooth'});});
  let rt;addEventListener('resize',()=>{clearTimeout(rt);rt=setTimeout(()=>{drawRiver();if(state.tab==='season')render();},150);});
}
StageNav.mount({seasons:()=>eraSeasons(),year:()=>state.year,whole:()=>state.whole,tab:()=>state.tab,setYear:y=>setSeason(y,false),unitTab:'match',unitName:'Test',units:s=>s.matches.map(m=>({key:m.id,label:dm(m.date)+' '+code(m.home)+'–'+code(m.away)})),unit:()=>state.match,setUnit:k=>{state.match=k;go('match',false);}});
StageSearch.mount({placeholder:'Find a nation, player, ground, coach, season or Test',groups:[
  {kind:'Nations',items:()=>TEN_NAMES.map(n=>({label:n,sub:teamBy[n]?.nickname||'',rank:MATCHES.filter(m=>m.home===n||m.away===n).length,open:()=>{state.nation=n;go('nations',false);}}))},
  {kind:'Players',items:()=>PLAYERS.map(p=>({label:p.name,rank:(p.caps||0)+p.games.length*0.5,keys:[p.fullName||''],sub:`${p.team||''}${p.caps?' · '+p.caps+' caps':p.games.length?' · '+p.games.length+' Tests captured':''}`,open:()=>{state.player=p.id;go('players',false);}}))},
  {kind:'Grounds',items:()=>{const n={};for(const m of MATCHES)if(m.stadium)n[m.stadium]=(n[m.stadium]||0)+1;return Object.values(GROUNDS).map(g=>({label:groundName(g.id),rank:n[g.id]||0,sub:[g.city,g.country].filter(Boolean).join(' · '),open:()=>{state.ground=g.id;go('grounds',false);}}));}},
  {kind:'Coaches',items:()=>COACHES.map(c=>({label:c.name,rank:(c.matches||[]).length,sub:`${c.team} · ${(c.spells||[]).join(', ')}`,open:()=>{state.coach=c.id;go('coaches',false);}}))},
  {kind:'Seasons',items:()=>S.map(s=>({label:String(s.year),sub:`${s.matches.length} Tests`,keys:['season'],open:()=>setSeason(s.year,false)}))},
  {kind:'Tests',items:()=>MATCHES.map(m=>({label:`${m.home} v ${m.away}`,sub:`${dm(m.date)} ${m.date.slice(0,4)} · ${m.hs}–${m.as_}${m.venue?' · '+m.venue:''}`,keys:[m.date.slice(0,4)],open:()=>openMatch(m.id,false)}))}]});
init();
