/* ---------- II · the Course: the Mountain Course to its mapped line, with its named places ---------- */
let coursePath=null;
function drawCourse(){const svg=$('#courseSvg');const L=COURSE.landmarks||[];const major=new Set(['Bray Hill','Quarterbridge','Braddan Bridge','Union Mills','Crosby','Greeba Castle','Ballacraine','Glen Helen','Kirk Michael','Ballaugh Bridge','Sulby Bridge','Ramsey Hairpin','Gooseneck','Bungalow','Windy Corner','Creg-ny-baa','Hillberry Corner','Signpost Corner',"Governor's Bridge","Governor's Dip",'Tourist Trophy course start line','The Highlander','Rhencullen','Quarry Bends','Parliament Square','Mountain Box','Brandywell','Kate\'s Cottage','Barregarrow Crosroads','Ballacraine']);
  const lab=L.filter(l=>major.has(l.n)||/bridge|hairpin|bungalow|creg|signpost|start/i.test(l.n));
  svg.innerHTML=`<path class="glow" d="${COURSE.d}"/><path class="line" id="courseLine" d="${COURSE.d}"/>${L.map(l=>`<circle class="lm${state.place===l.n?' on':''}" data-place="${esc(l.n)}" cx="${l.x}" cy="${l.y}" r="3.2"><title>${esc(l.n)}</title></circle>`).join('')}${lab.map(l=>`<text class="lmt" x="${l.x>360?l.x-6:l.x+6}" y="${l.y+3}"${l.x>360?' text-anchor="end"':''}>${esc(l.n.replace('Tourist Trophy course start line','Start · Grandstand'))}</text>`).join('')}<g id="replayLayer"></g>`;
  coursePath=$('#courseLine');
  const km=COURSE.km,mi=COURSE.miles;
  $('#courseLede').innerHTML=`The Snaefell Mountain Course, drawn to its mapped line: <b>${mi} miles</b> (${km} km) of public road from the Grandstand on Glencrutchery Road down Bray Hill, west to Ballacraine, north through Kirk Michael and Ballaugh to Ramsey, then over the mountain past the Bungalow and Creg-ny-Baa and home. Every named place below sits on the line. The four TTs of 1907–1910 ran on the shorter St John’s course and the smaller classes of 1954–1959 on the Clypse Course; those races are on the Stage, and the mountain is the only course the archive can draw.`;
  $('#places').innerHTML=L.map((l,i)=>`<button type="button" class="place${state.place===l.n?' on':''}" data-place="${esc(l.n)}"><span class="k">${String(Math.round(l.t*mi*10)/10).padStart(4,' ')} mi</span><span>${esc(l.n.replace('Tourist Trophy course start line','Start line · Grandstand'))}</span></button>`).join('');
  const others=Object.entries(COURSES).filter(([n])=>n!=='Mountain Course');
  $('#otherCourses').innerHTML=others.map(([n,c])=>{const races=RACES.filter(r=>r.course===n).length;return `<div class="kpi"><span>${esc(n)}</span><b>${c.km} km</b><small>${c.from?`${c.from}${c.to?'–'+c.to:''} · `:''}${races} race${races===1?'':'s'} · ${esc(c.note)}</small></div>`;}).join('');}
function placeAt(t){if(!coursePath)return null;const len=coursePath.getTotalLength();const p=coursePath.getPointAtLength(((t%1)+1)%1*len);return [p.x,p.y];}

/* ---------- Stage: tabs, era strip, era context ---------- */
const TABS=[['season','Season'],['race','Race'],['riders','Riders'],['marques','Marques'],['classes','Classes'],['records','Records'],['barcode','Barcode'],['duel','Duel']];
function drawTabs(){$('#tabs').innerHTML=TABS.map(([id,l])=>`<button type="button" role="tab" data-tab="${id}" aria-pressed="${state.tab===id}">${l}</button>`).join('');
  $('#stageStatus').textContent=(state.tab==='season'||state.tab==='race')&&!state.whole?`${state.year} · ${eraOf(state.year)?.name||''} · ${lensLabel()}`:eraLabel();}
function drawEraStrip(preview){const strip=$('#eraStrip');if(!strip.children.length)strip.innerHTML=ERAS.map(e=>`<button type="button" style="--w:${e.to-e.from+1}" data-era="${e.id}" title="${esc(e.name)} · ${e.from}–${e.to}" aria-label="${esc(e.name)} ${e.from}–${e.to}"></button>`).join('');
  for(const b of strip.children){b.classList.toggle('on',state.era===b.dataset.era);b.classList.toggle('demo',preview===b.dataset.era);}
  const e=preview?ERAS.find(x=>x.id===preview):state.era==='all'?eraOf(state.year):ERAS.find(x=>x.id===state.era);
  $('#eraCaption').innerHTML=`<span><b>${esc(e.name)}</b> · ${e.from}–${e.to}</span><span class="dim">${state.era===e.id?'Lens on · click again to release':'Click a segment to focus the whole page on that era'}</span>`;
  const ctx=$('#eraContext');ctx.innerHTML=`<div class="era-car">${e.ball.svg}</div><div><p class="eyebrow">${state.era===e.id?'Era lens':preview?'Era':'Era of the selected year'} · ${e.from}–${e.to}</p><h3>${esc(e.name)}</h3><p>${esc(e.text)}</p><div class="chips">${e.ball.features.map(f=>`<span>${esc(f)}</span>`).join('')}</div><p class="small dim" style="margin:10px 0 0">${esc(e.ball.label)} · an editorial reading of the period; the archive itself is not divided</p></div>`;}
const tour={i:-1,timer:null,visible:false,stopped:RM};
function tourStep(){if(tour.stopped||!tour.visible)return;tour.i=(tour.i+1)%ERAS.length;const ctx=$('#eraContext');ctx.classList.add('swap');setTimeout(()=>{if(tour.stopped)return;drawEraStrip(ERAS[tour.i].id);ctx.classList.remove('swap');},260);tour.timer=setTimeout(tourStep,4200);}
function tourStart(){if(tour.stopped||tour.timer)return;tour.timer=setTimeout(tourStep,1800);}
function tourPause(){clearTimeout(tour.timer);tour.timer=null;}
function tourStop(){if(tour.stopped)return;tour.stopped=true;tourPause();$('#eraContext').classList.remove('swap');drawEraStrip();}

/* ---------- shared pieces ---------- */
const rl=id=>`<a href="#" data-rider="${esc(id)}" style="color:inherit">${esc(pname(id))}</a>`;
const crewLinks=ids=>(ids||[]).map(rl).join(' / ');
const speedStr=v=>v?`${v.toFixed(2)} mph`:'—';
function raceCard(r,on){const w=r.winner;return `<button type="button" class="cal${on?' on':''}" data-race="${esc(r.id)}" style="${w?teamVar(w.marque):'--team:#5b616b'}"><div class="rd">${r.date?esc(dm(r.date))+' · ':''}${esc(r.course==='Mountain Course'?'Mountain':r.course.replace(' Course','').replace(' Circuit',''))}${r.laps?' · '+r.laps+' laps':''}</div><div class="sc"><span>${w&&w.mph?w.mph.toFixed(1):'—'}<small>mph</small></span></div><div class="nm">${esc(r.name)}</div><div class="w">${w?'<i class="dot" style="--c:'+color(w.marque)+'"></i>'+esc(crewName(w.crew))+' · '+esc(w.marque):'no result recorded'}</div></button>`;}
function bars(rows,valOf,subOf,max,attr,nameOf,colorOf,unit=''){return `<div class="board">${rows.map((a,i)=>`<button type="button" class="bar" data-${attr}="${esc(a.id)}" style="--i:${i};--team:${colorOf(a)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(nameOf(a))}</span><small>${subOf(a)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*valOf(a)/(max||1))}%"></span></span></span><span class="val">${valOf(a)==null?'—':fmt(valOf(a))}${unit}</span></button>`).join('')}</div>`;}
const riderBars=(rows,valOf,subOf,max,unit='')=>bars(rows,valOf,subOf,max,'rider',a=>pname(a.id),a=>color(a.top||Object.keys(a.marques||{})[0]||'Unrecorded'),unit);
const marqueBars=(rows,valOf,subOf,max,unit='')=>bars(rows,valOf,subOf,max,'marque',a=>a.id,a=>color(a.id),unit);
function drawChart(el,series,n,labelOf,xl,colorOf,ylabel){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(200,box.height);const padL=40,padR=130,padT=14,padB=26;const vals=series.flatMap(s=>s.pts.filter(v=>v!=null));const max=Math.max(1,...vals),min=Math.min(0,...vals);const x=i=>padL+(n>1?i*(W-padL-padR)/(n-1):0),y=v=>padT+(H-padT-padB)*(1-(v-min)/((max-min)||1));
  let g='';const step=max>200?50:max>60?25:max>20?10:max>8?5:1;for(let v=Math.ceil(min/step)*step;v<=max;v+=step)g+=`<line class="gridl" x1="${padL}" x2="${W-padR}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}"/><text class="lb" x="${padL-6}" y="${(y(v)+3).toFixed(1)}" text-anchor="end">${v}</text>`;
  for(let i=0;i<n;i++){const l=xl(i);if(l)g+=`<text class="lb" x="${x(i).toFixed(1)}" y="${H-8}" text-anchor="middle">${esc(l)}</text>`;}
  const paths=series.map(s=>{let d='',pen=false;s.pts.forEach((v,i)=>{if(v==null){pen=false;return;}d+=(pen?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1);pen=true;});const lastI=s.pts.map((v,i)=>v!=null?i:-1).filter(i=>i>=0).pop();const last=lastI!=null?s.pts[lastI]:null;return `<path class="ser" d="${d}" style="--c:${colorOf(s.id)}"><title>${esc(labelOf(s.id))}</title></path>${last!=null?`<text class="end" x="${(x(lastI)+6).toFixed(1)}" y="${(y(last)+4).toFixed(1)}" style="--c:${colorOf(s.id)}">${esc(labelOf(s.id))} ${fmt(last)}</text>`:''}`;}).join('');
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(ylabel||'Chart')}">${g}${paths}</svg>`;}

/* ---------- Season: TT week ---------- */
function seasonView(){if(state.whole)return eraView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No races in this lens.</p>';return;}
  const {best,ranked,senior,fastest}=champOf(s);const partial=s.year===A.lastYear&&!s.races.every(r=>r.winner);
  const podium=ranked.slice(0,3);const order=[podium[1],podium[0],podium[2]];const marques={};for(const r of s.races)if(r.winner)marques[r.winner.marque]=(marques[r.winner.marque]||0)+1;const mrows=Object.entries(marques).sort((a,b)=>b[1]-a[1]);
  const lead=best?Object.entries(best.marques).sort((a,b)=>b[1]-a[1])[0][0]:null;
  const head=`<div class="season-head"><div class="champ-card" style="${lead?`--accent:${color(lead)};--on-accent:${onColor(color(lead))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${partial?'TT week in progress':'TT week'} · ${esc(lensLabel())}</p><div class="yr">${s.year}</div>${best?`<div class="who"><small>Most wins of the week · ${best.wins} win${best.wins===1?'':'s'}</small><a href="#" data-rider="${esc(best.id)}" style="color:inherit;text-decoration:none">${esc(pname(best.id))}</a></div><div class="team"><i></i>${esc(lead)}</div><div class="facts"><div><b>${s.races.length}</b>races</div><div><b>${mrows.length}</b>winning marques</div>${fastest?`<div><b>${fastest.speed.toFixed(1)}</b>fastest average, mph</div>`:''}<div><b>${s.races.reduce((a,r)=>a+r.results.length,0)}</b>recorded results</div></div>`:`<div class="who"><small>No results recorded</small>—</div>`}
  ${senior?`<p class="small" style="margin:14px 0 0;color:var(--ink);opacity:.85">Senior TT: <b>${esc(crewName(senior.winner.crew))}</b> · ${esc(senior.winner.marque)}${senior.winner.mph?' · '+senior.winner.mph.toFixed(2)+' mph':''}</p>`:''}<p class="small dim" style="margin:${senior?6:18}px 0 0">Ranked by wins in the week, the Senior winner first among equals; a reading of the results, not an award.</p></div>
  <div><div class="podium">${order.map((d,i)=>d?`<button type="button" class="step p${podium.indexOf(d)+1} bar" data-rider="${esc(d.id)}" style="--h:${Math.round(120+120*d.wins/Math.max(1,podium[0].wins))}px;--team:${color(Object.entries(d.marques).sort((a,b)=>b[1]-a[1])[0][0])};display:flex"><span class="pos">${podium.indexOf(d)+1}</span><span class="nm">${esc(pname(d.id))}</span><span class="pt">${d.wins} win${d.wins===1?'':'s'} · ${d.races.map(r=>r.name).join(', ')}</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const cal=`<div class="h3"><span>The week’s races</span><small>${s.races.length} races · click one to open it</small></div><div class="calendar">${s.races.map(r=>raceCard(r,state.race===r.id&&state.tab==='race')).join('')}</div>`;
  const speeds=s.races.filter(r=>r.speed).sort((a,b)=>b.speed-a.speed);
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Marques of the week</span><small>by wins</small></div>${marqueBars(mrows.map(([id,w])=>({id,w})),a=>a.w,a=>`${s.races.filter(r=>r.winner&&r.winner.marque===a.id).map(r=>r.name).join(', ')}`,mrows[0]?.[1]||1)}</div><div class="panel"><div class="h3"><span>Fastest races of the week</span><small>winner’s race average</small></div><div class="board">${speeds.map((r,i)=>`<button type="button" class="bar" data-race="${esc(r.id)}" style="--i:${i};--team:${color(r.winner.marque)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(r.name)}<small> ${esc(crewName(r.winner.crew))}</small></span><small>${esc(r.winner.machine||r.winner.marque)}${r.laps?' · '+r.laps+' laps':''}${r.winner.time?' · '+esc(r.winner.time):''}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*r.speed/(speeds[0].speed||1))}%"></span></span></span><span class="val">${r.speed.toFixed(2)}</span></button>`).join('')||'<p class="muted small">No race averages recorded for this year.</p>'}</div></div></div>`;
  $('#view').innerHTML=head+cal+body;}
function eraView(){const ss=eraSeasons();const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);const races=eraRaces();
  const riders=riderAgg().sort(riderOrder);const top=riders[0];const marques=marqueAgg().sort((a,b)=>b.wins-a.wins).slice(0,12);
  const head=`<div class="season-head"><div class="champ-card" style="${top?`--accent:${color(top.top||'Unrecorded')};--on-accent:${onColor(color(top.top||'Unrecorded'))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${e?'Whole era':'All years'} · ${esc(lensLabel())}</p><div class="yr" style="font-size:clamp(44px,6vw,84px)">${ss[0]?.year}–${ss[ss.length-1]?.year}</div>${top?`<div class="who"><small>Most wins across the period · ${top.wins} win${top.wins===1?'':'s'} · ${top.pod} podiums</small><a href="#" data-rider="${esc(top.id)}" style="color:inherit;text-decoration:none">${esc(pname(top.id))}</a></div><div class="team"><i></i>${esc(top.top||'')}</div>`:''}<div class="facts"><div><b>${fmt(races.length)}</b>races</div><div><b>${ss.length}</b>TT weeks</div><div><b>${fmt(riders.length)}</b>riders</div><div><b>${fmt(races.reduce((a,r)=>a+r.results.length,0))}</b>recorded results</div></div></div>
  <div><div class="podium">${[riders[1],riders[0],riders[2]].map((d,i)=>d?`<button type="button" class="step p${riders.indexOf(d)+1} bar" data-rider="${esc(d.id)}" style="--h:${Math.round(120+120*d.wins/Math.max(1,riders[0].wins))}px;--team:${color(d.top||'Unrecorded')};display:flex"><span class="pos">${riders.indexOf(d)+1}</span><span class="nm">${esc(pname(d.id))}</span><span class="pt">${d.wins} wins · ${d.first}–${d.last}</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const roll=ss.map(s=>({s,c:champOf(s)}));
  const rollHtml=`<div class="h3"><span>Most wins, week by week</span><small>click a year to open it</small></div><div class="calendar">${roll.map(({s,c})=>`<button type="button" class="cal" data-year="${s.year}" style="--team:${c.best?color(Object.entries(c.best.marques).sort((a,b)=>b[1]-a[1])[0][0]):'#5b616b'}"><div class="rd">${s.year} · ${s.races.length} races</div><div class="nm">${c.best?esc(pname(c.best.id)):'—'}</div><div class="w">${c.best?c.best.wins+' win'+(c.best.wins===1?'':'s'):''}${c.fastest?' · '+c.fastest.speed.toFixed(1)+' mph':''}</div></button>`).join('')}</div>`;
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Marques across the period</span><small>by wins</small></div>${marqueBars(marques,a=>a.wins,a=>`${a.nw} different winners · ${a.first}–${a.last}`,Math.max(1,...marques.map(a=>a.wins)))}</div><div class="panel"><div class="h3"><span>Riders across the period</span><small>by wins, then podiums</small></div>${riderBars(riders.slice(0,12),a=>a.wins,a=>`${a.pod} podiums · ${a.starts} recorded starts · ${a.first}–${a.last}`,Math.max(1,...riders.slice(0,12).map(a=>a.wins)))}</div></div>`;
  $('#view').innerHTML=head+rollHtml+body;}

/* ---------- Race: the sheet and the lap replay ---------- */
let replay=null;
function stopReplay(){if(replay){cancelAnimationFrame(replay.raf);replay=null;}const g=$('#replayLayer');if(g)g.innerHTML='';const st=$('#courseStatus');if(st)st.textContent='';}
function raceView(){if(state.whole)return eraRacesView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No races in this lens.</p>';return;}let r=byId[state.race];if(!r||r.year!==s.year||!inLens(r))r=s.races[0];state.race=r.id;
  const nav=`<div class="chiplist" style="margin-top:20px">${s.races.map(x=>`<button type="button" class="chip${x.id===r.id?' on':''}" data-race="${esc(x.id)}" style="${x.id===r.id?'border-color:var(--accent);color:var(--accent)':''}"><i style="--c:${x.winner?color(x.winner.marque):'#444'}"></i>${esc(x.name)}</button>`).join('')}</div>`;
  const w=r.winner;const c=COURSES[r.course]||{};const dist=r.laps&&c.km?Math.round(r.laps*c.km*10)/10:null;
  const hero=`<div class="card" style="margin-top:18px;grid-template-columns:1fr;${w?teamVar(w.marque):''}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:18px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">${r.year} · ${esc(r.family)} · ${esc(r.course)}${r.laps?' · '+r.laps+' laps':''}${dist?' · '+dist+' km':''}${r.date?' · '+esc(day(r.date)):''}${r.scope==='support'?' · support race':''}</p><h2 style="margin:6px 0 0">${esc(r.name)} TT <span class="muted" style="font-size:.6em;font-weight:600;font-style:normal">${r.year}</span></h2></div>${w?`<div class="champline" style="--team:${color(w.marque)}"><span class="eyebrow">Winner</span><b>${crewLinks(w.crew)}</b><span class="small muted">${esc(w.machine||w.marque)}${w.mph?' · '+w.mph.toFixed(2)+' mph':''}${w.time?' · '+esc(w.time):''}</span></div>`:'<div class="champline"><span class="eyebrow">Winner</span><b class="muted">not recorded</b></div>'}</div></div>`;
  const rows=[...r.results].sort((a,b)=>(a.pos==null)-(b.pos==null)||(a.pos||0)-(b.pos||0));const fastest=Math.max(...rows.map(x=>x.mph||0));
  const table=`<div class="panel" style="margin-top:18px"><div class="h3"><span>Classification</span><small>${rows.length} recorded result${rows.length===1?'':'s'}${rows.length===1?' · the archive holds the winner alone for this race':''}</small></div><div class="tablewrap" style="max-height:none"><table><tr><th>Pos</th><th>Rider</th><th>Machine</th><th>Marque</th><th class="n">Time</th><th class="n">Average</th><th></th></tr>${rows.map(x=>`<tr class="${x.pos===1?'win':''}"><td class="n"><b>${x.pos??'—'}</b></td><td>${crewLinks(x.crew)}</td><td class="muted">${esc(x.machine||'')}</td><td><i class="dot" style="--c:${color(x.marque)}"></i><a href="#" data-marque="${esc(x.marque)}" style="color:inherit">${esc(x.marque)}</a>${x.mq==='machine'?' <span class="dim" title="marque read from the machine description">·</span>':''}</td><td class="n mono">${esc(x.time||'')}</td><td class="n">${x.mph?x.mph.toFixed(2):''}</td><td>${x.mph?`<span class="spd"><i style="width:${Math.round(100*x.mph/fastest)}%;background:${color(x.marque)}"></i></span>`:''}${!x.fin?`<span class="dim small">${esc(x.status)}</span>`:''}</td></tr>`).join('')}</table></div></div>`;
  const podium=rows.filter(x=>x.pos&&x.pos<=3&&x.mph);
  const replayHtml=r.course==='Mountain Course'&&podium.length?`<div class="panel" style="margin-top:18px"><div class="h3"><span>The lap, symbolically</span><small>${podium.length===1?'the winner':'the podium'} around the Mountain Course at recorded race average · <button type="button" class="linkbtn" id="replayGo">replay</button></small></div><div class="course-replay"><svg viewBox="0 0 500 500" id="replaySvg" aria-label="Race replay"><path class="glow" d="${COURSE.d}"/><path class="line" id="replayLine" d="${COURSE.d}"/>${(COURSE.landmarks||[]).filter(l=>/Ballacraine|Ramsey Hairpin|Bungalow|Creg-ny-baa|start line|Ballaugh|Kirk Michael|Glen Helen|Windy/i.test(l.n)).map(l=>`<text class="lmt" x="${l.x>360?l.x-6:l.x+6}" y="${l.y+3}"${l.x>360?' text-anchor="end"':''}>${esc(l.n.replace('Tourist Trophy course start line','Start'))}</text>`).join('')}<g id="replayDots"></g></svg><div class="replay-side"><div id="courseStatus" class="mono small muted"></div><div class="legend" id="replayLegend">${podium.map(x=>`<span><i style="background:${color(x.marque)}"></i>${esc(crewName(x.crew))} · ${x.mph.toFixed(1)} mph</span>`).join('')}</div><p class="small dim">Each dot circles the mapped course at its rider’s recorded race average, ${r.laps||'the'} lap${r.laps===1?'':'s'} compressed into ten seconds; positions along the lap are proportional to speed, not a record of where anyone was.</p></div></div></div>`:'';
  $('#view').innerHTML=nav+hero+table+replayHtml;
  if(replayHtml){const go=()=>runReplay(r,podium);$('#replayGo').onclick=go;if(!RM)go();}}
function runReplay(r,podium){stopReplay();const line=$('#replayLine');if(!line)return;const len=line.getTotalLength();const dots=$('#replayDots');const laps=r.laps||1;const lead=podium[0].mph;const dur=RM?1:10000;
  dots.innerHTML=podium.map((x,i)=>`<circle r="${i===0?7:5.5}" fill="${color(x.marque)}" stroke="#07080a" stroke-width="1.5"/>`).join('');const cs=[...dots.children];
  const rp={raf:0,t0:null};replay=rp;
  const tick=now=>{if(replay!==rp)return;if(rp.t0==null)rp.t0=now;const p=Math.min(1,(now-rp.t0)/dur);cs.forEach((c,i)=>{const frac=p*laps*(podium[i].mph/lead);const pt=line.getPointAtLength(((frac%1)+1)%1*len);c.setAttribute('cx',pt.x.toFixed(1));c.setAttribute('cy',pt.y.toFixed(1));});const st=$('#courseStatus');if(st)st.textContent=`lap ${Math.min(laps,Math.floor(p*laps)+1)} of ${laps} · ${Math.round(p*100)}%`;if(p<1)rp.raf=requestAnimationFrame(tick);else{const st2=$('#courseStatus');if(st2)st2.textContent=`chequered flag · ${crewName(podium[0].crew)} · ${podium[0].mph.toFixed(2)} mph`;}};
  rp.raf=requestAnimationFrame(tick);}
function eraRacesView(){const races=eraRaces().filter(r=>r.speed).sort((a,b)=>b.speed-a.speed).slice(0,40);const byFam={};for(const r of eraRaces())(byFam[r.family]||(byFam[r.family]=[])).push(r);
  $('#view').innerHTML=`<div class="h3" style="margin-top:20px"><span>Fastest races across the period</span><small>winner’s race average · click one to open it</small></div><div class="panel"><div class="board">${races.map((r,i)=>`<button type="button" class="bar" data-race="${esc(r.id)}" data-year="${r.year}" style="--i:${i};--team:${color(r.winner.marque)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(crewName(r.winner.crew))}<small> ${esc(r.name)} ${r.year}</small></span><small>${esc(r.winner.machine||r.winner.marque)}${r.laps?' · '+r.laps+' laps':''}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*r.speed/(races[0].speed||1))}%"></span></span></span><span class="val">${r.speed.toFixed(2)}</span></button>`).join('')||'<p class="muted small">No race averages recorded in this lens.</p>'}</div></div>
  <div class="h3" style="margin-top:22px"><span>Every race of the period, by class</span><small>${eraRaces().length} races</small></div>${Object.entries(byFam).sort((a,b)=>b[1].length-a[1].length).map(([f,rs])=>`<div class="panel" style="margin-top:12px"><div class="h3"><span>${esc(f)}</span><small>${rs.length} races</small></div><div class="chiplist">${rs.map(r=>`<button type="button" class="chip" data-race="${esc(r.id)}" data-year="${r.year}"><i style="--c:${r.winner?color(r.winner.marque):'#444'}"></i>${r.year} ${esc(r.name)}${r.winner?' · '+esc(crewName(r.winner.crew)):''}</button>`).join('')}</div></div>`).join('')}`;}
