/* ---------- Riders ---------- */
function ridersView(){const list=riderAgg();const lens=state.plens;let rows=list.filter(p=>p[lens]!=null);if(lens==='rate')rows=rows.filter(p=>p.starts>=10);rows.sort((a,b)=>b[lens]-a[lens]||b.wins-a.wins||b.pod-a.pod);rows=rows.slice(0,40);
  const max=Math.max(1,...rows.map(a=>a[lens]));const q=(state.find2||'').toLowerCase();const found=q?Object.entries(RIDERS).filter(([id,p])=>p.name.toLowerCase().includes(q)).slice(0,14):[];
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Riders · ${esc(eraLabel())}</h2></div><div class="small mono muted">${fmt(list.length)} riders with a recorded result</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><input type="search" id="find2" placeholder="Search a rider" value="${esc(state.find2||'')}" aria-label="Search"><select id="lens" aria-label="Lens">${Object.entries(PLENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(PLENSES[lens][1])}</span></div>${q?`<div class="chiplist" style="margin-bottom:14px">${found.map(([id,p])=>`<button type="button" class="chip" data-rider="${esc(id)}">${esc(p.name)}</button>`).join('')||'<span class="muted small">No match.</span>'}</div>`:''}
  ${riderBars(rows,a=>a[lens],a=>`${a.first}–${a.last} · ${a.wins} wins · ${a.pod} podiums · ${a.starts} starts${a.top?' · '+a.top:''}`,max,/rate/.test(lens)?'%':'')}</div>`;
  $('#find2').addEventListener('input',e=>{state.find2=e.target.value;ridersView();$('#find2').focus();const v=$('#find2');v.setSelectionRange(v.value.length,v.value.length);});$('#lens').addEventListener('change',e=>{state.plens=e.target.value;render();});}
function riderView(id){const p=RIDERS[id];if(!p){ridersView();return;}const all=riderAgg();const a=all.find(x=>x.id===id);const rank=[...all].sort(riderOrder).findIndex(x=>x.id===id)+1;
  const rows=eraRaces().flatMap(r=>r.results.filter(x=>x.crew.includes(id)).map(x=>({r,x}))).sort((u,v)=>v.r.year-u.r.year||(u.r.date||'')<(v.r.date||'')?1:-1);
  const wins=rows.filter(({x})=>x.pos===1);const byF={};for(const {r,x} of rows){const f=byF[r.family]||(byF[r.family]={f:r.family,starts:0,wins:0,pod:0});f.starts++;if(x.pos===1)f.wins++;if(x.pos&&x.pos<=3)f.pod++;}
  const byY={};for(const {r,x} of rows){const y=byY[r.year]||(byY[r.year]={y:r.year,starts:0,wins:0,best:null});y.starts++;if(x.pos===1)y.wins++;if(x.mph&&(!y.best||x.mph>y.best))y.best=x.mph;}
  const years=Object.values(byY).sort((u,v)=>u.y-v.y);const machines={};for(const {x} of rows)machines[x.marque]=(machines[x.marque]||0)+1;
  const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b>${s?`<small>${s}</small>`:''}</div>`;
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${color(a?.top||'Unrecorded')}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Rider${a?' · '+a.first+'–'+a.last:''}${a?.top?' · '+esc(a.top):''}</p><h2 style="margin:6px 0 0">${esc(p.name)}</h2></div><div class="small mono muted">${rank?`#${rank} by wins in ${esc(eraLabel())}`:''}${p.url?` · <a href="${esc(p.url)}" target="_blank" rel="noopener" style="color:var(--muted)">Wikipedia ↗</a>`:''}</div></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Wins',a?a.wins:0,'')}${kpi('Podiums',a?a.pod:0,'')}${kpi('Recorded starts',a?a.starts:0,a?`${a.fin} classified`:'')}${kpi('Fastest race',a&&a.best?a.best.toFixed(2)+' mph':'—',a&&a.bestRace?esc(byId[a.bestRace].name+' '+byId[a.bestRace].year):'')}${kpi('TT weeks',a?a.nyears:0,a?`${a.first}–${a.last}`:'')}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Wins</span><small>${wins.length} · click one to open the race</small></div><div class="board">${wins.map(({r,x},i)=>`<button type="button" class="bar" data-race="${esc(r.id)}" data-year="${r.year}" style="--i:${i};--team:${color(x.marque)}"><span class="rk">${wins.length-i}</span><span><span class="lab"><span>${esc(r.name)}<small> ${r.year}</small></span><small>${esc(x.machine||x.marque)}${x.mph?' · '+x.mph.toFixed(2)+' mph':''}${x.crew.length>1?' · with '+esc(crewName(x.crew.filter(c=>c!==id))):''}</small></span></span><span class="val" style="font-size:12px">${esc(r.course==='Mountain Course'?'Mountain':r.course)}</span></button>`).join('')||'<p class="muted small">No wins in this lens.</p>'}</div></div>
  <div><div class="panel"><div class="h3"><span>By class</span></div>${bars(Object.values(byF).sort((u,v)=>v.wins-u.wins||v.starts-u.starts),f=>f.wins,f=>`${f.starts} starts · ${f.pod} podiums`,Math.max(1,...Object.values(byF).map(f=>f.wins)),'cls',f=>f.f,()=>color(a?.top||'Unrecorded'))}</div><div class="panel" style="margin-top:14px"><div class="h3"><span>Machines</span><small>recorded starts by marque</small></div><div class="chips">${Object.entries(machines).sort((u,v)=>v[1]-u[1]).map(([m,n])=>`<a href="#" class="chip" data-marque="${esc(m)}"><i style="--c:${color(m)}"></i>${esc(m)} <span style="color:var(--muted)">${n}</span></a>`).join('')}</div></div></div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Year by year</span><small>${years.length} TT weeks</small></div><div class="tablewrap"><table><tr><th>Year</th><th class="n">Starts</th><th class="n">Wins</th><th class="n">Fastest average</th><th>Races</th></tr>${[...years].reverse().map(y=>`<tr><td><a href="#" data-year="${y.y}">${y.y}</a></td><td class="n">${y.starts}</td><td class="n"><b>${y.wins}</b></td><td class="n">${y.best?y.best.toFixed(2):'—'}</td><td>${rows.filter(({r})=>r.year===y.y).map(({r,x})=>`<a href="#" class="q" data-race="${esc(r.id)}" data-year="${r.year}" style="color:${x.pos===1?'var(--accent)':'inherit'}">${esc(r.name)} ${x.pos?'P'+x.pos:esc(x.status)}</a>`).join(' · ')}</td></tr>`).join('')}</table></div></div>`;}

/* ---------- Marques ---------- */
function marquesView(){const list=marqueAgg().filter(a=>a.id!=='Unrecorded');const lens=state.lens;let rows=list.filter(a=>a[lens]!=null);rows.sort((a,b)=>b[lens]-a[lens]||b.wins-a.wins);rows=rows.slice(0,40);const max=Math.max(1,...rows.map(a=>a[lens]));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Marques · ${esc(eraLabel())}</h2></div><div class="small mono muted">${list.length} marques</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="lens" aria-label="Lens">${Object.entries(LENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(LENSES[lens][1])}</span></div>${marqueBars(rows,a=>a[lens],a=>`${a.first}–${a.last} · ${a.wins} wins · ${a.pod} podiums · ${a.nw} winners`,max)}</div>`;
  $('#lens').addEventListener('change',e=>{state.lens=e.target.value;render();});}
function marqueView(id){const all=marqueAgg();const a=all.find(x=>x.id===id);if(!a){marquesView();return;}const rank=[...all].sort((u,v)=>v.wins-u.wins).findIndex(x=>x.id===id)+1;
  const rows=eraRaces().flatMap(r=>r.results.filter(x=>x.marque===id).map(x=>({r,x})));const wins=rows.filter(({x})=>x.pos===1).sort((u,v)=>v.r.year-u.r.year);
  const byY={};for(const {r,x} of rows){const y=byY[r.year]||(byY[r.year]={y:r.year,starts:0,wins:0});y.starts++;if(x.pos===1)y.wins++;}const years=Object.values(byY).sort((u,v)=>u.y-v.y);const maxW=Math.max(1,...years.map(y=>y.wins));
  const riders={};for(const {x} of wins)for(const c of x.crew)riders[c]=(riders[c]||0)+1;const topR=Object.entries(riders).sort((u,v)=>v[1]-u[1]).slice(0,12);
  const byF={};for(const {r,x} of wins)byF[r.family]=(byF[r.family]||0)+1;
  const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b>${s?`<small>${s}</small>`:''}</div>`;
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${color(id)}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Marque · ${a.first}–${a.last}</p><h2 style="margin:6px 0 0"><i class="dot" style="--c:${color(id)};width:.5em;height:.5em;vertical-align:.1em;margin-right:8px"></i>${esc(id)}</h2></div><div class="small mono muted">#${rank} by wins in ${esc(eraLabel())}</div></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Wins',a.wins,'')}${kpi('Podiums',a.pod,'')}${kpi('Recorded starts',a.starts,`${a.nr} riders`)}${kpi('Different winners',a.nw,'')}${kpi('Fastest race',a.best?a.best.toFixed(2)+' mph':'—','')}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Winners on the marque</span></div>${bars(topR.map(([rid,n])=>({id:rid,n})),x=>x.n,x=>`${wins.filter(({x:w})=>w.crew.includes(x.id)).map(({r})=>r.year).sort().join(', ')}`,topR[0]?.[1]||1,'rider',x=>pname(x.id),()=>color(id))}</div>
  <div><div class="panel"><div class="h3"><span>Wins by year</span><small>${years.length} years</small></div><div class="yearbars">${years.map(y=>`<button type="button" data-year="${y.y}" title="${y.y} · ${y.wins} wins · ${y.starts} starts" style="--h:${Math.round(100*y.wins/maxW)}%;--team:${color(id)}"><i></i><span>${y.y%10===0?y.y:''}</span></button>`).join('')}</div></div><div class="panel" style="margin-top:14px"><div class="h3"><span>Wins by class</span></div><div class="chips">${Object.entries(byF).sort((u,v)=>v[1]-u[1]).map(([f,n])=>`<a href="#" class="chip" data-cls="${esc(f)}"><i style="--c:${color(id)}"></i>${esc(f)} <span style="color:var(--muted)">${n}</span></a>`).join('')||'<span class="muted small">No wins in this lens.</span>'}</div></div></div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Every win</span><small>${wins.length}</small></div><div class="tablewrap" style="max-height:520px"><table><tr><th>Year</th><th>Race</th><th>Rider</th><th>Machine</th><th class="n">Average</th></tr>${wins.map(({r,x})=>`<tr><td><a href="#" data-race="${esc(r.id)}" data-year="${r.year}">${r.year}</a></td><td>${esc(r.name)}</td><td>${crewLinks(x.crew)}</td><td class="muted">${esc(x.machine||'')}</td><td class="n">${x.mph?x.mph.toFixed(2):''}</td></tr>`).join('')}</table></div></div>`;}

/* ---------- Classes ---------- */
function classesView(){const races=eraRaces();const byF={};for(const r of races){const f=byF[r.family]||(byF[r.family]={f:r.family,n:0,first:r.year,last:r.year,fast:null,wins:{},mw:{}});f.n++;f.first=Math.min(f.first,r.year);f.last=Math.max(f.last,r.year);if(r.speed&&(!f.fast||r.speed>f.fast.speed))f.fast=r;if(r.winner){for(const c of r.winner.crew)f.wins[c]=(f.wins[c]||0)+1;f.mw[r.winner.marque]=(f.mw[r.winner.marque]||0)+1;}}
  const rows=Object.values(byF).sort((a,b)=>(FAMILY_ORDER.indexOf(a.f)+1||99)-(FAMILY_ORDER.indexOf(b.f)+1||99));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Classes · ${esc(eraLabel())}</h2></div><div class="small mono muted">${rows.length} class families · ${races.length} races</div></div><div class="panel"><div class="tablewrap"><table><tr><th>Class</th><th class="n">Races</th><th>Years</th><th>Most wins</th><th>Most wins, marque</th><th>Fastest race</th></tr>${rows.map(f=>{const tr=Object.entries(f.wins).sort((a,b)=>b[1]-a[1])[0];const tm=Object.entries(f.mw).sort((a,b)=>b[1]-a[1])[0];return `<tr><td><a href="#" data-cls="${esc(f.f)}">${esc(f.f)}</a></td><td class="n">${f.n}</td><td>${f.first}–${f.last}</td><td>${tr?rl(tr[0])+' <span class="dim">'+tr[1]+'</span>':'—'}</td><td>${tm?'<i class="dot" style="--c:'+color(tm[0])+'"></i>'+esc(tm[0])+' <span class="dim">'+tm[1]+'</span>':'—'}</td><td>${f.fast?`<a href="#" data-race="${esc(f.fast.id)}" data-year="${f.fast.year}">${f.fast.speed.toFixed(2)} mph</a> <span class="dim">${esc(crewName(f.fast.winner.crew))} ${f.fast.year}</span>`:'—'}</td></tr>`;}).join('')}</table></div><p class="small dim" style="margin:10px 0 0">Class families group the archive’s race names: Lightweight holds the 125 and 250 races of their day, Sidecar every sidecar race, Production the production classes, Formula TT the Formula One, Two and Three races.</p></div>`;}
function classView(f){const races=eraRaces().filter(r=>r.family===f);if(!races.length){classesView();return;}const wins={};const mw={};for(const r of races)if(r.winner){for(const c of r.winner.crew)wins[c]=(wins[c]||0)+1;mw[r.winner.marque]=(mw[r.winner.marque]||0)+1;}
  const topR=Object.entries(wins).sort((a,b)=>b[1]-a[1]).slice(0,12);const topM=Object.entries(mw).sort((a,b)=>b[1]-a[1]).slice(0,12);const speeds=races.filter(r=>r.speed);
  const years=[...new Set(races.map(r=>r.year))].sort((a,b)=>a-b);const bestBy={};for(const r of speeds)bestBy[r.year]=Math.max(bestBy[r.year]||0,r.speed);
  const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b>${s?`<small>${s}</small>`:''}</div>`;const fast=[...speeds].sort((a,b)=>b.speed-a.speed)[0];
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${color(topM[0]?.[0]||'Unrecorded')}"><div class="panel"><p class="eyebrow">Class family · ${races[0].year}–${races[races.length-1].year}</p><h2 style="margin:6px 0 0">${esc(f)}</h2></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Races',races.length,'')}${kpi('Years',years.length,`${years[0]}–${years[years.length-1]}`)}${kpi('Most wins',topR[0]?pname(topR[0][0]):'—',topR[0]?topR[0][1]+' wins':'')}${kpi('Fastest race',fast?fast.speed.toFixed(2)+' mph':'—',fast?esc(crewName(fast.winner.crew)+' · '+fast.year):'')}</div>
  ${speeds.length>3?`<div class="h3" style="margin-top:22px"><span>The winning average, year by year</span><small>mph · the fastest race of the family each year</small></div><div class="chart" id="classChart" style="height:260px"></div>`:''}
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Most wins</span></div>${bars(topR.map(([id,n])=>({id,n})),x=>x.n,x=>`${races.filter(r=>r.winner&&r.winner.crew.includes(x.id)).map(r=>r.year).join(', ')}`,topR[0]?.[1]||1,'rider',x=>pname(x.id),x=>color(races.find(r=>r.winner&&r.winner.crew.includes(x.id))?.winner.marque||'Unrecorded'))}</div><div class="panel"><div class="h3"><span>Most wins, marques</span></div>${marqueBars(topM.map(([id,n])=>({id,wins:n})),x=>x.wins,x=>`${races.filter(r=>r.winner&&r.winner.marque===x.id).map(r=>r.year).slice(0,12).join(', ')}${races.filter(r=>r.winner&&r.winner.marque===x.id).length>12?'…':''}`,topM[0]?.[1]||1)}</div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Every race</span><small>${races.length}</small></div><div class="tablewrap" style="max-height:560px"><table><tr><th>Year</th><th>Race</th><th>Course</th><th>Winner</th><th>Machine</th><th class="n">Average</th></tr>${[...races].reverse().map(r=>`<tr><td><a href="#" data-race="${esc(r.id)}" data-year="${r.year}">${r.year}</a></td><td>${esc(r.name)}</td><td class="muted">${esc(r.course)}</td><td>${r.winner?crewLinks(r.winner.crew):'—'}</td><td class="muted">${r.winner?esc(r.winner.machine||r.winner.marque):''}</td><td class="n">${r.speed?r.speed.toFixed(2):''}</td></tr>`).join('')}</table></div></div>`;
  if(speeds.length>3){const ys=years.filter(y=>bestBy[y]);drawChart($('#classChart'),[{id:f,pts:ys.map(y=>bestBy[y])}],ys.length,()=>f,i=>ys[i]%10===0||i===0||i===ys.length-1?String(ys[i]):'',()=>color(topM[0]?.[0]||'Unrecorded'),'Winning average by year');}}

/* ---------- Records ---------- */
function recordsView(){const races=eraRaces();const riders=riderAgg().sort(riderOrder);const marques=marqueAgg().filter(a=>a.id!=='Unrecorded').sort((a,b)=>b.wins-a.wins);const speeds=races.filter(r=>r.speed).sort((a,b)=>b.speed-a.speed);
  const weeks=eraSeasons().map(s=>({s,c:champOf(s)})).filter(x=>x.c.best).sort((a,b)=>b.c.best.wins-a.c.best.wins||b.s.year-a.s.year).slice(0,10);
  const sidecar=riderAgg().filter(a=>a.fams['Sidecar']).sort((a,b)=>(b.fams['Sidecar']||0)-(a.fams['Sidecar']||0)).slice(0,10);
  const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b><small>${s}</small></div>`;
  const senior=races.filter(r=>r.family==='Senior'&&r.speed);const ys=[...new Set(senior.map(r=>r.year))].sort((a,b)=>a-b);
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Records · ${esc(eraLabel())}</h2></div><div class="small mono muted">${fmt(races.length)} races</div></div>
  <div class="kpis">${kpi('Races',fmt(races.length),`${eraSeasons().length} TT weeks`)}${kpi('Riders',fmt(riders.length),`${riders.filter(r=>r.wins).length} winners`)}${kpi('Marques',marques.length,`${marques.filter(m=>m.wins).length} with a win`)}${kpi('Fastest race',speeds[0]?speeds[0].speed.toFixed(2)+' mph':'—',speeds[0]?esc(crewName(speeds[0].winner.crew)+' · '+speeds[0].name+' '+speeds[0].year):'')}${kpi('Recorded results',fmt(races.reduce((a,r)=>a+r.results.length,0)),'')}</div>
  ${state.era==='all'&&state.family==='all'?`<div class="three" style="margin-top:20px"><div class="panel" style="grid-column:1/-1"><div class="h3"><span>Lap records</span><small>the standing records by class, as published · a lap, not a race average</small></div><div class="tablewrap"><table><tr><th>Class</th><th>Rider</th><th>Machine</th><th class="n">Year</th><th class="n">Time</th><th class="n">mph</th></tr>${RECORDS.map(r=>`<tr><td>${esc(r.category)}</td><td>${esc(r.rider)}</td><td class="muted">${esc(r.machine)}</td><td class="n">${r.year}</td><td class="n mono">${esc(r.time)}</td><td class="n"><b>${r.mph}</b></td></tr>`).join('')}</table></div></div></div>`:''}
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Most wins</span></div>${riderBars(riders.slice(0,10),a=>a.wins,a=>`${a.first}–${a.last} · ${a.pod} podiums`,riders[0]?.wins||1)}</div><div class="panel"><div class="h3"><span>Most podiums</span></div>${riderBars([...riders].sort((a,b)=>b.pod-a.pod||b.wins-a.wins).slice(0,10),a=>a.pod,a=>`${a.wins} wins · ${a.starts} starts`,Math.max(1,...riders.map(a=>a.pod)))}</div><div class="panel"><div class="h3"><span>Most sidecar wins</span><small>drivers and passengers</small></div>${riderBars(sidecar,a=>a.fams['Sidecar']||0,a=>`${a.first}–${a.last}`,sidecar[0]?.fams['Sidecar']||1)}</div></div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Fastest races</span><small>winner’s average</small></div><div class="board">${speeds.slice(0,10).map((r,i)=>`<button type="button" class="bar" data-race="${esc(r.id)}" data-year="${r.year}" style="--i:${i};--team:${color(r.winner.marque)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(crewName(r.winner.crew))}<small> ${esc(r.name)} ${r.year}</small></span><small>${esc(r.winner.machine||r.winner.marque)}</small></span></span><span class="val">${r.speed.toFixed(2)}</span></button>`).join('')}</div></div><div class="panel"><div class="h3"><span>Marques by wins</span></div>${marqueBars(marques.slice(0,10),a=>a.wins,a=>`${a.first}–${a.last} · ${a.nw} winners`,marques[0]?.wins||1)}</div><div class="panel"><div class="h3"><span>Most wins in one week</span></div><div class="board">${weeks.map(({s,c},i)=>`<button type="button" class="bar" data-year="${s.year}" style="--i:${i};--team:${color(Object.entries(c.best.marques).sort((a,b)=>b[1]-a[1])[0][0])}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(c.best.id))}<small> ${s.year}</small></span><small>${c.best.races.map(r=>r.name).join(', ')}</small></span></span><span class="val">${c.best.wins}</span></button>`).join('')}</div></div></div>
  ${ys.length>3?`<div class="h3" style="margin-top:22px"><span>The Senior TT, year by year</span><small>winner’s race average, mph</small></div><div class="panel"><div class="chart" id="seniorChart" style="height:260px"></div></div>`:''}`;
  if(ys.length>3){const best={};for(const r of senior)best[r.year]=Math.max(best[r.year]||0,r.speed);drawChart($('#seniorChart'),[{id:'Senior TT',pts:ys.map(y=>best[y])}],ys.length,()=>'Senior TT',i=>ys[i]%10===0||i===0||i===ys.length-1?String(ys[i]):'',()=>'var(--accent)','Senior TT winning average');}}

/* ---------- Barcode ---------- */
const HEATMETRICS={wins:['Wins','Races won by the marque that year.'],pod:['Podiums','Top-three finishes that year.'],starts:['Recorded starts','Results recorded for the marque that year.']};
function barcodeView(){const ss=eraSeasons();const years=ss.map(s=>s.year);const cell={};const tot={};
  for(const s of ss)for(const r of s.races)for(const x of r.results){const m=x.marque;if(m==='Unrecorded')continue;const c=cell[m]||(cell[m]={});const k=c[s.year]||(c[s.year]={wins:0,pod:0,starts:0});k.starts++;if(x.pos===1)k.wins++;if(x.pos&&x.pos<=3)k.pod++;tot[m]=(tot[m]||0)+(x.pos===1?1:0);}
  const marques=Object.keys(cell).sort((a,b)=>tot[b]-tot[a]).slice(0,28);const val=k=>k?k[state.heat]:0;const max=Math.max(1,...marques.flatMap(m=>years.map(y=>val(cell[m][y]))));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">TT barcode · ${esc(eraLabel())}</h2></div><div class="small mono muted">${marques.length} marques × ${years.length} weeks</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="heat" aria-label="Metric">${Object.entries(HEATMETRICS).map(([k,v])=>`<option value="${k}" ${k===state.heat?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(HEATMETRICS[state.heat][1])} Brightness is the cell’s share of the brightest cell; colour is the marque’s. Rows ordered by wins.</span></div>
  <div class="barcode"><div class="bc-row"><span></span><span class="cells" style="gap:2px">${years.map(y=>`<i style="background:none;height:14px;font-size:8px;color:var(--dim);text-align:center;line-height:14px">${years.length<=30||y%10===0?String(y).slice(2):''}</i>`).join('')}</span><span></span></div>${marques.map(m=>`<div class="bc-row"><span class="lab" data-marque="${esc(m)}">${esc(m)}</span><span class="cells">${years.map(y=>{const v=val(cell[m][y]);const a=v?Math.max(.12,v/max):0;return `<i data-year="${y}" title="${esc(m)} ${y} · ${v}" style="--c:${mixHex(color(m),'#0f1113',a)}"></i>`;}).join('')}</span><span class="tot">${fmt(tot[m])}</span></div>`).join('')}</div></div>`;
  $('#heat').addEventListener('change',e=>{state.heat=e.target.value;render();});}

/* ---------- Duel ---------- */
function swingChart(el,pts,labA,labB,cA,cB){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(180,box.height);const padL=30,padR=30,padT=16,padB=22;const n=pts.length;const max=Math.max(1,...pts.map(p=>Math.abs(p.v)));const x=i=>padL+(n>1?i*(W-padL-padR)/(n-1):(W-padL-padR)/2),y=v=>padT+(H-padT-padB)*(1-(v+max)/(2*max));
  const mid=y(0);let d='';pts.forEach((p,i)=>{d+=(i?'L':'M')+x(i).toFixed(1)+' '+y(p.v).toFixed(1);});
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Head-to-head swing"><line class="gridl" x1="${padL}" x2="${W-padR}" y1="${mid.toFixed(1)}" y2="${mid.toFixed(1)}"/><text class="lb" x="${padL}" y="${padT-4}" style="fill:${cA}">${esc(labA)} ahead</text><text class="lb" x="${padL}" y="${H-6}" style="fill:${cB}">${esc(labB)} ahead</text><path class="ser" d="${d}" style="--c:var(--muted)"/>${pts.map((p,i)=>`<circle class="pt" cx="${x(i).toFixed(1)}" cy="${y(p.v).toFixed(1)}" r="4" fill="${p.win==='A'?cA:p.win==='B'?cB:'#5b616b'}" data-year="${p.y}"><title>${esc(p.label)}</title></circle>`).join('')}</svg>`;}
function duelView(){const riders=riderAgg().sort(riderOrder);const marques=marqueAgg().filter(a=>a.id!=='Unrecorded').sort((a,b)=>b.wins-a.wins);
  if(state.duelBy==='r'){const ids=riders.slice(0,150).map(p=>p.id);if(!state.dA||!RIDERS[state.dA])state.dA=ids[0];if(!state.dB||!RIDERS[state.dB]||state.dB===state.dA)state.dB=ids.find(i=>i!==state.dA);}
  else{const ids=marques.slice(0,40).map(m=>m.id);if(!state.dA||!ids.includes(state.dA))state.dA=ids[0];if(!state.dB||!ids.includes(state.dB)||state.dB===state.dA)state.dB=ids.find(i=>i!==state.dA);}
  const opts=sel=>state.duelBy==='r'?[...new Set([state.dA,state.dB,...riders.slice(0,150).map(p=>p.id)])].filter(Boolean).map(id=>`<option value="${esc(id)}" ${id===sel?'selected':''}>${esc(pname(id))}</option>`).join(''):marques.slice(0,40).map(m=>`<option value="${esc(m.id)}" ${m.id===sel?'selected':''}>${esc(m.id)}</option>`).join('');
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Head to head · ${esc(eraLabel())}</h2></div><div class="small mono muted">${state.duelBy==='r'?'riders · wins and the races they shared':'marques · wins, week by week'}</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="duelBy" aria-label="Compare"><option value="r" ${state.duelBy==='r'?'selected':''}>Riders</option><option value="m" ${state.duelBy==='m'?'selected':''}>Marques</option></select><select id="dA" aria-label="First">${opts(state.dA)}</select><span class="mono small muted">vs</span><select id="dB" aria-label="Second">${opts(state.dB)}</select></div><div id="duelBody"></div></div>`;
  $('#duelBy').addEventListener('change',e=>{state.duelBy=e.target.value;state.dA=null;state.dB=null;render();});$('#dA').addEventListener('change',e=>{state.dA=e.target.value;render();});$('#dB').addEventListener('change',e=>{state.dB=e.target.value;render();});
  const a=state.dA,b=state.dB;if(!a||!b){$('#duelBody').innerHTML='<p class="muted">Pick two.</p>';return;}
  const isR=state.duelBy==='r';const has=(x,id)=>isR?x.crew.includes(id):x.marque===id;const cA=isR?color(riders.find(p=>p.id===a)?.top||'Unrecorded'):color(a),cB=isR?color(riders.find(p=>p.id===b)?.top||'Unrecorded'):color(b);const nameOf=id=>isR?pname(id):id;
  const shared=[];let lead=0;const pts=[];let wa=0,wb=0,ha=0,hb=0;
  for(const s of eraSeasons()){let ya=0,yb=0;for(const r of s.races){const xa=r.results.find(x=>has(x,a)),xb=r.results.find(x=>has(x,b));if(xa&&xa.pos===1)ya++;if(xb&&xb.pos===1)yb++;if(xa&&xb){shared.push({r,xa,xb});if(xa.pos&&xb.pos){if(xa.pos<xb.pos)ha++;else if(xb.pos<xa.pos)hb++;}}}wa+=ya;wb+=yb;lead+=ya-yb;pts.push({v:lead,win:ya>yb?'A':yb>ya?'B':'',y:s.year,label:`${s.year} · ${nameOf(a)} ${ya} · ${nameOf(b)} ${yb}`});}
  $('#duelBody').innerHTML=`<div class="duel-heads"><div class="dh" style="--team:${cA}"><span class="eyebrow">${esc(nameOf(a))}</span><b>${wa}</b><small>wins in the lens${isR?` · ${ha} of ${shared.length} shared races finished ahead`:''}</small></div><div class="dh" style="--team:${cB}"><span class="eyebrow">${esc(nameOf(b))}</span><b>${wb}</b><small>wins in the lens${isR?` · ${hb} finished ahead`:''}</small></div></div><div class="h3" style="margin-top:18px"><span>The lead in wins, week by week</span><small>cumulative</small></div><div class="chart" id="duelSwing" style="height:220px"></div>
  ${shared.length?`<div class="h3" style="margin-top:18px"><span>${isR?'Races they shared':'Races both marques started'}</span><small>${shared.length}</small></div><div class="tablewrap" style="max-height:480px"><table><tr><th>Year</th><th>Race</th><th style="color:${cA}">${esc(nameOf(a))}</th><th style="color:${cB}">${esc(nameOf(b))}</th></tr>${[...shared].reverse().map(({r,xa,xb})=>`<tr><td><a href="#" data-race="${esc(r.id)}" data-year="${r.year}">${r.year}</a></td><td>${esc(r.name)}</td><td>${xa.pos?'P'+xa.pos:esc(xa.status)}${xa.mph?' · '+xa.mph.toFixed(1):''}</td><td>${xb.pos?'P'+xb.pos:esc(xb.status)}${xb.mph?' · '+xb.mph.toFixed(1):''}</td></tr>`).join('')}</table></div>`:''}`;
  if(pts.length)swingChart($('#duelSwing'),pts,nameOf(a),nameOf(b),cA,cB);}

/* ---------- Sources & coverage ---------- */
function drawSources(){const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b><small>${s}</small></div>`;const cov=A.coverage||{};
  $('#sourcesBody').innerHTML=`<p class="eyebrow">Mountain edition / ${esc(day(A.snapshot))}</p><h2>Every TT race since 1907, one archive.</h2><div class="kpis">${kpi('Races',fmt(cov.races||RACES.length),`${cov.raceYears||S.length} TT weeks`)}${kpi('Recorded results',fmt(cov.results),`${fmt(cov.winnerOnly)} races hold the winner alone`)}${kpi('Riders',fmt(Object.keys(RIDERS).length),'')}${kpi('Course',`${COURSE.miles} mi`,`${(COURSE.landmarks||[]).length} named places`)}${kpi('Cancelled',fmt((A.cancelled||[]).length),'races and years, as recorded')}</div>
<h3>Sources</h3><ol><li><a href="https://de.wikipedia.org/wiki/Liste_der_Isle-of-Man-TT-Sieger" target="_blank" rel="noopener">German Wikipedia’s list of TT winners</a> and <a href="https://en.wikipedia.org/wiki/Isle_of_Man_TT" target="_blank" rel="noopener">English Wikipedia’s</a> race, class and year articles (<a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a>, Wikipedia contributors)<p>${esc(A.method||'')} ${(A.sources||[]).length} source pages, each recorded with its retrieval date and hash in the data file; ${(A.corrections||[]).length} reconciliations of conflicting winners and ${(A.issues||[]).length} remaining discrepancies are listed there too. Every race links to the page it came from.</p></li><li><a href="https://www.openstreetmap.org/relation/188240" target="_blank" rel="noopener">OpenStreetMap relation 188240</a> (© OpenStreetMap contributors, <a href="https://opendatacommons.org/licenses/odbl/1-0/" target="_blank" rel="noopener">ODbL 1.0</a>)<p>The Snaefell Mountain Course as currently mapped (relation version ${esc(COURSE.sourceVersion||'')}, ${esc(COURSE.sourceTimestamp||'')}), with its named corners and places; the line is today’s road, not a historical survey. Distances along the lap are measured on that line.</p></li></ol>
<h3>How to read the statistics</h3><p class="small muted">A win is first place in a race as the sources record it; the sidecar driver and passenger each receive the credit, and the 1975–76 Production co-riders likewise. Race averages are the winner’s speed over the whole race as published and are never lap records; the lap records table is the published set of standing records. Recorded starts count results held in the archive — for ${fmt(cov.winnerOnly)} races, the early decades above all, only the winner is known, so starts and podiums are lower bounds. Where the source leaves a sidecar outfit’s marque blank, the marque named in the machine description is used and marked. ${cov.speedsConverted?cov.speedsConverted+' result tables whose speeds were transcribed in km/h have been converted to mph, and '+cov.speedsDiscarded+' unreadable averages set aside; every such change is listed in the data file.':''} Class families are editorial groupings of the archive’s race names. Cancelled races and the years without a TT (1915–19, 1940–46, 2001, 2020–21) are gaps, never zeros; the river leaves them open.</p>`;}

/* ---------- deep links ---------- */
let routeLock=false;
function writeRoute(){if(routeLock)return;const q=[];if(state.family!=='all')q.push('class='+encodeURIComponent(state.family));if(state.era!=='all')q.push('era='+encodeURIComponent(state.era));if(state.whole)q.push('whole=1');else q.push('season='+state.year);q.push('tab='+state.tab);if(state.tab==='race'&&!state.whole&&state.race)q.push('race='+encodeURIComponent(state.race));for(const [k,t] of [['rider','riders'],['marque','marques'],['cls','classes']]){if(state.tab===t&&state[k])q.push(k+'='+encodeURIComponent(state[k]));}if(state.tab==='duel'&&state.dA&&state.dB)q.push('duel='+encodeURIComponent(state.dA+'|'+state.dB)+'&by='+state.duelBy);const h='#'+q.join('&');if(location.hash!==h){try{history[location.hash?'pushState':'replaceState'](null,'',h);}catch(e){}}}
function readRoute(){const h=location.hash.replace(/^#\/?/,'');if(!h||/^static-/.test(h))return false;const p={};for(const kv of h.split('&')){const i=kv.indexOf('=');p[i<0?kv:kv.slice(0,i)]=i<0?'1':decodeURIComponent(kv.slice(i+1));}let any=false;
  if(p.class&&(p.class==='all'||FAMILIES.includes(p.class))){state.family=p.class;any=true;}rebuildSeasons();
  if(p.era&&(p.era==='all'||ERAS.some(e=>e.id===p.era))){state.era=p.era;any=true;}
  if(p.race&&byId[p.race]){const r=byId[p.race];if(!inLens(r)){state.family='all';rebuildSeasons();}state.race=p.race;state.year=r.year;any=true;}else if(p.season&&byYear[+p.season]){state.year=+p.season;any=true;}
  if(state.era!=='all'&&!inEraYear(state.year)){if(p.season||p.race)state.era='all';else state.year=eraSeasons().slice(-1)[0]?.year||state.year;}
  state.whole=p.whole==='1';if(state.whole)any=true;
  if(p.tab&&TABS.some(t=>t[0]===p.tab)){state.tab=p.tab;any=true;}
  state.rider=p.rider&&RIDERS[p.rider]?p.rider:null;state.marque=p.marque||null;state.cls=p.cls&&FAMILIES.includes(p.cls)?p.cls:null;
  if(p.duel){const [a,b]=p.duel.split('|');state.duelBy=p.by==='m'?'m':'r';state.dA=a;state.dB=b;any=true;}
  return any;}

/* ---------- render, navigation, events ---------- */
function render(){stopReplay();drawTabs();if(tour.stopped||!tour.timer)drawEraStrip();const v={season:seasonView,race:raceView,riders:()=>state.rider?riderView(state.rider):ridersView(),marques:()=>state.marque?marqueView(state.marque):marquesView(),classes:()=>state.cls?classView(state.cls):classesView(),records:recordsView,barcode:barcodeView,duel:duelView}[state.tab];try{v();}catch(e){$('#view').innerHTML=`<p class="muted">Something in this view could not be drawn: ${esc(e.message)}</p>`;console.error(e);}StageNav.draw();writeRoute();}
function go(tab,scroll=true){state.tab=tab;render();if(scroll)$('#stage').scrollIntoView({behavior:RM?'auto':'smooth',block:'start'});}
function ensureYearInLens(y){if(state.era!=='all'&&!inEraYear(y)){state.era='all';$('#eraSelect').value='all';}}
function setSeason(y,scroll){state.whole=false;ensureYearInLens(y);state.year=y;state.race=null;fillSeasons();applyTheme();drawRiver();if(state.tab!=='season'&&state.tab!=='race')state.tab='season';go(state.tab,scroll);}
function openRace(id,scroll){const r=byId[id];if(!r)return;state.whole=false;if(!inLens(r)){state.family='all';$('#family').value='all';relens(false);}ensureYearInLens(r.year);state.year=r.year;state.race=id;fillSeasons();applyTheme();drawRiver();go('race',scroll);}
function fillSeasons(){const sel=$('#season');const ss=eraSeasons();if(!ss.length){sel.innerHTML='';return;}const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);sel.innerHTML=`<option value="era">${e?'Whole era':'All years'} · ${ss[0].year}–${ss[ss.length-1].year}</option>`+'<optgroup label="Newest first">'+ss.slice().reverse().map(s=>`<option value="${s.year}">${s.year}</option>`).join('')+'</optgroup>';sel.value=state.whole?'era':state.year;}
function setEra(id){tourStop();state.era=id;$('#eraSelect').value=id;if(id!=='all'){if(!inEraYear(state.year)){const last=eraSeasons().slice(-1)[0];state.year=last?last.year:state.year;state.race=null;}}fillSeasons();applyTheme();drawRiver();render();}
function relens(rerender=true){rebuildSeasons();if(!byYear[state.year])state.year=LAST_YEAR;state.race=null;state.rider=null;state.marque=null;state.cls=null;fillSeasons();$('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.filter(e=>e.to>=FIRST_YEAR).map(e=>`<option value="${e.id}">${esc(ERA_SHORT[e.id]||e.name)} · ${e.from}–${e.to}</option>`).join('');$('#eraSelect').value=state.era;if(rerender){applyTheme();drawRiver();render();}}
function init(){
  rebuildSeasons();
  $('#family').innerHTML=`<option value="all">All classes</option>`+FAMILIES.map(f=>`<option value="${esc(f)}">${esc(f)}</option>`).join('');
  $('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.map(e=>`<option value="${e.id}">${esc(ERA_SHORT[e.id]||e.name)} · ${e.from}–${e.to}</option>`).join('');
  const topM=marqueAgg().filter(a=>a.id!=='Unrecorded').sort((a,b)=>b.wins-a.wins).slice(0,14).map(m=>m.id);
  $('#theme').innerHTML=`<option value="champion">Marque of the year</option>`+topM.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join('');
  fillSeasons();
  const cov=A.coverage||{};
  $('#edition').innerHTML=`<span><span class="live"></span><b>${fmt(RACES.length)}</b> races</span><span><b>${S.length}</b> TT weeks</span><span><b>${fmt(cov.results)}</b> recorded results</span><span><b>${fmt(cov.winnerOnly)}</b> races winner-only</span><span><b>${fmt(Object.keys(RIDERS).length)}</b> riders</span><span>through <b>${A.lastYear}</b></span>`;
  $('#reading').open=false;
  const deep=readRoute();if(deep){tourStop();$('#family').value=state.family;$('#eraSelect').value=state.era;fillSeasons();}
  drawSources();applyTheme();drawRiver();drawCourse();render();lightsOut();if(deep&&(state.tab!=='season'||state.whole||state.era!=='all'))setTimeout(()=>$('#stage').scrollIntoView({behavior:'auto',block:'start'}),60);
  addEventListener('hashchange',()=>{if(/^#static-/.test(location.hash)){$('#reading').open=true;return;}routeLock=true;try{if(readRoute()){tourStop();$('#family').value=state.family;$('#eraSelect').value=state.era;fillSeasons();applyTheme();drawRiver();render();}}finally{routeLock=false;}});
  $('#eraSelect').addEventListener('change',e=>setEra(e.target.value));
  $('#family').addEventListener('change',e=>{state.family=e.target.value;relens();});
  $('#season').addEventListener('change',e=>{if(e.target.value==='era'){state.whole=true;applyTheme();drawRiver();if(state.tab!=='season'&&state.tab!=='race')state.tab='season';go(state.tab,false);}else setSeason(+e.target.value,false);});
  $('#theme').addEventListener('change',applyTheme);
  $('#eraStrip').addEventListener('click',e=>{const s=e.target.closest('[data-era]');if(s)setEra(state.era===s.dataset.era?'all':s.dataset.era);});
  $('#eraStrip').addEventListener('pointerenter',()=>{tourPause();},{passive:true});$('#eraStrip').addEventListener('pointerleave',()=>{if(!tour.stopped)tourStart();},{passive:true});
  $('#eraStrip').addEventListener('mouseover',e=>{const s=e.target.closest('[data-era]');if(s&&!tour.stopped){drawEraStrip(s.dataset.era);}});
  if('IntersectionObserver' in window){new IntersectionObserver(en=>{tour.visible=en[0].isIntersecting;if(tour.visible)tourStart();else tourPause();},{threshold:.2}).observe($('#eraStrip'));}else{tour.visible=true;tourStart();}
  const hi=name=>{state.place=name;$$('#courseSvg .lm').forEach(c=>c.classList.toggle('on',c.dataset.place===name));$$('#places .place').forEach(b=>b.classList.toggle('on',b.dataset.place===name));};
  $('#places').addEventListener('mouseover',e=>{const b=e.target.closest('[data-place]');if(b)hi(b.dataset.place);});$('#places').addEventListener('click',e=>{const b=e.target.closest('[data-place]');if(b)hi(state.place===b.dataset.place?null:b.dataset.place);});
  $('#courseSvg').addEventListener('mouseover',e=>{const c=e.target.closest('[data-place]');if(c){hi(c.dataset.place);const el=$(`#places [data-place="${CSS.escape(c.dataset.place)}"]`);if(el)el.scrollIntoView({block:'nearest'});}});
  const clear=t=>{if(t==='riders')state.rider=null;if(t==='marques')state.marque=null;if(t==='classes')state.cls=null;};
  $('#tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;clear(b.dataset.tab);go(b.dataset.tab,false);});
  $('#view').addEventListener('click',e=>{const a=e.target.closest('[data-race],[data-rider],[data-marque],[data-cls],[data-year],[data-tab]');if(!a)return;if(a.tagName==='A')e.preventDefault();
    if(a.dataset.tab){clear(a.dataset.tab);go(a.dataset.tab,false);return;}
    if(a.dataset.race){openRace(a.dataset.race,false);return;}
    if(a.dataset.year){const y=+a.dataset.year;if(!byYear[y])return;ensureYearInLens(y);state.whole=false;state.year=y;state.race=null;fillSeasons();applyTheme();drawRiver();go('season',false);return;}
    if(a.dataset.rider){state.rider=a.dataset.rider;go('riders',false);return;}
    if(a.dataset.marque){state.marque=a.dataset.marque;go('marques',false);return;}
    if(a.dataset.cls){state.cls=a.dataset.cls;go('classes',false);return;}});
  addEventListener('resize',()=>{clearTimeout(window.__rz);window.__rz=setTimeout(()=>{drawRiver();if(['season','duel','records','classes'].includes(state.tab))render();},150);});
}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):StageNav.mount({seasons:()=>eraSeasons(),year:()=>state.year,whole:()=>state.whole,tab:()=>state.tab,setYear:y=>setSeason(y,false),unitTab:'race',unitName:'Race',units:s=>s.races.filter(inLens).map(r=>({key:r.id,label:r.name})),unit:()=>state.race,setUnit:k=>{state.race=k;go('race',false);}});
init();
