/* ---------- the map: the land silhouette once, every route drawn schematically between its named towns ---------- */
const ERA_CARD={'Africa':'Africa','South America':'S. America','Saudi Arabia':'Arabia'};
function landDefs(){if($('#landDefs'))return;const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('id','landDefs');s.setAttribute('width','0');s.setAttribute('height','0');s.setAttribute('style','position:absolute;width:0;height:0;overflow:hidden');s.innerHTML=`<defs><path id="land" d="${MAP.land}"/></defs>`;document.body.prepend(s);}
function routePoints(stops){const pts=[];for(const s of stops){const p=proj(s);if(p&&!(pts.length&&pts[pts.length-1][0]===p[0]&&pts[pts.length-1][1]===p[1]))pts.push([p[0],p[1],s]);}
  if(stops.length>1&&stops[0]===stops[stops.length-1]&&pts.length&&pts[0][2]!==stops[stops.length-1])pts.push([pts[0][0],pts[0][1],stops[0]]);return pts;}
function loopD(p,era){const b=BOX[era]||[0,0,1080,540];let dx=b[0]+b[2]/2-p[0],dy=b[1]+b[3]/2-p[1];const n=Math.hypot(dx,dy)||1;dx/=n;dy/=n;if(n<1){dx=1;dy=0;}const r=5.5,L=15;const nx=-dy,ny=dx;const P=(a,b)=>`${(p[0]+dx*a+nx*b).toFixed(1)} ${(p[1]+dy*a+ny*b).toFixed(1)}`;
  return `M${P(0,0)} C${P(r,-1.3*r)} ${P(L-.3*r,-1.1*r)} ${P(L,0)} C${P(L-.3*r,1.1*r)} ${P(r,1.3*r)} ${P(0,0)} Z`;}
function routeD(pts,era){if(pts.length===1)return loopD(pts[0],era);
  if(pts.length===2){const [a,b]=pts;const dx=b[0]-a[0],dy=b[1]-a[1];const mx=(a[0]+b[0])/2-dy*.14,my=(a[1]+b[1])/2+dx*.14;return `M${a[0].toFixed(1)} ${a[1].toFixed(1)} Q${mx.toFixed(1)} ${my.toFixed(1)} ${b[0].toFixed(1)} ${b[1].toFixed(1)}`;}
  const loop=pts[0][0]===pts[pts.length-1][0]&&pts[0][1]===pts[pts.length-1][1];const xy=pts.map(p=>[p[0],p[1]]);return 'M'+xy[0][0].toFixed(1)+' '+xy[0][1].toFixed(1)+smooth(xy)+(loop?'Z':'');}
function fitBox(pts,era,minW){const b=BOX[era]||[0,0,1080,540];if(!pts.length)return b;let x0=Math.min(...pts.map(p=>p[0])),x1=Math.max(...pts.map(p=>p[0])),y0=Math.min(...pts.map(p=>p[1])),y1=Math.max(...pts.map(p=>p[1]));const w=Math.max(minW,(x1-x0)*1.6,(y1-y0)*1.6);const cx=(x0+x1)/2,cy=(y0+y1)/2;return [cx-w/2,cy-w/2,w,w];}
function routeSvg(ed,opts={}){const pts=routePoints(ed.stops);const box=opts.fit?fitBox(pts,ed.era,opts.minW||60):(BOX[ed.era]||[0,0,1080,540]);const u=box[2]/500*(opts.k||1);const d=routeD(pts,ed.era);const col=opts.color||'var(--team)';
  const dots=pts.map((p,i)=>{const first=i===0,last=i===pts.length-1&&pts.length>1;return `<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="${(first||last?5:3.4)*u}" fill="${first?col:'#07080a'}" stroke="${col}" stroke-width="${1.6*u}"/>`;}).join('');
  const labels=opts.labels?pts.filter((p,i,arr)=>arr.findIndex(q=>q[2]===p[2])===i).map(p=>`<text class="lmt" x="${(p[0]+7*u).toFixed(1)}" y="${(p[1]-5*u).toFixed(1)}" font-size="${9*u}">${esc(p[2])}</text>`).join(''):'';
  return `<svg viewBox="${box.map(v=>v.toFixed(1)).join(' ')}" ${opts.attrs||''} aria-hidden="${opts.labels?'false':'true'}"${opts.labels?` role="img" aria-label="${esc(ed.route)}"`:''}><rect x="${box[0]}" y="${box[1]}" width="${box[2]}" height="${box[3]}" fill="#0b0d12"/><use href="#land" class="land" style="stroke-width:${.5*u}"/><path class="glow" d="${d}" style="stroke:${col};stroke-width:${7*u}"/><path class="trk" d="${d}" style="stroke:${col};stroke-width:${1.8*u};stroke-dasharray:${4*u} ${3*u}" ${opts.id?`id="${opts.id}"`:''}/>${dots}${labels}${opts.extra||''}</svg>`;}

/* ---------- III · the Routes: every edition as a card, the route in the colour of its car winner (bikes where there were no cars) ---------- */
function routeModel(){return eraSeasons().map(s=>{const w=s.ed.winners;const lead=state.cat!=='all'?w[state.cat]:(w.Cars||w.Bikes||null);return {s,ed:s.ed,year:s.year,lead,top:lead?lead.make:null,stops:s.ed.stops,text:(s.year+' '+s.ed.route+' '+s.ed.era+' '+s.ed.stops.join(' ')).toLowerCase()};});}
function drawGrid(){const list=routeModel();const q=state.gridFind.trim().toLowerCase();let shown=list.filter(c=>!q||c.text.includes(q));
  const sorters={year:(a,b)=>b.year-a.year,oldest:(a,b)=>a.year-b.year,era:(a,b)=>a.ed.era.localeCompare(b.ed.era)||b.year-a.year,marque:(a,b)=>(a.top||'~').localeCompare(b.top||'~')||b.year-a.year};shown.sort(sorters[state.gridSort]||sorters.year);
  const towns=new Set(list.flatMap(c=>c.stops));
  $('#gridLede').textContent=`${list.length} editions in ${eraLabel().replace(' · ',', ')}, each route drawn between its named towns over the land as Natural Earth maps it — ${towns.size} towns from Paris to Cape Town, Buenos Aires to Lima, Jeddah to the Empty Quarter. The line is the journey as the archive names it, start, waypoint and finish; the stage-by-stage course is not carried. Each card takes the colour of the marque that won the ${state.cat==='all'?'cars (the bikes, before there were cars to speak of)':state.cat.toLowerCase()} that year.`;
  $('#circuits').innerHTML=shown.map(c=>`<button type="button" class="circ route${c.ed.cancelled?' off':''}" data-year="${c.year}" style="${c.top?teamVar(c.top):'--team:#5b616b'}" title="${c.year} · ${esc(c.ed.route)} · ${esc(c.ed.era)}${c.lead?' · '+esc(pname(c.lead.driver))+' · '+esc(c.lead.make):c.ed.cancelled?' · cancelled':''}"><span class="ct">${esc(ERA_CARD[c.ed.era]||c.ed.era)}</span><span class="n">${c.year}</span>${routeSvg(c.ed,{fit:true,minW:48,k:2.4})}<span class="nm">${esc(c.ed.route)}</span></button>`).join('')||`<p class="muted">No route matches.</p>`;}

/* ---------- Stage: tabs, era strip, era context ---------- */
const TABS=[['season','Edition'],['drivers','Drivers'],['marques','Marques'],['classes','Classes'],['records','Records'],['barcode','Barcode'],['duel','Duel']];
function drawTabs(){$('#tabs').innerHTML=TABS.map(([id,l])=>`<button type="button" role="tab" data-tab="${id}" aria-pressed="${state.tab===id}">${l}</button>`).join('');
  $('#stageStatus').textContent=state.tab==='season'&&!state.whole?`${state.year} · ${eraOf(state.year)?.name||''} · ${lensLabel()}`:eraLabel();}
function drawEraStrip(preview){const strip=$('#eraStrip');if(!strip.children.length)strip.innerHTML=ERAS.map(e=>`<button type="button" style="--w:${e.to-e.from+1}" data-era="${e.id}" title="${esc(e.name)} · ${e.from}–${e.to}" aria-label="${esc(e.name)} ${e.from}–${e.to}"></button>`).join('');
  for(const b of strip.children){b.classList.toggle('on',state.era===b.dataset.era);b.classList.toggle('demo',preview===b.dataset.era);}
  const e=preview?ERAS.find(x=>x.id===preview):state.era==='all'?eraOf(state.year):ERAS.find(x=>x.id===state.era);
  $('#eraCaption').innerHTML=`<span><b>${esc(e.name)}</b> · ${e.from}–${e.to}</span><span class="dim">${state.era===e.id?'Lens on · click again to release':'Click a segment to focus the whole page on that era'}</span>`;
  const ctx=$('#eraContext');ctx.innerHTML=`<div class="era-car">${e.ball.svg}</div><div><p class="eyebrow">${state.era===e.id?'Era lens':preview?'Era':'Era of the selected year'} · ${e.from}–${e.to}</p><h3>${esc(e.name)}</h3><p>${esc(e.text)}</p><div class="chips">${e.ball.features.map(f=>`<span>${esc(f)}</span>`).join('')}</div><p class="small dim" style="margin:10px 0 0">${esc(e.ball.label)} · an editorial reading of the period; the archive itself is not divided</p></div>`;}
const tour={i:-1,timer:null,visible:false,stopped:RM};
function tourStep(){if(tour.stopped||!tour.visible)return;tour.i=(tour.i+1)%ERAS.length;const ctx=$('#eraContext');ctx.classList.add('swap');setTimeout(()=>{if(tour.stopped)return;drawEraStrip(ERAS[tour.i].id);ctx.classList.remove('swap');},260);tour.timer=setTimeout(tourStep,4200);}
function tourStart(){if(tour.stopped||tour.timer)return;tour.timer=setTimeout(tourStep,1800);}
function tourPause(){clearTimeout(tour.timer);tour.timer=null;}
function tourStop(){if(tour.stopped)return;tour.stopped=true;tourPause();$('#eraContext').classList.remove('swap');drawEraStrip();}

/* ---------- shared pieces ---------- */
const dl=id=>`<a href="#" data-driver="${esc(id)}" style="color:inherit">${esc(pname(id))}</a>`;
const crewLinks=ids=>(ids||[]).map(dl).join(' / ');
const ml=m=>`<a href="#" data-marque="${esc(m)}" style="color:inherit"><i class="dot" style="--c:${color(m)}"></i>${esc(m)}</a>`;
const cl=c=>`<a href="#" data-cls="${esc(c)}" style="color:inherit">${esc(c)}</a>`;
function bars(rows,valOf,subOf,max,attr,nameOf,colorOf,unit=''){return `<div class="board">${rows.map((a,i)=>`<button type="button" class="bar" data-${attr}="${esc(a.id)}" style="--i:${i};--team:${colorOf(a)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(nameOf(a))}</span><small>${subOf(a)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*valOf(a)/(max||1))}%"></span></span></span><span class="val">${valOf(a)==null?'—':fmt(valOf(a))}${unit}</span></button>`).join('')}</div>`;}
const driverBars=(rows,valOf,subOf,max,unit='')=>bars(rows,valOf,subOf,max,'driver',a=>pname(a.id),a=>color(a.top||Object.keys(a.marques||{})[0]||'?'),unit);
const marqueBars=(rows,valOf,subOf,max,unit='')=>bars(rows,valOf,subOf,max,'marque',a=>a.id,a=>color(a.id),unit);
function drawChart(el,series,n,labelOf,xl,colorOf,ylabel){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(200,box.height);const padL=40,padR=130,padT=14,padB=26;const vals=series.flatMap(s=>s.pts.filter(v=>v!=null));const max=Math.max(1,...vals),min=Math.min(0,...vals);const x=i=>padL+(n>1?i*(W-padL-padR)/(n-1):0),y=v=>padT+(H-padT-padB)*(1-(v-min)/((max-min)||1));
  let g='';const step=max>200?50:max>60?25:max>20?10:max>8?5:1;for(let v=Math.ceil(min/step)*step;v<=max;v+=step)g+=`<line class="gridl" x1="${padL}" x2="${W-padR}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}"/><text class="lb" x="${padL-6}" y="${(y(v)+3).toFixed(1)}" text-anchor="end">${v}</text>`;
  for(let i=0;i<n;i++){const l=xl(i);if(l)g+=`<text class="lb" x="${x(i).toFixed(1)}" y="${H-8}" text-anchor="middle">${esc(l)}</text>`;}
  const paths=series.map(s=>{let d='',pen=false;s.pts.forEach((v,i)=>{if(v==null){pen=false;return;}d+=(pen?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1);pen=true;});const lastI=s.pts.map((v,i)=>v!=null?i:-1).filter(i=>i>=0).pop();const last=lastI!=null?s.pts[lastI]:null;return `<path class="ser" d="${d}" style="--c:${colorOf(s.id)}"><title>${esc(labelOf(s.id))}</title></path>${last!=null?`<text class="end" x="${(x(lastI)+6).toFixed(1)}" y="${(y(last)+4).toFixed(1)}" style="--c:${colorOf(s.id)}">${esc(labelOf(s.id))} ${fmt(last)}</text>`:''}`;}).join('');
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(ylabel||'Chart')}">${g}${paths}</svg>`;}
const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b>${s?`<small>${s}</small>`:''}</div>`;
const winLine=x=>x?`<b>${crewLinks(x.crew)}</b><span class="small muted">${ml(x.make)}</span>`:'<b class="muted">—</b>';

/* ---------- Edition: the route, the caravan, the podiums ---------- */
let replay=null;
function stopReplay(){if(replay){cancelAnimationFrame(replay.raf);replay=null;}const g=$('#caravan');if(g)g.innerHTML='';const st=$('#routeStatus');if(st)st.textContent='';}
function seasonView(){if(state.whole)return eraView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No editions in this lens.</p>';return;}const e=s.ed;const c=champOf(s);const marques={};for(const x of s.wins)marques[x.make]=(marques[x.make]||0)+1;const mrows=Object.entries(marques).sort((a,b)=>b[1]-a[1]);const onPodium=new Set(s.rows.map(x=>x.make));
  const lead=state.cat==='all'?(e.winners.Cars||e.winners.Bikes):e.winners[state.cat];const acc=lead?color(lead.make):ERA_COL[e.era];
  const head=`<div class="season-head"><div class="champ-card" style="--accent:${acc};--on-accent:${onColor(acc)}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${e.cancelled?'Cancelled before the start':'The edition'} · ${esc(e.era)} · ${esc(lensLabel())}</p><div class="yr">${s.year}</div><div class="who"><small>The route</small>${esc(e.route)}</div>${lead?`<div class="team"><i></i>${esc(state.cat==='all'?(e.winners.Cars?'Cars':'Bikes'):state.cat)} · ${esc(pname(lead.driver))} · ${esc(lead.make)}</div>`:''}<div class="facts"><div><b>${e.cats.length}</b>classes</div><div><b>${s.rows.length}</b>podium places</div><div><b>${onPodium.size}</b>marques on the podium</div><div><b>${new Set(e.stops).size}</b>named towns</div></div>${e.cancelled?'<p class="small" style="margin:14px 0 0;color:var(--ink);opacity:.85">The rally was called off before the start and has no results; it counts nothing in the statistics.</p>':''}<p class="small dim" style="margin:18px 0 0">A class win is first place in a class as the article lists it; the whole crew shares the credit.</p></div>
  <div class="three winners">${(()=>{const ks=e.cats.filter(k=>state.cat==='all'||k===state.cat);if(!ks.length)return `<div class="champline" style="--team:#5b616b"><span class="eyebrow">${esc(state.cat==='all'?'Results':state.cat)}</span><span class="muted">${e.cancelled?'Cancelled before the start':'No such class this year'}</span></div>`;return ks.map(k=>{const w=e.winners[k];return `<div class="champline" style="--team:${w?color(w.make):'#5b616b'}"><span class="eyebrow">${esc(k)}</span>${winLine(w)}</div>`;}).join('');})()}</div></div>`;
  const pts=routePoints(e.stops);const winners=CATS.filter(k=>e.winners[k]&&(state.cat==='all'||k===state.cat)).map(k=>e.winners[k]);
  const map=`<div class="panel" style="margin-top:22px"><div class="h3"><span>The route</span><small>${esc(e.route)} · drawn between its named towns · ${winners.length&&!e.cancelled?`the caravan, symbolically · <button type="button" class="linkbtn" id="replayGo">replay</button>`:'no caravan'}</small></div><div class="course"><div class="course-map">${routeSvg(e,{fit:true,minW:70,labels:true,id:'routeLine',extra:'<g id="caravan"></g>',attrs:'id="routeSvg"',color:acc})}<p class="small dim" style="margin:8px 0 0">Land: Natural Earth (public domain) · the line joins the towns the archive names, not the stages · dots travel it at equal pace and mean nothing about the race</p></div><div class="course-side"><p class="eyebrow">The towns, in order</p><div class="places">${e.stops.map((t,i)=>`<div class="place"><span class="k">${i===0?'start':i===e.stops.length-1?'finish':'via'}</span><span>${esc(t)}</span></div>`).join('')}</div><div id="routeStatus" class="mono small muted" style="margin-top:10px"></div><div class="legend" id="caravanLegend" style="margin-top:8px">${winners.map(w=>`<span><i style="background:${color(w.make)}"></i>${esc(w.cat)} · ${esc(pname(w.driver))}</span>`).join('')}</div></div></div></div>`;
  const cats=e.cats.filter(k=>state.cat==='all'||k===state.cat);
  const tower=`<div class="h3" style="margin-top:22px"><span>The podiums</span><small>${cats.length} class${cats.length===1?'':'es'} · the first three of each, as the article lists them</small></div><div class="podgrid">${cats.map(k=>{const rows=s.rows.filter(x=>x.cat===k).sort((a,b)=>a.rank-b.rank);return `<div class="panel pod"><div class="h3"><span>${cl(k)}</span><small>${esc(CAT_NOTE[k]||'')}</small></div>${rows.map(x=>`<div class="podrow r${x.rank}" style="${teamVar(x.make)}"><span class="pos">${x.rank}</span><span class="who">${crewLinks(x.crew)}</span><span class="mk">${ml(x.make)}</span></div>`).join('')}</div>`;}).join('')}</div>`;
  const body=`<div class="two" style="margin-top:22px"><div class="panel"><div class="h3"><span>Marques of the year</span><small>by class wins</small></div>${marqueBars(mrows.map(([id,w])=>({id,w})),a=>a.w,a=>`${s.wins.filter(x=>x.make===a.id).map(x=>x.cat).join(', ')}`,mrows[0]?.[1]||1)||'<p class="muted small">No class wins recorded.</p>'}</div><div class="panel"><div class="h3"><span>On the podium</span><small>places by marque</small></div>${marqueBars(Object.entries(s.rows.reduce((m,x)=>(m[x.make]=(m[x.make]||0)+1,m),{})).sort((a,b)=>b[1]-a[1]).map(([id,n])=>({id,n})),a=>a.n,a=>`${s.rows.filter(x=>x.make===a.id&&x.rank===1).length} wins`,Math.max(1,...Object.values(s.rows.reduce((m,x)=>(m[x.make]=(m[x.make]||0)+1,m),{}))))}</div></div>`;
  $('#view').innerHTML=head+map+tower+body;
  if(winners.length&&!e.cancelled){const go=()=>runReplay(e,winners);$('#replayGo').onclick=go;if(!RM)go();}}
function runReplay(e,winners){stopReplay();const line=$('#routeLine');if(!line)return;const len=line.getTotalLength();const g=$('#caravan');const box=$('#routeSvg').viewBox.baseVal;const u=box.width/500;const dur=RM?1:8000;
  g.innerHTML=winners.map((w,i)=>`<circle r="${(i===0?5:4)*u}" fill="${color(w.make)}" stroke="#07080a" stroke-width="${1.2*u}"/>`).join('');const cs=[...g.children];
  const rp={raf:0,t0:null};replay=rp;
  const tick=now=>{if(replay!==rp)return;if(rp.t0==null)rp.t0=now;const p=Math.min(1,(now-rp.t0)/dur);cs.forEach((c,i)=>{const q=Math.max(0,Math.min(1,p-i*.04));const pt=line.getPointAtLength(q*len);c.setAttribute('cx',pt.x.toFixed(1));c.setAttribute('cy',pt.y.toFixed(1));});const st=$('#routeStatus');if(st)st.textContent=p<1?`on the road · ${Math.round(p*100)}%`:`${esc(e.stops[e.stops.length-1])} · the finish`;if(p<1)rp.raf=requestAnimationFrame(tick);};
  rp.raf=requestAnimationFrame(tick);}
function eraView(){const ss=eraSeasons();const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);const rows=eraRows();const wins=rows.filter(x=>x.rank===1);
  const drivers=driverAgg().sort(driverOrder);const top=drivers[0];const marques=marqueAgg().sort((a,b)=>b.wins-a.wins||b.podiums-a.podiums).slice(0,12);
  const head=`<div class="season-head"><div class="champ-card" style="${top?`--accent:${color(top.top||'?')};--on-accent:${onColor(color(top.top||'?'))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${e?'Whole era':'All years'} · ${esc(lensLabel())}</p><div class="yr" style="font-size:clamp(44px,6vw,84px)">${ss[0]?.year}–${ss[ss.length-1]?.year}</div>${top?`<div class="who"><small>Most class wins across the period · ${top.wins} win${top.wins===1?'':'s'} · ${top.podiums} podiums</small><a href="#" data-driver="${esc(top.id)}" style="color:inherit;text-decoration:none">${esc(pname(top.id))}</a></div><div class="team"><i></i>${esc(top.top||'')}${top.topCat?' · '+esc(top.topCat):''}</div>`:''}<div class="facts"><div><b>${ss.filter(s=>!s.ed.cancelled).length}</b>editions held</div><div><b>${wins.length}</b>class wins</div><div><b>${fmt(drivers.length)}</b>people on a podium</div><div><b>${marqueAgg().length}</b>marques</div></div></div>
  <div><div class="podium">${[drivers[1],drivers[0],drivers[2]].map((d,i)=>d?`<button type="button" class="step p${drivers.indexOf(d)+1} bar" data-driver="${esc(d.id)}" style="--h:${Math.round(120+120*d.wins/Math.max(1,drivers[0].wins))}px;--team:${color(d.top||'?')};display:flex"><span class="pos">${drivers.indexOf(d)+1}</span><span class="nm">${esc(pname(d.id))}</span><span class="pt">${d.wins} wins · ${yspan(d)}</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const rollHtml=`<div class="h3"><span>Edition by edition</span><small>the car winner, or the bike winner in the lens · click a year to open it</small></div><div class="calendar">${ss.map(s=>{const w=state.cat==='all'?(s.ed.winners.Cars||s.ed.winners.Bikes):s.ed.winners[state.cat];return `<button type="button" class="cal" data-year="${s.year}" style="--team:${w?color(w.make):'#5b616b'}"><div class="rd">${s.year} · ${esc(s.ed.era)}</div><div class="nm">${esc(s.ed.route)}</div><div class="w">${s.ed.cancelled?'cancelled':w?'<i class="dot" style="--c:'+color(w.make)+'"></i>'+esc(pname(w.driver))+' · '+esc(w.make):'—'}</div></button>`;}).join('')}</div>`;
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Marques across the period</span><small>by class wins</small></div>${marqueBars(marques,a=>a.wins,a=>`${yspan(a)} · ${a.podiums} podiums · ${a.nw} different winners`,Math.max(1,...marques.map(a=>a.wins)))}</div><div class="panel"><div class="h3"><span>Drivers and riders across the period</span><small>by class wins, then podiums</small></div>${driverBars(drivers.slice(0,12),a=>a.wins,a=>`${a.podiums} podiums · ${yspan(a)}${a.topCat?' · '+esc(a.topCat):''}`,Math.max(1,...drivers.slice(0,12).map(a=>a.wins)))}</div></div>`;
  $('#view').innerHTML=head+rollHtml+body;}
