/* ---------- Drivers ---------- */
function driversView(){const list=driverAgg();const lens=state.plens;let rows=list.filter(p=>p[lens]!=null);rows.sort((a,b)=>b[lens]-a[lens]||b.wins-a.wins||b.podiums-a.podiums);rows=rows.slice(0,40);
  const max=Math.max(1,...rows.map(a=>a[lens]));const q=(state.find2||'').toLowerCase();const found=q?Object.entries(PEOPLE).filter(([id,p])=>p.name.toLowerCase().includes(q)).slice(0,14):[];
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Drivers and riders · ${esc(eraLabel())}</h2></div><div class="small mono muted">${fmt(list.length)} people on a podium</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><input type="search" id="find2" placeholder="Search a driver, rider or crew member" value="${esc(state.find2||'')}" aria-label="Search"><select id="lens" aria-label="Lens">${Object.entries(PLENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(PLENSES[lens][1])}</span></div>${q?`<div class="chiplist" style="margin-bottom:14px">${found.map(([id,p])=>`<button type="button" class="chip" data-driver="${esc(id)}">${esc(p.name)}</button>`).join('')||'<span class="muted small">No match.</span>'}</div>`:''}
  ${driverBars(rows,a=>a[lens],a=>`${yspan(a)} · ${a.wins} wins · ${a.podiums} podiums${a.topCat?' · '+esc(a.topCat):''}${a.top?' · '+esc(a.top):''}`,max)}<p class="small dim" style="margin:10px 0 0">Crews share the credit: a navigator or a truck co-driver on a winning entry is a winner here too; the “wins at the wheel” lens keeps the lead driver or rider alone.</p></div>`;
  $('#find2').addEventListener('input',e=>{state.find2=e.target.value;driversView();$('#find2').focus();const v=$('#find2');v.setSelectionRange(v.value.length,v.value.length);});$('#lens').addEventListener('change',e=>{state.plens=e.target.value;render();});}
function driverView(id){const p=PEOPLE[id];if(!p){driversView();return;}const all=driverAgg();const a=all.find(x=>x.id===id);const rank=[...all].sort(driverOrder).findIndex(x=>x.id===id)+1;
  const rows=eraRows().filter(x=>x.crew.includes(id)).sort((u,v)=>v.year-u.year||u.rank-v.rank);const wins=rows.filter(x=>x.rank===1);
  const byC={};for(const x of rows){const c=byC[x.cat]||(byC[x.cat]={c:x.cat,podiums:0,wins:0});c.podiums++;if(x.rank===1)c.wins++;}const machines={};for(const x of rows)machines[x.make]=(machines[x.make]||0)+1;
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${color(a?.top||'?')}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">${a&&a.leadWins<a.wins&&a.leadWins===0?'Crew':'Driver / rider'}${a?' · '+a.first+'–'+a.last:''}${a?.topCat?' · '+esc(a.topCat):''}</p><h2 style="margin:6px 0 0">${esc(p.name)}</h2></div><div class="small mono muted">${rank?`#${rank} by class wins in ${esc(eraLabel())}`:''}</div></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Class wins',a?a.wins:0,a&&a.leadWins!==a.wins?`${a.leadWins} at the wheel`:'')}${kpi('Podiums',a?a.podiums:0,'')}${kpi('Classes won',a?a.ncats:0,a?Object.keys(a.cats).join(', '):'')}${kpi('Editions',a?a.nyears:0,a?`${yspan(a)}`:'')}${kpi('Marques',Object.keys(machines).length,a?.top?esc(a.top):'')}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Every podium</span><small>${rows.length} · click a year to open the edition</small></div><div class="tablewrap" style="max-height:560px"><table><tr><th>Year</th><th>Class</th><th class="n">Place</th><th>Crew</th><th>Marque</th><th>Route</th></tr>${rows.map(x=>`<tr class="${x.rank===1?'win':''}"><td><a href="#" data-year="${x.year}">${x.year}</a></td><td>${cl(x.cat)}</td><td class="n"><b>${x.rank}</b></td><td>${crewLinks(x.crew.filter(c=>c!==id))||'<span class="dim">solo</span>'}</td><td>${ml(x.make)}</td><td class="muted small">${esc(x.ed.route)}</td></tr>`).join('')}</table></div></div>
  <div><div class="panel"><div class="h3"><span>By class</span></div>${bars(Object.values(byC).sort((u,v)=>v.wins-u.wins||v.podiums-u.podiums),f=>f.wins,f=>`${f.podiums} podiums`,Math.max(1,...Object.values(byC).map(f=>f.wins)),'cls',f=>f.c,()=>color(a?.top||'?'))}</div><div class="panel" style="margin-top:14px"><div class="h3"><span>Machines</span><small>podium places by marque</small></div><div class="chips">${Object.entries(machines).sort((u,v)=>v[1]-u[1]).map(([m,n])=>`<a href="#" class="chip" data-marque="${esc(m)}"><i style="--c:${color(m)}"></i>${esc(m)} <span style="color:var(--muted)">${n}</span></a>`).join('')}</div></div>${wins.length>2?`<div class="panel" style="margin-top:14px"><div class="h3"><span>Wins, edition by edition</span></div><div class="yearbars">${eraSeasons().map(s=>{const w=wins.filter(x=>x.year===s.year).length;const pd=rows.filter(x=>x.year===s.year).length;return `<button type="button" data-year="${s.year}" title="${s.year} · ${w} wins · ${pd} podiums" style="--h:${w?100:pd?40:0}%;--team:${color(a?.top||'?')}"><i></i><span>${s.year%10===0?s.year:''}</span></button>`;}).join('')}</div></div>`:''}</div></div>`;}

/* ---------- Marques ---------- */
function marquesView(){const list=marqueAgg();const lens=state.lens;let rows=list.filter(a=>a[lens]!=null);rows.sort((a,b)=>b[lens]-a[lens]||b.wins-a.wins);rows=rows.slice(0,40);const max=Math.max(1,...rows.map(a=>a[lens]));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Marques · ${esc(eraLabel())}</h2></div><div class="small mono muted">${list.length} marques on a podium</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="lens" aria-label="Lens">${Object.entries(LENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(LENSES[lens][1])}</span></div>${marqueBars(rows,a=>a[lens],a=>`${yspan(a)} · ${a.wins} wins · ${a.podiums} podiums · ${Object.keys(a.cats).join(', ')||'no wins'}`,max)}</div>`;
  $('#lens').addEventListener('change',e=>{state.lens=e.target.value;render();});}
function marqueView(id){const all=marqueAgg();const a=all.find(x=>x.id===id);if(!a){marquesView();return;}const rank=[...all].sort((u,v)=>v.wins-u.wins).findIndex(x=>x.id===id)+1;
  const rows=eraRows().filter(x=>x.make===id);const wins=rows.filter(x=>x.rank===1).sort((u,v)=>v.year-u.year);
  const byY={};for(const x of rows){const y=byY[x.year]||(byY[x.year]={y:x.year,podiums:0,wins:0});y.podiums++;if(x.rank===1)y.wins++;}const maxW=Math.max(1,...Object.values(byY).map(y=>y.wins));
  const drivers={};for(const x of wins)for(const c of x.crew)drivers[c]=(drivers[c]||0)+1;const topD=Object.entries(drivers).sort((u,v)=>v[1]-u[1]).slice(0,12);
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${color(id)}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Marque · ${yspan(a)}</p><h2 style="margin:6px 0 0"><i class="dot" style="--c:${color(id)};width:.5em;height:.5em;vertical-align:.1em;margin-right:8px"></i>${esc(id)}</h2></div><div class="small mono muted">#${rank} by class wins in ${esc(eraLabel())}</div></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Class wins',a.wins,Object.entries(a.cats).sort((u,v)=>v[1]-u[1]).map(([c,n])=>`${c} ${n}`).join(' · '))}${kpi('Podiums',a.podiums,'')}${kpi('Different winners',a.nw,'')}${kpi('Editions',a.ny,`${yspan(a)}`)}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Winners on the marque</span><small>drivers, riders and crews</small></div>${bars(topD.map(([rid,n])=>({id:rid,n})),x=>x.n,x=>`${wins.filter(w=>w.crew.includes(x.id)).map(w=>w.year).sort().join(', ')}`,topD[0]?.[1]||1,'driver',x=>pname(x.id),()=>color(id))||'<p class="muted small">No class wins in this lens.</p>'}</div>
  <div><div class="panel"><div class="h3"><span>Wins and podiums by year</span><small>${Object.keys(byY).length} editions</small></div><div class="yearbars">${eraSeasons().map(s=>{const y=byY[s.year];return `<button type="button" data-year="${s.year}" title="${s.year} · ${y?y.wins:0} wins · ${y?y.podiums:0} podiums" style="--h:${y?Math.round(100*(y.wins?y.wins/maxW:0.25*Math.min(1,y.podiums/3))):0}%;--team:${color(id)}"><i></i><span>${s.year%10===0?s.year:''}</span></button>`;}).join('')}</div></div><div class="panel" style="margin-top:14px"><div class="h3"><span>Wins by class</span></div><div class="chips">${Object.entries(a.cats).sort((u,v)=>v[1]-u[1]).map(([c,n])=>`<a href="#" class="chip" data-cls="${esc(c)}"><i style="--c:${color(id)}"></i>${esc(c)} <span style="color:var(--muted)">${n}</span></a>`).join('')||'<span class="muted small">No wins in this lens.</span>'}</div></div></div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Every podium</span><small>${rows.length}</small></div><div class="tablewrap" style="max-height:520px"><table><tr><th>Year</th><th>Class</th><th class="n">Place</th><th>Crew</th><th>Route</th></tr>${[...rows].sort((u,v)=>v.year-u.year||u.rank-v.rank).map(x=>`<tr class="${x.rank===1?'win':''}"><td><a href="#" data-year="${x.year}">${x.year}</a></td><td>${cl(x.cat)}</td><td class="n"><b>${x.rank}</b></td><td>${crewLinks(x.crew)}</td><td class="muted small">${esc(x.ed.route)}</td></tr>`).join('')}</table></div></div>`;}

/* ---------- Classes ---------- */
function classesView(){const rows=eraRows();const byC={};for(const x of rows){const c=byC[x.cat]||(byC[x.cat]={c:x.cat,n:0,first:x.year,last:x.year,wins:{},mw:{},years:new Set()});c.n++;c.years.add(x.year);c.first=Math.min(c.first,x.year);c.last=Math.max(c.last,x.year);if(x.rank===1){for(const p of x.crew)c.wins[p]=(c.wins[p]||0)+1;c.mw[x.make]=(c.mw[x.make]||0)+1;}}
  const list=Object.values(byC).sort((a,b)=>CATS.indexOf(a.c)-CATS.indexOf(b.c));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Classes · ${esc(eraLabel())}</h2></div><div class="small mono muted">${list.length} classes · ${rows.length} podium places</div></div><div class="panel"><div class="tablewrap"><table><tr><th>Class</th><th class="n">Editions</th><th>Years</th><th>Most wins</th><th>Most wins, marque</th><th>What it is</th></tr>${list.map(f=>{const tr=Object.entries(f.wins).sort((a,b)=>b[1]-a[1])[0];const tm=Object.entries(f.mw).sort((a,b)=>b[1]-a[1])[0];return `<tr><td>${cl(f.c)}</td><td class="n">${f.years.size}</td><td>${yspan(f)}</td><td>${tr?dl(tr[0])+' <span class="dim">'+tr[1]+'</span>':'—'}</td><td>${tm?'<i class="dot" style="--c:'+color(tm[0])+'"></i>'+esc(tm[0])+' <span class="dim">'+tm[1]+'</span>':'—'}</td><td class="small muted">${esc(CAT_NOTE[f.c]||'')}</td></tr>`;}).join('')}</table></div><p class="small dim" style="margin:10px 0 0">Classes are the article’s: the cars and bikes from 1979, trucks from 1980, quads 2009–2024, side-by-sides from 2017, then the Challenger, Stock and Classic lists of the Saudi years.</p></div>`;}
function classView(c){const rows=eraRows().filter(x=>x.cat===c);if(!rows.length){classesView();return;}const wins=rows.filter(x=>x.rank===1).sort((a,b)=>a.year-b.year);const dw={};const mw={};for(const x of wins){for(const p of x.crew)dw[p]=(dw[p]||0)+1;mw[x.make]=(mw[x.make]||0)+1;}
  const topD=Object.entries(dw).sort((a,b)=>b[1]-a[1]).slice(0,12);const topM=Object.entries(mw).sort((a,b)=>b[1]-a[1]).slice(0,12);const years=[...new Set(rows.map(x=>x.year))].sort((a,b)=>a-b);
  // the longest run of one marque
  let best={m:null,n:0},cur={m:null,n:0};for(const x of wins){if(x.make===cur.m)cur.n++;else cur={m:x.make,n:1};if(cur.n>best.n)best={...cur};}
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${color(topM[0]?.[0]||'?')}"><div class="panel"><p class="eyebrow">Class · ${years[0]}–${years[years.length-1]}</p><h2 style="margin:6px 0 0">${esc(c)}</h2><p class="muted" style="margin:8px 0 0">${esc(CAT_NOTE[c]||'')}</p></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Editions',years.length,`${years[0]}–${years[years.length-1]}`)}${kpi('Most wins',topD[0]?pname(topD[0][0]):'—',topD[0]?topD[0][1]+' wins':'')}${kpi('Most wins, marque',topM[0]?topM[0][0]:'—',topM[0]?topM[0][1]+' wins':'')}${kpi('Longest run',best.m?best.m:'—',best.m?`${best.n} editions in a row`:'')}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Most wins</span><small>drivers, riders and crews</small></div>${bars(topD.map(([id,n])=>({id,n})),x=>x.n,x=>`${wins.filter(w=>w.crew.includes(x.id)).map(w=>w.year).join(', ')}`,topD[0]?.[1]||1,'driver',x=>pname(x.id),x=>color(wins.find(w=>w.crew.includes(x.id))?.make||'?'))}</div><div class="panel"><div class="h3"><span>Most wins, marques</span></div>${marqueBars(topM.map(([id,n])=>({id,wins:n})),x=>x.wins,x=>`${wins.filter(w=>w.make===x.id).map(w=>w.year).slice(0,14).join(', ')}${wins.filter(w=>w.make===x.id).length>14?'…':''}`,topM[0]?.[1]||1)}</div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Every winner</span><small>${wins.length}</small></div><div class="tablewrap" style="max-height:560px"><table><tr><th>Year</th><th>Winner</th><th>Marque</th><th>Second</th><th>Third</th><th>Route</th></tr>${[...wins].reverse().map(x=>{const s=byYear[x.year];const p2=s.rows.find(r=>r.cat===c&&r.rank===2),p3=s.rows.find(r=>r.cat===c&&r.rank===3);return `<tr><td><a href="#" data-year="${x.year}">${x.year}</a></td><td>${crewLinks(x.crew)}</td><td>${ml(x.make)}</td><td class="muted">${p2?crewLinks(p2.crew)+' <span class="dim">'+esc(p2.make)+'</span>':''}</td><td class="muted">${p3?crewLinks(p3.crew)+' <span class="dim">'+esc(p3.make)+'</span>':''}</td><td class="muted small">${esc(x.ed.route)}</td></tr>`;}).join('')}</table></div></div>`;}

/* ---------- Records ---------- */
function topMarqueIn(id,cat){const m={};for(const x of eraRows()){if(x.cat===cat&&x.rank===1&&x.crew.includes(id))m[x.make]=(m[x.make]||0)+1;}return Object.entries(m).sort((p,q)=>q[1]-p[1])[0]?.[0]||null;}
function recordsView(){const rows=eraRows();const wins=rows.filter(x=>x.rank===1);const drivers=driverAgg().sort(driverOrder);const marques=marqueAgg().sort((a,b)=>b.wins-a.wins||b.podiums-a.podiums);const ss=eraSeasons().filter(s=>!s.ed.cancelled);
  const perCat=k=>driverAgg().filter(a=>a.cats[k]).sort((a,b)=>(b.cats[k]||0)-(a.cats[k]||0)||b.podiums-a.podiums).slice(0,8);
  const multi=drivers.filter(a=>a.ncats>=2).sort((a,b)=>b.ncats-a.ncats||b.wins-a.wins).slice(0,10);
  const streaks=[];for(const k of CATS){const ws=wins.filter(x=>x.cat===k).sort((a,b)=>a.year-b.year);let cur=null;for(const x of ws){if(cur&&cur.m===x.make&&x.year-cur.last<=2){cur.n++;cur.last=x.year;}else{if(cur)streaks.push(cur);cur={m:x.make,k,n:1,first:x.year,last:x.year};}}if(cur)streaks.push(cur);}
  const topStreaks=streaks.sort((a,b)=>b.n-a.n||a.first-b.first).slice(0,10);
  const towns={};for(const s of ss)for(const t of s.ed.stops)towns[t]=(towns[t]||0)+1;const topTowns=Object.entries(towns).sort((a,b)=>b[1]-a[1]).slice(0,10);
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Records · ${esc(eraLabel())}</h2></div><div class="small mono muted">${ss.length} editions held</div></div>
  <div class="kpis">${kpi('Editions held',ss.length,`${eraSeasons().length-ss.length} cancelled`)}${kpi('Class wins',wins.length,`${rows.length} podium places`)}${kpi('People on a podium',fmt(drivers.length),`${drivers.filter(d=>d.wins).length} winners`)}${kpi('Marques',marques.length,`${marques.filter(m=>m.wins).length} with a win`)}${kpi('Most wins',drivers[0]?pname(drivers[0].id):'—',drivers[0]?`${drivers[0].wins} · ${drivers[0].first}–${drivers[0].last}`:'')}</div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Most class wins</span><small>driver, rider or crew</small></div>${driverBars(drivers.slice(0,10),a=>a.wins,a=>`${yspan(a)} · ${Object.entries(a.cats).map(([c,n])=>c+' '+n).join(', ')}`,drivers[0]?.wins||1)}</div><div class="panel"><div class="h3"><span>Most podiums</span></div>${driverBars([...drivers].sort((a,b)=>b.podiums-a.podiums||b.wins-a.wins).slice(0,10),a=>a.podiums,a=>`${a.wins} wins · ${yspan(a)}`,Math.max(1,...drivers.map(a=>a.podiums)))}</div><div class="panel"><div class="h3"><span>Winners in more than one class</span></div>${driverBars(multi,a=>a.ncats,a=>`${Object.entries(a.cats).map(([c,n])=>c+' '+n).join(', ')}`,Math.max(1,...multi.map(a=>a.ncats)))||'<p class="muted small">None in this lens.</p>'}</div></div>
  <div class="three" style="margin-top:14px">${['Cars','Bikes','Trucks'].filter(k=>state.cat==='all'||k===state.cat).map(k=>`<div class="panel"><div class="h3"><span>${esc(k)}: most wins</span></div>${driverBars(perCat(k),a=>a.cats[k]||0,a=>`${yspan(a)} · ${esc(topMarqueIn(a.id,k)||'')}`,perCat(k)[0]?.cats[k]||1)}</div>`).join('')}</div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Marques by class wins</span></div>${marqueBars(marques.slice(0,10),a=>a.wins,a=>`${yspan(a)} · ${a.nw} different winners`,marques[0]?.wins||1)}</div><div class="panel"><div class="h3"><span>Longest runs</span><small>one marque, one class, consecutive held editions</small></div><div class="board">${topStreaks.map((s,i)=>`<button type="button" class="bar" data-marque="${esc(s.m)}" style="--i:${i};--team:${color(s.m)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(s.m)}<small> ${esc(s.k)}</small></span><small>${yspan(s)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*s.n/(topStreaks[0]?.n||1))}%"></span></span></span><span class="val">${s.n}</span></button>`).join('')}</div></div><div class="panel"><div class="h3"><span>Towns on the route</span><small>editions that started, passed or finished there</small></div><div class="board">${topTowns.map(([t,n],i)=>`<div class="bar" style="--i:${i};--team:var(--accent)"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(t)}</span><small>${ss.filter(s=>s.ed.stops.includes(t)).map(s=>s.year).slice(0,10).join(', ')}${n>10?'…':''}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*n/(topTowns[0]?.[1]||1))}%"></span></span></span><span class="val">${n}</span></div>`).join('')}</div></div></div>`;}

/* ---------- Barcode ---------- */
const HEATMETRICS={wins:['Class wins','Classes won by the marque that year.'],podiums:['Podiums','Podium places that year.']};
function barcodeView(){const ss=eraSeasons();const years=ss.map(s=>s.year);const cell={};const tot={};
  for(const s of ss)for(const x of s.rows){const m=x.make;const c=cell[m]||(cell[m]={});const k=c[s.year]||(c[s.year]={wins:0,podiums:0});k.podiums++;if(x.rank===1)k.wins++;tot[m]=(tot[m]||0)+(x.rank===1?1:0);}
  const marques=Object.keys(cell).sort((a,b)=>tot[b]-tot[a]).slice(0,28);const val=k=>k?k[state.heat]:0;const max=Math.max(1,...marques.flatMap(m=>years.map(y=>val(cell[m][y]))));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Barcode · ${esc(eraLabel())}</h2></div><div class="small mono muted">${marques.length} marques × ${years.length} editions</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="heat" aria-label="Metric">${Object.entries(HEATMETRICS).map(([k,v])=>`<option value="${k}" ${k===state.heat?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(HEATMETRICS[state.heat][1])} Brightness is the cell’s share of the brightest cell; colour is the marque’s. Rows ordered by class wins.</span></div>
  <div class="barcode"><div class="bc-row"><span></span><span class="cells" style="gap:2px">${years.map(y=>`<i style="background:none;height:14px;font-size:8px;color:var(--dim);text-align:center;line-height:14px">${years.length<=30||y%5===0?String(y).slice(2):''}</i>`).join('')}</span><span></span></div>${marques.map(m=>`<div class="bc-row"><span class="lab" data-marque="${esc(m)}">${esc(m)}</span><span class="cells">${years.map(y=>{const v=val(cell[m][y]);const a=v?Math.max(.12,v/max):0;return `<i data-year="${y}" title="${esc(m)} ${y} · ${v}" style="--c:${mixHex(color(m),'#0f1113',a)}"></i>`;}).join('')}</span><span class="tot">${fmt(tot[m])}</span></div>`).join('')}</div></div>`;
  $('#heat').addEventListener('change',e=>{state.heat=e.target.value;render();});}

/* ---------- Duel ---------- */
function swingChart(el,pts,labA,labB,cA,cB){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(180,box.height);const padL=30,padR=30,padT=16,padB=22;const n=pts.length;const max=Math.max(1,...pts.map(p=>Math.abs(p.v)));const x=i=>padL+(n>1?i*(W-padL-padR)/(n-1):(W-padL-padR)/2),y=v=>padT+(H-padT-padB)*(1-(v+max)/(2*max));
  const mid=y(0);let d='';pts.forEach((p,i)=>{d+=(i?'L':'M')+x(i).toFixed(1)+' '+y(p.v).toFixed(1);});
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Head-to-head swing"><line class="gridl" x1="${padL}" x2="${W-padR}" y1="${mid.toFixed(1)}" y2="${mid.toFixed(1)}"/><text class="lb" x="${padL}" y="${padT-4}" style="fill:${cA}">${esc(labA)} ahead</text><text class="lb" x="${padL}" y="${H-6}" style="fill:${cB}">${esc(labB)} ahead</text><path class="ser" d="${d}" style="--c:var(--muted)"/>${pts.map((p,i)=>`<circle class="pt" cx="${x(i).toFixed(1)}" cy="${y(p.v).toFixed(1)}" r="4" fill="${p.win==='A'?cA:p.win==='B'?cB:'#5b616b'}" data-year="${p.y}"><title>${esc(p.label)}</title></circle>`).join('')}</svg>`;}
function duelView(){const drivers=driverAgg().sort(driverOrder);const marques=marqueAgg().sort((a,b)=>b.wins-a.wins);
  if(state.duelBy==='d'){const ids=drivers.slice(0,150).map(p=>p.id);if(!state.dA||!PEOPLE[state.dA])state.dA=ids[0];if(!state.dB||!PEOPLE[state.dB]||state.dB===state.dA)state.dB=ids.find(i=>i!==state.dA);}
  else{const ids=marques.slice(0,40).map(m=>m.id);if(!state.dA||!ids.includes(state.dA))state.dA=ids[0];if(!state.dB||!ids.includes(state.dB)||state.dB===state.dA)state.dB=ids.find(i=>i!==state.dA);}
  const opts=sel=>state.duelBy==='d'?[...new Set([state.dA,state.dB,...drivers.slice(0,150).map(p=>p.id)])].filter(Boolean).map(id=>`<option value="${esc(id)}" ${id===sel?'selected':''}>${esc(pname(id))}</option>`).join(''):marques.slice(0,40).map(m=>`<option value="${esc(m.id)}" ${m.id===sel?'selected':''}>${esc(m.id)}</option>`).join('');
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Head to head · ${esc(eraLabel())}</h2></div><div class="small mono muted">${state.duelBy==='d'?'drivers and riders · class wins and the podiums they shared':'marques · class wins, edition by edition'}</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="duelBy" aria-label="Compare"><option value="d" ${state.duelBy==='d'?'selected':''}>Drivers and riders</option><option value="m" ${state.duelBy==='m'?'selected':''}>Marques</option></select><select id="dA" aria-label="First">${opts(state.dA)}</select><span class="mono small muted">vs</span><select id="dB" aria-label="Second">${opts(state.dB)}</select></div><div id="duelBody"></div></div>`;
  $('#duelBy').addEventListener('change',e=>{state.duelBy=e.target.value;state.dA=null;state.dB=null;render();});$('#dA').addEventListener('change',e=>{state.dA=e.target.value;render();});$('#dB').addEventListener('change',e=>{state.dB=e.target.value;render();});
  const a=state.dA,b=state.dB;if(!a||!b){$('#duelBody').innerHTML='<p class="muted">Pick two.</p>';return;}
  const isD=state.duelBy==='d';const has=(x,id)=>isD?x.crew.includes(id):x.make===id;const cA=isD?color(drivers.find(p=>p.id===a)?.top||'?'):color(a),cB=isD?color(drivers.find(p=>p.id===b)?.top||'?'):color(b);const nameOf=id=>isD?pname(id):id;
  const shared=[];let lead=0;const pts=[];let wa=0,wb=0,ha=0,hb=0;
  for(const s of eraSeasons()){let ya=0,yb=0;const cats=[...new Set(s.rows.map(x=>x.cat))];for(const k of cats){const rows=s.rows.filter(x=>x.cat===k);const xa=rows.find(x=>has(x,a)),xb=rows.find(x=>has(x,b));if(xa&&xa.rank===1)ya++;if(xb&&xb.rank===1)yb++;if(xa&&xb){shared.push({s,k,xa,xb});if(xa.rank<xb.rank)ha++;else if(xb.rank<xa.rank)hb++;}}wa+=ya;wb+=yb;lead+=ya-yb;pts.push({v:lead,win:ya>yb?'A':yb>ya?'B':'',y:s.year,label:`${s.year} · ${nameOf(a)} ${ya} · ${nameOf(b)} ${yb}`});}
  $('#duelBody').innerHTML=`<div class="duel-heads"><div class="dh" style="--team:${cA}"><span class="eyebrow">${esc(nameOf(a))}</span><b>${wa}</b><small>class wins in the lens${shared.length?` · ahead in ${ha} of ${shared.length} shared podiums`:''}</small></div><div class="dh" style="--team:${cB}"><span class="eyebrow">${esc(nameOf(b))}</span><b>${wb}</b><small>class wins in the lens${shared.length?` · ahead in ${hb}`:''}</small></div></div><div class="h3" style="margin-top:18px"><span>The lead in class wins, edition by edition</span><small>cumulative</small></div><div class="chart" id="duelSwing" style="height:220px"></div>
  ${shared.length?`<div class="h3" style="margin-top:18px"><span>Podiums they shared</span><small>${shared.length} · same year, same class</small></div><div class="tablewrap" style="max-height:480px"><table><tr><th>Year</th><th>Class</th><th style="color:${cA}">${esc(nameOf(a))}</th><th style="color:${cB}">${esc(nameOf(b))}</th></tr>${[...shared].reverse().map(({s,k,xa,xb})=>`<tr><td><a href="#" data-year="${s.year}">${s.year}</a></td><td>${esc(k)}</td><td>P${xa.rank} · ${esc(xa.make)}</td><td>P${xb.rank} · ${esc(xb.make)}</td></tr>`).join('')}</table></div>`:''}`;
  if(pts.length)swingChart($('#duelSwing'),pts,nameOf(a),nameOf(b),cA,cB);}

/* ---------- Sources & coverage ---------- */
function drawSources(){const cov=A.coverage||{};
  $('#sourcesBody').innerHTML=`<p class="eyebrow">Desert edition / ${esc(A.snapshot)}</p><h2>Every Dakar podium since 1979, one archive.</h2><div class="kpis">${kpi('Editions',fmt(cov.editions),`${cov.held} held · ${cov.cancelled} cancelled`)}${kpi('Podium places',fmt(cov.podiums),`${cov.wins} class wins`)}${kpi('People',fmt(cov.people),'drivers, riders and crews')}${kpi('Marques',fmt(cov.marques),'')}${kpi('Classes',fmt(cov.categories),'')}</div>
<h3>Sources</h3><ol><li><a href="${esc(A.source)}" target="_blank" rel="noopener">Wikipedia’s Dakar Rally article</a>, revision ${esc(A.revision)}, read on ${esc(A.retrieved)} (<a href="${esc(A.licenceUrl)}" target="_blank" rel="noopener">CC BY-SA 4.0</a>, Wikipedia contributors)<p>${esc(A.method||'')}</p></li><li><a href="${esc(MAP.sourceUrl)}" target="_blank" rel="noopener">Natural Earth 1:110m land</a> (public domain)<p>The land silhouette behind every route, projected and rounded by the prototype. Routes are drawn between the towns the archive names — a schematic line, not the course.</p></li></ol>
<h3>How to read the statistics</h3><p class="small muted">A class win is first place in a class as the article lists it, and every member of the crew — driver, navigator, the truck’s mechanic — receives the credit; the “wins at the wheel” lens keeps the lead driver or rider alone. Podiums are the first three of each class; the archive holds nothing below third. Classes are the article’s own: cars and bikes from the first edition, trucks from 1980, quads from 2009 to 2024, side-by-sides from 2017, and the Challenger, Stock and Classic lists of the Saudi years. The 2008 edition, cancelled before the start, is a gap, never a zero.</p>`;}

/* ---------- deep links ---------- */
let routeLock=false;
function writeRoute(){if(routeLock)return;const q=[];if(state.cat!=='all')q.push('class='+encodeURIComponent(state.cat));if(state.era!=='all')q.push('era='+encodeURIComponent(state.era));if(state.whole)q.push('whole=1');else q.push('season='+state.year);q.push('tab='+state.tab);for(const [k,t] of [['driver','drivers'],['marque','marques'],['cls','classes']]){if(state.tab===t&&state[k])q.push(k+'='+encodeURIComponent(state[k]));}if(state.tab==='duel'&&state.dA&&state.dB)q.push('duel='+encodeURIComponent(state.dA+'|'+state.dB)+'&by='+state.duelBy);const h='#'+q.join('&');if(location.hash!==h){try{history[location.hash?'pushState':'replaceState'](null,'',h);}catch(e){}}}
function readRoute(){const h=location.hash.replace(/^#\/?/,'');if(!h||/^static-/.test(h))return false;const p={};for(const kv of h.split('&')){const i=kv.indexOf('=');p[i<0?kv:kv.slice(0,i)]=i<0?'1':decodeURIComponent(kv.slice(i+1));}let any=false;
  if(p.class&&(p.class==='all'||CATS.includes(p.class))){state.cat=p.class;any=true;}rebuildSeasons();
  if(p.era&&(p.era==='all'||ERAS.some(e=>e.id===p.era))){state.era=p.era;any=true;}
  if(p.season&&byYear[+p.season]){state.year=+p.season;any=true;}
  if(state.era!=='all'&&!inEraYear(state.year)){if(p.season)state.era='all';else state.year=eraSeasons().slice(-1)[0]?.year||state.year;}
  state.whole=p.whole==='1';if(state.whole)any=true;
  if(p.tab&&TABS.some(t=>t[0]===p.tab)){state.tab=p.tab;any=true;}
  state.driver=p.driver&&PEOPLE[p.driver]?p.driver:null;state.marque=p.marque||null;state.cls=p.cls&&CATS.includes(p.cls)?p.cls:null;
  if(p.duel){const [a,b]=p.duel.split('|');state.duelBy=p.by==='m'?'m':'d';state.dA=a;state.dB=b;any=true;}
  return any;}

/* ---------- render, navigation, events ---------- */
function render(){stopReplay();drawTabs();if(tour.stopped||!tour.timer)drawEraStrip();const v={season:seasonView,drivers:()=>state.driver?driverView(state.driver):driversView(),marques:()=>state.marque?marqueView(state.marque):marquesView(),classes:()=>state.cls?classView(state.cls):classesView(),records:recordsView,barcode:barcodeView,duel:duelView}[state.tab];try{v();}catch(e){$('#view').innerHTML=`<p class="muted">Something in this view could not be drawn: ${esc(e.message)}</p>`;console.error(e);}StageNav.draw();writeRoute();}
function go(tab,scroll=true){state.tab=tab;render();if(scroll)$('#stage').scrollIntoView({behavior:RM?'auto':'smooth',block:'start'});}
function ensureYearInLens(y){if(state.era!=='all'&&!inEraYear(y)){state.era='all';$('#eraSelect').value='all';}}
function setSeason(y,scroll){state.whole=false;ensureYearInLens(y);state.year=y;fillSeasons();applyTheme();drawRiver();state.tab='season';go(state.tab,scroll);}
function fillSeasons(){const sel=$('#season');const ss=eraSeasons();if(!ss.length){sel.innerHTML='';return;}const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);sel.innerHTML=`<option value="era">${e?'Whole era':'All years'} · ${ss[0].year}–${ss[ss.length-1].year}</option>`+'<optgroup label="Newest first">'+ss.slice().reverse().map(s=>`<option value="${s.year}">${s.year}${s.ed.cancelled?' · cancelled':''}</option>`).join('')+'</optgroup>';sel.value=state.whole?'era':state.year;}
function setEra(id){tourStop();state.era=id;$('#eraSelect').value=id;if(id!=='all'){if(!inEraYear(state.year)){const last=eraSeasons().slice(-1)[0];state.year=last?last.year:state.year;}}fillSeasons();applyTheme();drawRiver();drawGrid();render();}
function relens(rerender=true){rebuildSeasons();if(!byYear[state.year])state.year=LAST_YEAR;state.driver=null;state.marque=null;state.cls=null;fillSeasons();$('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.filter(e=>e.to>=FIRST_YEAR).map(e=>`<option value="${e.id}">${esc(ERA_SHORT[e.id]||e.name)} · ${e.from}–${e.to}</option>`).join('');$('#eraSelect').value=state.era;if(rerender){applyTheme();drawRiver();drawGrid();render();}}
function init(){
  landDefs();rebuildSeasons();
  $('#family').innerHTML=`<option value="all">All classes</option>`+CATS.map(f=>`<option value="${esc(f)}">${esc(f)}</option>`).join('');
  $('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.map(e=>`<option value="${e.id}">${esc(ERA_SHORT[e.id]||e.name)} · ${e.from}–${e.to}</option>`).join('');
  const topM=marqueAgg().sort((a,b)=>b.wins-a.wins).slice(0,14).map(m=>m.id);
  $('#theme').innerHTML=`<option value="champion">Marque of the year</option>`+topM.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join('');
  fillSeasons();
  const cov=A.coverage||{};
  $('#edition').innerHTML=`<span><span class="live"></span><b>${fmt(cov.held)}</b> editions</span><span><b>${fmt(cov.wins)}</b> class wins</span><span><b>${fmt(cov.podiums)}</b> podium places</span><span><b>${fmt(cov.people)}</b> people</span><span>through <b>${A.lastYear}</b></span>`;
  $('#reading').open=false;
  const deep=readRoute();if(deep){tourStop();$('#family').value=state.cat;$('#eraSelect').value=state.era;fillSeasons();}
  drawSources();applyTheme();drawRiver();drawGrid();render();lightsOut();if(deep&&(state.tab!=='season'||state.whole||state.era!=='all'))setTimeout(()=>$('#stage').scrollIntoView({behavior:'auto',block:'start'}),60);
  addEventListener('hashchange',()=>{if(/^#static-/.test(location.hash)){$('#reading').open=true;return;}routeLock=true;try{if(readRoute()){tourStop();$('#family').value=state.cat;$('#eraSelect').value=state.era;fillSeasons();applyTheme();drawRiver();drawGrid();render();}}finally{routeLock=false;}});
  $('#eraSelect').addEventListener('change',e=>setEra(e.target.value));
  $('#family').addEventListener('change',e=>{state.cat=e.target.value;relens();});
  $('#season').addEventListener('change',e=>{if(e.target.value==='era'){state.whole=true;applyTheme();drawRiver();state.tab='season';go(state.tab,false);}else setSeason(+e.target.value,false);});
  $('#theme').addEventListener('change',applyTheme);
  $('#eraStrip').addEventListener('click',e=>{const s=e.target.closest('[data-era]');if(s)setEra(state.era===s.dataset.era?'all':s.dataset.era);});
  $('#eraStrip').addEventListener('pointerenter',()=>{tourPause();},{passive:true});$('#eraStrip').addEventListener('pointerleave',()=>{if(!tour.stopped)tourStart();},{passive:true});
  $('#eraStrip').addEventListener('mouseover',e=>{const s=e.target.closest('[data-era]');if(s&&!tour.stopped){drawEraStrip(s.dataset.era);}});
  if('IntersectionObserver' in window){new IntersectionObserver(en=>{tour.visible=en[0].isIntersecting;if(tour.visible)tourStart();else tourPause();},{threshold:.2}).observe($('#eraStrip'));}else{tour.visible=true;tourStart();}
  $('#gridSort').addEventListener('change',e=>{state.gridSort=e.target.value;drawGrid();});$('#gridFind').addEventListener('input',e=>{state.gridFind=e.target.value;drawGrid();});
  $('#circuits').addEventListener('click',e=>{const b=e.target.closest('[data-year]');if(b)setSeason(+b.dataset.year,true);});
  const clear=t=>{if(t==='drivers')state.driver=null;if(t==='marques')state.marque=null;if(t==='classes')state.cls=null;};
  $('#tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;clear(b.dataset.tab);go(b.dataset.tab,false);});
  $('#view').addEventListener('click',e=>{const a=e.target.closest('[data-driver],[data-marque],[data-cls],[data-year],[data-tab]');if(!a)return;if(a.tagName==='A')e.preventDefault();
    if(a.dataset.tab){clear(a.dataset.tab);go(a.dataset.tab,false);return;}
    if(a.dataset.year){const y=+a.dataset.year;if(!byYear[y])return;setSeason(y,false);return;}
    if(a.dataset.driver){state.driver=a.dataset.driver;go('drivers',false);return;}
    if(a.dataset.marque){state.marque=a.dataset.marque;go('marques',false);return;}
    if(a.dataset.cls){state.cls=a.dataset.cls;go('classes',false);return;}});
  addEventListener('resize',()=>{clearTimeout(window.__rz);window.__rz=setTimeout(()=>{drawRiver();if(['season','duel','records','classes'].includes(state.tab))render();},150);});
}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):StageNav.mount({seasons:()=>eraSeasons().map(s=>({year:s.year,cancelled:!!(s.ed&&s.ed.cancelled)})),year:()=>state.year,whole:()=>state.whole,tab:()=>state.tab,setYear:y=>setSeason(y,false),unitTab:null});
init();
