/* ---------- the Grid ---------- */
function circuitModel(){const rr=eraRaces();const m={};for(const r of rr){let c=m[r.cid]||(m[r.cid]={cid:r.cid,count:0,first:r.year,last:r.year,wins:{},layout:null,name:r.circuit,country:r.country,place:r.place});c.count++;c.first=Math.min(c.first,r.year);c.last=Math.max(c.last,r.year);c.layout=r.layout||c.layout;const w=r.rows.find(x=>x.cw);if(w)c.wins[w.t]=(c.wins[w.t]||0)+1;}
  return Object.values(m).map(c=>({...c,top:Object.entries(c.wins).sort((a,b)=>b[1]-a[1])[0]?.[0]||null}));}
function drawGrid(){const list=circuitModel();const q=state.gridFind.trim().toLowerCase();let shown=list.filter(c=>!q||(c.name+' '+c.country+' '+c.place).toLowerCase().includes(q));
  const sorters={count:(a,b)=>b.count-a.count||a.name.localeCompare(b.name),name:(a,b)=>a.name.localeCompare(b.name),country:(a,b)=>a.country.localeCompare(b.country)||b.count-a.count,recent:(a,b)=>b.last-a.last||b.count-a.count};shown.sort(sorters[state.gridSort]);
  const bigN=state.gridSort==='count'&&!q?6:0;
  $('#gridLede').textContent=`${list.length} circuits have hosted a Grand Prix in ${eraLabel().replace(' · ',', ')}. Each outline is drawn from the circuit’s own survey line, lit in the colours of its most successful constructor there; the size follows how often the calendar returned.`;
  $('#circuits').innerHTML=shown.map((c,i)=>`<button type="button" class="circ${i<bigN?' big':''}" data-cid="${esc(c.cid)}" style="${c.top?teamVar(c.top):'--team:#8b9099'}" title="${esc(c.name)} · ${c.count} Grands Prix · ${c.first}–${c.last}${c.top?' · most wins: '+esc(tn(c.top)):''}"><span class="ct">${esc(c.country)}</span><span class="n">${c.count}</span>${outline(c.layout,{lap:!RM,delay:(i%9)-9})}<span class="nm">${esc(c.name)}</span></button>`).join('')||`<p class="muted">No circuit matches.</p>`;}

/* ---------- Stage: tabs, era strip, era context ---------- */
const TABS=[['season','Season'],['race','Race'],['drivers','Drivers'],['teams','Constructors'],['circuits','Circuits'],['records','Records'],['barcode','Barcode'],['duel','Duel']];
function drawTabs(){$('#tabs').innerHTML=TABS.map(([id,l])=>`<button type="button" role="tab" data-tab="${id}" aria-pressed="${state.tab===id}">${l}</button>`).join('');
  $('#stageStatus').textContent=(state.tab==='season'||state.tab==='race')&&!state.whole?`${state.year} · ${eraOf(state.year)?.name||''}`:eraLabel();}
function drawEraStrip(preview){const strip=$('#eraStrip');if(!strip.children.length)strip.innerHTML=ERAS.map(e=>`<button type="button" style="--w:${e.to-e.from+1}" data-era="${e.id}" title="${esc(e.name)} · ${e.from}–${e.to}" aria-label="${esc(e.name)} ${e.from}–${e.to}"></button>`).join('');
  for(const b of strip.children){b.classList.toggle('on',state.era===b.dataset.era);b.classList.toggle('demo',preview===b.dataset.era);}
  const e=preview?ERAS.find(x=>x.id===preview):state.era==='all'?eraOf(state.year):ERAS.find(x=>x.id===state.era);
  $('#eraCaption').innerHTML=`<span><b>${esc(e.name)}</b> · ${e.from}–${e.to}</span><span class="dim">${state.era===e.id?'Lens on · click again to release':'Click a segment to focus the whole page on that era'}</span>`;
  const ctx=$('#eraContext');ctx.innerHTML=`<div class="era-car">${e.car.svg}</div><div><p class="eyebrow">${state.era===e.id?'Era lens':preview?'Era':'Era of the selected season'} · ${e.from}–${e.to}</p><h3>${esc(e.name)}</h3><p>${esc(e.text)}</p><div class="chips">${e.car.features.map(f=>`<span>${esc(f)}</span>`).join('')}</div><p class="small dim" style="margin:10px 0 0">${esc(e.car.label)} · schematic outline, not a specific car${e.car.source?` · <a href="${esc(e.car.source)}" target="_blank" rel="noopener">reference ↗</a>`:''}</p></div>`;}
/* Attract mode: the strip walks through the eras, one every few seconds, until the visitor touches it. */
const tour={i:-1,timer:null,visible:false,stopped:RM};
function tourStep(){if(tour.stopped||!tour.visible)return;tour.i=(tour.i+1)%ERAS.length;const ctx=$('#eraContext');ctx.classList.add('swap');setTimeout(()=>{if(tour.stopped)return;drawEraStrip(ERAS[tour.i].id);ctx.classList.remove('swap');},260);tour.timer=setTimeout(tourStep,4200);}
function tourStart(){if(tour.stopped||tour.timer)return;tour.timer=setTimeout(tourStep,1800);}
function tourPause(){clearTimeout(tour.timer);tour.timer=null;}
function tourStop(){if(tour.stopped)return;tour.stopped=true;tourPause();$('#eraContext').classList.remove('swap');drawEraStrip();}
/* ---------- Season ---------- */
function seasonStandings(s){
  const st=standingsOf(s);const dr=st.drivers.map(d=>({id:d.id,p:d.p,pts:d.pts,wins:d.wins,teams:d.teams,team:d.teams?.[0]}));const derivedD=st.derived;
  let tm,derived=false;if(s.teams&&s.teams.length)tm=s.teams.map(t=>({id:t.id,p:t.p,pts:t.pts,wins:t.wins}));else{derived=true;const m={};for(const r of s.races){for(const x of r.rows){let a=m[x.t]||(m[x.t]={id:x.t,pts:0,wins:0});a.pts+=x.pts;a.wins+=x.cw;}}tm=Object.values(m).sort((a,b)=>b.pts-a.pts||b.wins-a.wins).map((t,i)=>({...t,p:String(i+1)}));}
  return {dr,tm,derived,derivedD};}
function cumulative(s,top=8){const done=s.races.filter(r=>r.rows.length);const sd=standingsOf(s).drivers;const ids=sd.slice(0,top).map(d=>d.id);const series=ids.map(id=>({id,team:sd.find(d=>d.id===id).teams?.[0],pts:[0]}));
  for(const r of done){for(const sr of series){const x=r.rows.find(x=>x.d===sr.id);const sp=r.sprint.find(x=>x.d===sr.id);sr.pts.push(sr.pts[sr.pts.length-1]+(x?x.pts:0)+(sp?sp.pts:0));}}
  return {series,rounds:done.map(r=>r.round)};}
function drawChart(el,series,rounds,labelOf,xl=r=>'R'+r){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(200,box.height);const padL=34,padR=90,padT=14,padB=26;const max=Math.max(1,...series.flatMap(s=>s.pts));const n=rounds.length;const x=i=>padL+(n?i*(W-padL-padR)/n:0),y=v=>padT+(H-padT-padB)*(1-v/max);
  let g='';const step=max>200?100:max>60?25:max>20?10:5;for(let v=0;v<=max;v+=step)g+=`<line class="gridl" x1="${padL}" x2="${W-padR}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}"/><text class="lb" x="${padL-6}" y="${(y(v)+3).toFixed(1)}" text-anchor="end">${v}</text>`;
  for(let i=0;i<n;i++)if(n<=30||i%2===0)g+=`<text class="lb" x="${x(i+1).toFixed(1)}" y="${H-8}" text-anchor="middle">${xl(rounds[i])}</text>`;
  const paths=series.map((s,k)=>{const d=s.pts.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1)).join('');const last=s.pts[s.pts.length-1];return `<path class="ser" d="${d}" style="--c:${color(s.team)}"><title>${esc(labelOf(s.id))} · ${fmt(last)}</title></path><text class="end" x="${(x(n)+6).toFixed(1)}" y="${(y(last)+4-(k%2?0:0)).toFixed(1)}" style="--c:${color(s.team)}">${esc(labelOf(s.id))} ${fmt(last)}</text>`;}).join('');
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Cumulative points by round">${g}${paths}</svg>`;}
function seasonView(){if(state.whole)return eraView();const s=byYear[state.year];const {dr,tm,derived,derivedD}=seasonStandings(s);const done=s.races.filter(r=>r.rows.length);const champ=dr[0];const ct=tm[0];const cteam=champ?.team;const partial=String(s.year)===(DATA.cutoff||'').slice(-4);
  const wins=new Set(done.map(r=>r.rows.find(x=>x.dw)?.d).filter(Boolean)).size;const teamsWon=new Set(done.map(r=>r.rows.find(x=>x.cw)?.t).filter(Boolean)).size;
  const podium=dr.slice(0,3);const maxPts=podium[0]?.pts||1;const order=[podium[1],podium[0],podium[2]];
  const head=`<div class="season-head"><div class="champ-card" style="${cteam?`--accent:${color(cteam)};--on-accent:${onColor(color(cteam))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${partial?'Season in progress · standings as at '+esc(DATA.cutoff):'Drivers’ champion'}</p><div class="yr">${s.year}</div>${champ?`<div class="who"><small>${partial?'Leads the standings':derivedD?'Most race points':'Champion'}</small>${esc(name(champ.id))}</div><div class="team"><i></i>${esc(champ.teams.map(tn).join(' / '))}</div><div class="facts"><div><b>${fmt(champ.pts)}</b>points</div><div><b>${champ.wins}</b>wins</div><div><b>${done.length}</b>Grands Prix${done.length<s.races.length?` of ${s.races.length}`:''}</div><div><b>${wins}</b>race winners</div></div>`:'<div class="who">No results yet</div>'}${ct?`<p class="small" style="margin:18px 0 0;color:var(--ink);opacity:.8">Constructors: <b>${esc(tn(ct.id))}</b> · ${fmt(ct.pts)} pts${derived?' · <span class="dim">from race points; no constructors’ championship was awarded</span>':''}</p>`:''}</div>
  <div><div class="podium">${order.map((d,i)=>d?`<button type="button" class="step p${d.p} bar" data-driver="${esc(d.id)}" style="--h:${Math.round(120+120*d.pts/maxPts)}px;${teamVar(d.team)};display:flex"><span class="pos">${esc(d.p)}</span><span class="nm">${esc(short(d.id))}</span><span class="pt">${fmt(d.pts)} pts · ${d.wins} wins · ${esc(tn(d.team))}</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const cal=`<div class="h3"><span>Calendar</span><small>${partial?done.length+' rounds run so far':done.length+' rounds'} · click a race to replay it</small></div><div class="calendar">${s.races.map(r=>{const w=r.rows.find(x=>x.dw);return `<button type="button" class="cal${r.rows.length?'':' future'}${state.race===r.round&&state.tab==='race'?' on':''}" data-race="${r.round}" style="${w?teamVar(w.t):'--team:#5b616b'}"><div class="rd">R${r.round} · ${esc(r.date.slice(5))}</div>${outline(r.layout)}<div class="nm">${esc(r.name.replace(' Grand Prix',' GP'))}</div><div class="w">${w?esc(short(w.d)):'not yet run'}</div></button>`;}).join('')}</div>`;
  const bars=(rows,by)=>`<div class="board">${rows.map((r,i)=>`<button type="button" class="bar" data-${by}="${esc(r.id)}" style="--i:${i};${teamVar(by==='driver'?r.team:r.id)}"><span class="rk">${esc(r.p)}</span><span><span class="lab"><span>${esc(by==='driver'?name(r.id):tn(r.id))}<small> ${esc(by==='driver'?r.teams.map(tn).join(' / '):'')}</small></span><small>${r.wins} win${r.wins===1?'':'s'}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*r.pts/(rows[0]?.pts||1))}%"></span></span></span><span class="val">${fmt(r.pts)}</span></button>`).join('')}</div>`;
  const cum=cumulative(s);
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Drivers’ standings</span><small>${derivedD?'ordered by race points — this archive holds no published table for '+s.year+'; the title that year counted only the best four results':'published standings'}</small></div>${bars(dr,'driver')}</div><div class="panel"><div class="h3"><span>Constructors’ standings</span><small>${derived?'from race points':'published standings'}</small></div>${bars(tm,'team')}</div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>The title fight, round by round</span><small>cumulative GP + sprint points, top ${cum.series.length}</small></div><div class="chart" id="cumChart"></div></div>`;
  $('#view').innerHTML=head+cal+body;drawChart($('#cumChart'),cum.series,cum.rounds,short);}

/* ---------- Whole era, combined ---------- */
function eraView(){const seasons=eraSeasons();const rr=eraRaces();const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);const label=e?e.name:'All eras';const span=`${seasons[0].year}–${seasons[seasons.length-1].year}`;
  const cutYear=+(DATA.cutoff||'').slice(-4);const dr=enriched(rr,'d').sort((a,b)=>b.total-a.total||b.wins-a.wins);const tm=enriched(rr,'t').sort((a,b)=>b.total-a.total||b.wins-a.wins);
  const titles={},ttitles={};const roll=seasons.map(s=>{const st=standingsOf(s);const c=st.drivers[0];const ct=s.teams?.[0];const partial=s.year===cutYear;if(c&&!partial)titles[c.id]=(titles[c.id]||0)+1;if(ct&&!partial)ttitles[ct.id]=(ttitles[ct.id]||0)+1;return {year:s.year,d:c?.id,t:c?champTeam(s):null,ct:ct?.id,partial,derived:st.derived,races:s.races.filter(r=>r.rows.length).length};});
  const winners=new Set(rr.map(r=>r.rows.find(x=>x.dw)?.d).filter(Boolean)).size;const circuits=new Set(rr.map(r=>r.cid)).size;
  const podium=[...dr].sort((a,b)=>(titles[b.id]||0)-(titles[a.id]||0)||b.wins-a.wins||b.total-a.total).slice(0,3);const order=[podium[1],podium[0],podium[2]];const maxW=Math.max(1,podium[0]?.wins||1);
  const topTeam=tm[0]?.id;
  const head=`<div class="season-head"><div class="champ-card" style="${topTeam?`--accent:${color(topTeam)};--on-accent:${onColor(color(topTeam))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">Whole era, combined · ${seasons.length} seasons</p><div class="yr" style="font-size:clamp(44px,6vw,84px)">${span}</div><div class="who"><small>${esc(label)}</small>${esc(dr[0]?name(dr[0].id):'—')}</div><div class="team"><i></i>most race points in the era · ${esc(dr[0]?tn([...dr[0].teams].pop()):'')}</div><div class="facts"><div><b>${rr.length}</b>Grands Prix</div><div><b>${winners}</b>race winners</div><div><b>${circuits}</b>circuits</div><div><b>${tm.length}</b>constructors</div></div><p class="small" style="margin:18px 0 0;color:var(--ink);opacity:.8">Constructors: <b>${esc(topTeam?tn(topTeam):'—')}</b> · ${fmt(tm[0]?.total||0)} race points${ttitles[topTeam]?` · ${ttitles[topTeam]} title${ttitles[topTeam]===1?'':'s'}`:''}<br><span class="dim">Podium ranked by titles in the era, then wins</span></p></div>
  <div><div class="podium">${order.map(d=>d?`<button type="button" class="step p${podium.indexOf(d)+1} bar" data-driver="${esc(d.id)}" style="--h:${Math.round(120+120*d.wins/maxW)}px;${teamVar([...d.teams].pop())};display:flex"><span class="pos">${podium.indexOf(d)+1}</span><span class="nm">${esc(short(d.id))}</span><span class="pt">${titles[d.id]||0} title${titles[d.id]===1?'':'s'} · ${d.wins} wins · ${fmt(d.total)} pts</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const rollHtml=`<div class="h3"><span>Champions, season by season</span><small>click a season to open it</small></div><div class="calendar">${roll.map(c=>`<button type="button" class="cal" data-year="${c.year}" style="${c.t?teamVar(c.t):'--team:#5b616b'}"><div class="rd">${c.year} · ${c.races} GP</div><div class="nm" style="font-size:16px;margin-top:10px;color:var(--team)">${esc(c.d?short(c.d):'—')}</div><div class="w" style="color:var(--muted)">${c.partial?'leads, in progress':c.derived?'most race points':esc(c.t?tn(c.t):'')}</div><div class="w">${c.ct?'⚑ '+esc(tn(c.ct)):''}</div></button>`).join('')}</div>`;
  const bars=(rows,by)=>`<div class="board">${rows.slice(0,20).map((a,i)=>`<button type="button" class="bar" data-${by}="${esc(a.id)}" style="--i:${i};${teamVar(by==='driver'?[...a.teams].pop():a.id)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(by==='driver'?name(a.id):tn(a.id))}<small> ${by==='driver'?esc([...a.teams].map(tn).slice(0,3).join(' / ')):a.first+'–'+a.last}</small></span><small>${(by==='driver'?titles:ttitles)[a.id]?((by==='driver'?titles:ttitles)[a.id]+' title'+((by==='driver'?titles:ttitles)[a.id]===1?'':'s')+' · '):''}${a.wins} win${a.wins===1?'':'s'}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*a.total/(rows[0]?.total||1))}%"></span></span></span><span class="val">${fmt(a.total)}</span></button>`).join('')}</div>`;
  const top8=dr.slice(0,8);const series=top8.map(a=>({id:a.id,team:[...a.teams].pop(),pts:[0]}));for(const s of seasons){for(const sr of series){let w=0;for(const r of s.races)for(const x of r.rows)if(x.d===sr.id&&x.dw)w++;sr.pts.push(sr.pts[sr.pts.length-1]+w);}}
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Drivers across the era</span><small>GP + sprint points summed over ${seasons.length} seasons</small></div>${bars(dr,'driver')}</div><div class="panel"><div class="h3"><span>Constructors across the era</span><small>race points summed; titles from published tables</small></div>${bars(tm,'team')}</div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Wins, season by season</span><small>cumulative Grand Prix wins, top ${series.length} by points</small></div><div class="chart" id="cumChart"></div></div><p class="small dim" style="margin-top:12px">Published championship tables are per season, so era totals here are race points as awarded; drop-score rules in 1950–1990 mean they can exceed the published season figures.</p>`;
  $('#view').innerHTML=head+rollHtml+body;drawChart($('#cumChart'),series,seasons.map(s=>s.year),short,y=>String(y).slice(2));}
function eraRacesView(){const rr=eraRaces();$('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Every Grand Prix · ${esc(eraLabel())}</span><small>${rr.length} races · newest first · click one to replay it</small></div><div class="tablewrap"><table><tr><th>Season</th><th>Rd</th><th>Race</th><th>Circuit</th><th>Winner</th><th>Constructor</th><th>Grid P1</th><th>Fastest lap</th></tr>${rr.slice().reverse().map(r=>{const w=r.rows.find(x=>x.dw);const p=r.rows.find(x=>x.g===1);const f=r.rows.find(x=>x.fr===1);return `<tr><td><a href="#" data-year="${r.year}" data-round="${r.round}" style="color:inherit">${r.year}</a></td><td>${r.round}</td><td><a href="#" data-year="${r.year}" data-round="${r.round}" style="color:inherit">${esc(r.name)}</a></td><td>${esc(r.circuit)}</td><td>${w?esc(name(w.d)):'—'}</td><td>${w?`<i class="dot" style="${teamVar(w.t)}"></i>${esc(tn(w.t))}`:'—'}</td><td>${p?esc(short(p.d)):'—'}</td><td>${f?esc(f.fl)+' · '+esc(short(f.d)):'—'}</td></tr>`;}).join('')}</table></div>`;}
