/* ---------- Race: replay + timing tower ---------- */
let replay=null;
function stopReplay(){if(replay){cancelAnimationFrame(replay.raf);replay=null;}}
function raceView(){if(state.whole)return eraRacesView();const s=byYear[state.year];let r=s.races.find(x=>x.round===state.race)||s.races.find(x=>x.rows.length)||s.races[0];if(!r){$('#view').innerHTML='<p class="muted">No races.</p>';return;}state.race=r.round;
  const winner=r.rows.find(x=>x.dw);const L=r.scheduledLaps||Math.max(1,...r.rows.map(x=>x.laps));const fl=r.rows.find(x=>x.fr===1);
  const nav=`<div class="chiplist" style="margin-top:20px">${s.races.map(x=>`<button type="button" class="chip${x.round===r.round?' on':''}" data-race="${x.round}" style="${x.round===r.round?'border-color:var(--accent);color:var(--accent)':''}${x.rows.length?'':';opacity:.45'}"><i style="--c:${(w=>w?color(w.t):'#444')(x.rows.find(y=>y.dw))}"></i>R${x.round} ${esc(x.name.replace(' Grand Prix',''))}</button>`).join('')}</div>`;
  const meta=`<div class="kpis" style="margin-top:18px"><div class="kpi"><span>Date</span><b style="font-size:22px">${esc(r.date)}</b><small>Round ${r.round} of ${s.races.length}</small></div><div class="kpi"><span>Circuit</span><b style="font-size:22px"><a href="#" data-circuit="${esc(r.cid)}" style="color:inherit;text-decoration:none">${esc(r.circuit)}</a></b><small>${esc(r.place)}, ${esc(r.country)}</small></div><div class="kpi"><span>Lap</span><b>${r.length?r.length.toFixed(3)+' km':'—'}</b><small>${r.turns||'—'} turns · ${esc((r.trackType||'').toLowerCase())} · ${esc((r.direction||'').toLowerCase().replace('_',' '))}</small></div><div class="kpi"><span>Distance</span><b>${r.distance?Math.round(r.distance)+' km':'—'}</b><small>${r.scheduledLaps||'—'} laps scheduled</small></div><div class="kpi"><span>Fastest lap</span><b style="font-size:24px">${esc(fl?.fl||'—')}</b><small>${fl?esc(short(fl.d)):'not recorded'}</small></div></div>`;
  if(!r.rows.length){stopReplay();$('#view').innerHTML=`${nav}<div class="panel" style="margin-top:20px"><div class="h3"><span>${esc(r.name)} · ${s.year}</span><small>not yet run</small></div><div style="max-width:320px">${outline(r.layout,{lap:!RM})}</div></div>${meta}`;return;}
  const d=pathD(r.layout);
  const cars=r.rows.map((x,i)=>`<g class="car" data-i="${i}" style="opacity:${0}"><circle r="11" fill="${color(x.t)}"/><text>${esc(code(x.d))}</text></g>`).join('');
  const rep=`<div class="replay" id="replay"><div class="hud"><div><h3>${esc(r.name)}</h3><div class="sub">${s.year} · ${esc(r.circuit)} · ${r.rows.length} cars · ${L} laps</div></div><div class="flag"></div></div><div class="track"><svg viewBox="-30 -30 560 560" id="trackSvg"><path class="base" d="${d}"/><path class="line" d="${d}" id="trackPath"/><path class="kerb" d="${d}"/><g id="cars">${cars}</g></svg></div>
  <div class="ctl"><button type="button" class="btn on" id="playBtn" aria-label="Play or pause">▶ Play</button><input type="range" id="scrub" min="0" max="1000" value="0" aria-label="Race progress"><span class="lapct" id="lapct">Lap 0 / ${L}</span><select id="speed" aria-label="Replay speed"><option value="1" selected>Slow</option><option value="2">Medium</option><option value="4">Quick</option></select></div><p class="small dim" style="margin:10px 0 0">A symbolic replay, not a timing feed: cars leave their grid slots and circulate slowly on the real circuit line until their recorded lap count, retirements fading where they stopped. Spacing follows the finishing order.</p></div>`;
  const rows=r.rows;const tower=`<div class="tower"><div class="th"><span>Pos</span><span></span><span>Driver</span><span style="text-align:center">Grid</span><span style="text-align:right">Gap</span><span style="text-align:right">Pts</span><span style="text-align:right">Status</span></div>${rows.map((x,i)=>{const gain=x.g?x.g-x.p:null;return `<div class="tr p${x.p}${finished(x)?'':' dnf'}" style="--i:${i};${teamVar(x.t)}"><span class="pos">${esc(x.label)}</span><span class="code">${esc(code(x.d))}</span><span class="name"><a href="#" data-driver="${esc(x.d)}" style="color:inherit;text-decoration:none">${esc(name(x.d))}</a><small>${esc(tn(x.t))}</small></span><span class="delta ${gain>0?'up':gain<0?'down':''}">${x.g?`${x.g}${gain?`<small style="font-weight:400"> ${gain>0?'▲':'▼'}${Math.abs(gain)}</small>`:''}`:'—'}</span><span class="gap">${esc(x.time||'')}</span><span class="pts">${x.pts?fmt(x.pts):''}</span><span class="st ${x.fr===1?'fl':''}">${x.fr===1?'★ '+esc(x.fl):esc(x.status)}</span></div>`;}).join('')}</div>`;
  const sprint=r.sprint.length?`<div class="panel" style="margin-top:20px"><div class="h3"><span>Sprint</span><small>separate classification</small></div><div class="tablewrap"><table><tr><th>Pos</th><th>Driver</th><th>Constructor</th><th>Grid</th><th>Laps</th><th>Time</th><th>Status</th><th>Pts</th></tr>${r.sprint.map(x=>`<tr><td>${esc(x.label)}</td><td>${esc(name(x.d))}</td><td><i class="dot" style="${teamVar(x.t)}"></i>${esc(tn(x.t))}</td><td>${x.g||'—'}</td><td>${x.laps}</td><td>${esc(x.time||'—')}</td><td>${esc(x.status)}</td><td>${fmt(x.pts)}</td></tr>`).join('')}</table></div></div>`:'';
  const links=`<p class="small dim" style="margin-top:14px">${r.url?`<a href="${esc(r.url)}" target="_blank" rel="noopener">Race on Wikipedia ↗</a> · `:''}${r.circuitUrl?`<a href="${esc(r.circuitUrl)}" target="_blank" rel="noopener">Circuit ↗</a> · `:''}${r.trackSource?`<a href="${esc(r.trackSource)}" target="_blank" rel="noopener">Track record (F1DB) ↗</a>`:''}</p>`;
  $('#view').innerHTML=`${nav}<div class="race">${rep}<div><div class="h3"><span>Classification</span><small>${winner?'won by '+esc(name(winner.d)):''}</small></div>${tower}</div></div>${meta}${sprint}${links}`;
  startReplay(r,L);}
function startReplay(r,L){stopReplay();const path=$('#trackPath');if(!path||!path.getTotalLength)return;const len=path.getTotalLength();const cars=$$('#cars .car');const rows=r.rows;const nFin=rows.filter(finished).length||1;
  const model=rows.map((x,i)=>{const fin=finished(x);const laps=Math.max(0,Math.min(x.laps||0,L));const stopAt=laps/L;const speed=fin?1-0.012*(x.p-1)/Math.max(1,nFin):1;const grid=x.g?x.g:rows.length;return {x,fin,stopAt,speed,start:-(grid-1)*0.0065,el:cars[i]};});
  const place=t=>{for(const m of model){const tt=Math.min(t,m.stopAt);const lapsRun=tt*L;const frac=((m.start+lapsRun*m.speed)%1+1)%1;const p=path.getPointAtLength(frac*len);m.el.setAttribute('transform',`translate(${p.x.toFixed(1)} ${p.y.toFixed(1)})`);const dead=!m.fin&&t>=m.stopAt+0.002;m.el.style.opacity=dead?.22:1;}
    $('#lapct').textContent=`Lap ${Math.min(L,Math.floor(t*L+1e-9))} / ${L}`;$('#scrub').value=Math.round(t*1000);$('#replay').classList.toggle('done',t>=1);};
  const rp={t:0,playing:!RM,raf:0,last:0,dur:150000};replay=rp;
  const tick=now=>{if(replay!==rp)return;if(rp.playing){const sp=+$('#speed').value;if(rp.last)rp.t=Math.min(1,rp.t+(now-rp.last)*sp/rp.dur);rp.last=now;place(rp.t);if(rp.t>=1){rp.playing=false;$('#playBtn').textContent='↻ Replay';}}else rp.last=now;rp.raf=requestAnimationFrame(tick);};
  place(0);$('#playBtn').textContent=rp.playing?'❚❚ Pause':'▶ Play';rp.raf=requestAnimationFrame(tick);
  $('#playBtn').onclick=()=>{if(rp.t>=1){rp.t=0;}rp.playing=!rp.playing;$('#playBtn').textContent=rp.playing?'❚❚ Pause':'▶ Play';};
  $('#scrub').oninput=e=>{rp.t=+e.target.value/1000;place(rp.t);};}

/* ---------- Drivers & constructors ---------- */
function radar(el,axes,a,b){const W=260,H=260,cx=130,cy=130,R=96,n=axes.length;const pt=(i,v)=>{const ang=-Math.PI/2+i*2*Math.PI/n;return [cx+Math.cos(ang)*R*v,cy+Math.sin(ang)*R*v];};
  let g='';for(const k of [.25,.5,.75,1])g+=`<polygon class="ring" points="${axes.map((_,i)=>pt(i,k).map(v=>v.toFixed(1)).join(',')).join(' ')}"/>`;for(let i=0;i<n;i++){const [x,y]=pt(i,1);g+=`<line class="axis" x1="${cx}" y1="${cy}" x2="${x.toFixed(1)}" y2="${y.toFixed(1)}"/>`;const [lx,ly]=pt(i,1.24);g+=`<text class="lbl" x="${lx.toFixed(1)}" y="${(ly+3).toFixed(1)}">${esc(axes[i].label)}</text>`;}
  const poly=(vals,cls)=>`<polygon class="poly ${cls}" points="${vals.map((v,i)=>pt(i,Math.max(0,Math.min(1,v))).map(q=>q.toFixed(1)).join(',')).join(' ')}"/>`;
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}">${g}${poly(a,'a')}${b?poly(b,'b'):''}</svg>`;}
const AXES=[{k:'wins',label:'Wins'},{k:'podiums',label:'Podiums'},{k:'grid1',label:'Grid P1'},{k:'fl',label:'Fast laps'},{k:'total',label:'Points'},{k:'winRate',label:'Win %'},{k:'finishRate',label:'Finish %'}];
function normAxes(list){const max={};for(const ax of AXES)max[ax.k]=Math.max(1,...list.map(a=>a[ax.k]));return a=>AXES.map(ax=>a[ax.k]/max[ax.k]);}
function listView(by){const rr=eraRaces();const list=enriched(rr,by);const lens=state.lens;const minEntries=/Rate/.test(lens)?(by==='d'?20:20):0;const q=(state.gridFind2||'').toLowerCase();const nm=a=>(by==='d'?name(a.id):tn(a.id)).toLowerCase();const rows=(q?list.filter(a=>nm(a).includes(q)):list.filter(a=>a.entries>=minEntries)).sort((a,b)=>b[lens]-a[lens]||b.wins-a.wins).slice(0,q?60:30);const max=rows[0]?.[lens]||1;
  const lensSel=`<select id="lens" aria-label="Lens">${Object.entries(LENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select>`;
  const found=q?list.filter(a=>(by==='d'?name(a.id):tn(a.id)).toLowerCase().includes(q)).sort((a,b)=>b.total-a.total).slice(0,12):[];
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>${by==='d'?'Drivers':'Constructors'} · ${esc(eraLabel())}</span><small>${list.length} ${by==='d'?'drivers':'constructors'} · ${rr.length} Grands Prix</small></div><div class="panel"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:14px"><input type="search" id="find2" placeholder="Search ${by==='d'?'a driver':'a constructor'}" value="${esc(state.gridFind2||'')}" aria-label="Search">${lensSel}<span class="small muted">${esc(LENSES[lens][1])}${minEntries?` Minimum ${minEntries} entries.`:''}</span></div>${q?`<div class="chiplist" style="margin-bottom:14px">${found.map(a=>`<button type="button" class="chip" data-${by==='d'?'driver':'team'}="${esc(a.id)}"><i style="--c:${color(by==='d'?[...a.teams].pop():a.id)}"></i>${esc(by==='d'?name(a.id):tn(a.id))}</button>`).join('')||'<span class="muted small">No match.</span>'}</div>`:''}<div class="board">${rows.map((a,i)=>`<button type="button" class="bar" data-${by==='d'?'driver':'team'}="${esc(a.id)}" style="--i:${i};${teamVar(by==='d'?[...a.teams].pop():a.id)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(by==='d'?name(a.id):tn(a.id))}<small> ${a.first}–${a.last}</small></span><small>${a.wins} wins · ${a.races.size} GPs</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*a[lens]/max)}%"></span></span></span><span class="val">${fmt(a[lens])}${/Rate/.test(lens)?'%':''}</span></button>`).join('')}</div></div>`;}
function seasonsTable(id,by){const out=[];for(const s of S){if(by==='d'){const d=standingsOf(s).drivers.find(x=>x.id===id);const rr=s.races.filter(r=>r.rows.some(x=>x.d===id));if(!d&&!rr.length)continue;const wins=rr.filter(r=>r.rows.some(x=>x.d===id&&x.dw)).length;const pod=rr.filter(r=>r.rows.some(x=>x.d===id&&x.dp)).length;out.push({year:s.year,p:d?.p||'—',pts:d?.pts??rr.reduce((a,r)=>a+(r.rows.find(x=>x.d===id)?.pts||0),0),wins,pod,teams:d?.teams||[...new Set(rr.flatMap(r=>r.rows.filter(x=>x.d===id).map(x=>x.t)))],gps:rr.length});}
    else{const t=s.teams?.find(x=>x.id===id);const rr=s.races.filter(r=>r.rows.some(x=>x.t===id));if(!t&&!rr.length)continue;const wins=rr.filter(r=>r.rows.some(x=>x.t===id&&x.cw)).length;const pod=rr.reduce((a,r)=>a+r.rows.filter(x=>x.t===id&&x.cp).length,0);out.push({year:s.year,p:t?.p||'—',pts:t?.pts??rr.reduce((a,r)=>a+r.rows.filter(x=>x.t===id).reduce((b,x)=>b+x.pts,0),0),wins,pod,teams:[...new Set(rr.flatMap(r=>r.rows.filter(x=>x.t===id).map(x=>x.d)))],gps:rr.length});}}
  return out;}
function participantView(id,by){const rr=eraRaces();const all=enriched(rr,by);const a=all.find(x=>x.id===id);const back=`<button type="button" class="btn" data-tab="${by==='d'?'drivers':'teams'}">← All ${by==='d'?'drivers':'constructors'}</button>`;
  if(!a){$('#view').innerHTML=`<div style="margin-top:22px">${back}</div><p class="muted" style="margin-top:16px">${esc(by==='d'?name(id):tn(id))} has no results in ${esc(eraLabel())}. Change the era lens to see them.</p>`;return;}
  const norm=normAxes(all.filter(x=>x.entries>=(by==='d'?10:10)));const mainTeam=by==='d'?[...a.teams].sort((p,q)=>rr.filter(r=>r.rows.some(x=>x.d===id&&x.t===q)).length-rr.filter(r=>r.rows.some(x=>x.d===id&&x.t===p)).length)[0]:id;
  const tbl=seasonsTable(id,by).filter(x=>state.era==='all'||(x.year>=ERAS.find(e=>e.id===state.era).from&&x.year<=ERAS.find(e=>e.id===state.era).to));const titles=tbl.filter(x=>x.p==='1').length;
  const ribbon=rr.filter(r=>r.rows.some(x=>x[by]===id)).map(r=>{const x=r.rows.filter(y=>y[by]===id).sort((p,q)=>p.p-q.p)[0];const c=x.p===1?'var(--gold)':x.p<=3?'var(--silver)':x.p<=10&&x.pts?'#5a6270':finished(x)?'#2a2f39':'#3a1414';return `<i style="--c:${c}" title="${r.year} ${esc(r.name)} · ${esc(x.label)}${x.status!=='Finished'?' · '+esc(x.status):''}"></i>`;}).join('');
  const info=by==='d'?`<p class="muted" style="margin:4px 0 0">${esc(D[id]?.nationality||'')}${D[id]?.dob?' · born '+esc(D[id].dob):''} · #${esc([...new Set(rr.flatMap(r=>r.rows.filter(x=>x.d===id).map(x=>x.num)))].slice(0,4).join(', #'))}</p>`:'';
  $('#view').innerHTML=`<div style="margin-top:22px;display:flex;gap:10px;flex-wrap:wrap;align-items:center">${back}<span class="small muted">${esc(eraLabel())}</span></div>
  <div class="card" style="margin-top:18px;${teamVar(mainTeam)}"><div class="panel"><div class="trace" id="trace"></div><p class="small dim" style="text-align:center;margin:8px 0 0">Form trace · each axis relative to the best in this era lens</p></div>
  <div><p class="eyebrow">${by==='d'?'Driver':'Constructor'} · ${a.first}–${a.last}</p><h2 class="display" style="font-size:clamp(40px,6vw,84px);margin:6px 0 0;color:var(--team);text-shadow:0 0 30px rgba(255,255,255,.18)">${esc(by==='d'?name(id):tn(id))}</h2>${info}
  <div class="kpis" style="margin-top:18px"><div class="kpi"><span>Titles</span><b>${titles}</b><small>championships in lens</small></div><div class="kpi"><span>Wins</span><b>${a.wins}</b><small>${a.winRate}% of ${by==='d'?'entries':'weekends'}</small></div><div class="kpi"><span>Podiums</span><b>${a.podiums}</b><small>${a.podiumRate}% of entries</small></div><div class="kpi"><span>Grid P1</span><b>${a.grid1}</b><small>first on the grid</small></div><div class="kpi"><span>Fastest laps</span><b>${a.fl}</b></div><div class="kpi"><span>Points</span><b>${fmt(a.total)}</b><small>${fmt(a.gp)} GP${a.sprint?' + '+fmt(a.sprint)+' sprint':''}</small></div><div class="kpi"><span>Grands Prix</span><b>${a.races.size}</b><small>${a.entries} entries · ${a.finishRate}% finish</small></div></div>
  <div class="h3" style="margin-top:20px"><span>Every Grand Prix</span><small>gold win · silver podium · grey points · dark finish · red non-finish</small></div><div class="ribbon">${ribbon}</div>
  <div class="h3" style="margin-top:20px"><span>${by==='d'?'Constructors driven for':'Drivers'}</span></div><div class="chiplist">${[...(by==='d'?a.teams:a.drivers)].map(t=>`<button type="button" class="chip" data-${by==='d'?'team':'driver'}="${esc(t)}"><i style="--c:${color(by==='d'?t:mainTeam)}"></i>${esc(by==='d'?tn(t):name(t))}</button>`).join('')}</div></div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Season by season</span><small>published standings where available</small></div><div class="tablewrap"><table><tr><th>Season</th><th>Pos</th><th>Points</th><th>Wins</th><th>Podiums</th><th>GPs</th><th>${by==='d'?'Constructor':'Drivers'}</th></tr>${tbl.map(x=>`<tr><td><a href="#" data-year="${x.year}" style="color:inherit">${x.year}</a></td><td>${x.p==='1'?'<b style="color:var(--gold)">1 ★</b>':esc(x.p)}</td><td>${fmt(x.pts)}</td><td>${x.wins}</td><td>${x.pod}</td><td>${x.gps}</td><td>${esc(x.teams.map(by==='d'?tn:short).join(', '))}</td></tr>`).join('')}</table></div></div>`;
  radar($('#trace'),AXES,norm(a));}
