/* ---------- Circuits ---------- */
function circuitStats(rr){let winners={},constructors={};let gridKnown=rr.filter(r=>r.rows.some(x=>x.g===1));let p1wins=gridKnown.filter(r=>r.rows[0].g===1).length;let entries=rr.flatMap(r=>r.rows.filter(x=>x.ce));let gaps=rr.map(r=>r.rows.find(x=>x.p===2)?.time||'').filter(t=>t.startsWith('+')&&!/lap/i.test(t)).map(lapSeconds).filter(v=>v!==null).sort((a,b)=>a-b);let median=gaps.length?(gaps[Math.floor((gaps.length-1)/2)]+gaps[Math.floor(gaps.length/2)])/2:null;for(const r of rr){for(const w of r.rows){if(w.dw)winners[w.d]=(winners[w.d]||0)+1;if(w.cw)constructors[w.t]=(constructors[w.t]||0)+1;}}return {winners,constructors,p1wins,gridKnown:gridKnown.length,nf:entries.reduce((sum,x)=>sum+x.cn,0),entries:entries.length,median,gapN:gaps.length};}
function circuitsView(){const list=circuitModel().sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Circuits · ${esc(eraLabel())}</span><small>${list.length} venues</small></div><div class="tablewrap"><table><tr><th>Circuit</th><th>Country</th><th>GPs</th><th>Years</th><th>Most wins</th></tr>${list.map(c=>`<tr><td><a href="#" data-circuit="${esc(c.cid)}" style="color:inherit">${esc(c.name)}</a></td><td>${esc(c.country)}</td><td>${c.count}</td><td>${c.first}${c.last!==c.first?'–'+c.last:''}</td><td>${c.top?`<i class="dot" style="${teamVar(c.top)}"></i>${esc(tn(c.top))} (${c.wins[c.top]})`:'—'}</td></tr>`).join('')}</table></div>`;}
function circuitView(cid){const c=CIRC[cid];const rr=eraRaces().filter(r=>r.cid===cid);const back=`<button type="button" class="btn" data-tab="circuits">← All circuits</button>`;
  if(!rr.length){$('#view').innerHTML=`<div style="margin-top:22px">${back}</div><p class="muted" style="margin-top:16px">${esc(c?.name||cid)} hosted no Grand Prix in ${esc(eraLabel())}.</p>`;return;}
  const st=circuitStats(rr);const last=rr[rr.length-1];const topT=Object.entries(st.constructors).sort((a,b)=>b[1]-a[1]);const topD=Object.entries(st.winners).sort((a,b)=>b[1]-a[1]);
  let rec=null;for(const r of rr)for(const x of r.rows){if(x.fr===1){const s=lapSeconds(x.fl);if(s!==null&&(!rec||s<rec.s))rec={s,x,r};}}
  const ribbon=rr.map(r=>{const w=r.rows.find(x=>x.dw);return `<i style="--c:${w?color(w.t):'#333'}" title="${r.year} · ${esc(w?name(w.d):'—')} · ${esc(w?tn(w.t):'')}"></i>`;}).join('');
  const layouts=[...new Set(rr.map(r=>r.layout).filter(Boolean))];
  const bars=(arr,by)=>`<div class="board">${arr.slice(0,8).map(([id,n],i)=>`<button type="button" class="bar" data-${by}="${esc(id)}" style="--i:${i};${teamVar(by==='driver'?(rr.find(r=>r.rows.some(x=>x.d===id&&x.dw))?.rows.find(x=>x.d===id)?.t):id)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(by==='driver'?name(id):tn(id))}</span></span><span class="trk"><span class="fill" style="--w:${Math.round(100*n/arr[0][1])}%"></span></span></span><span class="val">${n}</span></button>`).join('')}</div>`;
  $('#view').innerHTML=`<div style="margin-top:22px;display:flex;gap:10px;flex-wrap:wrap;align-items:center">${back}<span class="small muted">${esc(eraLabel())}</span></div>
  <div class="card" style="margin-top:18px;grid-template-columns:minmax(240px,380px) 1fr;${topT[0]?teamVar(topT[0][0]):''}"><div class="panel circ" style="aspect-ratio:auto;cursor:default;transform:none">${outline(last.layout,{lap:!RM})}<p class="small dim" style="text-align:center;margin:8px 0 0">${esc(last.layout)} · ${layouts.length} layout${layouts.length===1?'':'s'} used in lens</p></div>
  <div><p class="eyebrow">Circuit · ${esc(c?.place||last.place)}, ${esc(c?.country||last.country)}</p><h2 class="display" style="font-size:clamp(36px,5.6vw,76px);margin:6px 0 0">${esc(c?.name||last.circuit)}</h2>
  <div class="kpis" style="margin-top:18px"><div class="kpi"><span>Grands Prix</span><b>${rr.length}</b><small>${rr[0].year}–${last.year}</small></div><div class="kpi"><span>Lap</span><b>${last.length?last.length.toFixed(3):'—'}</b><small>km · ${last.turns||'—'} turns</small></div><div class="kpi"><span>Type</span><b style="font-size:22px">${esc((last.trackType||'—').toLowerCase())}</b><small>${esc((last.direction||'').toLowerCase().replace('_',' '))}</small></div><div class="kpi"><span>Won from grid P1</span><b>${st.gridKnown?Math.round(100*st.p1wins/st.gridKnown)+'%':'—'}</b><small>${st.p1wins} of ${st.gridKnown} with grid data</small></div><div class="kpi"><span>Median winning margin</span><b>${st.median!==null?fmtLap(st.median):'—'}</b><small>${st.gapN} timed gaps</small></div><div class="kpi"><span>Non-finish rate</span><b>${pct(st.nf,st.entries)}%</b><small>of ${st.entries} car entries</small></div><div class="kpi"><span>Quickest race lap</span><b style="font-size:24px">${rec?esc(rec.x.fl):'—'}</b><small>${rec?esc(short(rec.x.d))+' · '+rec.r.year:'in this archive'}</small></div></div>
  <div class="h3" style="margin-top:20px"><span>Winners, year by year</span><small>one block per Grand Prix, in the winning constructor’s colour</small></div><div class="ribbon">${ribbon}</div>
  <p class="small dim" style="margin-top:12px">${c?.url?`<a href="${esc(c.url)}" target="_blank" rel="noopener">Circuit on Wikipedia ↗</a>`:''}</p></div></div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Most wins · drivers</span></div>${bars(topD,'driver')}</div><div class="panel"><div class="h3"><span>Most wins · constructors</span></div>${bars(topT,'team')}</div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Every race here</span></div><div class="tablewrap"><table><tr><th>Season</th><th>Race</th><th>Winner</th><th>Constructor</th><th>Grid P1</th><th>Fastest lap</th><th>Layout</th></tr>${rr.slice().reverse().map(r=>{const w=r.rows.find(x=>x.dw);const p=r.rows.find(x=>x.g===1);const f=r.rows.find(x=>x.fr===1);return `<tr><td><a href="#" data-year="${r.year}" data-round="${r.round}" style="color:inherit">${r.year}</a></td><td>${esc(r.name)}</td><td>${w?esc(name(w.d)):'—'}</td><td>${w?`<i class="dot" style="${teamVar(w.t)}"></i>${esc(tn(w.t))}`:'—'}</td><td>${p?esc(short(p.d)):'—'}</td><td>${f?esc(f.fl)+' · '+esc(short(f.d)):'—'}</td><td class="dim">${esc(r.layout||'')}</td></tr>`;}).join('')}</table></div></div>`;}

/* ---------- Records (lenses) ---------- */
function recordsView(){const rr=eraRaces();const dr=enriched(rr,'d'),tm=enriched(rr,'t');const w=new Set(rr.flatMap(r=>r.rows.filter(x=>x.dw).map(x=>x.d)));const teams=new Set(rr.flatMap(r=>r.rows.map(x=>x.t)));const sp=rr.filter(r=>r.sprint.length).length;const circuits=new Set(rr.map(r=>r.cid));
  const top=(list,k,by,min)=>{const rows=list.filter(a=>a.entries>=min).sort((a,b)=>b[k]-a[k]||b.wins-a.wins).slice(0,5);const max=rows[0]?.[k]||1;return `<div class="board">${rows.map((a,i)=>`<button type="button" class="bar" data-${by==='d'?'driver':'team'}="${esc(a.id)}" style="--i:${i};${teamVar(by==='d'?[...a.teams].pop():a.id)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(by==='d'?short(a.id):tn(a.id))}</span></span><span class="trk"><span class="fill" style="--w:${Math.round(100*a[k]/max)}%"></span></span></span><span class="val">${fmt(a[k])}${/Rate/.test(k)?'%':''}</span></button>`).join('')}</div>`;};
  // notable single-race records
  let bigGain=null,oldest=null,youngest=null,closest=null,mostLead=null;for(const r of rr){for(const x of r.rows){if(x.g&&x.p&&x.dw){const gain=x.g-1;if(!bigGain||gain>bigGain.gain)bigGain={gain,x,r};}if(x.dw&&D[x.d]?.dob){const age=(new Date(r.date)-new Date(D[x.d].dob))/31557600000;if(!oldest||age>oldest.age)oldest={age,x,r};if(!youngest||age<youngest.age)youngest={age,x,r};}}
    const g=r.rows.find(x=>x.p===2)?.time;if(g&&g.startsWith('+')&&!/lap/i.test(g)){const s=lapSeconds(g);if(s!==null&&(!closest||s<closest.s))closest={s,r};}}
  const rec=(t,v,sub)=>`<div class="kpi"><span>${t}</span><b style="font-size:24px">${v}</b><small>${sub}</small></div>`;
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Records · ${esc(eraLabel())}</span><small>${rr.length} Grands Prix</small></div>
  <div class="kpis"><div class="kpi"><span>Grands Prix</span><b>${rr.length}</b><small>${eraSeasons().length} seasons · ${circuits.size} circuits</small></div><div class="kpi"><span>Race winners</span><b>${w.size}</b><small>different GP-winning drivers</small></div><div class="kpi"><span>Constructors</span><b>${teams.size}</b><small>source identities, not merged</small></div><div class="kpi"><span>Sprints</span><b>${sp}</b><small>separate classifications</small></div><div class="kpi"><span>Result rows</span><b>${rr.reduce((a,r)=>a+r.rows.length,0)}</b><small>every classified entry</small></div></div>
  <div class="kpis" style="margin-top:12px">${bigGain?rec('Deepest charge to victory',`P${bigGain.x.g} → P1`,`${esc(short(bigGain.x.d))} · ${bigGain.r.year} ${esc(bigGain.r.name)}`):''}${closest?rec('Closest finish',`+${fmtLap(closest.s)}`,`${closest.r.year} ${esc(closest.r.name)} · timed gap to P2`):''}${youngest?rec('Youngest winner',`${youngest.age.toFixed(1)} yrs`,`${esc(short(youngest.x.d))} · ${youngest.r.year} ${esc(youngest.r.name)}`):''}${oldest?rec('Oldest winner',`${oldest.age.toFixed(1)} yrs`,`${esc(short(oldest.x.d))} · ${oldest.r.year} ${esc(oldest.r.name)}`):''}</div>
  <div class="three" style="margin-top:20px">${Object.entries(LENSES).map(([k,v])=>`<div class="panel"><div class="h3"><span>${esc(v[0])}</span><small>drivers</small></div>${top(dr,k,'d',/Rate/.test(k)?20:0)}<div class="h3" style="margin-top:16px"><span></span><small>constructors</small></div>${top(tm,k,'t',/Rate/.test(k)?20:0)}<p class="small dim" style="margin:10px 0 0">${esc(v[1])}${/Rate/.test(k)?' Minimum 20 entries.':''}</p></div>`).join('')}</div>`;}

/* ---------- Barcode (season heatmap) ---------- */
function heatData(by,metric){const seasons=eraSeasons();const per={};for(const s of seasons){const rr=s.races.filter(r=>r.rows.length).map(r=>({...r,year:s.year}));const agg=enriched(rr,by);for(const a of agg){let v=metric==='champPoints'?((by==='d'?standingsOf(s).drivers:s.teams||[]).find(x=>x.id===a.id)?.pts??a.gp):a[metric];per[a.id]=per[a.id]||{id:a.id,cells:{},total:0,team:a.id};per[a.id].team=by==='d'?[...a.teams].pop():a.id;per[a.id].cells[s.year]=v;per[a.id].total+=v;}}
  return {seasons:seasons.map(s=>s.year),rows:Object.values(per).sort((a,b)=>b.total-a.total).slice(0,28)};}
function barcodeView(){const by=state.heatBy,metric=state.heat;const {seasons,rows}=heatData(by,metric);const max=Math.max(1,...rows.flatMap(r=>Object.values(r.cells)));
  const sel=`<select id="heatBy"><option value="d" ${by==='d'?'selected':''}>Drivers</option><option value="t" ${by==='t'?'selected':''}>Constructors</option></select><select id="heatMetric">${Object.entries(HEATMETRICS).map(([k,v])=>`<option value="${k}" ${k===metric?'selected':''}>${v[0]}</option>`).join('')}</select>`;
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Season barcode · ${esc(eraLabel())}</span><small>${rows.length} rows × ${seasons.length} seasons</small></div><div class="panel"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:14px">${sel}<span class="small muted">${esc(HEATMETRICS[metric][1])} Brightness is the cell’s share of the brightest cell; colour is the ${by==='d'?'driver’s last':'constructor’s'} livery.</span></div>
  <div class="barcode"><div class="bc-row"><span></span><span class="cells" style="gap:2px">${seasons.map(y=>`<i style="background:none;height:14px;font-size:8px;color:var(--dim);text-align:center;line-height:14px">${seasons.length<=30||y%5===0?String(y).slice(2):''}</i>`).join('')}</span><span></span></div>${rows.map(r=>`<div class="bc-row"><span class="lab" data-${by==='d'?'driver':'team'}="${esc(r.id)}">${esc(by==='d'?name(r.id):tn(r.id))}</span><span class="cells">${seasons.map(y=>{const v=r.cells[y];const a=v===undefined?0:Math.max(.12,v/max);return `<i style="--c:${v===undefined?'#0e1014':mixHex(color(r.team),'#12141a',a)}" title="${y} · ${esc(by==='d'?short(r.id):tn(r.id))} · ${v===undefined?'no entries':fmt(v)+(/Rate/.test(metric)?'%':'')}"></i>`;}).join('')}</span><span class="tot">${fmt(Math.round(r.total*10)/10)}</span></div>`).join('')}</div>
  <div class="bc-key"><span><i style="--c:#0e1014"></i>no entry</span><span><i style="--c:#2a2f39"></i>low</span><span><i style="--c:var(--accent)"></i>high, in livery colour</span></div></div>`;}

/* ---------- Duel ---------- */
function duelView(){const by=state.duelBy;const rr=eraRaces();const all=enriched(rr,by).filter(a=>a.races.size>=5).sort((a,b)=>b.total-a.total);const lab=id=>by==='d'?name(id):tn(id);
  if(!all.find(a=>a.id===state.dA))state.dA=all[0]?.id;if(!all.find(a=>a.id===state.dB)||state.dB===state.dA)state.dB=all.find(a=>a.id!==state.dA)?.id;
  const opt=v=>all.map(a=>`<option value="${esc(a.id)}" ${a.id===v?'selected':''}>${esc(lab(a.id))}</option>`).join('');
  const A=all.find(a=>a.id===state.dA),B=all.find(a=>a.id===state.dB);
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Head to head · ${esc(eraLabel())}</span><small>${all.length} with 5+ Grands Prix</small></div><div class="panel"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:16px"><select id="duelBy"><option value="d" ${by==='d'?'selected':''}>Drivers</option><option value="t" ${by==='t'?'selected':''}>Constructors</option></select><select id="dA">${opt(state.dA)}</select><span class="eyebrow">vs</span><select id="dB">${opt(state.dB)}</select></div><div id="duelBody"></div></div>`;
  if(!A||!B)return;const norm=normAxes(all);const tA=by==='d'?[...A.teams].pop():A.id,tB=by==='d'?[...B.teams].pop():B.id;
  let shared=0,aw=0,bw=0,ap=0,bp=0;for(const r of rr){const x=r.rows.filter(y=>y[by]===A.id).sort((p,q)=>p.p-q.p)[0],y=r.rows.filter(z=>z[by]===B.id).sort((p,q)=>p.p-q.p)[0];if(x&&y){shared++;if(x.p<y.p)aw++;else if(y.p<x.p)bw++;if(x.g&&y.g){if(x.g<y.g)ap++;else if(y.g<x.g)bp++;}}}
  const rowsK=[['GP wins','wins'],['Podiums','podiums'],['Grid P1','grid1'],['Fastest laps','fl'],['Points (GP+sprint)','total'],['Win rate %','winRate'],['Podium rate %','podiumRate'],['Finish rate %','finishRate'],['Grands Prix',null]];
  $('#duelBody').innerHTML=`<div class="card" style="grid-template-columns:300px 1fr;--team:${color(tA)};--team2:${color(tB)}"><div class="trace" id="duelTrace"></div><div>
  <div class="two" style="gap:12px"><div class="kpi" style="border-color:${color(tA)}"><span>${esc(lab(A.id))}</span><b>${aw}</b><small>times ahead at ${shared} shared GPs · ${ap} grid</small></div><div class="kpi" style="border-color:${color(tB)}"><span>${esc(lab(B.id))}</span><b>${bw}</b><small>times ahead at ${shared} shared GPs · ${bp} grid</small></div></div>
  <div class="tablewrap" style="margin-top:14px"><table><tr><th style="text-align:right;color:${color(tA)}">${esc(lab(A.id))}</th><th style="text-align:center"></th><th style="color:${color(tB)}">${esc(lab(B.id))}</th></tr>${rowsK.map(([l,k])=>{const va=k?A[k]:A.races.size,vb=k?B[k]:B.races.size;const m=Math.max(va,vb,1);return `<tr><td style="text-align:right"><span style="display:inline-block;height:8px;width:${Math.round(120*va/m)}px;background:${color(tA)};border-radius:2px;vertical-align:middle;margin-right:8px"></span><b>${fmt(va)}</b></td><td style="text-align:center;color:var(--muted);font-size:10.5px;letter-spacing:.14em;text-transform:uppercase">${l}</td><td><b>${fmt(vb)}</b><span style="display:inline-block;height:8px;width:${Math.round(120*vb/m)}px;background:${color(tB)};border-radius:2px;vertical-align:middle;margin-left:8px"></span></td></tr>`;}).join('')}</table></div>
  <p class="small dim" style="margin-top:10px">Shared Grands Prix count both entered; “ahead” compares final classification position, with non-finishers ranked below finishers by the source ordering. Percentages use the lens definitions.</p></div></div>`;
  radar($('#duelTrace'),AXES,norm(A),norm(B));}

/* ---------- render, navigation, events ---------- */
/* ---------- deep links: the address bar mirrors the state, so any view can be shared or opened from a static page ---------- */
let routeLock=false;
function writeRoute(){if(routeLock)return;const q=[];if(state.era!=='all')q.push('era='+encodeURIComponent(state.era));if(state.whole)q.push('whole=1');else q.push('season='+state.year);q.push('tab='+state.tab);if(state.tab==='race'&&!state.whole)q.push('race='+state.race);if(state.tab==='drivers'&&state.driver)q.push('driver='+encodeURIComponent(state.driver));if(state.tab==='teams'&&state.team)q.push('team='+encodeURIComponent(state.team));if(state.tab==='circuits'&&state.circuit)q.push('circuit='+encodeURIComponent(state.circuit));const h='#'+q.join('&');if(location.hash!==h){try{history.replaceState(null,'',h);}catch(e){}}}
function readRoute(){const h=location.hash.replace(/^#\/?/,'');if(!h||/^static-/.test(h))return false;const p={};for(const kv of h.split('&')){const i=kv.indexOf('=');p[i<0?kv:kv.slice(0,i)]=i<0?'1':decodeURIComponent(kv.slice(i+1));}let any=false;
  if(p.era&&(p.era==='all'||ERAS.some(e=>e.id===p.era))){state.era=p.era;any=true;}
  if(p.season&&byYear[+p.season]){state.year=+p.season;any=true;if(state.era!=='all'){const e=ERAS.find(x=>x.id===state.era);if(!(state.year>=e.from&&state.year<=e.to))state.era='all';}}else if(state.era!=='all'){const e=ERAS.find(x=>x.id===state.era);if(!(state.year>=e.from&&state.year<=e.to))state.year=e.to;}
  state.whole=p.whole==='1';if(state.whole)any=true;
  if(p.tab&&TABS.some(t=>t[0]===p.tab)){state.tab=p.tab;any=true;}
  state.driver=p.driver&&D[p.driver]?p.driver:null;state.team=p.team&&T[p.team]?p.team:null;state.circuit=p.circuit&&CIRC[p.circuit]?p.circuit:null;
  if(p.race&&byYear[state.year].races.some(r=>r.round===+p.race))state.race=+p.race;else state.race=byYear[state.year].races.filter(r=>r.rows.length).slice(-1)[0]?.round||1;
  return any;}
function render(){stopReplay();drawTabs();if(tour.stopped||!tour.timer)drawEraStrip();const v={season:seasonView,race:raceView,drivers:()=>state.driver?participantView(state.driver,'d'):listView('d'),teams:()=>state.team?participantView(state.team,'t'):listView('t'),circuits:()=>state.circuit?circuitView(state.circuit):circuitsView(),records:recordsView,barcode:barcodeView,duel:duelView}[state.tab];try{v();}catch(e){$('#view').innerHTML=`<p class="muted">Something in this view could not be drawn: ${esc(e.message)}</p>`;console.error(e);}writeRoute();}
function go(tab,scroll=true){state.tab=tab;render();if(scroll)$('#stage').scrollIntoView({behavior:RM?'auto':'smooth',block:'start'});}
function setSeason(y,scroll){state.whole=false;state.year=y;if(state.era!=='all'&&!(y>=ERAS.find(e=>e.id===state.era).from&&y<=ERAS.find(e=>e.id===state.era).to)){state.era='all';$('#eraSelect').value='all';drawGrid();}fillSeasons();state.race=byYear[y].races.filter(r=>r.rows.length).slice(-1)[0]?.round||1;applyTheme();drawRiver();if(state.tab!=='season'&&state.tab!=='race')state.tab='season';go(state.tab,scroll);}
function fillSeasons(){const sel=$('#season');const ss=eraSeasons();const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);sel.innerHTML=`<option value="era">${e?'Whole era':'All seasons'} · ${ss[0].year}–${ss[ss.length-1].year}</option>`+ss.slice().reverse().map(s=>`<option value="${s.year}">${s.year}</option>`).join('');sel.value=state.whole?'era':state.year;}
function setEra(id){tourStop();state.era=id;$('#eraSelect').value=id;if(id!=='all'){const e=ERAS.find(x=>x.id===id);if(!(state.year>=e.from&&state.year<=e.to)){state.year=e.to;}}fillSeasons();applyTheme();drawRiver();drawGrid();render();}
function init(){
  $('#eraSelect').innerHTML=`<option value="all">All eras · 1950–2026</option>`+ERAS.map(e=>`<option value="${e.id}">${esc(e.name)} · ${e.from}–${e.to}</option>`).join('');
  fillSeasons();
  const nR=S.reduce((a,s)=>a+s.races.filter(r=>r.rows.length).length,0),nRows=S.reduce((a,s)=>a+s.races.reduce((b,r)=>b+r.rows.length,0),0);
  $('#edition').innerHTML=`<span><span class="live"></span><b>${nR.toLocaleString('en')}</b> Grands Prix</span><span><b>${nRows.toLocaleString('en')}</b> results</span><span><b>${Object.keys(D).length}</b> drivers</span><span><b>${Object.keys(T).length}</b> constructors</span><span><b>${Object.keys(CIRC).length}</b> circuits</span><span>as at <b>${esc(DATA.cutoff)}</b></span>`;
  $('#reading').open=false;state.race=byYear[state.year].races.filter(r=>r.rows.length).slice(-1)[0]?.round||1;
  const deep=readRoute();if(deep){tourStop();$('#eraSelect').value=state.era;fillSeasons();}
  applyTheme();drawRiver();drawGrid();render();lightsOut();if(deep&&(state.tab!=='season'||state.whole||state.era!=='all'))setTimeout(()=>$('#stage').scrollIntoView({behavior:'auto',block:'start'}),60);
  $('#eraSelect').addEventListener('change',e=>setEra(e.target.value));
  $('#season').addEventListener('change',e=>{if(e.target.value==='era'){state.whole=true;applyTheme();drawRiver();if(state.tab!=='season'&&state.tab!=='race')state.tab='season';go(state.tab,false);}else setSeason(+e.target.value,false);});
  $('#theme').addEventListener('change',applyTheme);
  $('#gridSort').addEventListener('change',e=>{state.gridSort=e.target.value;drawGrid();});
  $('#gridFind').addEventListener('input',e=>{state.gridFind=e.target.value;drawGrid();});
  $('#eraStrip').addEventListener('click',e=>{const s=e.target.closest('[data-era]');if(s)setEra(state.era===s.dataset.era?'all':s.dataset.era);});
  $('#eraStrip').addEventListener('pointerenter',()=>{tourPause();},{passive:true});$('#eraStrip').addEventListener('pointerleave',()=>{if(!tour.stopped)tourStart();},{passive:true});
  $('#eraStrip').addEventListener('mouseover',e=>{const s=e.target.closest('[data-era]');if(s&&!tour.stopped){drawEraStrip(s.dataset.era);}});
  if('IntersectionObserver' in window){new IntersectionObserver(en=>{tour.visible=en[0].isIntersecting;if(tour.visible)tourStart();else tourPause();},{threshold:.2}).observe($('#eraStrip'));}else{tour.visible=true;tourStart();}
  $('#circuits').addEventListener('click',e=>{const b=e.target.closest('[data-cid]');if(b){state.circuit=b.dataset.cid;go('circuits');}});
  $('#tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;if(b.dataset.tab==='drivers')state.driver=null;if(b.dataset.tab==='teams')state.team=null;if(b.dataset.tab==='circuits')state.circuit=null;go(b.dataset.tab,false);});
  $('#view').addEventListener('click',e=>{const a=e.target.closest('[data-driver],[data-team],[data-circuit],[data-race],[data-year],[data-tab]');if(!a)return;if(a.tagName==='A')e.preventDefault();
    if(a.dataset.tab){if(a.dataset.tab==='drivers')state.driver=null;if(a.dataset.tab==='teams')state.team=null;if(a.dataset.tab==='circuits')state.circuit=null;go(a.dataset.tab,false);return;}
    if(a.dataset.year){const y=+a.dataset.year;if(state.era!=='all'&&!(y>=ERAS.find(e=>e.id===state.era).from&&y<=ERAS.find(e=>e.id===state.era).to)){state.era='all';$('#eraSelect').value='all';drawGrid();}state.whole=false;state.year=y;fillSeasons();applyTheme();drawRiver();if(a.dataset.round){state.race=+a.dataset.round;go('race',false);}else{state.race=byYear[y].races.filter(r=>r.rows.length).slice(-1)[0]?.round||1;go('season',false);}return;}
    if(a.dataset.race){state.race=+a.dataset.race;go('race',false);return;}
    if(a.dataset.driver){state.driver=a.dataset.driver;go('drivers',false);return;}
    if(a.dataset.team){state.team=a.dataset.team;go('teams',false);return;}
    if(a.dataset.circuit){state.circuit=a.dataset.circuit;go('circuits',false);return;}});
  $('#view').addEventListener('change',e=>{const t=e.target;if(t.id==='lens'){state.lens=t.value;render();}else if(t.id==='heatBy'){state.heatBy=t.value;render();}else if(t.id==='heatMetric'){state.heat=t.value;render();}else if(t.id==='duelBy'){state.duelBy=t.value;state.dA=state.dB=null;render();}else if(t.id==='dA'){state.dA=t.value;render();}else if(t.id==='dB'){state.dB=t.value;render();}});
  $('#view').addEventListener('input',e=>{if(e.target.id==='find2'){state.gridFind2=e.target.value;const pos=e.target.selectionStart;render();const f=$('#find2');if(f){f.focus();f.setSelectionRange(pos,pos);}}});
  let rt;addEventListener('resize',()=>{clearTimeout(rt);rt=setTimeout(()=>{drawRiver();if(state.tab==='season')render();},150);});
  addEventListener('hashchange',()=>{if(/^#static-/.test(location.hash)){$('#reading').open=true;return;}routeLock=true;try{if(readRoute()){tourStop();$('#eraSelect').value=state.era;fillSeasons();applyTheme();drawRiver();drawGrid();render();}}finally{routeLock=false;}});if(/^#static-/.test(location.hash))$('#reading').open=true;
}
init();
