/* ---------- the map: the land silhouette once, the final of every tournament placed on it ---------- */
function landDefs(){if($('#landDefs'))return;const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('id','landDefs');s.setAttribute('width','0');s.setAttribute('height','0');s.setAttribute('style','position:absolute;width:0;height:0;overflow:hidden');s.innerHTML=`<defs><path id="land" d="${MAP.land}"/></defs>`;document.body.prepend(s);}
const HOSTS=(()=>{const m={};for(const t of TOUR){if(!t.point)continue;const p=t.point;const h=m[p[0]]||(m[p[0]]={city:p[0],lon:p[1],lat:p[2],years:[],ids:[],countries:new Set()});h.years.push(t.year);h.ids.push(t.id);for(const c of t.hosts)h.countries.add(c);}return Object.values(m).map(h=>({...h,countries:[...h.countries],xy:proj([h.city,h.lon,h.lat])})).sort((a,b)=>a.years[0]-b.years[0]);})();
const hostOf=city=>HOSTS.find(h=>h.city===city);
function fitBox(pts,minW){if(!pts.length)return [0,0,1080,540];let x0=Math.min(...pts.map(p=>p[0])),x1=Math.max(...pts.map(p=>p[0])),y0=Math.min(...pts.map(p=>p[1])),y1=Math.max(...pts.map(p=>p[1]));const w=Math.max(minW,(x1-x0)*1.8,(y1-y0)*1.8);const cx=(x0+x1)/2,cy=(y0+y1)/2;return [Math.max(0,Math.min(1080-w,cx-w/2)),Math.max(0,Math.min(540-w,cy-w/2)),w,w];}
function hostSvg(t,opts={}){const pts=t.point?[{xy:proj(t.point),city:t.point[0]}]:[];const box=opts.world?[0,0,1080,540]:fitBox(pts.map(p=>p.xy),opts.minW||60);const u=box[2]/500*(opts.k||1);const col=opts.color||'var(--team)';
  const dots=pts.map(p=>`<circle cx="${p.xy[0].toFixed(1)}" cy="${p.xy[1].toFixed(1)}" r="${12*u}" fill="none" stroke="${col}" stroke-width="${1.2*u}" opacity=".45"><animate attributeName="r" values="${8*u};${16*u}" dur="2.6s" repeatCount="indefinite"/><animate attributeName="opacity" values=".6;0" dur="2.6s" repeatCount="indefinite"/></circle><circle cx="${p.xy[0].toFixed(1)}" cy="${p.xy[1].toFixed(1)}" r="${4.2*u}" fill="${col}" stroke="#07080a" stroke-width="${1.4*u}"/>`).join('');
  const labels=opts.labels?pts.map(p=>`<text class="hostlbl" x="${(p.xy[0]+8*u).toFixed(1)}" y="${(p.xy[1]-6*u).toFixed(1)}" font-size="${9*u}">${esc(p.city)}</text>`).join(''):'';
  const others=opts.others?HOSTS.filter(h=>!pts.some(p=>p.city===h.city)).map(h=>`<circle cx="${h.xy[0].toFixed(1)}" cy="${h.xy[1].toFixed(1)}" r="${2.2*u}" fill="#5b616b"><title>${esc(h.city)} · ${h.years.join(', ')}</title></circle>`).join(''):'';
  return `<svg viewBox="${box.map(v=>v.toFixed(1)).join(' ')}" ${opts.attrs||''} aria-hidden="${opts.labels?'false':'true'}"${opts.labels?` role="img" aria-label="${esc(pts[0]?.city||'')}, ${esc((t.hosts||[]).join(' / '))}"`:''}><rect x="${box[0]}" y="${box[1]}" width="${box[2]}" height="${box[3]}" fill="#0b0d12"/><use href="#land" class="land" style="stroke-width:${.5*u}"/>${others}${dots}${labels}${opts.extra||''}</svg>`;}
function worldSvg(){const sel=state.whole?null:state.year;return `<svg viewBox="0 0 1080 540" role="img" aria-label="The city of every World Cup final"><rect width="1080" height="540" fill="#0b0d12"/><use href="#land" class="land" style="stroke-width:.6"/>${HOSTS.map(h=>{const mine=h.ids.filter(id=>tById[id].sex===state.sex);if(!mine.length)return '';const on=mine.some(id=>tById[id].year===sel);const lead=tById[mine[mine.length-1]].winner;return `<g class="host" data-host="${esc(h.city)}"><circle class="ring" cx="${h.xy[0].toFixed(1)}" cy="${h.xy[1].toFixed(1)}" r="${on?14:9}" fill="none" stroke="${on?'var(--accent)':color(lead||'?')}" stroke-width="1.2" opacity="${on?1:.35}"/><circle cx="${h.xy[0].toFixed(1)}" cy="${h.xy[1].toFixed(1)}" r="${on?5.5:3.2+Math.min(3,mine.length)}" fill="${on?'var(--accent)':color(lead||'?')}" stroke="#07080a" stroke-width="1.2"/><title>${esc(h.city)} · ${mine.map(id=>tById[id].year).join(', ')}</title></g>`;}).join('')}</svg>`;}

/* ---------- III · the Grounds: the final of every tournament on the map, every stadium as a card in the colour of the team that has won there most ---------- */
function drawGrid(){const list=groundAgg();const q=state.gridFind.trim().toLowerCase();let shown=list.filter(c=>!q||(c.name+' '+c.country+' '+c.city).toLowerCase().includes(q));
  const sorters={matches:(a,b)=>b.count-a.count||a.name.localeCompare(b.name),name:(a,b)=>a.name.localeCompare(b.name),country:(a,b)=>a.country.localeCompare(b.country)||b.count-a.count,recent:(a,b)=>b.last-a.last||b.count-a.count,finals:(a,b)=>b.finals-a.finals||b.count-a.count};shown.sort(sorters[state.gridSort]||sorters.matches);
  const bigN=state.gridSort==='matches'&&!q?6:0;const noGround=eraMatches().filter(m=>!m.stadium).length;
  $('#gridLede').textContent=`${list.length} grounds have staged a match in ${eraLabel().replace(' · ',', ')}${noGround?`; ${noGround} matches have no ground recorded`:''}. The map places the final of every tournament; each card carries the colour of the team that has won there most, and the largest cards are the grounds the World Cup has returned to most often. Grounds are listed, never drawn.`;
  $('#worldMap').innerHTML=worldSvg();
  $('#circuits').innerHTML=shown.map((c,i)=>`<button type="button" class="circ flat${i<bigN?' big':''}" data-ground="${esc(c.id)}" style="${c.top?teamVar(c.top):'--team:#8b9099'}" title="${esc(c.name)} · ${c.count} matches · ${c.first}–${c.last}${c.top?' · most wins: '+esc(c.top):''}"><span class="ct">${esc(c.country)}${c.city&&c.city!==c.country?' · '+esc(c.city):''}</span><span class="n">${c.count}</span><span class="nm">${esc(c.name)}</span><span class="yrs">${c.first}${c.last!==c.first?'–'+c.last:''}${c.finals?` · ${c.finals} final${c.finals>1?'s':''}`:''}${c.top?' · <i style="background:var(--team)"></i>'+esc(c.top)+' '+c.wins[c.top]:''}</span></button>`).join('')||`<p class="muted">No ground matches.</p>`;}

/* ---------- Stage: tabs, era strip, era context ---------- */
const TABS=[['season','Tournament'],['match','Match'],['teams','Teams'],['players','Players'],['grounds','Grounds'],['hosts','Hosts'],['records','Records'],['barcode','Barcode'],['duel','Duel']];
function drawTabs(){$('#tabs').innerHTML=TABS.map(([id,l])=>`<button type="button" role="tab" data-tab="${id}" aria-pressed="${state.tab===id}">${l}</button>`).join('');
  const s=byYear[state.year];$('#stageStatus').textContent=(state.tab==='season'||state.tab==='match')&&!state.whole&&s?`${state.year} · ${s.t.hosts.join(' / ')} · ${lensLabel()}`:eraLabel();}
function drawEraStrip(preview){const strip=$('#eraStrip');strip.innerHTML=ERAS.map(e=>`<button type="button" style="--w:${e.to-e.from+4}" data-era="${e.id}" title="${esc(e.name)} · ${e.from}–${e.to}" aria-label="${esc(e.name)} ${e.from}–${e.to}"></button>`).join('');
  for(const b of strip.children){b.classList.toggle('on',state.era===b.dataset.era);b.classList.toggle('demo',preview===b.dataset.era);}
  const e=preview?ERAS.find(x=>x.id===preview):state.era==='all'?eraOf(state.year):ERAS.find(x=>x.id===state.era);
  $('#eraCaption').innerHTML=`<span><b>${esc(e.name)}</b> · ${e.from}–${e.to}</span><span class="dim">${state.era===e.id?'Lens on · click again to release':'Click a segment to focus the whole page on that era'}</span>`;
  const ctx=$('#eraContext');ctx.innerHTML=`<div class="era-car">${e.ball.svg}</div><div><p class="eyebrow">${state.era===e.id?'Era lens':preview?'Era':'Era of the selected tournament'} · ${e.from}–${e.to}</p><h3>${esc(e.name)}</h3><p>${esc(e.text)}</p><div class="chips">${e.ball.features.map(f=>`<span>${esc(f)}</span>`).join('')}</div><p class="small dim" style="margin:10px 0 0">${esc(e.ball.label)} · an editorial reading of the period; the archive itself is not divided</p></div>`;}
const tour={i:-1,timer:null,visible:false,stopped:RM};
function tourStep(){if(tour.stopped||!tour.visible)return;tour.i=(tour.i+1)%ERAS.length;const ctx=$('#eraContext');ctx.classList.add('swap');setTimeout(()=>{if(tour.stopped)return;drawEraStrip(ERAS[tour.i].id);ctx.classList.remove('swap');},260);tour.timer=setTimeout(tourStep,4200);}
function tourStart(){if(tour.stopped||tour.timer)return;tour.timer=setTimeout(tourStep,1800);}
function tourPause(){clearTimeout(tour.timer);tour.timer=null;}
function tourStop(){if(tour.stopped)return;tour.stopped=true;tourPause();$('#eraContext').classList.remove('swap');drawEraStrip();}

/* ---------- shared pieces ---------- */
const pl=id=>`<a href="#" data-player="${esc(id)}" style="color:inherit">${esc(pname(id))}</a>`;
const tl=n=>`<a href="#" data-team="${esc(n)}" style="color:inherit"><i class="dot" style="--c:${color(n)}"></i>${esc(n)}</a>`;
const gl=id=>id&&ST[id]?`<a href="#" data-ground="${esc(id)}" style="color:inherit">${esc(ST[id].name)}</a>`:'<span class="dim">—</span>';
const ml=(m,label)=>`<a href="#" data-match="${esc(m.id)}" style="color:inherit">${esc(label||`${m.home} ${scoreOf(m)} ${m.away}`)}</a>`;
const yl=y=>`<a href="#" data-year="${y}" style="color:inherit">${y}</a>`;
function bars(rows,valOf,subOf,max,attr,nameOf,colorOf,unit=''){return `<div class="board">${rows.map((a,i)=>`<button type="button" class="bar" data-${attr}="${esc(a.id)}" style="--i:${i};--team:${colorOf(a)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(nameOf(a))}</span><small>${subOf(a)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*valOf(a)/(max||1))}%"></span></span></span><span class="val">${valOf(a)==null?'—':fmt(valOf(a))}${unit}</span></button>`).join('')}</div>`;}
const playerBars=(rows,valOf,subOf,max,unit='')=>bars(rows,valOf,subOf,max,'player',a=>pname(a.id),a=>color(a.team||'?'),unit);
const teamBars=(rows,valOf,subOf,max,unit='')=>bars(rows,valOf,subOf,max,'team',a=>a.id,a=>color(a.id),unit);
const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b>${s?`<small>${s}</small>`:''}</div>`;
const yearBars=(items,colorOf)=>`<div class="yearbars">${items.map(it=>`<button type="button" data-year="${it.y}" title="${it.title}" style="--h:${it.h}%;--team:${colorOf(it)}"><i></i><span>${it.y%20===0||items.length<=12?it.y:''}</span></button>`).join('')}</div>`;
const scoreCell=(m,team)=>{const r=resFor(m,team);const sd=sideOf(m,team);const gf=sd==='h'?m.hs:m.as,ga=sd==='h'?m.as:m.hs;return `<b class="${r==='W'?'win':r==='L'?'loss':'draw'}">${gf}–${ga}</b>${m.et?'<span class="dim small"> aet</span>':''}${m.ph!=null?`<span class="dim small"> ${sd==='h'?m.ph:m.pa}–${sd==='h'?m.pa:m.ph}p</span>`:''}`;};
const goalsOf=(m,sd)=>m.d.g.filter(g=>g[0]===(sd==='h'?1:0));
const scorerLine=(m,sd)=>{const gs=goalsOf(m,sd);if(!gs.length)return '';const by={};for(const g of gs){const k=g[1]+(g[4]?'|og':'');const e=by[k]||(by[k]={id:g[1],og:g[4],mins:[]});e.mins.push(minuteLabel(g[2],g[3])+(g[5]?' pen':''));}return Object.values(by).map(e=>`${pl(e.id)}${e.og?' <span class="dim">(o.g.)</span>':''} <span class="dim small">${e.mins.join(', ')}</span>`).join(' · ');};
function recordTable(rows,cols){return `<div class="tablewrap"><table><tr>${cols.map(c=>`<th${c[2]?' class="n"':''}>${c[0]}</th>`).join('')}</tr>${rows.map(r=>`<tr${r.cls?` class="${r.cls}"`:''}>${cols.map(c=>`<td${c[2]?' class="n"':''}>${c[1](r)}</td>`).join('')}</tr>`).join('')}</table></div>`;}
function groupTable(g,s){return `<div class="group"><div class="gh"><span>${esc(g.name)}</span><small>${g.table.length} teams</small></div><table><tr><th></th><th class="n">P</th><th class="n">W</th><th class="n">D</th><th class="n">L</th><th class="n">GF</th><th class="n">GA</th><th class="n">Pts</th></tr>${g.table.map(r=>`<tr class="${r[8]?'adv':''}"><td>${tl(r[0])}</td><td class="n">${r[1]}</td><td class="n">${r[2]}</td><td class="n">${r[3]}</td><td class="n">${r[4]}</td><td class="n">${r[5]}</td><td class="n">${r[6]}</td><td class="n"><b>${r[7]}</b></td></tr>`).join('')}</table></div>`;}
function bracket(s){const ko=s.matches.filter(m=>m.ko&&m.stage!=='3rd'&&m.replay!=='replayed');if(!ko.length)return '';const rounds=['r32','r16','qf','sf','final'].filter(r=>ko.some(m=>m.stage===r));const by=Object.fromEntries(rounds.map(r=>[r,ko.filter(m=>m.stage===r)]));
  const feeders=(m,prev)=>prev.filter(p=>[m.home,m.away].includes(winnerName(p)||'~'));const ordered={};const last=rounds[rounds.length-1];ordered[last]=by[last];
  for(let i=rounds.length-2;i>=0;i--){const r=rounds[i],nxt=rounds[i+1];const used=new Set();const list=[];for(const m of ordered[nxt]){for(const f of feeders(m,by[r])){if(!used.has(f.id)){used.add(f.id);list.push(f);}}}for(const f of by[r])if(!used.has(f.id))list.push(f);ordered[r]=list;}
  const card=m=>{const w=winnerName(m);return `<button type="button" class="bk" data-match="${esc(m.id)}" style="--team:${color(w||'?')}"><span class="${w===m.home?'w':''}"><i style="--c:${color(m.home)}"></i>${esc(m.home)}<b>${m.hs}</b></span><span class="${w===m.away?'w':''}"><i style="--c:${color(m.away)}"></i>${esc(m.away)}<b>${m.as}</b></span>${m.et||m.ph!=null?`<small>${m.et?'a.e.t.':''}${m.ph!=null?` ${m.ph}–${m.pa} pens`:''}</small>`:''}</button>`;};
  const third=s.matches.find(m=>m.stage==='3rd');
  return `<div class="bracket">${rounds.map(r=>`<div class="round"><div class="rh">${esc(SL[r])}</div><div class="rcards">${ordered[r].map(card).join('')}${r==='final'&&third?`<div class="rh" style="margin-top:14px">Third place</div>${card(third)}`:''}</div></div>`).join('')}</div>`;}

/* ---------- Tournament: the champions, the final, the host, the bracket, the groups, the Golden Boot race ---------- */
let replay=null;
function stopReplay(){if(replay){cancelAnimationFrame(replay.raf);clearTimeout(replay.t);replay=null;}}
function seasonView(){if(state.whole)return eraView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No tournament in this lens.</p>';return;}const t=s.t;const c=champOf(s);const lead=c.leader;const acc=lead?color(lead):'#f2db50';const f=c.final;
  const pod=t.standings.slice(0,3);const sq=lead?squadOf(t.id,lead):[];const topS=c.scorers.slice(0,8);
  const head=`<div class="season-head"><div class="champ-card" style="--accent:${acc};--on-accent:${onColor(acc)}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${esc(SEX_NAME[state.sex])} · ${esc(t.hosts.join(' / '))}</p><div class="yr">${s.year}</div><div class="who"><small>${esc(longDate(t.start))} – ${esc(longDate(t.end))}</small>${lead?tl(lead).replace('<a ','<a style="color:inherit;text-decoration:none" '):'—'}</div>${f?`<div class="team"><i></i>The final · ${esc(f.home)} ${scoreOf(f)} ${esc(f.away)}${f.et?' a.e.t.':''}${f.ph!=null?` · ${f.ph}–${f.pa} on penalties`:''} · ${esc(sname(f.stadium)||'')}</div>`:t.note?`<div class="team"><i></i>${esc(t.note.split('.')[0])}</div>`:''}<div class="facts"><div><b>${t.count}</b>teams</div><div><b>${s.matches.length}</b>matches</div><div><b>${c.goals}</b>goals</div><div><b>${(c.goals/Math.max(1,s.matches.length)).toFixed(2)}</b>per match</div></div>${t.note?`<p class="small" style="margin:14px 0 0;color:var(--ink);opacity:.85">${esc(t.note)}</p>`:''}<p class="small dim" style="margin:18px 0 0">Scores are after extra time; a shoot-out decides the tie, not the result. ${t.lineups?`Line-ups for ${t.lineups} of ${s.matches.length} matches`:'No line-ups in the source for this tournament'}${t.goals?` · ${t.goals} goals with their scorers`:' · no scorers in the source'}.</p></div>
  <div><div class="podium">${[pod[1],pod[0],pod[2]].map((n,i)=>n?`<button type="button" class="step p${pod.indexOf(n)+1} bar" data-team="${esc(n)}" style="--h:${[200,240,170][pod.indexOf(n)]}px;--team:${color(n)};display:flex"><span class="pos">${pod.indexOf(n)+1}</span><span class="nm">${esc(n)}</span><span class="pt">${['champions','runners-up','third'][pod.indexOf(n)]}</span></button>`:'<div></div>').join('')}<div class="base"></div></div>${t.standings[3]?`<p class="small muted" style="text-align:center;margin:8px 0 0">Fourth: ${tl(t.standings[3])}</p>`:''}</div></div>`;
  const map=`<div class="panel" style="margin-top:22px"><div class="h3"><span>The host${t.hosts.length>1?'s':''}</span><small>${esc(t.hosts.join(' / '))} · the final’s city on the map, not the grounds</small></div><div class="course"><div class="course-map">${hostSvg(t,{minW:90,k:1,labels:true,others:true,attrs:'id="hostSvg"',color:acc})}<p class="small dim" style="margin:8px 0 0">Land: Natural Earth (public domain) · the point is the city of the final at approximate coordinates · grey points are the other finals</p></div><div class="course-side"><p class="eyebrow">The tournament in numbers</p><div class="kpis" style="grid-template-columns:1fr 1fr">${kpi('Teams',t.count,'')}${kpi('Grounds',new Set(s.matches.map(m=>m.stadium).filter(Boolean)).size,[...new Set(s.matches.map(m=>ST[m.stadium]?.city).filter(Boolean))].length+' cities')}${kpi('Shoot-outs',s.matches.filter(m=>m.ph!=null).length,`${s.matches.filter(m=>m.et).length} to extra time`)}${(()=>{const gb=t.awards.find(a=>a[0]==='Golden Boot');const id=gb?gb[1]:topS[0]?.id;const sc=topS.find(x=>x.id===id)||topS[0];return kpi(gb?'Golden Boot':'Top scorer',id?pname(id):'—',sc?`${sc.goals} goals · ${esc(gb?gb[2]:sc.team)}`:'');})()}</div>${t.awards.length?`<div class="h3" style="margin-top:16px"><span>The awards</span><small>as the source records them</small></div><div class="awards">${t.awards.map(a=>`<div><span class="aw">${esc(a[0])}</span>${pl(a[1])} <span class="dim small">${esc(a[2])}${a[3]?' · shared':''}</span></div>`).join('')}</div>`:''}</div></div></div>`;
  const stages=`<div class="panel" style="margin-top:22px"><div class="h3"><span>The knockout</span><small>winners in bold · click a match to open its sheet</small></div>${bracket(s)||'<p class="muted small">No knockout rounds: the title was decided in the groups.</p>'}</div>`;
  const groups=t.groups.length?`<div class="panel" style="margin-top:22px"><div class="h3"><span>${t.groups.some(g=>g.stage!=='group')?'The groups and the final round':'The groups'}</span><small>${t.points} points for a win · the teams that went on are marked</small></div><div class="groups">${t.groups.map(g=>groupTable(g,s)).join('')}</div></div>`:'';
  const race=`<div class="two" style="margin-top:22px"><div class="replaybox"><div class="h3" style="margin-top:0"><span>The Golden Boot race</span><small>a symbolic replay, match by match · <button type="button" class="linkbtn" id="replayGo">replay</button></small></div><div class="ticker" id="ticker">—</div><div class="board" id="replayTable"></div><div class="prog"><i id="replayProg" style="--w:0%"></i></div></div>
  <div class="panel"><div class="h3"><span>Every match</span><small>${s.matches.length} · newest first · click one</small></div><div class="tablewrap" style="max-height:520px"><table><tr><th>Date</th><th>Stage</th><th>Match</th><th>Ground</th></tr>${[...s.matches].reverse().map(m=>`<tr class="${m.stage==='final'?'win':''}"><td class="small muted">${esc(m.date.slice(5))}</td><td class="small">${esc(stageLabel(m))}${m.replay?` <span class="dim">${m.replay}</span>`:''}</td><td>${ml(m,`${m.home} ${resultLine(m)} ${m.away}`)}</td><td class="small muted">${esc(ST[m.stadium]?.city||'')}</td></tr>`).join('')}</table></div></div></div>`;
  $('#view').innerHTML=head+map+stages+groups+race;
  const go=()=>runReplay(s);$('#replayGo').onclick=go;go();}
function runReplay(s){stopReplay();const table=$('#replayTable'),tick=$('#ticker'),prog=$('#replayProg');if(!table)return;const ms=s.matches;const n=ms.length;const tot={};const rp={raf:0,t:0,i:0};replay=rp;
  if(!s.t.goals){tick.innerHTML='No scorers in the source for this tournament — the race cannot be run.';return;}
  const draw=()=>{const rows=Object.values(tot).sort((a,b)=>b.goals-a.goals||a.id.localeCompare(b.id)).slice(0,8);const mx=rows[0]?.goals||1;table.innerHTML=rows.map((a,i)=>`<div class="bar" style="--i:0;--team:${color(a.team)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(a.id))}</span><small>${esc(a.team)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*a.goals/mx)}%"></span></span></span><span class="val">${a.goals}</span></div>`).join('');};
  const step=()=>{if(replay!==rp)return;const per=RM?n:1;let lastGoal=null;for(let k=0;k<per&&rp.i<n;k++,rp.i++){const m=ms[rp.i];for(const g of m.d.g){if(g[4])continue;const team=g[0]===1?m.home:m.away;const a=tot[g[1]]||(tot[g[1]]={id:g[1],goals:0,team});a.goals++;lastGoal=a;}}
    const m=ms[Math.min(n-1,rp.i-1)];if(m)tick.innerHTML=`<b>${rp.i} / ${n}</b> · ${esc(stageLabel(m))} · ${esc(m.home)} ${scoreOf(m)} ${esc(m.away)}${lastGoal?` · <span style="color:var(--accent)">${esc(pname(lastGoal.id))} ${lastGoal.goals}</span>`:''}`;
    prog.style.setProperty('--w',(100*rp.i/n).toFixed(1)+'%');draw();
    if(rp.i<n)rp.t=setTimeout(()=>{rp.raf=requestAnimationFrame(step);},RM?0:Math.max(28,Math.round(5200/n)));else tick.innerHTML=`<b>${n} matches</b> · the Golden Boot as it stood at the final whistle`;};
  step();}
function eraView(){const ss=eraHeld();const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);const teams=teamAgg();const players=playerAgg();const top=teams[0];const ms=eraMatches();const goals=ms.reduce((n,m)=>n+m.hs+m.as,0);
  const head=`<div class="season-head"><div class="champ-card" style="${top?`--accent:${color(top.id)};--on-accent:${onColor(color(top.id))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${e?'Whole era':'Every tournament'} · ${esc(lensLabel())}</p><div class="yr" style="font-size:clamp(44px,6vw,84px)">${ss[0]?.year}–${ss[ss.length-1]?.year}</div>${top?`<div class="who"><small>Most titles across the period · ${top.titles} · ${top.wins} wins in ${top.played} matches</small><a href="#" data-team="${esc(top.id)}" style="color:inherit;text-decoration:none">${esc(top.id)}</a></div><div class="team"><i></i>${players[0]?esc(pname(players[0].id))+' · '+players[0].goals+' goals, the most of any player':''}</div>`:''}<div class="facts"><div><b>${ss.length}</b>tournaments</div><div><b>${fmt(ms.length)}</b>matches</div><div><b>${fmt(goals)}</b>goals</div><div><b>${teams.length}</b>teams</div></div></div>
  <div><div class="podium">${[teams[1],teams[0],teams[2]].map((n,i)=>n?`<button type="button" class="step p${teams.indexOf(n)+1} bar" data-team="${esc(n.id)}" style="--h:${Math.round(120+120*n.titles/Math.max(1,teams[0].titles))}px;--team:${color(n.id)};display:flex"><span class="pos">${teams.indexOf(n)+1}</span><span class="nm">${esc(n.id)}</span><span class="pt">${n.titles} title${n.titles===1?'':'s'} · ${n.finals} finals</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const roll=`<div class="h3"><span>Tournament by tournament</span><small>the champions of each · click a year to open it</small></div><div class="calendar">${eraSeasons().map(s=>{const l=leaderOf(s);const c=champOf(s);const f=c.final;return `<button type="button" class="cal" data-year="${s.year}" style="--team:${l?color(l):'#5b616b'}"><div class="rd">${s.year}</div><div class="nm">${esc(s.t.hosts.join(' / '))}</div><div class="w">${l?'<i class="dot" style="--c:'+color(l)+'"></i>'+esc(l)+(f?' · '+scoreOf(f)+(f.ph!=null?' p':f.et?' aet':''):''):'—'}</div></button>`;}).join('')}</div>`;
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>The table across the period</span><small>titles, then finals, then wins</small></div>${recordTable(teams.slice(0,14),[['Team',a=>tl(a.id)],['Titles',a=>a.titles,1],['Finals',a=>a.finals,1],['P',a=>a.played,1],['W',a=>a.wins,1],['D',a=>a.draws,1],['L',a=>a.losses,1],['GF–GA',a=>`${a.gf}–${a.ga}`,1]])}</div><div class="panel"><div class="h3"><span>Scorers across the period</span><small>goals, own goals left out</small></div>${playerBars(players.slice(0,12),a=>a.goals,a=>`${esc(a.team||'')} · ${a.ntour} tournament${a.ntour===1?'':'s'} · ${yspan(a)}`,players[0]?.goals||1)}</div></div>`;
  $('#view').innerHTML=head+roll+body;}

/* ---------- Match: one match of one tournament — the atlas's unit, as a race is to a season ---------- */
function matchChips(s,m){const stages=[];for(const x of s.matches){const k=x.stage==='group'||x.stage==='group2'?(x.stage+'|'+(x.group||'')):x.stage;if(!stages.some(z=>z.k===k))stages.push({k,label:stageLabel(x),stage:x.stage,group:x.group});}
  const cur=stages.find(z=>z.k===(m.stage==='group'||m.stage==='group2'?(m.stage+'|'+(m.group||'')):m.stage));const here=s.matches.filter(x=>(x.stage==='group'||x.stage==='group2'?(x.stage+'|'+(x.group||'')):x.stage)===cur.k);
  return `<div class="chiplist" style="margin-top:20px">${stages.map(z=>`<button type="button" class="chip${z===cur?' on':''}" data-mstage="${esc(z.k)}" style="${z===cur?'border-color:var(--accent);color:var(--accent)':''}">${esc(z.label)} <span class="dim">${s.matches.filter(x=>(x.stage==='group'||x.stage==='group2'?(x.stage+'|'+(x.group||'')):x.stage)===z.k).length}</span></button>`).join('')}</div><div class="eventchips" style="margin-top:10px">${here.map(x=>`<button type="button" class="chip${x.id===m.id?' on':''}" data-match="${esc(x.id)}"><i style="--c:${color(winnerName(x)||'?')}"></i>${esc(x.home)} ${scoreOf(x)} ${esc(x.away)}${x.ph!=null?' <span class="dim">p</span>':x.et?' <span class="dim">aet</span>':''}</button>`).join('')}</div>`;}
function timelineSvg(m){const end=m.et?120:90;const W=800,H=102,padL=24,padR=24;const x=mm=>padL+(W-padL-padR)*Math.min(mm,end)/end;
  const marks=m.d.g.map(g=>{const mm=g[2]+(g[3]?g[3]*0.3:0);const team=g[0]===1?(g[4]?m.away:m.home):(g[4]?m.home:m.away);const up=g[0]===1;return `<g><circle cx="${x(mm).toFixed(1)}" cy="${up?30:66}" r="6" fill="${color(team)}" stroke="#07080a" stroke-width="1.5"/><line x1="${x(mm).toFixed(1)}" x2="${x(mm).toFixed(1)}" y1="${up?36:48}" y2="${up?48:60}" stroke="${color(team)}" stroke-width="1.5" opacity=".6"/><title>${esc(pname(g[1]))} ${minuteLabel(g[2],g[3])}${g[5]?' pen':''}${g[4]?' own goal':''}</title></g>`;}).join('');
  const cards=m.d.b.map(b=>`<rect x="${(x(b[2]+(b[3]?b[3]*0.3:0))-2).toFixed(1)}" y="${b[0]===1?12:80}" width="4" height="8" rx="1" fill="${b[4]==='Y'?'#f2db50':'#e8505b'}"><title>${esc(pname(b[1]))} ${b[4]==='Y'?'yellow':b[4]==='Y2'?'second yellow':'red'} ${minuteLabel(b[2],b[3])}</title></rect>`).join('');
  const ticks=[0,15,30,45,60,75,90].concat(m.et?[105,120]:[]).map(t=>`<line x1="${x(t).toFixed(1)}" x2="${x(t).toFixed(1)}" y1="44" y2="52" stroke="#2c333c"/><text x="${x(t).toFixed(1)}" y="${H-4}" text-anchor="middle" class="lb">${t}</text>`).join('');
  return `<svg viewBox="0 0 ${W} ${H}" class="timeline" role="img" aria-label="Goals and cards by minute"><line x1="${padL}" x2="${W-padR}" y1="48" y2="48" stroke="#2c333c" stroke-width="2"/>${m.et?`<rect x="${x(90).toFixed(1)}" y="46" width="${(x(120)-x(90)).toFixed(1)}" height="4" fill="var(--accent)" opacity=".35"/>`:''}${ticks}<text x="${W-padR}" y="24" text-anchor="end" class="lb" style="fill:${color(m.home)}">${esc(m.home)}</text><text x="${W-padR}" y="74" text-anchor="end" class="lb" style="fill:${color(m.away)}">${esc(m.away)}</text>${cards}${marks}</svg>`;}
function lineupTower(m,sd){const l=m.d.l;if(!l)return '';const team=sd==='h'?m.home:m.away;const rows=l[sd];const goals=m.d.g.filter(g=>g[0]===(sd==='h'?1:0)&&!g[4]).reduce((o,g)=>((o[g[1]]=(o[g[1]]||[])).push(minuteLabel(g[2],g[3])),o),{});const ogs=m.d.g.filter(g=>g[0]===(sd==='h'?0:1)&&g[4]).reduce((o,g)=>((o[g[1]]=(o[g[1]]||[])).push(minuteLabel(g[2],g[3])),o),{});
  const cards=m.d.b.filter(b=>b[0]===(sd==='h'?1:0)).reduce((o,b)=>((o[b[1]]=(o[b[1]]||[])).push(b[4]),o),{});const off=m.d.s.filter(x=>x[0]===(sd==='h'?1:0)).reduce((o,x)=>{if(x[1])o[x[1]]=minuteLabel(x[3],x[4]);return o;},{});const on=m.d.s.filter(x=>x[0]===(sd==='h'?1:0)).reduce((o,x)=>{if(x[2])o[x[2]]=minuteLabel(x[3],x[4]);return o;},{});
  const marks=pid=>`${(goals[pid]||[]).map(mn=>`<i class="g" title="goal ${mn}">⚽</i>`).join('')}${(ogs[pid]||[]).map(mn=>`<i class="og" title="own goal ${mn}">og</i>`).join('')}${(cards[pid]||[]).map(c=>`<i class="card ${c==='Y'?'y':'r'}" title="${c==='Y'?'yellow card':c==='Y2'?'second yellow':'red card'}"></i>`).join('')}`;
  const starters=rows.filter(r=>r[3]),bench=rows.filter(r=>!r[3]);const manager=sd==='h'?m.mh:m.ma;
  return `<div class="tower" style="--team:${color(team)}"><div class="th"><span class="shirt">#</span><span>${esc(team)}</span><span class="pos">pos</span><span class="ev"></span></div>${starters.map(([pid,shirt,pos],i)=>`<div class="tr" style="--i:${i}"><span class="shirt">${shirt??''}</span><span class="name">${pl(pid)}${off[pid]?`<small>↓ ${esc(off[pid])}</small>`:''}</span><span class="pos">${esc(pos)}</span><span class="ev">${marks(pid)}</span></div>`).join('')}${bench.length?`<div class="th"><span></span><span>From the bench</span><span></span><span></span></div>${bench.map(([pid,shirt,pos],i)=>`<div class="tr sub" style="--i:${starters.length+i}"><span class="shirt">${shirt??''}</span><span class="name">${pl(pid)}${on[pid]?`<small>↑ ${esc(on[pid])}</small>`:''}${off[pid]?`<small>↓ ${esc(off[pid])}</small>`:''}</span><span class="pos">${esc(pos)}</span><span class="ev">${marks(pid)}</span></div>`).join('')}`:''}${manager&&MAN[manager]?`<div class="tf">Manager · ${esc(MAN[manager].n)}${MAN[manager].c&&MAN[manager].c!==team?` <span class="dim">(${esc(MAN[manager].c)})</span>`:''}</div>`:''}</div>`;}
function matchView(){if(state.whole)return eraMatchesView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No tournament in this lens.</p>';return;}
  let m=mById[state.match];if(!m||m.y!==s.year||m.sex!==state.sex){const st=state.mstage;const pool=st?s.matches.filter(x=>(x.stage==='group'||x.stage==='group2'?(x.stage+'|'+(x.group||'')):x.stage)===st):null;m=(pool&&pool.length?pool:[s.matches.find(x=>x.stage==='final')||s.matches[s.matches.length-1]])[0];}state.match=m.id;
  const w=winnerName(m);const acc=w?color(w):'#f2db50';const st=ST[m.stadium];const ref=m.ref&&REF[m.ref];const prev=MATCHES.filter(x=>x.sex===m.sex&&((x.home===m.home&&x.away===m.away)||(x.home===m.away&&x.away===m.home))).sort((a,b)=>a.date.localeCompare(b.date));
  const hero=`<div class="panel" style="margin-top:18px;--team:${acc}"><p class="eyebrow">${s.year} · ${esc(stageLabel(m))}${m.replay?' · '+esc(m.replay):''} · ${esc(longDate(m.date))}${m.time?' · '+esc(m.time):''} · ${st?gl(m.stadium)+(st.city?', '+esc(st.city):''):'ground not recorded'}</p>
  <div class="scoreboard"><div class="side h"><a href="#" data-team="${esc(m.home)}" style="color:inherit;text-decoration:none"><i style="--c:${color(m.home)}"></i>${esc(m.home)}</a><div class="scorers">${scorerLine(m,'h')||(m.hs?'<span class="dim">scorers not in the source</span>':'')}</div></div><div class="score"><div class="num"><b>${m.hs}</b><b>${m.as}</b></div><small>${m.et?'after extra time':m.stage==='group'||m.stage==='group2'||m.stage==='final-round'?'full time':'full time'}${m.ph!=null?` · ${esc(w||'')} ${Math.max(m.ph,m.pa)}–${Math.min(m.ph,m.pa)} on penalties`:''}${m.replay==='replayed'?' · replayed':''}</small></div><div class="side a"><a href="#" data-team="${esc(m.away)}" style="color:inherit;text-decoration:none"><i style="--c:${color(m.away)}"></i>${esc(m.away)}</a><div class="scorers">${scorerLine(m,'a')||(m.as?'<span class="dim">scorers not in the source</span>':'')}</div></div></div>
  ${m.d.g.length||m.d.b.length?timelineSvg(m):''}<div class="small muted" style="margin-top:8px">${ref?`Referee · ${esc(ref.n)}${ref.c?' ('+esc(ref.c)+')':''}`:''}${m.ph!=null&&m.d.p.length?` · Shoot-out: ${m.d.p.map(k=>`<span class="pk ${k[2]?'in':'out'}" style="--c:${color(k[0]===1?m.home:m.away)}" title="${esc(pname(k[1]))} ${k[2]?'scored':'missed'}">${esc(pname(k[1]).split(' ').slice(-1)[0])}</span>`).join(' ')}`:''}</div></div>`;
  const replayBox=`<div class="replaybox" style="margin-top:14px"><div class="h3" style="margin-top:0"><span>The match, minute by minute</span><small>a symbolic replay · <button type="button" class="linkbtn" id="replayGo">replay</button></small></div><div class="clock"><span id="clockMin">0’</span><span id="clockScore">${esc(m.home)} 0–0 ${esc(m.away)}</span></div><div class="ticker" id="ticker">—</div><div class="prog"><i id="replayProg" style="--w:0%"></i></div></div>`;
  const towers=m.d.l?`<div class="two" style="margin-top:14px">${lineupTower(m,'h')}${lineupTower(m,'a')}</div>`:`<p class="small dim" style="margin:14px 0 0">No line-ups in the source for this match${m.y<1970&&m.src==='fjelstul'?' — the database carries line-ups from 1970':''}.</p>`;
  const h2h=prev.length>1?`<div class="panel" style="margin-top:14px"><div class="h3"><span>${esc(m.home)} and ${esc(m.away)} at the World Cup</span><small>${prev.length} meetings · click one</small></div><div class="tablewrap" style="max-height:320px"><table><tr><th>Year</th><th>Stage</th><th>Match</th></tr>${[...prev].reverse().map(x=>`<tr${x.id===m.id?' style="color:var(--accent)"':''}><td>${yl(x.y)}</td><td class="small">${esc(stageLabel(x))}</td><td>${ml(x,`${x.home} ${resultLine(x)} ${x.away}`)}</td></tr>`).join('')}</table></div></div>`:'';
  $('#view').innerHTML=matchChips(s,m)+hero+replayBox+towers+h2h;
  const go=()=>runMatchReplay(m);$('#replayGo').onclick=go;go();}
function runMatchReplay(m){stopReplay();const tick=$('#ticker'),prog=$('#replayProg'),cm=$('#clockMin'),cs=$('#clockScore');if(!tick)return;const end=m.et?120:90;const rp={raf:0,t:0,min:0};replay=rp;const goals=[...m.d.g].sort((a,b)=>a[2]-b[2]||a[3]-b[3]);let gi=0,h=0,a=0;
  if(!m.d.g.length&&(m.hs||m.as)){tick.innerHTML='No scorers in the source for this match — the clock has nothing to tell.';cm.textContent='90’';cs.textContent=`${m.home} ${m.hs}–${m.as} ${m.away}`;return;}
  const step=()=>{if(replay!==rp)return;const per=RM?end:1;for(let k=0;k<per&&rp.min<end;k++){rp.min++;while(gi<goals.length&&goals[gi][2]<=rp.min){const g=goals[gi++];if((g[0]===1)!==g[4])h++;else a++;tick.innerHTML=`<b>${minuteLabel(g[2],g[3])}</b> · ${esc(pname(g[1]))}${g[5]?' (pen)':''}${g[4]?' (own goal)':''} · ${esc(m.home)} ${h}–${a} ${esc(m.away)}`;}}
    cm.textContent=rp.min+'’';cs.textContent=`${m.home} ${h}–${a} ${m.away}`;prog.style.setProperty('--w',(100*rp.min/end).toFixed(1)+'%');
    if(rp.min<end)rp.t=setTimeout(()=>{rp.raf=requestAnimationFrame(step);},RM?0:36);else{if(!goals.length)tick.innerHTML='<b>Full time</b> · no goals';else tick.innerHTML+=` · <b>full time</b>${m.ph!=null?` · ${esc(winnerName(m))} on penalties`:''}`;}};
  tick.innerHTML='<b>Kick-off</b>';step();}
function eraMatchesView(){const list=eraMatches().slice().sort((a,b)=>b.date.localeCompare(a.date));const shown=list.slice(0,600);
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Every match · ${esc(eraLabel())}</span><small>${fmt(list.length)} matches · newest first${list.length>600?' · the first 600 shown; narrow the lens for the rest':''} · click one to open its sheet</small></div><div class="tablewrap" style="max-height:640px"><table><tr><th>Date</th><th>Year</th><th>Stage</th><th>Match</th><th>Ground</th></tr>${shown.map(m=>`<tr class="${m.stage==='final'?'win':''}"><td class="small muted">${esc(m.date)}</td><td>${yl(m.y)}</td><td class="small">${esc(stageLabel(m))}</td><td>${ml(m,`${m.home} ${resultLine(m)} ${m.away}`)}</td><td class="small muted">${esc(ST[m.stadium]?.name||'')}</td></tr>`).join('')}</table></div>`;}
