/* ---------- Teams ---------- */
function teamsView(){const list=teamAgg();const lens=state.lens;let rows=list.filter(a=>a[lens]!=null);rows.sort((a,b)=>b[lens]-a[lens]||recCmp(a,b));rows=rows.slice(0,48);const max=Math.max(1,...rows.map(a=>a[lens]));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Teams · ${esc(eraLabel())}</h2></div><div class="small mono muted">${list.length} teams</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="lens" aria-label="Lens">${Object.entries(LENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(LENSES[lens][1])}</span></div>${lens==='titles'?recordTable(rows,[['#',a=>a.rank,1],['Team',a=>tl(a.id)],['Titles',a=>a.titles?`<b>${a.titles}</b>`:'',1],['Finals',a=>a.finals,1],['Top 4',a=>a.top4,1],['Tournaments',a=>a.tournaments,1],['P',a=>a.played,1],['W',a=>a.wins,1],['D',a=>a.draws,1],['L',a=>a.losses,1],['GF–GA',a=>`${a.gf}–${a.ga}`,1],['Best',a=>`<span class="small">${esc(finishLabel(a.best?.pos,a.best?.far))} ${a.best?'<span class="dim">'+a.best.y+'</span>':''}</span>`]]):teamBars(rows,a=>a[lens],a=>`${a.titles} title${a.titles===1?'':'s'} · ${a.played} matches · ${a.wins}–${a.draws}–${a.losses} · ${yspan(a)}`,max)}<p class="small dim" style="margin:10px 0 0">Teams as the sources name them: West Germany and Germany, the Soviet Union and Russia, Czechoslovakia and the Czech Republic, Yugoslavia and Serbia are separate. Shoot-outs are draws in the record; the winner went through.</p></div>`;
  $('#lens').addEventListener('change',e=>{state.lens=e.target.value;render();});}
function teamView(id){const all=teamAgg();const a=all.find(x=>x.id===id);if(!a){teamsView();return;}const ms=eraMatches().filter(m=>(m.home===id||m.away===id)&&m.replay!=='replayed').sort((p,q)=>q.date.localeCompare(p.date));
  const players=playerAgg().filter(p=>p.teams[id]);const scorers=[...players].sort((p,q)=>q.goals-p.goals||q.apps-p.apps).slice(0,10);const apps=[...players].filter(p=>p.apps).sort((p,q)=>q.apps-p.apps||q.goals-p.goals).slice(0,10);
  const big=[...ms].map(m=>{const sd=sideOf(m,id);return {m,gf:sd==='h'?m.hs:m.as,ga:sd==='h'?m.as:m.hs};}).filter(x=>x.gf>x.ga).sort((p,q)=>(q.gf-q.ga)-(p.gf-p.ga)||q.gf-p.gf).slice(0,6);
  const years=eraHeld().map(s=>({s,y:a.byYear[s.year]}));const info=TEAMS[id]||{};
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${color(id)}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Team · ${yspan(a)} · ${a.tournaments} tournament${a.tournaments===1?'':'s'}${info.conf?' · '+esc(info.conf):''}</p><h2 style="margin:6px 0 0"><i class="dot" style="--c:${color(id)};width:.5em;height:.5em;vertical-align:.1em;margin-right:8px"></i>${esc(id)}${info.code?` <span class="muted" style="font-size:.5em;font-weight:600;font-style:normal;letter-spacing:.1em">${esc(info.code)}</span>`:''}</h2></div><div class="small mono muted">#${a.rank} by titles, finals and wins in ${esc(eraLabel())}${(state.sex==='W'?info.wikiW:info.wiki)?` · <a href="${esc(state.sex==='W'?info.wikiW:info.wiki)}" target="_blank" rel="noopener">Wikipedia ↗</a>`:''}</div></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Titles',a.titles,a.titles?years.filter(x=>x.y&&x.y.pos===1).map(x=>x.s.year).join(', '):'')}${kpi('Finals',a.finals,'')}${kpi('Matches',a.played,`${a.wins} W · ${a.draws} D · ${a.losses} L`)}${kpi('Goals',`${a.gf}–${a.ga}`,'for and against')}${kpi('Best',esc(finishLabel(a.best?.pos,a.best?.far)),a.best?String(a.best.y):'')}${kpi('Shoot-outs',`${a.shootW}–${a.shootL}`,'won and lost')}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Every tournament</span><small>finish, newest first · click a year</small></div><div class="tablewrap" style="max-height:520px"><table><tr><th>Year</th><th>Host</th><th>Finish</th><th class="n">P</th><th class="n">W</th><th class="n">D</th><th class="n">L</th><th class="n">GF–GA</th></tr>${[...years].reverse().filter(x=>x.y).map(x=>`<tr class="${x.y.pos===1?'win':''}"><td>${yl(x.s.year)}</td><td class="small muted">${esc(x.s.t.hosts.join(' / '))}</td><td class="small"><b>${esc(finishLabel(x.y.pos,x.y.far))}</b></td><td class="n">${x.y.played}</td><td class="n">${x.y.w}</td><td class="n">${x.y.d}</td><td class="n">${x.y.l}</td><td class="n">${x.y.gf}–${x.y.ga}</td></tr>`).join('')}</table></div></div>
  <div><div class="panel"><div class="h3"><span>Wins, tournament by tournament</span></div>${yearBars(eraHeld().map(s=>{const y=a.byYear[s.year];return {y:s.year,h:y?Math.round(100*Math.max(.15,y.w/Math.max(1,...Object.values(a.byYear).map(z=>z.w)))):0,title:`${s.year} · ${y?finishLabel(y.pos,y.far)+' · '+y.w+' wins in '+y.played:'did not play'}`};}),()=>color(id))}</div><div class="panel" style="margin-top:14px"><div class="h3"><span>Biggest wins</span></div><div class="tablewrap"><table>${big.map(x=>`<tr><td>${yl(x.m.y)}</td><td class="small">${esc(stageLabel(x.m))}</td><td>${ml(x.m,`${x.m.home} ${scoreOf(x.m)} ${x.m.away}`)}</td></tr>`).join('')||'<tr><td class="muted">No wins in this lens.</td></tr>'}</table></div></div></div></div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Top scorers</span><small>for the team in the lens</small></div>${scorers.length?playerBars(scorers,p=>p.goals,p=>`${p.ntour} tournament${p.ntour===1?'':'s'} · ${yspan(p)}`,scorers[0]?.goals||1):'<p class="muted small">No scorers in the source.</p>'}</div><div class="panel"><div class="h3"><span>Most appearances</span><small>from the line-ups the source holds (1970 on)</small></div>${apps.length?playerBars(apps,p=>p.apps,p=>`${p.goals} goals · ${yspan(p)}`,apps[0]?.apps||1):'<p class="muted small">No line-ups in the source.</p>'}</div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Every match</span><small>${ms.length} · newest first · click one</small></div><div class="tablewrap" style="max-height:560px"><table><tr><th>Date</th><th>Year</th><th>Stage</th><th>Opponent</th><th>Result</th><th>Ground</th></tr>${ms.map(m=>{const opp=m.home===id?m.away:m.home;return `<tr class="${resFor(m,id)==='W'?'win':''}"><td class="small muted">${esc(m.date)}</td><td>${yl(m.y)}</td><td class="small">${esc(stageLabel(m))}</td><td>${tl(opp)}${m.home===id?'':' <span class="dim small">(h)</span>'}</td><td>${ml(m,'').replace('></a>','>'+scoreCell(m,id)+'</a>')}</td><td class="small muted">${esc(ST[m.stadium]?.name||'')}</td></tr>`;}).join('')}</table></div></div>`;}

/* ---------- Players ---------- */
function playersView(){const list=playerAgg();const lens=state.plens;let rows=list.filter(p=>p[lens]);rows.sort((a,b)=>b[lens]-a[lens]||b.goals-a.goals||b.apps-a.apps||a.name.localeCompare(b.name));rows=rows.slice(0,40);
  const max=Math.max(1,...rows.map(a=>a[lens]));const q=(state.find2||'').toLowerCase();const found=q?Object.entries(PL).filter(([id,p])=>p.w===(state.sex==='W')&&p.n.toLowerCase().includes(q)).slice(0,14):[];
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Players · ${esc(eraLabel())}</h2></div><div class="small mono muted">${fmt(list.length)} players in the squads</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><input type="search" id="find2" placeholder="Search a player" value="${esc(state.find2||'')}" aria-label="Search"><select id="lens" aria-label="Lens">${Object.entries(PLENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(PLENSES[lens][1])}</span></div>${q?`<div class="chiplist" style="margin-bottom:14px">${found.map(([id,p])=>`<button type="button" class="chip" data-player="${esc(id)}">${esc(p.n)}</button>`).join('')||'<span class="muted small">No match.</span>'}</div>`:''}
  ${playerBars(rows,a=>a[lens],a=>`${esc(a.team||'')} · ${a.goals} goals${a.apps?' · '+a.apps+' apps':''} · ${a.ntour} tournament${a.ntour===1?'':'s'} · ${yspan(a)}`,max)}<p class="small dim" style="margin:10px 0 0">Goals from the source’s goal records (every tournament but the 2023 Women’s World Cup); appearances from its line-ups, which begin in 1970; tournaments from its squads, which 2026 does not have yet.</p></div>`;
  $('#find2').addEventListener('input',e=>{state.find2=e.target.value;playersView();$('#find2').focus();const v=$('#find2');v.setSelectionRange(v.value.length,v.value.length);});$('#lens').addEventListener('change',e=>{state.plens=e.target.value;render();});}
function playerView(id){const p=PL[id];if(!p){playersView();return;}const all=playerAgg();const a=all.find(x=>x.id===id);const rank=all.findIndex(x=>x.id===id)+1;
  const goals=[];const apps=[];for(const s of eraSeasons())for(const m of s.matches){for(const g of m.d.g)if(g[1]===id)goals.push({m,g});if(m.d.l){for(const sd of ['h','a'])for(const r of m.d.l[sd])if(r[0]===id)apps.push({m,sd,r});}}
  goals.sort((x,y)=>y.m.date.localeCompare(x.m.date));apps.sort((x,y)=>y.m.date.localeCompare(x.m.date));
  const squads=TOUR.filter(t=>t.sex===state.sex&&inEraYear(t.year)).flatMap(t=>Object.entries(A.squads[t.id]||{}).flatMap(([tn,rows])=>rows.filter(r=>r[0]===id).map(r=>({t,tn,shirt:r[1],pos:r[2]}))));
  const awards=TOUR.filter(t=>t.sex===state.sex).flatMap(t=>t.awards.filter(w=>w[1]===id).map(w=>({t,w})));
  const col=color(a?.team||squads[0]?.tn||'?');const born=p.b?longDate(p.b):null;const age=(d)=>{if(!p.b)return '';const b=new Date(p.b),x=new Date(d);let y=x.getUTCFullYear()-b.getUTCFullYear();if(x.getUTCMonth()<b.getUTCMonth()||(x.getUTCMonth()===b.getUTCMonth()&&x.getUTCDate()<b.getUTCDate()))y--;return y;};
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${col}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Player${a?' · '+yspan(a):''} · ${[...new Set([...(a?Object.keys(a.teams):[]),...squads.map(x=>x.tn)])].map(tl).join(' / ')||''}${p.pos?' · '+esc({G:'goalkeeper',D:'defender',M:'midfielder',F:'forward'}[p.pos[0]]||p.pos):''}</p><h2 style="margin:6px 0 0">${esc(p.n)}</h2>${born?`<p class="small muted" style="margin:6px 0 0">Born ${esc(born)}</p>`:''}</div><div class="small mono muted">${rank?`#${rank} by goals in ${esc(eraLabel())}`:'no goals in this lens'}${p.wiki?` · <a href="${esc(p.wiki)}" target="_blank" rel="noopener">Wikipedia ↗</a>`:''}</div></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Goals',a?a.goals:0,a&&a.pens?`${a.pens} from the spot`:'')}${kpi('Appearances',a&&a.apps?a.apps:'—',a&&a.apps?`${a.starts} starts · line-ups from 1970`:'no line-ups in the source')}${kpi('Tournaments',a?a.ntour:squads.length,a?a.years.join(', '):'')}${kpi('Hat-tricks',a?a.hat:0,'')}${kpi('Cards',a?a.cards:0,a&&a.reds?`${a.reds} red`:'')}${awards.length?kpi('Awards',awards.length,awards.map(x=>x.w[0]+' '+x.t.year).join(', ')):''}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Every goal</span><small>${goals.length} · click a match</small></div><div class="tablewrap" style="max-height:480px"><table><tr><th>Year</th><th>Stage</th><th>Match</th><th>Minute</th></tr>${goals.map(({m,g})=>`<tr><td>${yl(m.y)}</td><td class="small">${esc(stageLabel(m))}</td><td>${ml(m,`${m.home} ${scoreOf(m)} ${m.away}`)}</td><td class="small">${minuteLabel(g[2],g[3])}${g[5]?' <span class="dim">pen</span>':''}${g[4]?' <span class="dim">o.g.</span>':''}${p.b?` <span class="dim">aged ${age(m.date)}</span>`:''}</td></tr>`).join('')||'<tr><td class="muted">None in the source.</td></tr>'}</table></div></div>
  <div class="panel"><div class="h3"><span>Squads</span><small>${squads.length} tournament${squads.length===1?'':'s'}</small></div><div class="tablewrap"><table><tr><th>Year</th><th>Team</th><th class="n">Shirt</th><th>Position</th><th>Finish</th></tr>${squads.map(x=>{const pos=x.t.standings.indexOf(x.tn)+1;return `<tr><td>${yl(x.t.year)}</td><td>${tl(x.tn)}</td><td class="n">${x.shirt??'—'}</td><td class="small">${esc(x.pos)}</td><td class="small">${esc(pos?finishLabel(pos):'')}</td></tr>`;}).join('')||'<tr><td class="muted">No squad in the source.</td></tr>'}</table></div></div></div>
  ${apps.length?`<div class="panel" style="margin-top:20px"><div class="h3"><span>Every appearance</span><small>${apps.length} · from the line-ups · newest first</small></div><div class="tablewrap" style="max-height:480px"><table><tr><th>Date</th><th>Year</th><th>Stage</th><th>Match</th><th>For</th><th></th></tr>${apps.map(({m,sd,r})=>`<tr><td class="small muted">${esc(m.date)}</td><td>${yl(m.y)}</td><td class="small">${esc(stageLabel(m))}</td><td>${ml(m,`${m.home} ${scoreOf(m)} ${m.away}`)}</td><td>${tl(sd==='h'?m.home:m.away)}</td><td class="small dim">${r[3]?'start':'from the bench'}</td></tr>`).join('')}</table></div></div>`:''}`;}

/* ---------- Grounds ---------- */
function groundsView(){const list=groundAgg();const lens=state.glens;let rows=list.slice().sort((a,b)=>b[lens]-a[lens]||b.count-a.count||a.name.localeCompare(b.name)).slice(0,60);const max=Math.max(1,...rows.map(a=>a[lens]));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Grounds · ${esc(eraLabel())}</h2></div><div class="small mono muted">${list.length} grounds</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="lens" aria-label="Lens">${Object.entries(GLENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(GLENSES[lens][1])}</span></div>${bars(rows,a=>a[lens],a=>`${esc(a.city)}${a.country?', '+esc(a.country):''} · ${a.count} matches · ${a.finals?a.finals+' final'+(a.finals>1?'s':'')+' · ':''}${a.first}${a.last!==a.first?'–'+a.last:''}${a.top?' · most wins: '+esc(a.top):''}`,max,'ground',a=>a.name,a=>color(a.top||'?'))}<p class="small dim" style="margin:10px 0 0">Grounds as the source names them; capacities where it gives them. The 2026 grounds are named by the editor from the host cities the source lists.</p></div>`;
  $('#lens').addEventListener('change',e=>{state.glens=e.target.value;render();});}
function groundView(id){const g=groundAgg().find(x=>x.id===id);if(!g){groundsView();return;}const st=ST[id];const ms=[...g.matches].sort((a,b)=>b.date.localeCompare(a.date));const wins=Object.entries(g.wins).sort((p,q)=>q[1]-p[1]).slice(0,8).map(([t,n])=>({id:t,n}));const finals=ms.filter(m=>m.stage==='final');
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${color(g.top||'?')}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Ground · ${esc(g.city)}${g.country?', '+esc(g.country):''} · ${g.first}${g.last!==g.first?'–'+g.last:''}</p><h2 style="margin:6px 0 0">${esc(g.name)}</h2></div><div class="small mono muted">${st?.cap?`capacity ${fmt(st.cap)} · `:''}${st?.wiki?`<a href="${esc(st.wiki)}" target="_blank" rel="noopener">Wikipedia ↗</a>`:''}</div></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Matches',g.count,'')}${kpi('Tournaments',g.tournaments,[...g.years].sort().join(', '))}${kpi('Finals',g.finals,finals.map(m=>m.y).join(', '))}${kpi('Goals',g.goals,`${(g.goals/Math.max(1,g.count)).toFixed(2)} per match`)}${kpi('Most wins here',g.top||'—',g.top?g.wins[g.top]+' wins':'')}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Winners here</span></div>${wins.length?teamBars(wins,a=>a.n,a=>`${g.matches.filter(m=>m.home===a.id||m.away===a.id).length} matches`,wins[0]?.n||1):'<p class="muted small">No wins recorded.</p>'}</div><div class="panel"><div class="h3"><span>Every match here</span><small>${ms.length} · newest first</small></div><div class="tablewrap" style="max-height:480px"><table><tr><th>Date</th><th>Year</th><th>Stage</th><th>Match</th></tr>${ms.map(m=>`<tr class="${m.stage==='final'?'win':''}"><td class="small muted">${esc(m.date)}</td><td>${yl(m.y)}</td><td class="small">${esc(stageLabel(m))}</td><td>${ml(m,`${m.home} ${resultLine(m)} ${m.away}`)}</td></tr>`).join('')}</table></div></div></div>`;}

/* ---------- Hosts ---------- */
function hostsView(){const rows=HOSTS.map(h=>({...h,ts:h.ids.map(id=>tById[id]).filter(t=>t.sex===state.sex&&inEraYear(t.year))})).filter(h=>h.ts.length).sort((a,b)=>b.ts.length-a.ts.length||a.years[0]-b.years[0]);
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Hosts · ${esc(eraLabel())}</h2></div><div class="small mono muted">${rows.length} cities of finals</div></div><div class="panel"><div class="worldmap" style="margin-top:0">${worldSvg()}</div><div class="tablewrap" style="max-height:560px"><table><tr><th>City of the final</th><th>Host</th><th class="n">Finals</th><th>Years</th><th>Champions</th></tr>${rows.map(h=>`<tr><td><a href="#" data-host="${esc(h.city)}" style="color:inherit"><b>${esc(h.city)}</b></a></td><td class="muted">${esc([...new Set(h.ts.flatMap(t=>t.hosts))].join(' / '))}</td><td class="n">${h.ts.length}</td><td class="small">${h.ts.map(t=>yl(t.year)).join(', ')}</td><td class="small">${[...new Set(h.ts.map(t=>t.winner).filter(Boolean))].map(tl).join(' · ')}</td></tr>`).join('')}</table></div><p class="small dim" style="margin:10px 0 0">The city of the final, at approximate coordinates, on the land as Natural Earth maps it; a tournament’s other grounds are listed under Grounds. Two hosts in 2002 (South Korea and Japan), 2023 (Australia and New Zealand) and three in 2026 (the United States, Canada and Mexico).</p></div>`;
  $('#view').querySelectorAll('.host').forEach(g=>g.addEventListener('click',()=>{state.host=g.dataset.host;go('hosts',false);}));}
function hostView(city){const h=hostOf(city);if(!h){hostsView();return;}const ts=h.ids.map(id=>tById[id]).filter(t=>t.sex===state.sex);const fake={point:[h.city,h.lon,h.lat],hosts:h.countries};
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:var(--accent)"><div class="panel"><p class="eyebrow">City of the final · ${esc(h.countries.join(' / '))} · ${ts.map(t=>t.year).join(', ')||h.years.join(', ')}</p><h2 style="margin:6px 0 0">${esc(h.city)}</h2></div></div>
  <div class="course" style="margin-top:20px"><div class="course-map">${hostSvg(fake,{minW:90,k:1,labels:true,others:true,color:'var(--accent)'})}</div><div class="course-side"><p class="eyebrow">The finals here</p><div class="calendar" style="flex-direction:column;overflow:visible">${(ts.length?ts:h.ids.map(id=>tById[id])).map(t=>{const f=t.final?mById[t.final]:null;return `<button type="button" class="cal" data-year="${t.year}" data-sex="${t.sex}" style="flex:none;--team:${t.winner?color(t.winner):'#5b616b'}"><div class="rd">${t.year} · ${esc(SEX_NAME[t.sex])}</div><div class="nm">${esc(t.hosts.join(' / '))}</div><div class="w">${f?'<i class="dot" style="--c:'+color(t.winner||'?')+'"></i>'+esc(f.home)+' '+resultLine(f)+' '+esc(f.away):t.winner?'<i class="dot" style="--c:'+color(t.winner)+'"></i>'+esc(t.winner):'—'}</div>${f&&ST[f.stadium]?`<div class="small muted" style="margin-top:4px">${esc(ST[f.stadium].name)}</div>`:''}</button>`;}).join('')}</div></div></div>`;}

/* ---------- Records ---------- */
function recordsView(){const ss=eraHeld();const ms=eraMatches().filter(m=>m.replay!=='replayed');const teams=teamAgg();const players=playerAgg();
  const margin=[...ms].sort((a,b)=>Math.abs(b.hs-b.as)-Math.abs(a.hs-a.as)||(b.hs+b.as)-(a.hs+a.as)).slice(0,8);const most=[...ms].sort((a,b)=>(b.hs+b.as)-(a.hs+a.as)||a.date.localeCompare(b.date)).slice(0,8);
  const perT={};for(const s of ss)for(const m of s.matches)for(const g of m.d.g){if(g[4])continue;const k=g[1]+'|'+s.year;const a=perT[k]||(perT[k]={id:g[1],y:s.year,goals:0,team:g[0]===1?m.home:m.away});a.goals++;}const bestT=Object.values(perT).sort((a,b)=>b.goals-a.goals||a.y-b.y).slice(0,10);
  const hats=[];for(const m of ms){const c={};for(const g of m.d.g){if(g[4])continue;const k=g[1];(c[k]=c[k]||{id:k,n:0,team:g[0]===1?m.home:m.away}).n++;}for(const k in c)if(c[k].n>=3)hats.push({...c[k],m});}hats.sort((a,b)=>b.n-a.n||a.m.date.localeCompare(b.m.date));
  const fast=ms.flatMap(m=>m.d.g.filter(g=>!g[4]&&g[2]<=3).map(g=>({m,g,team:g[0]===1?m.home:m.away}))).sort((a,b)=>a.g[2]-b.g[2]||a.m.date.localeCompare(b.m.date)).slice(0,8);
  const ageOf=(pid,date)=>{const b=PL[pid]?.b;if(!b)return null;const bd=new Date(b),x=new Date(date);let y=x.getUTCFullYear()-bd.getUTCFullYear();if(x.getUTCMonth()<bd.getUTCMonth()||(x.getUTCMonth()===bd.getUTCMonth()&&x.getUTCDate()<bd.getUTCDate()))y--;return y+(((x-bd)/86400000%365.25)/365.25);};
  const aged=ms.flatMap(m=>m.d.g.filter(g=>!g[4]).map(g=>({m,g,team:g[0]===1?m.home:m.away,age:ageOf(g[1],m.date)}))).filter(x=>x.age!=null);const young=[...aged].sort((a,b)=>a.age-b.age).slice(0,6),old=[...aged].sort((a,b)=>b.age-a.age).slice(0,6);
  const titles=teams.filter(t=>t.titles).slice(0,10);const mostFinals=[...teams].sort((a,b)=>b.finals-a.finals||recCmp(a,b)).slice(0,8);const mostT=[...teams].sort((a,b)=>b.tournaments-a.tournaments||recCmp(a,b)).slice(0,8);
  const hostRows=ss.map(s=>{const hs=s.t.hosts.map(h=>({h,pos:s.t.standings.indexOf(h)+1,a:teams.find(t=>t.id===h)}));return hs.map(x=>({s,...x,far:x.a?.byYear[s.year]?.far||0}));}).flat().filter(x=>x.a).sort((a,b)=>(a.pos||9)-(b.pos||9)||b.far-a.far).slice(0,10);
  const shoot=[...teams].filter(t=>t.shootW+t.shootL).sort((a,b)=>b.shootW-a.shootW||a.shootL-b.shootL).slice(0,8);const mostTour=[...players].sort((a,b)=>b.ntour-a.ntour||b.goals-a.goals).slice(0,8);const mostApps=[...players].filter(p=>p.apps).sort((a,b)=>b.apps-a.apps||b.goals-a.goals).slice(0,8);
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Records · ${esc(eraLabel())}</h2></div><div class="small mono muted">${ss.length} tournaments</div></div>
  <div class="kpis">${kpi('Tournaments',ss.length,`${ss[0]?.year}–${ss[ss.length-1]?.year}`)}${kpi('Matches',fmt(ms.length),`${fmt(ms.reduce((n,m)=>n+m.hs+m.as,0))} goals`)}${kpi('Teams',teams.length,`${teams.filter(t=>t.titles).length} champions`)}${kpi('Most goals',players[0]?pname(players[0].id):'—',players[0]?`${players[0].goals} · ${esc(players[0].team||'')} · ${yspan(players[0])}`:'')}${kpi('Most titles',titles[0]?titles[0].id:'—',titles[0]?`${titles[0].titles}`:'')}</div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Most goals</span><small>players</small></div>${playerBars(players.slice(0,10),a=>a.goals,a=>`${esc(a.team||'')} · ${a.ntour} tournament${a.ntour===1?'':'s'} · ${yspan(a)}`,players[0]?.goals||1)}</div><div class="panel"><div class="h3"><span>Most goals at one tournament</span></div>${bars(bestT,a=>a.goals,a=>`${a.y} · ${esc(a.team)}`,bestT[0]?.goals||1,'player',a=>pname(a.id),a=>color(a.team))}</div><div class="panel"><div class="h3"><span>Hat-tricks</span><small>${hats.length} · three or more in a match</small></div>${hats.length?`<div class="board">${hats.slice(0,10).map((h,i)=>`<button type="button" class="bar" data-match="${esc(h.m.id)}" style="--i:${i};--team:${color(h.team)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(h.id))}</span><small>${h.m.y} · ${esc(h.m.home)} ${scoreOf(h.m)} ${esc(h.m.away)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*h.n/(hats[0]?.n||1))}%"></span></span></span><span class="val">${h.n}</span></button>`).join('')}</div>`:'<p class="muted small">None in the source for this lens.</p>'}</div></div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Biggest wins</span></div><div class="board">${margin.map((m,i)=>`<button type="button" class="bar" data-match="${esc(m.id)}" style="--i:${i};--team:${color(winnerName(m)||'?')}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(m.home)} ${scoreOf(m)} ${esc(m.away)}</span><small>${m.y} · ${esc(stageLabel(m))}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*Math.abs(m.hs-m.as)/Math.abs(margin[0].hs-margin[0].as))}%"></span></span></span><span class="val">+${Math.abs(m.hs-m.as)}</span></button>`).join('')}</div></div><div class="panel"><div class="h3"><span>Most goals in a match</span></div><div class="board">${most.map((m,i)=>`<button type="button" class="bar" data-match="${esc(m.id)}" style="--i:${i};--team:${color(winnerName(m)||'?')}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(m.home)} ${scoreOf(m)} ${esc(m.away)}</span><small>${m.y} · ${esc(stageLabel(m))}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*(m.hs+m.as)/(most[0].hs+most[0].as))}%"></span></span></span><span class="val">${m.hs+m.as}</span></button>`).join('')}</div></div><div class="panel"><div class="h3"><span>Fastest goals</span><small>minute of the goal</small></div>${fast.length?`<div class="board">${fast.map((x,i)=>`<button type="button" class="bar" data-match="${esc(x.m.id)}" style="--i:${i};--team:${color(x.team)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(x.g[1]))}</span><small>${x.m.y} · ${esc(x.m.home)} ${scoreOf(x.m)} ${esc(x.m.away)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100-25*x.g[2])}%"></span></span></span><span class="val">${minuteLabel(x.g[2],x.g[3])}</span></button>`).join('')}</div>`:'<p class="muted small">None in the source for this lens.</p>'}</div></div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Most titles</span></div>${teamBars(titles,a=>a.titles,a=>`${a.finals} finals · ${a.tournaments} tournaments`,titles[0]?.titles||1)}</div><div class="panel"><div class="h3"><span>Most finals</span></div>${teamBars(mostFinals,a=>a.finals,a=>`${a.titles} won`,mostFinals[0]?.finals||1)}</div><div class="panel"><div class="h3"><span>Most tournaments</span></div>${teamBars(mostT,a=>a.tournaments,a=>`${a.played} matches · ${yspan(a)}`,mostT[0]?.tournaments||1)}</div></div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Youngest and oldest scorers</span><small>where the source gives a birth date</small></div><div class="tablewrap"><table>${young.map(x=>`<tr><td class="small">${x.age.toFixed(1)}</td><td>${pl(x.g[1])}</td><td class="small muted">${x.m.y} · ${esc(x.team)}</td></tr>`).join('')}<tr><td colspan="3" class="dim small" style="text-align:center">· · ·</td></tr>${old.map(x=>`<tr><td class="small">${x.age.toFixed(1)}</td><td>${pl(x.g[1])}</td><td class="small muted">${x.m.y} · ${esc(x.team)}</td></tr>`).join('')}</table></div></div><div class="panel"><div class="h3"><span>The hosts</span><small>where the host finished</small></div><div class="tablewrap"><table>${hostRows.map(x=>`<tr class="${x.pos===1?'win':''}"><td>${yl(x.s.year)}</td><td>${tl(x.h)}</td><td class="small">${esc(finishLabel(x.pos,x.far))}</td></tr>`).join('')}</table></div></div><div class="panel"><div class="h3"><span>Shoot-outs</span><small>won and lost</small></div>${shoot.length?teamBars(shoot,a=>a.shootW,a=>`${a.shootL} lost`,shoot[0]?.shootW||1):'<p class="muted small">None in this lens.</p>'}</div></div>
  <div class="two" style="margin-top:14px"><div class="panel"><div class="h3"><span>Most tournaments</span><small>players in a squad</small></div>${playerBars(mostTour,a=>a.ntour,a=>`${esc(a.team||'')} · ${a.years.join(', ')}`,mostTour[0]?.ntour||1)}</div><div class="panel"><div class="h3"><span>Most appearances</span><small>from the line-ups, 1970 on</small></div>${mostApps.length?playerBars(mostApps,a=>a.apps,a=>`${esc(a.team||'')} · ${a.goals} goals · ${yspan(a)}`,mostApps[0]?.apps||1):'<p class="muted small">No line-ups in this lens.</p>'}</div></div>`;}

/* ---------- Barcode ---------- */
const HEATMETRICS={wins:['Wins','Matches won at that tournament.'],goals:['Goals','Goals scored at that tournament.'],finish:['Finish','How far the team went: brightest for the champions.']};
function barcodeView(){const ss=eraHeld();const years=ss.map(s=>s.year);const teams=teamAgg();const rows=teams.slice(0,32);const val=(a,y)=>{const b=a.byYear[y];if(!b)return 0;return state.heat==='wins'?b.w:state.heat==='goals'?b.gf:b.pos?10-b.pos:Math.min(5,b.far);};const max=Math.max(1,...rows.flatMap(a=>years.map(y=>val(a,y))));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Barcode · ${esc(eraLabel())}</h2></div><div class="small mono muted">${rows.length} teams × ${years.length} tournaments</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="heat" aria-label="Metric">${Object.entries(HEATMETRICS).map(([k,v])=>`<option value="${k}" ${k===state.heat?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(HEATMETRICS[state.heat][1])} Brightness is the cell’s share of the brightest cell; colour is the team’s. Rows ordered by titles, finals and wins; a dark cell is a tournament the team did not play.</span></div>
  <div class="barcode"><div class="bc-row"><span></span><span class="cells" style="gap:2px">${years.map(y=>`<i style="background:none;height:14px;font-size:8px;color:var(--dim);text-align:center;line-height:14px">${String(y).slice(2)}</i>`).join('')}</span><span></span></div>${rows.map(a=>`<div class="bc-row"><span class="lab" data-team="${esc(a.id)}">${esc(a.id)}</span><span class="cells">${years.map(y=>{const v=val(a,y);const b=a.byYear[y];const x=v?Math.max(.12,v/max):b?.08:0;return `<i data-year="${y}" title="${esc(a.id)} ${y} · ${b?finishLabel(b.pos,b.far)+' · '+b.w+' wins · '+b.gf+' goals':'did not play'}" style="--c:${mixHex(color(a.id),'#0f1113',x)}"></i>`;}).join('')}</span><span class="tot">${a.titles}</span></div>`).join('')}</div></div>`;
  $('#heat').addEventListener('change',e=>{state.heat=e.target.value;render();});}

/* ---------- Duel ---------- */
function swingChart(el,pts,labA,labB,cA,cB){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(180,box.height);const padL=30,padR=30,padT=16,padB=22;const n=pts.length;const max=Math.max(1,...pts.map(p=>Math.abs(p.v)));const x=i=>padL+(n>1?i*(W-padL-padR)/(n-1):(W-padL-padR)/2),y=v=>padT+(H-padT-padB)*(1-(v+max)/(2*max));
  const mid=y(0);let d='';pts.forEach((p,i)=>{d+=(i?'L':'M')+x(i).toFixed(1)+' '+y(p.v).toFixed(1);});
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Head-to-head swing"><line class="gridl" x1="${padL}" x2="${W-padR}" y1="${mid.toFixed(1)}" y2="${mid.toFixed(1)}"/><text class="lb" x="${padL}" y="${padT-4}" style="fill:${cA}">${esc(labA)} ahead</text><text class="lb" x="${padL}" y="${H-6}" style="fill:${cB}">${esc(labB)} ahead</text><path class="ser" d="${d}" style="--c:var(--muted)"/>${pts.map((p,i)=>`<circle class="pt" cx="${x(i).toFixed(1)}" cy="${y(p.v).toFixed(1)}" r="4" fill="${p.win==='A'?cA:p.win==='B'?cB:'#5b616b'}" data-year="${p.y}"><title>${esc(p.label)}</title></circle>`).join('')}</svg>`;}
function duelView(){const teams=teamAgg();const players=playerAgg();
  if(state.duelBy==='p'){const ids=players.slice(0,200).map(p=>p.id);if(!state.dA||!(state.dA in PL))state.dA=ids[0];if(!state.dB||!(state.dB in PL)||state.dB===state.dA)state.dB=ids.find(i=>i!==state.dA);}
  else{const ids=teams.slice(0,60).map(m=>m.id);if(!state.dA||!ids.includes(state.dA))state.dA=ids[0];if(!state.dB||!ids.includes(state.dB)||state.dB===state.dA)state.dB=ids.find(i=>i!==state.dA);}
  const opts=sel=>state.duelBy==='p'?[...new Set([state.dA,state.dB,...players.slice(0,200).map(p=>p.id)])].filter(Boolean).map(id=>`<option value="${esc(id)}" ${id===sel?'selected':''}>${esc(pname(id))}</option>`).join(''):teams.slice(0,60).map(m=>`<option value="${esc(m.id)}" ${m.id===sel?'selected':''}>${esc(m.id)}</option>`).join('');
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Head to head · ${esc(eraLabel())}</h2></div><div class="small mono muted">${state.duelBy==='p'?'players · goals, tournament by tournament':'teams · their meetings, and the lead in wins'}</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="duelBy" aria-label="Compare"><option value="t" ${state.duelBy==='t'?'selected':''}>Teams</option><option value="p" ${state.duelBy==='p'?'selected':''}>Players</option></select><select id="dA" aria-label="First">${opts(state.dA)}</select><span class="mono small muted">vs</span><select id="dB" aria-label="Second">${opts(state.dB)}</select></div><div id="duelBody"></div></div>`;
  $('#duelBy').addEventListener('change',e=>{state.duelBy=e.target.value;state.dA=null;state.dB=null;render();});$('#dA').addEventListener('change',e=>{state.dA=e.target.value;render();});$('#dB').addEventListener('change',e=>{state.dB=e.target.value;render();});
  const a=state.dA,b=state.dB;if(!a||!b){$('#duelBody').innerHTML='<p class="muted">Pick two.</p>';return;}
  if(state.duelBy==='p'){const pa=players.find(p=>p.id===a)||{goals:0,byYear:{},team:'?'},pb=players.find(p=>p.id===b)||{goals:0,byYear:{},team:'?'};const cA=color(pa.team||'?'),cB=color(pb.team||'?');let lead=0;const pts=eraHeld().map(s=>{const ga=pa.byYear[s.year]?.goals||0,gb=pb.byYear[s.year]?.goals||0;lead+=ga-gb;return {v:lead,win:ga>gb?'A':gb>ga?'B':'',y:s.year,label:`${s.year} · ${pname(a)} ${ga} · ${pname(b)} ${gb}`};});
    $('#duelBody').innerHTML=`<div class="duel-heads"><div class="dh" style="--team:${cA}"><span class="eyebrow">${esc(pname(a))}</span><b>${pa.goals}</b><small>goals · ${pa.apps||'—'} apps · ${pa.ntour||0} tournaments</small></div><div class="dh" style="--team:${cB}"><span class="eyebrow">${esc(pname(b))}</span><b>${pb.goals}</b><small>goals · ${pb.apps||'—'} apps · ${pb.ntour||0} tournaments</small></div></div><div class="h3" style="margin-top:18px"><span>The lead in goals, tournament by tournament</span><small>cumulative</small></div><div class="chart" id="duelSwing" style="height:220px"></div>`;if(pts.length)swingChart($('#duelSwing'),pts,pname(a),pname(b),cA,cB);return;}
  const cA=color(a),cB=color(b);const meets=eraMatches().filter(m=>m.replay!=='replayed'&&((m.home===a&&m.away===b)||(m.home===b&&m.away===a))).sort((p,q)=>p.date.localeCompare(q.date));let wa=0,wb=0,dr=0,ga=0,gb=0;for(const m of meets){const r=resFor(m,a);if(r==='W')wa++;else if(r==='L')wb++;else dr++;const sd=sideOf(m,a);ga+=sd==='h'?m.hs:m.as;gb+=sd==='h'?m.as:m.hs;}
  const ta=teams.find(t=>t.id===a),tb=teams.find(t=>t.id===b);let lead=0;const pts=eraHeld().map(s=>{const xa=ta?.byYear[s.year]?.w||0,xb=tb?.byYear[s.year]?.w||0;lead+=xa-xb;return {v:lead,win:xa>xb?'A':xb>xa?'B':'',y:s.year,label:`${s.year} · ${a} ${xa} wins · ${b} ${xb} wins`};});
  $('#duelBody').innerHTML=`<div class="duel-heads"><div class="dh" style="--team:${cA}"><span class="eyebrow">${esc(a)}</span><b>${wa}</b><small>wins in ${meets.length} meeting${meets.length===1?'':'s'} · ${ga} goals${ta?` · ${ta.titles} title${ta.titles===1?'':'s'} in all`:''}</small></div><div class="dh" style="--team:${cB}"><span class="eyebrow">${esc(b)}</span><b>${wb}</b><small>wins · ${dr} drawn · ${gb} goals${tb?` · ${tb.titles} title${tb.titles===1?'':'s'} in all`:''}</small></div></div><div class="h3" style="margin-top:18px"><span>The lead in wins, tournament by tournament</span><small>cumulative, against everyone</small></div><div class="chart" id="duelSwing" style="height:220px"></div>
  ${meets.length?`<div class="h3" style="margin-top:18px"><span>Their meetings</span><small>${meets.length} · click one</small></div><div class="tablewrap" style="max-height:480px"><table><tr><th>Year</th><th>Stage</th><th>Match</th><th>Ground</th></tr>${[...meets].reverse().map(m=>`<tr class="${m.stage==='final'?'win':''}"><td>${yl(m.y)}</td><td class="small">${esc(stageLabel(m))}</td><td>${ml(m,`${m.home} ${resultLine(m)} ${m.away}`)}</td><td class="small muted">${esc(ST[m.stadium]?.name||'')}</td></tr>`).join('')}</table></div>`:'<p class="muted small" style="margin-top:14px">They have never met at the World Cup in this lens.</p>'}`;
  if(pts.length)swingChart($('#duelSwing'),pts,a,b,cA,cB);}

/* ---------- Sources & coverage ---------- */
function drawSources(){const cov=A.coverage||{};
  $('#sourcesBody').innerHTML=`<p class="eyebrow">World Cup edition / ${esc(A.snapshot)}</p><h2>Every match of every World Cup, one archive.</h2><div class="kpis">${kpi('Tournaments',cov.tournaments,`${cov.men} men’s · ${cov.women} women’s`)}${kpi('Matches',fmt(cov.matches),`${fmt(cov.withScorers)} with scorers`)}${kpi('Goals',fmt(cov.goals),'with their scorers')}${kpi('Line-ups',fmt(cov.lineups),'matches with a full sheet')}${kpi('Players',fmt(cov.players),`${fmt(cov.playersWithArticle)} with an article`)}${kpi('Teams',cov.teams,'')}${kpi('Grounds',cov.stadiums,'')}</div>
<h3>Sources</h3><ol>${(A.sources||[]).map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.name)}</a> (${esc(s.licence)}; ${esc(s.attribution)}) — ${esc(s.covers)}.</li>`).join('')}</ol><p>${esc(A.method||'')}</p>
<h3>What the atlas counts</h3><p class="small muted">A result is the score after extra time; a shoot-out decides who went through and is kept beside it, so a shoot-out is a draw in every record and a win for the team that advanced. A replayed match stands with its replay; the replay’s result is the one that counts. Group tables use the points rule of the year and are ordered as the database ranks them; the final round of 1950 is a group. Goals are credited to the scorer, own goals to the scorer against. Appearances come from the line-ups, which the database carries from 1970; squads from 1930. The 2026 record (OpenFootball) has scorers but no line-ups, squads, referees or managers; the 2023 Women’s World Cup (Wikipedia) has results and grounds only — both will fill when the database publishes them.</p>
<h3>Names</h3><p class="small muted">Teams stay as the sources name them, joined across sources only where the same team is spelled differently (USA and United States, Ivory Coast and Côte d’Ivoire). ${cov.minted} players of the tournaments held from OpenFootball or the ledger are known only by the name that source prints and are not yet joined to the database’s register; they join it when the database publishes the tournament. The 2026 grounds are named by the editor from the host cities the source lists.</p>`;}

/* ---------- deep links ---------- */
let routeLock=false;
function writeRoute(){if(routeLock)return;const q=[];if(state.sex!=='M')q.push('sex='+state.sex);if(state.era!=='all')q.push('era='+encodeURIComponent(state.era));if(state.whole)q.push('whole=1');else q.push('season='+state.year);q.push('tab='+state.tab);for(const [k,t] of [['player','players'],['team','teams'],['ground','grounds'],['host','hosts']]){if(state.tab===t&&state[k])q.push(k+'='+encodeURIComponent(state[k]));}if(state.tab==='match'&&!state.whole&&state.match)q.push('match='+encodeURIComponent(state.match));if(state.tab==='duel'&&state.dA&&state.dB)q.push('duel='+encodeURIComponent(state.dA+'|'+state.dB)+'&by='+state.duelBy);const h='#'+q.join('&');if(location.hash!==h){try{history[location.hash?'pushState':'replaceState'](null,'',h);}catch(e){}}}
function readRoute(){const h=location.hash.replace(/^#\/?/,'');if(!h||/^static-/.test(h))return false;const p={};for(const kv of h.split('&')){const i=kv.indexOf('=');p[i<0?kv:kv.slice(0,i)]=i<0?'1':decodeURIComponent(kv.slice(i+1));}let any=false;
  if(p.match&&mById[p.match]){p.sex=mById[p.match].sex;}
  if(p.sex&&['M','W'].includes(p.sex)){state.sex=p.sex;any=true;}rebuildSeasons();buildEras();
  if(p.era&&(p.era==='all'||ERAS.some(e=>e.id===p.era))){state.era=p.era;any=true;}
  if(p.season&&byYear[+p.season]){state.year=+p.season;any=true;}
  if(state.era!=='all'&&!inEraYear(state.year)){if(p.season)state.era='all';else state.year=eraHeld().slice(-1)[0]?.year||state.year;}
  state.whole=p.whole==='1';if(state.whole)any=true;
  if(p.tab&&TABS.some(t=>t[0]===p.tab)){state.tab=p.tab;any=true;}
  if(p.match&&mById[p.match]){state.match=p.match;state.year=mById[p.match].y;state.whole=false;any=true;}
  state.player=p.player&&(p.player in PL)?p.player:null;state.team=p.team||null;state.ground=p.ground&&ST[p.ground]?p.ground:null;state.host=p.host&&hostOf(p.host)?p.host:null;
  if(p.duel){const [a,b]=p.duel.split('|');state.duelBy=p.by==='p'?'p':'t';state.dA=a;state.dB=b;any=true;}
  return any;}

/* ---------- render, navigation, events ---------- */
function render(){stopReplay();drawTabs();if(tour.stopped||!tour.timer)drawEraStrip();const v={season:seasonView,match:matchView,teams:()=>state.team?teamView(state.team):teamsView(),players:()=>state.player?playerView(state.player):playersView(),grounds:()=>state.ground?groundView(state.ground):groundsView(),hosts:()=>state.host?hostView(state.host):hostsView(),records:recordsView,barcode:barcodeView,duel:duelView}[state.tab];try{v();}catch(e){$('#view').innerHTML=`<p class="muted">Something in this view could not be drawn: ${esc(e.message)}</p>`;console.error(e);}StageNav.draw();writeRoute();}
function go(tab,scroll=true){state.tab=tab;render();if(scroll)$('#stage').scrollIntoView({behavior:RM?'auto':'smooth',block:'start'});}
function ensureYearInLens(y){if(state.era!=='all'&&!inEraYear(y)){state.era='all';$('#eraSelect').value='all';}}
function setSeason(y,scroll){state.whole=false;ensureYearInLens(y);state.year=y;state.showAll=false;fillSeasons();applyTheme();drawRiver();if(state.tab!=='match')state.tab='season';go(state.tab,scroll);}
function fillSeasons(){const sel=$('#season');const ss=eraSeasons();if(!ss.length){sel.innerHTML='';return;}const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);sel.innerHTML=`<option value="era">${e?'Whole era':'Every tournament'} · ${ss[0].year}–${ss[ss.length-1].year}</option>`+'<optgroup label="Newest first">'+ss.slice().reverse().map(s=>`<option value="${s.year}">${s.year} ${esc(s.t.hosts.join(' / '))}</option>`).join('')+'</optgroup>';sel.value=state.whole?'era':state.year;}
function setEra(id){tourStop();state.era=id;$('#eraSelect').value=id;if(id!=='all'){if(!inEraYear(state.year)){const last=eraHeld().slice(-1)[0];state.year=last?last.year:state.year;}}fillSeasons();applyTheme();drawRiver();drawGrid();render();}
function relens(rerender=true){rebuildSeasons();buildEras();if(!byYear[state.year])state.year=LAST_YEAR;state.player=null;state.team=null;state.ground=null;state.host=null;state.match=null;state.dA=null;state.dB=null;fillSeasons();$('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.map(e=>`<option value="${e.id}">${esc(ERA_SHORT[e.id]||e.name)} · ${e.from}–${e.to}</option>`).join('');if(![...$('#eraSelect').options].some(o=>o.value===state.era))state.era='all';$('#eraSelect').value=state.era;$('#eraStrip').innerHTML='';const topN=teamAgg().slice(0,16).map(m=>m.id);$('#theme').innerHTML=`<option value="champion">Champions of the tournament</option>`+topN.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join('');if(rerender){applyTheme();drawRiver();drawGrid();render();}}
function openMatch(id,scroll){const m=mById[id];if(!m)return;if(m.sex!==state.sex){state.sex=m.sex;$('#family').value=state.sex;relens(false);}state.whole=false;ensureYearInLens(m.y);state.year=m.y;state.match=id;state.mstage=null;fillSeasons();applyTheme();drawRiver();go('match',scroll);}
function init(){
  landDefs();rebuildSeasons();buildEras();
  $('#family').innerHTML=`<option value="M">Men’s World Cup</option><option value="W">Women’s World Cup</option>`;
  $('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.map(e=>`<option value="${e.id}">${esc(ERA_SHORT[e.id]||e.name)} · ${e.from}–${e.to}</option>`).join('');
  const topN=teamAgg().slice(0,16).map(m=>m.id);
  $('#theme').innerHTML=`<option value="champion">Champions of the tournament</option>`+topN.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join('');
  fillSeasons();
  const cov=A.coverage||{};
  $('#edition').innerHTML=`<span><span class="live"></span><b>${cov.tournaments}</b> tournaments</span><span><b>${fmt(cov.matches)}</b> matches</span><span><b>${fmt(cov.goals)}</b> goals</span><span><b>${fmt(cov.players)}</b> players</span><span>through <b>${A.lastYear.M}</b></span>`;
  $('#reading').open=false;
  const deep=readRoute();if(deep){tourStop();$('#family').value=state.sex;$('#eraSelect').value=state.era;fillSeasons();if(state.sex!=='M'){const topW=teamAgg().slice(0,16).map(m=>m.id);$('#theme').innerHTML=`<option value="champion">Champions of the tournament</option>`+topW.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join('');}}
  drawSources();applyTheme();drawRiver();drawGrid();render();lightsOut();if(deep&&(state.tab!=='season'||state.whole||state.era!=='all'))setTimeout(()=>$('#stage').scrollIntoView({behavior:'auto',block:'start'}),60);
  addEventListener('hashchange',()=>{if(/^#static-/.test(location.hash)){$('#reading').open=true;return;}routeLock=true;try{if(readRoute()){tourStop();$('#family').value=state.sex;$('#eraSelect').value=state.era;fillSeasons();applyTheme();drawRiver();drawGrid();render();}}finally{routeLock=false;}});
  $('#eraSelect').addEventListener('change',e=>setEra(e.target.value));
  $('#family').addEventListener('change',e=>{state.sex=e.target.value;relens();});
  $('#season').addEventListener('change',e=>{if(e.target.value==='era'){state.whole=true;applyTheme();drawRiver();if(state.tab!=='match')state.tab='season';go(state.tab,false);}else setSeason(+e.target.value,false);});
  $('#theme').addEventListener('change',applyTheme);
  $('#riverMetric').addEventListener('click',e=>{const b=e.target.closest('[data-metric]');if(!b)return;state.metric=b.dataset.metric;$$('#riverMetric button').forEach(x=>x.setAttribute('aria-pressed',x===b));riverModel=null;drawRiver();});
  $('#eraStrip').addEventListener('click',e=>{const s=e.target.closest('[data-era]');if(s)setEra(state.era===s.dataset.era?'all':s.dataset.era);});
  $('#eraStrip').addEventListener('pointerenter',()=>{tourPause();},{passive:true});$('#eraStrip').addEventListener('pointerleave',()=>{if(!tour.stopped)tourStart();},{passive:true});
  $('#eraStrip').addEventListener('mouseover',e=>{const s=e.target.closest('[data-era]');if(s&&!tour.stopped){drawEraStrip(s.dataset.era);}});
  if('IntersectionObserver' in window){new IntersectionObserver(en=>{tour.visible=en[0].isIntersecting;if(tour.visible)tourStart();else tourPause();},{threshold:.2}).observe($('#eraStrip'));}else{tour.visible=true;tourStart();}
  $('#gridSort').addEventListener('change',e=>{state.gridSort=e.target.value;drawGrid();});$('#gridFind').addEventListener('input',e=>{state.gridFind=e.target.value;drawGrid();});
  $('#circuits').addEventListener('click',e=>{const b=e.target.closest('[data-ground]');if(b){state.ground=b.dataset.ground;go('grounds',true);}});
  $('#worldMap').addEventListener('click',e=>{const g=e.target.closest('[data-host]');if(g){state.host=g.dataset.host;go('hosts',true);}});
  const clear=t=>{if(t==='players')state.player=null;if(t==='teams')state.team=null;if(t==='grounds')state.ground=null;if(t==='hosts')state.host=null;};
  $('#tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;clear(b.dataset.tab);go(b.dataset.tab,false);});
  $('#view').addEventListener('click',e=>{const a=e.target.closest('[data-match],[data-mstage],[data-player],[data-team],[data-ground],[data-host],[data-year],[data-tab]');if(!a)return;if(a.tagName==='A')e.preventDefault();
    if(a.dataset.match){openMatch(a.dataset.match,false);return;}
    if(a.dataset.mstage){state.mstage=a.dataset.mstage;state.match=null;go('match',false);return;}
    if(a.dataset.tab){clear(a.dataset.tab);go(a.dataset.tab,false);return;}
    if(a.dataset.year){const y=+a.dataset.year;if(a.dataset.sex&&a.dataset.sex!==state.sex){state.sex=a.dataset.sex;$('#family').value=state.sex;relens(false);}if(!byYear[y])return;setSeason(y,false);return;}
    if(a.dataset.player){state.player=a.dataset.player;go('players',false);return;}
    if(a.dataset.team){state.team=a.dataset.team;go('teams',false);return;}
    if(a.dataset.ground){state.ground=a.dataset.ground;go('grounds',false);return;}
    if(a.dataset.host){state.host=a.dataset.host;go('hosts',false);return;}});
  addEventListener('resize',()=>{clearTimeout(window.__rz);window.__rz=setTimeout(()=>{drawRiver();if(['season','duel','records','hosts'].includes(state.tab))render();},150);});
}
StageNav.mount({seasons:()=>eraSeasons().map(s=>({year:s.year,cancelled:false})),year:()=>state.year,whole:()=>state.whole,tab:()=>state.tab,setYear:y=>{if(byYear[y])setSeason(y,false);},unitTab:'match',unitName:'Match',units:s=>{const t=byYear[s.year];return t?t.matches.map(m=>({key:m.id,label:`${stageLabel(m)} · ${m.home} ${scoreOf(m)} ${m.away}`})):[];},unit:()=>state.match,setUnit:k=>{openMatch(k,false);}});
StageSearch.mount({placeholder:'Find a player, a team, a ground, a match or a tournament',groups:[
  {kind:'Players',items:()=>{const n={};for(const m of MATCHES)for(const g of m.d.g)n[g[1]]=(n[g[1]]||0)+1;return Object.entries(PL).map(([id,p])=>({label:p.n,sub:p.b?p.b.slice(0,4):'',rank:(n[id]||0)*3+(p.t?.length||0),keys:[],open:()=>{if(p.w!==(state.sex==='W')){state.sex=p.w?'W':'M';$('#family').value=state.sex;relens(false);}state.player=id;go('players',false);}}));}},
  {kind:'Teams',items:()=>Object.keys(TEAMS).map(t=>({label:t,sub:TEAMS[t].code||'',rank:MATCHES.filter(m=>m.home===t||m.away===t).length,open:()=>{state.team=t;go('teams',false);}}))},
  {kind:'Grounds',items:()=>Object.entries(ST).map(([id,s])=>({label:s.name,sub:`${s.city}${s.country?', '+s.country:''}`,rank:MATCHES.filter(m=>m.stadium===id).length,keys:[s.city],open:()=>{state.ground=id;go('grounds',false);}}))},
  {kind:'Matches',items:()=>MATCHES.filter(m=>m.ko).map(m=>({label:`${m.home} ${scoreOf(m)} ${m.away}`,sub:`${m.y} · ${stageLabel(m)}`,rank:STAGE_RANK[m.stage],keys:[String(m.y)],open:()=>openMatch(m.id,false)}))},
  {kind:'Tournaments',items:()=>TOUR.map(t=>({label:`${t.year} ${t.hosts.join(' / ')}`,sub:SEX_NAME[t.sex],keys:['world cup',String(t.year)],open:()=>{if(t.sex!==state.sex){state.sex=t.sex;$('#family').value=state.sex;relens(false);}setSeason(t.year,false);}}))}]});
init();
