/* ---------- Stage chrome: tabs, era strip, era context ---------- */
const TABS=[['matches','Matches'],['rivals','Rivalries'],['cups','World Cups'],['players','Players'],['grounds','Grounds'],['coaches','Coaches'],['records','Records'],['carpet','Carpet'],['heat','Heatmap'],['duel','Duel']];
function drawTabs(){$('#tabs').innerHTML=TABS.map(([id,l])=>`<button type="button" role="tab" data-tab="${id}" aria-pressed="${state.tab===id}">${l}</button>`).join('');$('#stageStatus').textContent=`${T().name} · ${eraLabel()}`;}
function drawEraStrip(preview){const strip=$('#eraStrip');if(!strip.children.length)strip.innerHTML=ERA_LIST.map(e=>`<button type="button" style="--w:${e.to-e.from+1}" data-era="${e.id}" title="${esc(e.label)}" aria-label="${esc(e.label)}"></button>`).join('');
  for(const b of strip.children){b.classList.toggle('on',state.era===b.dataset.era);b.classList.toggle('demo',preview===b.dataset.era);}
  const e=preview?ERAS.find(x=>x.id===preview):era();const ms=M().filter(m=>m.year>=e.from&&m.year<=e.to&&inScope(m));const a=aggregate(ms);
  $('#eraCaption').innerHTML=`<span><b>${esc(e.name)}</b> · ${e.from}–${e.to}</span><span class="dim">${state.era===e.id&&e.id!=='all'?'Lens on · click again to release':'Click a segment to focus the whole page on that era'}</span>`;
  $('#eraContext').innerHTML=`<div><p class="eyebrow">${state.era===e.id&&e.id!=='all'?'Historical lens':'Era'} · ${e.from}–${e.to}</p><h3>${esc(e.name)}</h3><p>${esc(e.text)} ${esc(T().name)} played ${ms.length} matches in these years${ms.length?`, winning ${a.w}, losing ${a.l}${a.d?' and drawing '+a.d:''}`:''}.</p></div><div class="rec">${ms.length?recStr(a):'—'}<small>${T().code} won–lost${a.d?'–drawn':''} · ${pct(a.rate)}</small></div>`;}
const tour={i:-1,timer:null,visible:false,stopped:RM};
function tourStep(){if(tour.stopped||!tour.visible)return;tour.i=(tour.i+1)%ERA_LIST.length;const ctx=$('#eraContext');ctx.classList.add('swap');setTimeout(()=>{if(tour.stopped)return;drawEraStrip(ERA_LIST[tour.i].id);ctx.classList.remove('swap');},260);tour.timer=setTimeout(tourStep,4200);}
function tourStart(){if(tour.stopped||tour.timer)return;tour.timer=setTimeout(tourStep,1800);}
function tourPause(){clearTimeout(tour.timer);tour.timer=null;}
function tourStop(){if(tour.stopped)return;tour.stopped=true;tourPause();$('#eraContext').classList.remove('swap');drawEraStrip();}

/* ---------- shared bits ---------- */
const kpi=(l,v,s='')=>`<div class="kpi"><span>${l}</span><b>${v}</b>${s?`<small>${s}</small>`:''}</div>`;
function recordKpis(ms){const a=aggregate(ms);return `<div class="kpis">${kpi('Matches',fmt(a.n),`${a.w} won · ${a.l} lost · ${a.d} drawn`)}${kpi('Win rate',pct(a.rate),'wins ÷ all matches, draws included')}${kpi('Points for',fmt(a.pf),`${fmt(a.pa)} conceded${a.np<a.n?' · goals-era scores excluded':''}`)}${kpi('Average margin',a.margin==null?'—':(a.margin>0?'+':'')+a.margin.toFixed(1),'per match, points era only')}</div>`;}
function mrow(m,i){return `<button type="button" class="mrow" data-match="${m.archiveId}" style="--i:${i};--rc:${m.res==='W'?'var(--win)':m.res==='L'?'var(--loss)':'var(--draw)'}"><span class="d">${esc(m.date)}<small>${esc(m.competitionRaw||m.competition)}${m.stage?' · '+esc(m.stage):''}</small></span><span class="t">${esc(T().name)}</span><span class="sc">${m.pf}<i>–</i>${m.pa}</span><span class="t r">${esc(m.opponent)}</span><span class="pill ${m.res}">${m.res}</span><span class="v" style="grid-column:1/-1">${esc(m.venue)}${m.city?' · '+esc(m.city):''} · ${m.location.toLowerCase()}${m.historical?' · legacy fixture':''}${m.dateUncertain?' · date flagged':''}</span></button>`;}
function matchList(ms,limit=40){return `<div class="mlist">${ms.slice(0,limit).map(mrow).join('')}</div>${ms.length>limit?`<p class="small dim" style="margin-top:10px">Showing ${limit} of ${ms.length}. <button type="button" class="btn" data-more="1">Show more</button></p>`:''}`;}
function splitBar(a){const n=a.n||1;return `<div class="split"><i style="--c:var(--win);--w:${100*a.w/n}%" title="${a.w} won"></i><i style="--c:var(--draw);--w:${100*a.d/n}%" title="${a.d} drawn"></i><i style="--c:var(--loss);--w:${100*a.l/n}%" title="${a.l} lost"></i></div>`;}

/* ---------- Match sheet ---------- */
function openMatch(archiveId){state.match=archiveId;go('matches',true);}
function matchSheet(m){const t=T();const home=m.isHome;const o=home?0:6,a=home?6:0;const sc=m.scoring;
  const tally=sc?`<div class="tally"><div class="side">${'<i class="try" style="--c:'+t.accent+'"></i>'.repeat(sc[o])}${'<i class="pt" style="--c:'+t.accent+'"></i>'.repeat(sc[o+5])}${'<i class="c" style="--c:'+t.accent+'"></i>'.repeat(sc[o+1])}${'<i class="p" style="--c:'+t.accent+'"></i>'.repeat(sc[o+2])}${'<i class="g" style="--c:'+t.accent+'"></i>'.repeat(sc[o+3])}</div><div class="lbl">tries · conversions · penalties · drops</div><div class="side r">${'<i class="try" style="--c:'+colourOf(m.opponent)+'"></i>'.repeat(sc[a])}${'<i class="pt" style="--c:'+colourOf(m.opponent)+'"></i>'.repeat(sc[a+5])}${'<i class="c" style="--c:'+colourOf(m.opponent)+'"></i>'.repeat(sc[a+1])}${'<i class="p" style="--c:'+colourOf(m.opponent)+'"></i>'.repeat(sc[a+2])}${'<i class="g" style="--c:'+colourOf(m.opponent)+'"></i>'.repeat(sc[a+3])}</div></div>
  <div class="tablewrap" style="margin-top:12px"><table><tr><th>Recorded scoring</th><th class="num">${esc(t.code)}</th><th class="num">${esc(m.opponent)}</th></tr>${[['Tries',0],['Conversions',1],['Penalty goals',2],['Drop goals',3],['Penalty tries',5]].map(([l,k])=>`<tr><td>${l}</td><td class="num">${sc[o+k]}</td><td class="num">${sc[a+k]}</td></tr>`).join('')}</table></div><p class="small dim" style="margin:8px 0 0">Circles are tries (hollow: penalty tries), small squares conversions, tall bars penalties, diamonds drop goals. The breakdown reconciles with the score under the scoring values of the day.</p>`:`<p class="small dim" style="margin-top:14px">No scoring breakdown is recorded for this match.</p>`;
  const appearances=P().filter(p=>p.history&&p.history.some(h=>h.match===M().indexOf(m)||h.date===m.date&&h.opponent===m.opponent));
  const players=appearances.length?`<div class="h3" style="margin-top:18px"><span>Recorded appearances</span><small>${appearances.length} captured career histories</small></div><div class="chiplist">${appearances.map(p=>{const h=p.history.find(h=>h.date===m.date);return `<button type="button" class="chip" data-player="${esc(p.id)}"><i style="--c:${t.accent}"></i>${esc(p.name)}<span class="dim"> ${esc(h?.position||'')}${h?.tries?' · '+h.tries+' T':''}</span></button>`;}).join('')}</div>`:'';
  const coach=COACHES().find(c=>c.matchIds.includes(m.archiveId));
  return `<div class="sheet"><div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;align-items:center"><p class="eyebrow">${day(m.date)} · ${esc(m.competitionRaw||m.competition)}${m.stage?' · '+esc(m.stage):''}</p><button type="button" class="btn" data-close="1">Close ×</button></div>
  <div class="score"><div class="n">${esc(t.name)}</div><div class="s">${m.pf}<i>–</i>${m.pa}</div><div class="n r">${esc(m.opponent)}</div></div>
  <div style="text-align:center"><span class="pill ${m.res}" style="font-size:12px">${m.res==='W'?'Won':m.res==='L'?'Lost':'Drawn'}${m.scoreUnit!=='goals'?` by ${Math.abs(m.pf-m.pa)}`:''}</span></div>
  ${pitchSvg(m)}
  ${tally}
  <div class="infogrid"><div><small>Ground</small><b><a href="#" data-ground="${esc(m.stadium)}" style="color:inherit;text-decoration:none">${esc(m.venue)} ↗</a></b></div><div><small>City / country</small><b>${esc(m.city||'Unknown')} · ${esc(m.country||'Unknown')}</b></div><div><small>Setting for ${esc(t.code)}</small><b>${m.location}</b></div><div><small>Recorded competition</small><b>${esc(m.competitionRaw||'Not classified')}</b></div>${coach?`<div><small>Head coach</small><b><a href="#" data-coach="${esc(coach.id)}" style="color:inherit;text-decoration:none">${esc(coach.name)} ↗</a></b></div>`:''}<div><small>Source id</small><b class="mono small">${esc(m.sourceId)}</b></div></div>
  ${m.scoreUnit==='goals'?'<div class="note">This pre-1885 score counts goals, not modern points. It contributes to results but is excluded from point sums and margins.</div>':''}${m.historical?'<div class="note">Recorded as a historical / legacy capped fixture; recognition differs between unions.</div>':''}${m.notes?.length?m.notes.map(n=>`<div class="note">${esc(n)}</div>`).join(''):''}
  ${players}
  <p class="small dim" style="margin-top:14px">Sources: ${m.sources.map(s=>`<a href="${esc(s)}" target="_blank" rel="noopener">${esc(new URL(s).hostname)} ↗</a>`).join(' · ')}</p></div>`;}

/* ---------- Matches ---------- */
function matchesView(){let ms=lensMatches();const q=state.q.trim().toLowerCase();
  if(q)ms=ms.filter(m=>(m.opponent+' '+m.venue+' '+(m.city||'')+' '+(m.country||'')+' '+(m.competitionRaw||'')+' '+m.competition+' '+m.year).toLowerCase().includes(q));
  if(state.result!=='all')ms=ms.filter(m=>m.res===state.result);if(state.loc!=='all')ms=ms.filter(m=>m.location===state.loc);
  const comps=[...new Set(lensMatches().map(m=>m.competition))].sort();if(state.comp&&state.comp!=='all')ms=ms.filter(m=>m.competition===state.comp);
  const sorted=[...ms];if(state.sort==='newest')sorted.reverse();else if(state.sort==='margin')sorted.sort((a,b)=>(b.pf-b.pa)-(a.pf-a.pa));else if(state.sort==='points')sorted.sort((a,b)=>b.pf-a.pf);
  const sheet=state.match!=null?(()=>{const m=M().find(x=>x.archiveId===state.match);return m?matchSheet(m):'';})():'';
  $('#view').innerHTML=`${sheet}<div class="h3" style="margin-top:${sheet?0:22}px"><span>Match centre · ${esc(eraLabel())}</span><small>${ms.length} of ${lensMatches().length} matches</small></div>${recordKpis(ms)}
  <div class="toolrow" style="margin-top:16px"><input type="search" id="q" placeholder="Opponent, ground, city, competition, year" value="${esc(state.q)}" aria-label="Search matches" style="min-width:260px"><select id="fRes" aria-label="Result"><option value="all">Any result</option><option value="W" ${state.result==='W'?'selected':''}>Won</option><option value="L" ${state.result==='L'?'selected':''}>Lost</option><option value="D" ${state.result==='D'?'selected':''}>Drawn</option></select><select id="fLoc" aria-label="Location"><option value="all">Anywhere</option>${['Home','Away','Neutral','Unknown'].map(l=>`<option ${state.loc===l?'selected':''}>${l}</option>`).join('')}</select><select id="fComp" aria-label="Competition"><option value="all">All competitions</option>${comps.map(c=>`<option ${state.comp===c?'selected':''}>${esc(c)}</option>`).join('')}</select><select id="fSort" aria-label="Sort"><option value="newest" ${state.sort==='newest'?'selected':''}>Newest first</option><option value="oldest" ${state.sort==='oldest'?'selected':''}>Oldest first</option><option value="margin" ${state.sort==='margin'?'selected':''}>Biggest margin</option><option value="points" ${state.sort==='points'?'selected':''}>Most points scored</option></select></div>
  ${sorted.length?matchList(sorted,(state.page+1)*40):'<p class="muted">No matches fit those filters.</p>'}`;}

/* ---------- Rivalries ---------- */
function rivalsView(){const ms=lensMatches();if(state.opp)return rivalView(state.opp);const by={};for(const m of ms){(by[m.opponent]||(by[m.opponent]=[])).push(m);}
  const rows=Object.entries(by).map(([o,list])=>({o,a:aggregate(list),first:list[0].year,last:list[list.length-1].year})).sort((p,q)=>q.a.n-p.a.n);
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Rivalries · ${esc(eraLabel())}</span><small>${rows.length} opponents · bars split won / drawn / lost</small></div><div class="board">${rows.map((r,i)=>`<button type="button" class="bar" data-opp="${esc(r.o)}" style="--i:${i}"><span class="rk">${i+1}</span><span><span class="lab"><span><i class="dot" style="--c:${colourOf(r.o)}"></i>${esc(r.o)}<small> ${r.first}–${r.last}</small></span><small>${r.a.w}–${r.a.l}${r.a.d?'–'+r.a.d:''} · ${pct(r.a.rate)}</small></span>${splitBar(r.a)}</span><span class="val">${r.a.n}</span></button>`).join('')}</div>`;}
function rivalView(o){const ms=lensMatches().filter(m=>m.opponent===o);const back=`<button type="button" class="btn" data-tab="rivals" data-clear="opp">← All rivalries</button>`;if(!ms.length){$('#view').innerHTML=`<div style="margin-top:22px">${back}</div><p class="muted" style="margin-top:16px">No meetings with ${esc(o)} in ${esc(eraLabel())}.</p>`;return;}
  const a=aggregate(ms);let best=null,worst=null,streak=0,bestStreak=0,cur='';for(const m of ms){if(m.scoreUnit!=='goals'){if(!best||m.pf-m.pa>best.pf-best.pa)best=m;if(!worst||m.pf-m.pa<worst.pf-worst.pa)worst=m;}if(m.res==='W'){streak=cur==='W'?streak+1:1;cur='W';}else{cur=m.res;streak=0;}bestStreak=Math.max(bestStreak,streak);}
  const venues=Object.entries(ms.reduce((v,m)=>{v[m.venue]=(v[m.venue]||0)+1;return v;},{})).sort((p,q)=>q[1]-p[1]).slice(0,6);
  const byDecade={};for(const m of ms){const d=Math.floor(m.year/10)*10;(byDecade[d]||(byDecade[d]=[])).push(m);}
  $('#view').innerHTML=`<div style="margin-top:22px;display:flex;gap:10px;flex-wrap:wrap;align-items:center">${back}<span class="small muted">${esc(eraLabel())}</span></div>
  <div class="duel-head" style="margin-top:18px;--c:${colourOf(o)}"><div class="n" style="color:var(--accent)">${esc(T().name)}</div><div class="rec"><span class="W">${a.w}</span><i>·</i><span class="D">${a.d}</span><i>·</i><span class="L">${a.l}</span></div><div class="n" style="color:${colourOf(o)}">${esc(o)}</div></div>
  <p class="small dim" style="text-align:center;margin:6px 0 16px">won · drawn · lost, from ${esc(T().code)}'s side · ${ms.length} meetings · ${ms[0].year}–${ms[ms.length-1].year}</p>
  ${recordKpis(ms)}
  <div class="kpis" style="margin-top:10px">${best?kpi('Best result','+'+(best.pf-best.pa),`${best.pf}–${best.pa} · ${best.year} · ${esc(best.venue)}`):''}${worst?kpi('Heaviest defeat',(worst.pf-worst.pa),`${worst.pf}–${worst.pa} · ${worst.year} · ${esc(worst.venue)}`):''}${kpi('Longest winning run',bestStreak,'consecutive wins in this fixture')}${kpi('Tries',ms.some(m=>m.tries!=null)?fmt(ms.reduce((s,m)=>s+(m.tries||0),0))+' – '+fmt(ms.reduce((s,m)=>s+(m.triesAgainst||0),0)):'—','where a breakdown is recorded')}</div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Who leads, meeting by meeting</span><small>cumulative wins minus losses from ${esc(T().code)}'s side</small></div>${swingChart(ms,o)}<div class="h3" style="margin-top:14px"><span>Every result</span><small>oldest to newest · click a tick</small></div>${formStrip(ms)}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Decade by decade</span></div><div class="board">${Object.entries(byDecade).map(([d,l],i)=>{const x=aggregate(l);return `<div class="bar" style="--i:${i};cursor:default"><span class="rk">${d}s</span><span><span class="lab"><span>${x.n} match${x.n===1?'':'es'}</span><small>${x.w}–${x.l}${x.d?'–'+x.d:''}</small></span>${splitBar(x)}</span><span class="val">${x.rate==null?'—':Math.round(x.rate)+'%'}</span></div>`;}).join('')}</div></div>
  <div class="panel"><div class="h3"><span>Where they meet</span></div><div class="board">${venues.map(([v,n],i)=>`<div class="bar" style="--i:${i};cursor:default"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(v)}</span></span><span class="trk"><i style="--c:var(--accent);--w:${100*n/venues[0][1]}%"></i></span></span><span class="val">${n}</span></div>`).join('')}</div></div></div>
  <div class="h3" style="margin-top:22px"><span>Every meeting</span><small>newest first</small></div>${matchList([...ms].reverse(),(state.page+1)*40)}`;}

/* ---------- World Cups ---------- */
function cupsView(){const t=T();const all=M().filter(m=>m.worldcup);const years=[...new Set(all.map(m=>m.worldcup))].sort();const inLens=years.filter(y=>{const e=era();return y>=e.from&&y<=e.to;});
  if(!inLens.length){$('#view').innerHTML=`<p class="muted" style="margin-top:22px">No World Cup campaign falls inside ${esc(eraLabel())}.</p>`;return;}
  if(!inLens.includes(state.cup))state.cup=inLens[inLens.length-1];
  const finish=y=>{const ms=all.filter(m=>m.worldcup===y);const last=ms[ms.length-1];return last.stage==='Final'?(last.res==='W'?'World champions':'Runners-up'):last.stage==='Bronze final'?(last.res==='W'?'Third place':'Fourth place'):last.stage==='Quarter-final'?'Quarter-finalists':last.stage==='Quarter-final playoff'?'Quarter-final playoff':'Pool stage';};
  const ms=all.filter(m=>m.worldcup===state.cup);const extra=t.name==='South Africa'?A.saWorldcups.find(w=>w.year===state.cup):null;const won=t.titles.includes(state.cup);
  const cards=`<div class="cups">${years.map(y=>`<button type="button" class="cup${t.titles.includes(y)?' win':''}${y===state.cup?' on':''}${inLens.includes(y)?'':' dim'}" data-cup="${y}" ${inLens.includes(y)?'':'style="opacity:.4"'}>${t.titles.includes(y)?'<span class="star">★</span>':''}<b>${y}</b><small>${finish(y)}</small></button>`).join('')}</div>`;
  const path=`<div class="path" style="margin-top:18px">${ms.map(m=>`<button type="button" class="step${m.stage&&m.stage!=='Pool match'?' ko':''}" data-match="${m.archiveId}" style="--rc:${m.res==='W'?'var(--win)':m.res==='L'?'var(--loss)':'var(--draw)'}"><div class="st">${esc(m.stage||'Pool')} · ${esc(m.date.slice(5))}</div><div class="o">v ${esc(m.opponent)}</div><div class="s"><span class="${m.res}">${m.pf}–${m.pa}</span></div><div class="st">${esc(m.city||m.venue)}</div></button>`).join('')}</div>`;
  const a=aggregate(ms);
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Rugby World Cup · ${esc(t.name)}</span><small>${years.length} campaigns · ${t.titles.length} title${t.titles.length===1?'':'s'}</small></div>${cards}
  <div class="panel" style="margin-top:20px;${won?'border-color:var(--gold)':''}"><div class="h3"><span>${state.cup} · ${finish(state.cup)}${won?' ★':''}</span><small>${a.w} won · ${a.l} lost${a.d?' · '+a.d+' drawn':''} · ${fmt(a.pf)}–${fmt(a.pa)} points</small></div>${extra?`<p class="muted" style="margin:0 0 6px">Captain <b style="color:var(--ink)">${esc(extra.captain)}</b> · Coach <b style="color:var(--ink)">${esc(extra.coach)}</b></p>`:''}${path}
  ${extra?.squad?.length?`<div class="h3" style="margin-top:14px"><span>Squad</span><small>${extra.squad.length} players · <a href="${esc(extra.source)}" target="_blank" rel="noopener">source ↗</a></small></div><div class="chiplist">${extra.squad.map(n=>{const p=P().find(p=>p.name===n);return p?`<button type="button" class="chip" data-player="${esc(p.id)}"><i style="--c:var(--accent)"></i>${esc(n)}</button>`:`<span class="chip"><i style="--c:var(--line2)"></i>${esc(n)}</span>`;}).join('')}</div>`:''}</div>
  <div class="h3" style="margin-top:22px"><span>All World Cup matches</span><small>${all.length} played</small></div><div class="tablewrap"><table><tr><th>Year</th><th>Stage</th><th>Opponent</th><th class="num">Score</th><th>Result</th><th>Venue</th></tr>${[...all].reverse().map(m=>`<tr><td><a href="#" data-match="${m.archiveId}" style="color:inherit">${m.worldcup}</a></td><td>${esc(m.stage||'')}</td><td><i class="dot" style="--c:${colourOf(m.opponent)}"></i>${esc(m.opponent)}</td><td class="num">${m.pf}–${m.pa}</td><td><span class="pill ${m.res}">${m.res}</span></td><td>${esc(m.venue)}, ${esc(m.city||m.country||'')}</td></tr>`).join('')}</table></div>`;}
