/* ---------- Players ---------- */
function playersView(){if(state.player)return playerView(state.player);const ps=P();const q=(state.pq||'').toLowerCase();const e=era();
  let list=ps.filter(p=>!q||p.name.toLowerCase().includes(q)||(p.position||'').toLowerCase().includes(q)).filter(p=>state.era==='all'||(p.startYear&&p.endYear&&p.endYear>=e.from&&p.startYear<=e.to));
  const k=state.playerSort;list.sort((a,b)=>(b[k]??-1)-(a[k]??-1)||(a.startYear||0)-(b.startYear||0));
  const y0=state.era==='all'?Math.min(...ps.map(p=>p.startYear||9999)):e.from,y1=state.era==='all'?2026:e.to;const span=Math.max(1,y1-y0);
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Players · ${esc(T().name)}</span><small>${list.length} of ${ps.length} career snapshots${state.era!=='all'?' active in '+esc(era().name.toLowerCase()):''}</small></div><div class="panel"><div class="toolrow"><input type="search" id="pq" placeholder="Name or position" value="${esc(state.pq||'')}" aria-label="Search players"><select id="pSort" aria-label="Sort players"><option value="caps" ${k==='caps'?'selected':''}>Most caps</option><option value="tries" ${k==='tries'?'selected':''}>Most tries</option><option value="points" ${k==='points'?'selected':''}>Most points</option><option value="startYear" ${k==='startYear'?'selected':''}>Debut year</option></select><span class="small muted">Bars are career spans; the number is ${k==='startYear'?'debut year':k}.</span></div>
  <div class="years-axis"><span>${y0}</span><span>${Math.round((y0+y1)/2)}</span><span>${y1}</span></div><div class="career">${list.slice(0,80).map(p=>{const s=Math.max(y0,p.startYear||y0),en=Math.min(y1,p.endYear||y1);return `<button type="button" class="crow" data-player="${esc(p.id)}"><span class="nm">${esc(p.name)}<small> ${esc(p.position||'')}</small></span><span class="span"><i style="--l:${100*(s-y0)/span}%;--w:${Math.max(.6,100*(en-s+1)/span)}%;--c:${p.history?.length?'var(--accent)':'var(--accent2)'}"></i></span><span class="caps">${k==='startYear'?(p.startYear||'—'):fmt(p[k])}</span></button>`;}).join('')}</div>${list.length>80?`<p class="small dim" style="margin-top:8px">Showing 80 of ${list.length}; search to narrow.</p>`:''}<p class="small dim" style="margin-top:10px">Green spans carry a captured appearance history; gold spans are published career snapshots only. Career snapshots can lag match results.</p></div>`;}
function playerView(id){const p=A.players.find(x=>x.id===id);const back=`<button type="button" class="btn" data-tab="players" data-clear="player">← All players</button>`;if(!p){$('#view').innerHTML=`<div style="margin-top:22px">${back}</div>`;return;}
  const hs=p.history||[];const ms=M();const byYear={},byOpp={};let tries=0;for(const h of hs){const y=yr(h.date);byYear[y]=(byYear[y]||0)+1;byOpp[h.opponent]=(byOpp[h.opponent]||0)+1;tries+=h.tries||0;}
  const years=Object.keys(byYear).map(Number);const maxY=Math.max(1,...Object.values(byYear));
  const results=hs.map(h=>{const m=ms[h.match];return m&&m.date===h.date?m:ms.find(x=>x.date===h.date&&x.opponent===h.opponent);}).filter(Boolean);const a=aggregate(results);
  $('#view').innerHTML=`<div style="margin-top:22px;display:flex;gap:10px;flex-wrap:wrap;align-items:center">${back}</div>
  <div class="sheet" style="margin-top:18px"><p class="eyebrow">${esc(p.position||'Player')} · ${esc(p.span||'')}${p.number?' · '+esc(T().code)+' No. '+esc(p.number):''}</p><h2 class="display" style="font-size:clamp(40px,6vw,84px);margin:6px 0 0;color:var(--accent)">${esc(p.name)}</h2><p class="muted" style="margin:6px 0 0">${p.dob?'born '+esc(p.dob):''}${p.birthplace?' · '+esc(p.birthplace):''}${p.first?' · debut '+day(p.first):''}${p.last?' · last '+day(p.last):''}</p>
  <div class="kpis" style="margin-top:18px">${kpi('Caps',fmt(p.caps),p.complete?'history reconciles to caps':hs.length?hs.length+' captured appearances':'published snapshot')}${kpi('Tries',fmt(p.tries),hs.length?tries+' in captured matches':'')}${kpi('Points',fmt(p.points))}${hs.length?kpi('Record when playing',recStr(a),pct(a.rate)+' win rate'):''}</div>
  ${hs.length?`<div class="h3" style="margin-top:18px"><span>Appearances by year</span></div><div style="display:flex;gap:3px;align-items:end;height:70px">${years.map(y=>`<div title="${y}: ${byYear[y]}" style="flex:1;background:var(--accent);height:${100*byYear[y]/maxY}%;border-radius:2px 2px 0 0;min-width:4px"></div>`).join('')}</div><div class="years-axis" style="margin-left:0"><span>${years[0]}</span><span>${years[years.length-1]}</span></div>
  <div class="h3" style="margin-top:14px"><span>Opponents faced</span></div><div class="chiplist">${Object.entries(byOpp).sort((a,b)=>b[1]-a[1]).map(([o,n])=>`<button type="button" class="chip" data-opp="${esc(o)}"><i style="--c:${colourOf(o)}"></i>${esc(o)} <span class="dim">${n}</span></button>`).join('')}</div>`:''}
  ${p.notes?.length?p.notes.map(n=>`<div class="note">${esc(n)}</div>`).join(''):''}
  <p class="small dim" style="margin-top:14px">Sources: ${(p.sources||[]).map(s=>`<a href="${esc(s)}" target="_blank" rel="noopener">${esc(new URL(s).hostname)} ↗</a>`).join(' · ')}</p></div>
  ${hs.length?`<div class="h3"><span>Every recorded appearance</span><small>newest first</small></div><div class="tablewrap"><table><tr><th>Date</th><th>Opponent</th><th>Position</th><th class="num">${esc(T().code)} – Opp.</th><th>Scoring</th></tr>${[...hs].reverse().map(h=>{const m=results.find(x=>x.date===h.date);return `<tr><td>${m?`<a href="#" data-match="${m.archiveId}" style="color:inherit">${esc(h.date)}</a>`:esc(h.date)}</td><td>${esc(h.opponent)}</td><td>${esc(h.position)}</td><td class="num">${m?`<span class="${m.res}">${m.pf}–${m.pa}</span>`:'—'}</td><td>${esc(h.scoring)||'—'}</td></tr>`;}).join('')}</table></div>`:''}`;}

/* ---------- Grounds ---------- */
function groundsView(){if(state.ground)return groundView(state.ground);const ms=lensMatches();const by={};for(const m of ms){const g=by[m.stadium]||(by[m.stadium]={id:m.stadium,name:m.venue,city:m.city,country:m.country,list:[]});g.list.push(m);}
  const rows=Object.values(by).map(g=>({...g,a:aggregate(g.list)})).sort((p,q)=>q.a.n-p.a.n);
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Grounds · ${esc(eraLabel())}</span><small>${rows.length} venues</small></div><div class="board">${rows.slice(0,60).map((g,i)=>`<button type="button" class="bar" data-ground="${esc(g.id)}" style="--i:${i}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(g.name)}<small> ${esc(g.city||'')}${g.country?', '+esc(g.country):''}</small></span><small>${g.a.w}–${g.a.l}${g.a.d?'–'+g.a.d:''} · ${pct(g.a.rate)}</small></span>${splitBar(g.a)}</span><span class="val">${g.a.n}</span></button>`).join('')}</div>${rows.length>60?`<p class="small dim" style="margin-top:8px">Showing 60 of ${rows.length} grounds.</p>`:''}`;}
function groundView(id){const ms=lensMatches().filter(m=>m.stadium===id);const back=`<button type="button" class="btn" data-tab="grounds" data-clear="ground">← All grounds</button>`;if(!ms.length){$('#view').innerHTML=`<div style="margin-top:22px">${back}</div><p class="muted" style="margin-top:16px">No matches at this ground in ${esc(eraLabel())}.</p>`;return;}
  const g=ms[0];const a=aggregate(ms);const opps=Object.entries(ms.reduce((o,m)=>{o[m.opponent]=(o[m.opponent]||0)+1;return o;},{})).sort((p,q)=>q[1]-p[1]);
  $('#view').innerHTML=`<div style="margin-top:22px">${back}</div><div class="sheet" style="margin-top:18px"><p class="eyebrow">Ground · ${esc(g.city||'')}${g.country?', '+esc(g.country):''} · ${ms[0].location.toLowerCase()} for ${esc(T().code)}</p><h2 class="display" style="font-size:clamp(36px,5.6vw,76px);margin:6px 0 0">${esc(g.venue)}</h2><div class="kpis" style="margin-top:18px">${kpi('Matches',ms.length,`${ms[0].year}–${ms[ms.length-1].year}`)}${kpi('Record',recStr(a),pct(a.rate)+' win rate')}${kpi('Points',fmt(a.pf)+'–'+fmt(a.pa),'for – against')}${kpi('Opponents',opps.length)}</div><div class="h3" style="margin-top:18px"><span>Opponents here</span></div><div class="chiplist">${opps.map(([o,n])=>`<button type="button" class="chip" data-opp="${esc(o)}"><i style="--c:${colourOf(o)}"></i>${esc(o)} <span class="dim">${n}</span></button>`).join('')}</div></div><div class="h3"><span>Every match here</span></div>${matchList([...ms].reverse(),(state.page+1)*40)}`;}

/* ---------- Coaches ---------- */
function coachesView(){if(state.coach)return coachView(state.coach);const cs=COACHES();const e=era();const list=cs.filter(c=>c.startYear&&c.endYear>=e.from&&c.startYear<=e.to).sort((a,b)=>a.startYear-b.startYear);const cov=A.coachCoverage[state.team];
  const y0=state.era==='all'?(cov?.firstYear||Math.min(...list.map(c=>c.startYear))):e.from,y1=state.era==='all'?2026:e.to;const span=Math.max(1,y1-y0+1);
  const linkedRate=c=>{const r=c.linkedRecord||c.reported;return r&&r.n?100*r.w/r.n:null;};
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Coaches · ${esc(T().name)}</span><small>${list.length} tenures · colour = win rate</small></div><div class="panel"><div class="years-axis"><span>${y0}</span><span>${Math.round((y0+y1)/2)}</span><span>${y1}</span></div><div class="gantt">${list.map(c=>{const r=linkedRate(c);const col=r==null?'var(--line2)':mixHex('#4fd28f','#e6605c',Math.max(0,Math.min(1,(r-30)/50)));return `<button type="button" class="grow" data-coach="${esc(c.id)}"><span class="nm">${esc(c.name)}</span><span class="lane">${c.periods.map(([s,en])=>`<i style="--l:${100*(Math.max(s,y0)-y0)/span}%;--w:${Math.max(.8,100*(Math.min(en,y1)-Math.max(s,y0)+1)/span)}%;--c:${col}" title="${s}–${en}"></i>`).join('')}</span><span class="rt">${r==null?'—':Math.round(r)+'%'}</span></button>`;}).join('')}</div><p class="small dim" style="margin-top:12px">${esc(cov?.note||'')} Win rate uses the linked match record where reconciled, otherwise the published record.</p></div>`;}
function coachView(id){const c=A.coaches.find(x=>x.id===id);const back=`<button type="button" class="btn" data-tab="coaches" data-clear="coach">← All coaches</button>`;if(!c){$('#view').innerHTML=`<div style="margin-top:22px">${back}</div>`;return;}
  const ms=M().filter(m=>c.matchIds.includes(m.archiveId));const a=aggregate(ms);const rep=c.reported;
  let run=0,best=0,unb=0,bestUnb=0;for(const m of ms){run=m.res==='W'?run+1:0;best=Math.max(best,run);unb=m.res==='L'?0:unb+1;bestUnb=Math.max(bestUnb,unb);}
  const opps=Object.entries(ms.reduce((o,m)=>{(o[m.opponent]||(o[m.opponent]=[])).push(m);return o;},{})).map(([o,l])=>({o,a:aggregate(l)})).sort((p,q)=>q.a.n-p.a.n);
  $('#view').innerHTML=`<div style="margin-top:22px">${back}</div><div class="sheet" style="margin-top:18px"><p class="eyebrow">${esc(c.role)} · ${esc(c.tenure)} · ${esc(c.method)}</p><h2 class="display" style="font-size:clamp(40px,6vw,84px);margin:6px 0 0;color:var(--accent)">${esc(c.name)}</h2>
  <div class="kpis" style="margin-top:18px">${rep?kpi('Published record',`${rep.w}–${rep.l}${rep.d?'–'+rep.d:''}`,`${rep.n} matches · ${esc(c.snapshotDate||'')}`):''}${ms.length?kpi('Linked record',recStr(a),`${ms.length} archive matches · ${pct(a.rate)}`):kpi('Linked record','—','no match linkage captured')}${ms.length?kpi('Points',fmt(a.pf)+'–'+fmt(a.pa),'for – against'):''}${ms.length?kpi('Best run',best+' wins',bestUnb+' unbeaten'):''}</div>
  ${c.reconciles===false?'<div class="note">The linked archive record does not reconcile exactly with the published snapshot; both are shown.</div>':''}${c.notes?.length?c.notes.map(n=>`<div class="note">${esc(n)}</div>`).join(''):''}
  ${ms.length?`<div class="h3" style="margin-top:18px"><span>Every match, oldest to newest</span></div>${formStrip(ms)}`:''}
  ${opps.length?`<div class="h3" style="margin-top:18px"><span>Against each opponent</span></div><div class="board">${opps.slice(0,12).map((r,i)=>`<button type="button" class="bar" data-opp="${esc(r.o)}" style="--i:${i}"><span class="rk">${i+1}</span><span><span class="lab"><span><i class="dot" style="--c:${colourOf(r.o)}"></i>${esc(r.o)}</span><small>${recStr(r.a)}</small></span>${splitBar(r.a)}</span><span class="val">${r.a.n}</span></button>`).join('')}</div>`:''}
  <p class="small dim" style="margin-top:14px">Sources: ${c.sources.map(s=>`<a href="${esc(s)}" target="_blank" rel="noopener">${esc(new URL(s).hostname)} ↗</a>`).join(' · ')}</p></div>${ms.length?`<div class="h3"><span>Matches under ${esc(c.name.split(' ').pop())}</span><small>newest first</small></div>${matchList([...ms].reverse(),(state.page+1)*40)}`:''}`;}

/* ---------- Records ---------- */
function recordsView(){const ms=lensMatches();const pts=ms.filter(m=>m.scoreUnit!=='goals');const a=aggregate(ms);
  const top=(list,k,n=5)=>[...list].sort(k).slice(0,n);
  const biggest=top(pts,(x,y)=>(y.pf-y.pa)-(x.pf-x.pa)),heaviest=top(pts,(x,y)=>(x.pf-x.pa)-(y.pf-y.pa)),highest=top(pts,(x,y)=>(y.pf+y.pa)-(x.pf+x.pa)),mostPts=top(pts,(x,y)=>y.pf-x.pf),mostTries=top(ms.filter(m=>m.tries!=null),(x,y)=>y.tries-x.tries);
  let run=0,best=null,cur=[];let unb=[],bestUnb=null;for(const m of ms){if(m.res==='W'){cur.push(m);if(!best||cur.length>best.length)best=[...cur];}else cur=[];if(m.res!=='L'){unb.push(m);if(!bestUnb||unb.length>bestUnb.length)bestUnb=[...unb];}else unb=[];}
  const byDecade={};for(const m of ms){const d=Math.floor(m.year/10)*10;(byDecade[d]||(byDecade[d]=[])).push(m);}
  const nations=TEN.map(n=>{const l=perspective(n).filter(m=>inEra(m)&&inScope(m));return {n,a:aggregate(l)};}).sort((p,q)=>(q.a.rate||0)-(p.a.rate||0));
  const list=(title,arr,f)=>`<div class="panel"><div class="h3"><span>${title}</span></div><div class="tablewrap"><table>${arr.map(m=>`<tr><td><a href="#" data-match="${m.archiveId}" style="color:inherit">${m.year}</a></td><td><i class="dot" style="--c:${colourOf(m.opponent)}"></i>${esc(m.opponent)}</td><td class="num"><span class="${m.res}">${m.pf}–${m.pa}</span></td><td class="num"><b>${f(m)}</b></td></tr>`).join('')||'<tr><td class="muted">—</td></tr>'}</table></div></div>`;
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Records · ${esc(T().name)} · ${esc(eraLabel())}</span><small>${ms.length} matches</small></div>${recordKpis(ms)}
  <div class="kpis" style="margin-top:10px">${best?kpi('Longest winning run',best.length,`${best[0].year}–${best[best.length-1].year}`):''}${bestUnb?kpi('Longest unbeaten run',bestUnb.length,`${bestUnb[0].year}–${bestUnb[bestUnb.length-1].year}`):''}${kpi('Home record',(x=>recStr(x))(aggregate(ms.filter(m=>m.location==='Home'))),pct(aggregate(ms.filter(m=>m.location==='Home')).rate)+' at home')}${kpi('Away record',(x=>recStr(x))(aggregate(ms.filter(m=>m.location==='Away'))),pct(aggregate(ms.filter(m=>m.location==='Away')).rate)+' away')}${kpi('Tries scored',ms.some(m=>m.tries!=null)?fmt(ms.reduce((s,m)=>s+(m.tries||0),0)):'—',`${ms.filter(m=>m.tries!=null).length} matches with a breakdown`)}</div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Every result, oldest to newest</span><small>${ms.length} ticks · green won · red lost · grey drawn · click one</small></div>${formStrip(ms)}</div>
  <div class="three" style="margin-top:20px">${list('Biggest wins',biggest,m=>'+'+(m.pf-m.pa))}${list('Heaviest defeats',heaviest,m=>m.pf-m.pa)}${list('Highest-scoring matches',highest,m=>m.pf+m.pa+' pts')}${list('Most points scored',mostPts,m=>m.pf)}${list('Most tries',mostTries,m=>m.tries+' T')}<div class="panel"><div class="h3"><span>Decade by decade</span></div><div class="board">${Object.entries(byDecade).map(([d,l],i)=>{const x=aggregate(l);return `<div class="bar" style="--i:${i};cursor:default"><span class="rk">${d}s</span><span><span class="lab"><span>${x.n} matches</span><small>${recStr(x)}</small></span>${splitBar(x)}</span><span class="val">${Math.round(x.rate)}%</span></div>`;}).join('')}</div></div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>The ten nations in this lens</span><small>each from its own side · draws stay in the denominator</small></div><div class="board">${nations.map((r,i)=>`<button type="button" class="bar" data-team="${esc(r.n)}" style="--i:${i}"><span class="rk">${i+1}</span><span><span class="lab"><span><i class="dot" style="--c:${colourOf(r.n)}"></i>${esc(r.n)}${r.n===state.team?' <small>· your colours</small>':''}</span><small>${r.a.n} matches · ${recStr(r.a)}</small></span>${splitBar(r.a)}</span><span class="val">${r.a.rate==null?'—':r.a.rate.toFixed(1)+'%'}</span></button>`).join('')}</div></div>`;}

/* ---------- Heatmap ---------- */
function heatView(){const ms=lensMatches();const e=era();const step=e.to-e.from>60?10:e.to-e.from>25?5:1;const cols=[];for(let y=Math.floor(e.from/step)*step;y<=e.to;y+=step)cols.push(y);
  const key=m=>state.heatBy==='opponent'?m.opponent:state.heatBy==='ground'?m.venue:m.competition;const rows={};for(const m of ms){const r=rows[key(m)]||(rows[key(m)]={k:key(m),cells:{},n:0,col:state.heatBy==='opponent'?colourOf(m.opponent):T().accent});const c=Math.floor(m.year/step)*step;(r.cells[c]||(r.cells[c]=[])).push(m);r.n++;}
  const val=l=>{const a=aggregate(l);return state.heatMetric==='matches'?a.n:state.heatMetric==='rate'?a.rate:state.heatMetric==='wins'?a.w:a.margin;};
  const list=Object.values(rows).sort((p,q)=>q.n-p.n).slice(0,26);const vals=list.flatMap(r=>Object.values(r.cells).map(val)).filter(v=>v!=null);const max=Math.max(1,...vals.map(Math.abs));
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Heatmap · ${esc(eraLabel())}</span><small>${list.length} rows × ${cols.length} ${step===1?'years':step+'-year bands'}</small></div><div class="panel"><div class="toolrow"><select id="heatBy"><option value="opponent" ${state.heatBy==='opponent'?'selected':''}>By opponent</option><option value="ground" ${state.heatBy==='ground'?'selected':''}>By ground</option><option value="competition" ${state.heatBy==='competition'?'selected':''}>By competition</option></select><select id="heatMetric"><option value="matches" ${state.heatMetric==='matches'?'selected':''}>Matches played</option><option value="wins" ${state.heatMetric==='wins'?'selected':''}>Wins</option><option value="rate" ${state.heatMetric==='rate'?'selected':''}>Win rate</option><option value="margin" ${state.heatMetric==='margin'?'selected':''}>Average margin</option></select><span class="small muted">${state.heatMetric==='margin'?'Green above zero, red below.':state.heatMetric==='rate'?'Brightness is the win rate.':'Brightness is the cell’s share of the largest cell.'}</span></div>
  <div class="barcode"><div class="bc-row"><span></span><span class="cells">${cols.map(c=>`<i style="background:none;height:14px;font-size:8px;color:var(--dim);text-align:center;line-height:14px">${cols.length<=16||c%(step*2)===0?String(c).slice(2):''}</i>`).join('')}</span><span></span></div>${list.map(r=>`<div class="bc-row"><span class="lab" ${state.heatBy==='opponent'?`data-opp="${esc(r.k)}"`:''}>${esc(r.k)}</span><span class="cells">${cols.map(c=>{const l=r.cells[c];if(!l)return `<i style="--c:#0d1210" title="${c}s · no matches"></i>`;const v=val(l);let col;if(state.heatMetric==='margin'){col=v>=0?mixHex('#4fd28f','#12181a',Math.min(1,.2+v/max)):mixHex('#e6605c','#12181a',Math.min(1,.2-v/max));}else if(state.heatMetric==='rate'){col=mixHex(r.col,'#12181a',Math.max(.12,v/100));}else col=mixHex(r.col,'#12181a',Math.max(.12,v/max));return `<i style="--c:${col}" title="${c}${step>1?'–'+(c+step-1):''} · ${esc(r.k)} · ${l.length} matches · ${recStr(aggregate(l))}${state.heatMetric==='margin'?' · margin '+(v>0?'+':'')+v.toFixed(1):state.heatMetric==='rate'?' · '+pct(v):''}"></i>`;}).join('')}</span><span class="tot">${r.n}</span></div>`).join('')}</div></div>`;}

/* ---------- Duel ---------- */
function duelView(){const by=state.duelBy;
  if(by==='nation'){if(!TEN.includes(state.dA))state.dA=TEN.find(n=>n!==state.team)||TEN[1];if(!TEN.includes(state.dB)||state.dB===state.dA)state.dB=TEN.find(n=>n!==state.dA);
    const opt=v=>TEN.map(n=>`<option value="${esc(n)}" ${n===v?'selected':''}>${esc(n)}</option>`).join('');const A1=perspective(state.dA).filter(m=>inEra(m)&&inScope(m)),B1=perspective(state.dB).filter(m=>inEra(m)&&inScope(m));const h2h=A1.filter(m=>m.opponent===state.dB);const a=aggregate(A1),b=aggregate(B1),h=aggregate(h2h);
    const rowsK=[['Matches',x=>x.n],['Won',x=>x.w],['Lost',x=>x.l],['Drawn',x=>x.d],['Win rate %',x=>x.rate==null?0:+x.rate.toFixed(1)],['Points for',x=>x.pf],['Points against',x=>x.pa],['Avg margin',x=>x.margin==null?0:+x.margin.toFixed(1)],['World Cup titles',x=>x===a?teamBy[state.dA].titles.length:teamBy[state.dB].titles.length]];
    $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Head to head · ${esc(eraLabel())}</span><small>two nations, each from its own side</small></div><div class="panel"><div class="toolrow"><select id="duelBy"><option value="nation" selected>Nations</option><option value="player">Players</option></select><select id="dA">${opt(state.dA)}</select><span class="eyebrow">v</span><select id="dB">${opt(state.dB)}</select></div>
    <div class="duel-head" style="margin-top:10px"><div class="n" style="color:${colourOf(state.dA)}">${esc(state.dA)}</div><div class="rec"><span style="color:${colourOf(state.dA)}">${h.w}</span><i>·</i><span class="D">${h.d}</span><i>·</i><span style="color:${colourOf(state.dB)}">${h.l}</span></div><div class="n" style="color:${colourOf(state.dB)}">${esc(state.dB)}</div></div><p class="small dim" style="text-align:center;margin:6px 0 16px">${h.n} meetings in this lens · ${h.n?`${esc(state.dA)} ${fmt(h.pf)} – ${fmt(h.pa)} ${esc(state.dB)} on aggregate`:''}</p>
    ${rowsK.map(([l,f])=>{const va=f(a),vb=f(b);const m=Math.max(Math.abs(va),Math.abs(vb),1);return `<div class="vsrow"><span class="a"><b>${fmt(va)}</b><i style="--c:${colourOf(state.dA)};--w:${Math.round(120*Math.abs(va)/m)}px"></i></span><span class="m">${l}</span><span class="b"><i style="--c:${colourOf(state.dB)};--w:${Math.round(120*Math.abs(vb)/m)}px"></i><b>${fmt(vb)}</b></span></div>`;}).join('')}
    <p class="small dim" style="margin-top:12px">Each nation's totals count every opponent in its own archive for this lens; the big numbers are their meetings with each other.</p></div>${h2h.length?`<div class="h3" style="margin-top:22px"><span>Their meetings</span><small>from ${esc(state.dA)}'s side · newest first</small></div><div class="tablewrap"><table><tr><th>Date</th><th class="num">${esc(state.dA)}</th><th class="num">${esc(state.dB)}</th><th>Venue</th><th>Competition</th></tr>${[...h2h].reverse().slice(0,60).map(m=>`<tr><td>${esc(m.date)}</td><td class="num ${m.res}">${m.pf}</td><td class="num">${m.pa}</td><td>${esc(m.venue)}, ${esc(m.city||m.country||'')}</td><td>${esc(m.competitionRaw||m.competition)}</td></tr>`).join('')}</table></div>`:''}`;return;}
  const ps=P().filter(p=>p.caps);if(!ps.find(p=>p.id===state.pA))state.pA=ps[0]?.id;if(!ps.find(p=>p.id===state.pB)||state.pB===state.pA)state.pB=ps.find(p=>p.id!==state.pA)?.id;const pa=ps.find(p=>p.id===state.pA),pb=ps.find(p=>p.id===state.pB);
  const opt=v=>ps.map(p=>`<option value="${esc(p.id)}" ${p.id===v?'selected':''}>${esc(p.name)}</option>`).join('');
  const rowsK=[['Caps',p=>p.caps],['Tries',p=>p.tries],['Points',p=>p.points],['Debut year',p=>p.startYear],['Last year',p=>p.endYear],['Seasons',p=>p.startYear&&p.endYear?p.endYear-p.startYear+1:null],['Captured appearances',p=>p.history?.length||null]];
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Head to head · players · ${esc(T().name)}</span></div><div class="panel"><div class="toolrow"><select id="duelBy"><option value="nation">Nations</option><option value="player" selected>Players</option></select><select id="dA">${opt(state.pA)}</select><span class="eyebrow">v</span><select id="dB">${opt(state.pB)}</select></div>${pa&&pb?`<div class="duel-head" style="margin-top:10px"><div class="n" style="color:var(--accent)">${esc(pa.name)}<div class="small muted" style="font:12px var(--mono);text-transform:none;letter-spacing:0">${esc(pa.position||'')} · ${esc(pa.span||'')}</div></div><div class="rec"><span class="muted" style="font-size:22px">v</span></div><div class="n" style="color:var(--accent2)">${esc(pb.name)}<div class="small muted" style="font:12px var(--mono);text-transform:none;letter-spacing:0">${esc(pb.position||'')} · ${esc(pb.span||'')}</div></div></div>
  ${rowsK.map(([l,f])=>{const va=f(pa),vb=f(pb);const m=Math.max(va||0,vb||0,1);return `<div class="vsrow"><span class="a"><b>${fmt(va)}</b><i style="--c:var(--accent);--w:${Math.round(120*(va||0)/m)}px"></i></span><span class="m">${l}</span><span class="b"><i style="--c:var(--accent2);--w:${Math.round(120*(vb||0)/m)}px"></i><b>${fmt(vb)}</b></span></div>`;}).join('')}<p class="small dim" style="margin-top:12px">Published career snapshots; unavailable values stay blank.</p>`:''}</div>`;}

/* ---------- The Pitch: a symbolic scoring replay ---------- */
const PTS=(y)=>({try:y>=1992?5:y>=1971?4:3,con:2,pen:3,drop:y>=1948?3:4,ptry:y>=2017?7:(y>=1992?5:y>=1971?4:3)});
function pitchEvents(m){const sc=m.scoring;if(!sc)return null;const o=m.isHome?0:6,a=m.isHome?6:0;const v=PTS(m.year);const mk=(side,off)=>{const ev=[];const push=(kind,n,pts)=>{for(let i=0;i<n;i++)ev.push({side,kind,pts});};push('try',sc[off],v.try);push('ptry',sc[off+5],v.ptry);push('con',sc[off+1],v.con);push('pen',sc[off+2],v.pen);push('drop',sc[off+3],v.drop);return ev;};
  const us=mk('us',o),them=mk('them',a);/* interleave in proportion so the scoreboard builds from both ends */const out=[];let i=0,j=0;while(i<us.length||j<them.length){if(j>=them.length||(i<us.length&&i/us.length<=j/them.length))out.push(us[i++]);else out.push(them[j++]);}return out;}
function pitchSvg(m){const ev=pitchEvents(m);if(!ev)return '';const t=T();const oc=colourOf(m.opponent);let cu=0,ct=0,iu=0,it=0;const marks=ev.map((e,k)=>{const mine=e.side==='us';const idx=mine?iu++:it++;const c=mine?t.accent:oc;const y=40+((idx*37)%110);let x,shape;
  if(e.kind==='try'||e.kind==='ptry'){x=mine?362+(idx*11)%26:38-(idx*11)%26;shape=`<ellipse cx="${x}" cy="${y}" rx="9" ry="6" fill="${e.kind==='ptry'?'none':c}" stroke="${c}" stroke-width="2" transform="rotate(-30 ${x} ${y})"/>`;}
  else if(e.kind==='con'){x=mine?330-(idx*9)%40:70+(idx*9)%40;shape=`<path d="M${x} ${y+8}l6-16" stroke="${c}" stroke-width="2.5" fill="none"/><circle cx="${x+6}" cy="${y-8}" r="2.5" fill="${c}"/>`;}
  else if(e.kind==='pen'){x=mine?260-(idx*13)%90:140+(idx*13)%90;shape=`<path d="M${x} ${y+9}v-18" stroke="${c}" stroke-width="3"/><path d="M${x-5} ${y-9}h10" stroke="${c}" stroke-width="3"/>`;}
  else{x=mine?300-(idx*15)%60:100+(idx*15)%60;shape=`<path d="M${x} ${y-8}l7 8-7 8-7-8z" fill="${c}"/>`;}
  if(mine)cu+=e.pts;else ct+=e.pts;return `<g class="ev" data-k="${k}" data-u="${cu}" data-t="${ct}" style="animation-delay:${RM?0:k*.55}s"><title>${mine?esc(t.code):esc(m.opponent)} · ${e.kind==='try'?'try':e.kind==='ptry'?'penalty try':e.kind==='con'?'conversion':e.kind==='pen'?'penalty goal':'drop goal'} · +${e.pts}</title>${shape}</g>`;}).join('');
  return `<div class="pitchwrap"><svg viewBox="0 0 400 190" class="pitch" role="img" aria-label="Symbolic scoring map: tries in the in-goal areas, kicks in the field"><rect x="0" y="0" width="400" height="190" rx="6" fill="#0f2a1c"/><rect x="0" y="0" width="30" height="190" fill="${oc}" opacity=".13"/><rect x="370" y="0" width="30" height="190" fill="${t.accent}" opacity=".13"/>${[30,70,110,150,200,250,290,330,370].map(x=>`<line x1="${x}" y1="6" x2="${x}" y2="184" stroke="#e9f1ea" stroke-opacity="${x===200?.55:x===30||x===370?.7:.22}" stroke-width="${x===200?1.5:1}" ${x===110||x===290?'stroke-dasharray="4 4"':''}/>`).join('')}<path d="M30 70v50M370 70v50" stroke="#f3f5f2" stroke-width="3"/><path d="M26 78h8M366 78h8" stroke="#f3f5f2" stroke-width="2"/><text x="52" y="182" font-size="8" fill="#e9f1ea" fill-opacity=".5" font-family="JetBrains Mono,monospace">${esc(m.opponent)} in-goal</text><text x="348" y="182" font-size="8" fill="#e9f1ea" fill-opacity=".5" font-family="JetBrains Mono,monospace" text-anchor="end">${esc(t.code)} in-goal</text><g id="pitchEvents">${marks}</g></svg>
  <div class="pitchscore"><span style="color:${t.accent}">${esc(t.code)}</span><b id="psU">0</b><i>–</i><b id="psT">0</b><span style="color:${oc}">${esc(m.opponent)}</span><button type="button" class="btn" id="pitchReplay">↻ Replay</button></div><p class="small dim" style="margin:6px 0 0">A symbolic build of the scoreboard from the recorded breakdown — balls are tries (hollow: penalty tries), flags conversions, posts penalties, diamonds drop goals. The order of events is not recorded; the values are those of ${m.year}.</p></div>`;}
function runPitch(){const evs=$$('#pitchEvents .ev');if(!evs.length)return;const u=$('#psU'),tt=$('#psT');let timers=[];const set=(k)=>{const e=evs[k];u.textContent=e.dataset.u;tt.textContent=e.dataset.t;};
  const play=()=>{timers.forEach(clearTimeout);timers=[];evs.forEach(e=>{e.style.animation='none';e.offsetHeight;e.style.animation='';});u.textContent='0';tt.textContent='0';evs.forEach((e,k)=>timers.push(setTimeout(()=>set(k),RM?0:k*550+300)));};
  play();$('#pitchReplay').onclick=play;}

/* ---------- swing chart: who leads the rivalry, meeting by meeting ---------- */
function swingChart(ms,o){const W=800,H=180,padL=30,padR=30,padT=16,padB=22;let cum=0;const pts=ms.map(m=>{cum+=m.res==='W'?1:m.res==='L'?-1:0;return cum;});const max=Math.max(1,...pts.map(Math.abs));const n=ms.length;const x=i=>padL+(n>1?i*(W-padL-padR)/(n-1):(W-padL-padR)/2),y=v=>padT+(H-padT-padB)*(1-(v/max+1)/2);const y0=y(0);
  const line=pts.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1)).join('');const area=`M${x(0).toFixed(1)} ${y0.toFixed(1)}${pts.map((v,i)=>'L'+x(i).toFixed(1)+' '+y(v).toFixed(1)).join('')}L${x(n-1).toFixed(1)} ${y0.toFixed(1)}Z`;
  const ticks=[];for(let i=0;i<n;i+=Math.max(1,Math.round(n/8)))ticks.push(i);if(n-1-ticks[ticks.length-1]>n/16)ticks.push(n-1);
  return `<svg viewBox="0 0 ${W} ${H}" class="swing" role="img" aria-label="Cumulative lead in the rivalry"><defs><clipPath id="swUp"><rect x="0" y="0" width="${W}" height="${y0}"/></clipPath><clipPath id="swDn"><rect x="0" y="${y0}" width="${W}" height="${H-y0}"/></clipPath></defs><line x1="${padL}" x2="${W-padR}" y1="${y0.toFixed(1)}" y2="${y0.toFixed(1)}" stroke="#2b3934"/><path d="${area}" fill="var(--accent)" opacity=".35" clip-path="url(#swUp)"/><path d="${area}" fill="${colourOf(o)}" opacity=".35" clip-path="url(#swDn)"/><path d="${line}" fill="none" stroke="var(--ink)" stroke-width="1.5"/>${ticks.map(i=>`<text x="${x(i).toFixed(1)}" y="${H-6}" font-size="9" fill="#5c6b64" text-anchor="middle" font-family="JetBrains Mono,monospace">${ms[i].year}</text>`).join('')}<text x="${padL}" y="${padT+8}" font-size="9" fill="var(--accent)" font-family="JetBrains Mono,monospace">+${max} ${esc(T().code)} ahead</text><text x="${padL}" y="${H-padB-2}" font-size="9" fill="${colourOf(o)}" font-family="JetBrains Mono,monospace">+${max} ${esc(o)} ahead</text><text x="${W-padR}" y="${(y(pts[n-1])+(pts[n-1]>=0?-6:12)).toFixed(1)}" font-size="10" font-weight="700" fill="var(--ink)" text-anchor="end" font-family="JetBrains Mono,monospace">${pts[n-1]>0?'+':''}${pts[n-1]}</text></svg>`;}

/* ---------- form strip: every result as a tick ---------- */
function formStrip(ms){return `<div class="ribbon">${ms.map(m=>`<i class="${m.res}" title="${m.year} v ${esc(m.opponent)} ${m.pf}–${m.pa}" data-match="${m.archiveId}"></i>`).join('')}</div>`;}

/* ---------- the Carpet: every match as a cell, year × opponent ---------- */
function carpetView(){const ms=lensMatches();const e=era();const years=[];for(let y=e.from;y<=e.to;y++)years.push(y);const by={};for(const m of ms){const r=by[m.opponent]||(by[m.opponent]={o:m.opponent,n:0,cells:{}});r.n++;(r.cells[m.year]||(r.cells[m.year]=[])).push(m);}
  const rows=Object.values(by).sort((p,q)=>q.n-p.n);const playedYears=new Set(ms.map(m=>m.year));
  const cell=(l)=>{if(!l)return `<i class="e"></i>`;const w=l.filter(m=>m.res==='W').length,d=l.filter(m=>m.res==='D').length,lo=l.length-w-d;const n=l.length;const bg=n===1?`var(--${l[0].res==='W'?'win':l[0].res==='L'?'loss':'draw'})`:`linear-gradient(180deg,var(--win) 0 ${100*w/n}%,var(--draw) ${100*w/n}% ${100*(w+d)/n}%,var(--loss) ${100*(w+d)/n}% 100%)`;return `<i style="background:${bg}" data-match="${l[0].archiveId}" title="${l[0].year} v ${esc(l[0].opponent)} · ${l.map(m=>m.pf+'–'+m.pa).join(', ')}"></i>`;};
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>The carpet · ${esc(eraLabel())}</span><small>${rows.length} opponents × ${years.length} years · ${ms.length} matches</small></div><div class="panel"><p class="small muted" style="margin:0 0 12px">Every match as one cell: green won, red lost, grey drawn; a year with several meetings against the same opponent is split top to bottom. Empty columns are years without a Test — tours, wars and isolation leave their gaps.</p><div class="carpet"><div class="crow2 head"><span></span><span class="cells">${years.map(y=>`<i class="yl ${playedYears.has(y)?'':'none'}">${y%10===0?String(y).slice(2):''}</i>`).join('')}</span><span></span></div>${rows.map(r=>`<div class="crow2"><span class="lab" data-opp="${esc(r.o)}"><i class="dot" style="--c:${colourOf(r.o)}"></i>${esc(r.o)}</span><span class="cells">${years.map(y=>cell(r.cells[y])).join('')}</span><span class="tot">${r.n}</span></div>`).join('')}</div></div>`;}
