/* ---------- the map: the land silhouette once, every host city placed on it ---------- */
function landDefs(){if($('#landDefs'))return;const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('id','landDefs');s.setAttribute('width','0');s.setAttribute('height','0');s.setAttribute('style','position:absolute;width:0;height:0;overflow:hidden');s.innerHTML=`<defs><path id="land" d="${MAP.land}"/></defs>`;document.body.prepend(s);}
const HOSTS=(()=>{const m={};for(const g of GAMES)for(const p of g.points){const h=m[p[0]]||(m[p[0]]={city:p[0],lon:p[1],lat:p[2],years:[],countries:new Set()});h.years.push(g.year);if(p===g.points[0])h.countries.add(g.country);}return Object.values(m).map(h=>({...h,countries:[...h.countries],xy:proj([h.city,h.lon,h.lat])})).sort((a,b)=>a.years[0]-b.years[0]);})();
const hostOf=city=>HOSTS.find(h=>h.city===city);
function fitBox(pts,minW){if(!pts.length)return [0,0,1080,540];let x0=Math.min(...pts.map(p=>p[0])),x1=Math.max(...pts.map(p=>p[0])),y0=Math.min(...pts.map(p=>p[1])),y1=Math.max(...pts.map(p=>p[1]));const w=Math.max(minW,(x1-x0)*1.8,(y1-y0)*1.8);const cx=(x0+x1)/2,cy=(y0+y1)/2;return [Math.max(0,Math.min(1080-w,cx-w/2)),Math.max(0,Math.min(540-w,cy-w/2)),w,w];}
function hostSvg(g,opts={}){const pts=g.points.map(p=>({xy:proj(p),city:p[0]}));const box=opts.world?[0,0,1080,540]:fitBox(pts.map(p=>p.xy),opts.minW||60);const u=box[2]/500*(opts.k||1);const col=opts.color||'var(--team)';
  const dots=pts.map(p=>`<circle cx="${p.xy[0].toFixed(1)}" cy="${p.xy[1].toFixed(1)}" r="${12*u}" fill="none" stroke="${col}" stroke-width="${1.2*u}" opacity=".45"><animate attributeName="r" values="${8*u};${16*u}" dur="2.6s" repeatCount="indefinite"/><animate attributeName="opacity" values=".6;0" dur="2.6s" repeatCount="indefinite"/></circle><circle cx="${p.xy[0].toFixed(1)}" cy="${p.xy[1].toFixed(1)}" r="${4.2*u}" fill="${col}" stroke="#07080a" stroke-width="${1.4*u}"/>`).join('');
  const labels=opts.labels?pts.map(p=>`<text class="hostlbl" x="${(p.xy[0]+8*u).toFixed(1)}" y="${(p.xy[1]-6*u).toFixed(1)}" font-size="${9*u}">${esc(p.city)}</text>`).join(''):'';
  const others=opts.others?HOSTS.filter(h=>!pts.some(p=>p.city===h.city)).map(h=>`<circle cx="${h.xy[0].toFixed(1)}" cy="${h.xy[1].toFixed(1)}" r="${2.2*u}" fill="#5b616b"><title>${esc(h.city)} · ${h.years.join(', ')}</title></circle>`).join(''):'';
  return `<svg viewBox="${box.map(v=>v.toFixed(1)).join(' ')}" ${opts.attrs||''} aria-hidden="${opts.labels?'false':'true'}"${opts.labels?` role="img" aria-label="${esc(g.city)}, ${esc(g.country)}"`:''}><rect x="${box[0]}" y="${box[1]}" width="${box[2]}" height="${box[3]}" fill="#0b0d12"/><use href="#land" class="land" style="stroke-width:${.5*u}"/>${others}${dots}${labels}${opts.extra||''}</svg>`;}
function worldSvg(){const sel=state.whole?null:state.year;return `<svg viewBox="0 0 1080 540" role="img" aria-label="Host cities of every ${GAMES_WORD}"><rect width="1080" height="540" fill="#0b0d12"/><use href="#land" class="land" style="stroke-width:.6"/>${HOSTS.map(h=>{const on=h.years.includes(sel);const lead=byYear[h.years[h.years.length-1]]?leaderOf(byYear[h.years[h.years.length-1]]):null;return `<g class="host" data-host="${esc(h.city)}"><circle class="ring" cx="${h.xy[0].toFixed(1)}" cy="${h.xy[1].toFixed(1)}" r="${on?14:9}" fill="none" stroke="${on?'var(--accent)':color(lead||'?')}" stroke-width="1.2" opacity="${on?1:.35}"/><circle cx="${h.xy[0].toFixed(1)}" cy="${h.xy[1].toFixed(1)}" r="${on?5.5:3.2+Math.min(3,h.years.length)}" fill="${on?'var(--accent)':color(lead||'?')}" stroke="#07080a" stroke-width="1.2"/><title>${esc(h.city)} · ${h.years.join(', ')}</title></g>`;}).join('')}</svg>`;}

/* ---------- III · the Hosts: every Games as a card, the city on the map in the colour of the nation on top ---------- */
function hostModel(){return eraSeasons().map(s=>{const lead=leaderOf(s);return {s,g:s.g,year:s.year,lead,text:(s.year+' '+s.g.city+' '+s.g.country+' '+(lead||'')).toLowerCase()};});}
function drawGrid(){const list=hostModel();const q=state.gridFind.trim().toLowerCase();let shown=list.filter(c=>!q||c.text.includes(q));
  const sorters={year:(a,b)=>b.year-a.year,oldest:(a,b)=>a.year-b.year,city:(a,b)=>a.g.city.localeCompare(b.g.city)||a.year-b.year,leader:(a,b)=>(a.lead||'~').localeCompare(b.lead||'~')||b.year-a.year,size:(a,b)=>b.s.events.length-a.s.events.length};shown.sort(sorters[state.gridSort]||sorters.year);
  const cities=new Set(list.flatMap(c=>c.g.points.map(p=>p[0])));
  $('#gridLede').textContent=`${list.filter(c=>!c.g.cancelled).length} Games in ${eraLabel().replace(' · ',', ')}, each host city placed on the land as Natural Earth maps it — ${cities.size} cities${WINTER?' in the mountains of three continents, St. Moritz, Lake Placid, Innsbruck and Cortina d’Ampezzo twice each':' on five continents, Athens and Paris and London more than once'}. The point is the city, not the venues; satellite venues are not shown. Each card takes the colour of the delegation that topped the medal table that year in the lens.`;
  $('#worldMap').innerHTML=worldSvg();
  $('#circuits').innerHTML=shown.map(c=>`<button type="button" class="circ host${c.g.cancelled?' off':''}" data-year="${c.year}" style="${c.lead?teamVar(c.lead):'--team:#5b616b'}" title="${c.year} · ${esc(c.g.city)}${c.g.country?' · '+esc(c.g.country):''}${c.lead?' · on top: '+esc(c.lead):c.g.cancelled?' · cancelled':''}"><span class="ct">${esc(c.g.cancelled?'cancelled':c.g.country)}</span><span class="n">${c.year}</span>${c.g.cancelled?`<svg viewBox="0 0 100 100" aria-hidden="true"><rect width="100" height="100" fill="#0b0d12"/><text x="50" y="54" text-anchor="middle" font-family="JetBrains Mono,monospace" font-size="9" letter-spacing="2" fill="#5b616b">NO GAMES</text></svg>`:hostSvg(c.g,{minW:60,k:2.4})}<span class="nm">${esc(c.g.city)}</span></button>`).join('')||`<p class="muted">No Games match.</p>`;}

/* ---------- Stage: tabs, era strip, era context ---------- */
const TABS=[['season','Games'],['podium','Event'],['athletes','Athletes'],['nations','Nations'],['sports','Sports'],['hosts','Hosts'],['records','Records'],['barcode','Barcode'],['duel','Duel']];
function drawTabs(){$('#tabs').innerHTML=TABS.map(([id,l])=>`<button type="button" role="tab" data-tab="${id}" aria-pressed="${state.tab===id}">${l}</button>`).join('');
  const s=byYear[state.year];$('#stageStatus').textContent=(state.tab==='season'||state.tab==='podium')&&!state.whole&&s?`${state.year} · ${s.g.city} · ${lensLabel()}`:eraLabel();}
function drawEraStrip(preview){const strip=$('#eraStrip');if(!strip.children.length)strip.innerHTML=ERAS.map(e=>`<button type="button" style="--w:${e.to-e.from+4}" data-era="${e.id}" title="${esc(e.name)} · ${e.from}–${e.to}" aria-label="${esc(e.name)} ${e.from}–${e.to}"></button>`).join('');
  for(const b of strip.children){b.classList.toggle('on',state.era===b.dataset.era);b.classList.toggle('demo',preview===b.dataset.era);}
  const e=preview?ERAS.find(x=>x.id===preview):state.era==='all'?eraOf(state.year):ERAS.find(x=>x.id===state.era);
  $('#eraCaption').innerHTML=`<span><b>${esc(e.name)}</b> · ${e.from}–${e.to}</span><span class="dim">${state.era===e.id?'Lens on · click again to release':'Click a segment to focus the whole page on that era'}</span>`;
  const ctx=$('#eraContext');ctx.innerHTML=`<div class="era-car">${e.ball.svg}</div><div><p class="eyebrow">${state.era===e.id?'Era lens':preview?'Era':'Era of the selected Games'} · ${e.from}–${e.to}</p><h3>${esc(e.name)}</h3><p>${esc(e.text)}</p><div class="chips">${e.ball.features.map(f=>`<span>${esc(f)}</span>`).join('')}</div><p class="small dim" style="margin:10px 0 0">${esc(e.ball.label)} · an editorial reading of the period; the archive itself is not divided</p></div>`;}
const tour={i:-1,timer:null,visible:false,stopped:RM};
function tourStep(){if(tour.stopped||!tour.visible)return;tour.i=(tour.i+1)%ERAS.length;const ctx=$('#eraContext');ctx.classList.add('swap');setTimeout(()=>{if(tour.stopped)return;drawEraStrip(ERAS[tour.i].id);ctx.classList.remove('swap');},260);tour.timer=setTimeout(tourStep,4200);}
function tourStart(){if(tour.stopped||tour.timer)return;tour.timer=setTimeout(tourStep,1800);}
function tourPause(){clearTimeout(tour.timer);tour.timer=null;}
function tourStop(){if(tour.stopped)return;tour.stopped=true;tourPause();$('#eraContext').classList.remove('swap');drawEraStrip();}

/* ---------- shared pieces ---------- */
const al=id=>`<a href="#" data-athlete="${esc(id)}" style="color:inherit">${esc(aname(id))}</a>`;
const alist=ids=>(ids||[]).map(al).join(', ');
const nl=n=>`<a href="#" data-nation="${esc(n)}" style="color:inherit"><i class="dot" style="--c:${color(n)}"></i>${esc(n)}</a>`;
const sl=s=>`<a href="#" data-sportv="${esc(s)}" style="color:inherit">${esc(s)}</a>`;
const el=(e,label)=>`<a href="#" data-event="${esc(e.id)}" style="color:inherit">${esc(label||evLabel(e))}</a>`;
const yl=y=>`<a href="#" data-year="${y}" style="color:inherit">${y}</a>`;
const mk=r=>`<i class="mk${r}" title="${MEDALCAP[r]}"></i>`;
const tally=a=>`<span class="mono small"><span style="color:var(--gold)">${a.gold}</span> · <span style="color:var(--silver)">${a.silver}</span> · <span style="color:var(--bronze)">${a.bronze}</span></span>`;
function bars(rows,valOf,subOf,max,attr,nameOf,colorOf,unit=''){return `<div class="board">${rows.map((a,i)=>`<button type="button" class="bar" data-${attr}="${esc(a.id)}" style="--i:${i};--team:${colorOf(a)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(nameOf(a))}</span><small>${subOf(a)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*valOf(a)/(max||1))}%"></span></span></span><span class="val">${valOf(a)==null?'—':fmt(valOf(a))}${unit}</span></button>`).join('')}</div>`;}
const athleteBars=(rows,valOf,subOf,max,unit='')=>bars(rows,valOf,subOf,max,'athlete',a=>aname(a.id),a=>color(a.nation||'?'),unit);
const nationBars=(rows,valOf,subOf,max,unit='')=>bars(rows,valOf,subOf,max,'nation',a=>a.id,a=>color(a.id),unit);
const sportBars=(rows,valOf,subOf,max,unit='')=>bars(rows,valOf,subOf,max,'sportv',a=>a.id,a=>'var(--accent)',unit);
function medalTable(rows,attr='nation',nameOf=a=>a.id,colorOf=a=>color(a.id),subOf=null,max=null){const mx=max||Math.max(1,...rows.map(a=>a.total));return `<div class="mtab">${rows.map((a,i)=>`<button type="button" class="mrow" data-${attr}="${esc(a.id)}" style="--team:${colorOf(a)}"><span class="rk">${a.rank||i+1}</span><span><span class="lab"><span><i></i>${esc(nameOf(a))}</span><small>${subOf?subOf(a):''}</small></span><span class="trk"><b class="g" style="width:${(100*a.gold/mx).toFixed(2)}%"></b><b class="s" style="width:${(100*a.silver/mx).toFixed(2)}%"></b><b class="b" style="width:${(100*a.bronze/mx).toFixed(2)}%"></b></span></span><span class="val"><span class="g">${a.gold}</span><small>${a.silver} · ${a.bronze} · ${a.total}</small></span></button>`).join('')}</div>`;}
function drawChart(el,series,n,labelOf,xl,colorOf,ylabel){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(200,box.height);const padL=40,padR=130,padT=14,padB=26;const vals=series.flatMap(s=>s.pts.filter(v=>v!=null));const max=Math.max(1,...vals),min=Math.min(0,...vals);const x=i=>padL+(n>1?i*(W-padL-padR)/(n-1):0),y=v=>padT+(H-padT-padB)*(1-(v-min)/((max-min)||1));
  let g='';const step=max>200?50:max>60?25:max>20?10:max>8?5:1;for(let v=Math.ceil(min/step)*step;v<=max;v+=step)g+=`<line class="gridl" x1="${padL}" x2="${W-padR}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}"/><text class="lb" x="${padL-6}" y="${(y(v)+3).toFixed(1)}" text-anchor="end">${v}</text>`;
  for(let i=0;i<n;i++){const l=xl(i);if(l)g+=`<text class="lb" x="${x(i).toFixed(1)}" y="${H-8}" text-anchor="middle">${esc(l)}</text>`;}
  const paths=series.map(s=>{let d='',pen=false;s.pts.forEach((v,i)=>{if(v==null){pen=false;return;}d+=(pen?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1);pen=true;});const lastI=s.pts.map((v,i)=>v!=null?i:-1).filter(i=>i>=0).pop();const last=lastI!=null?s.pts[lastI]:null;return `<path class="ser" d="${d}" style="--c:${colorOf(s.id)}"><title>${esc(labelOf(s.id))}</title></path>${last!=null?`<text class="end" x="${(x(lastI)+6).toFixed(1)}" y="${(y(last)+4).toFixed(1)}" style="--c:${colorOf(s.id)}">${esc(labelOf(s.id))} ${fmt(last)}</text>`:''}`;}).join('');
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(ylabel||'Chart')}">${g}${paths}</svg>`;}
const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b>${s?`<small>${s}</small>`:''}</div>`;
const yearBars=(items,colorOf)=>`<div class="yearbars">${items.map(it=>`<button type="button" data-year="${it.y}" title="${it.title}" style="--h:${it.h}%;--team:${colorOf(it)}"><i></i><span>${it.y%20===0?it.y:''}</span></button>`).join('')}</div>`;

/* ---------- Games: the host, the medal table, the programme, the table building event by event ---------- */
let replay=null;
function stopReplay(){if(replay){cancelAnimationFrame(replay.raf);clearTimeout(replay.t);replay=null;}}
function seasonView(){if(state.whole)return eraView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No Games in this lens.</p>';return;}const g=s.g;const c=champOf(s);const lead=c.leader;const acc=lead?color(lead):'#f2c666';
  if(g.cancelled){$('#view').innerHTML=`<div class="season-head"><div class="champ-card" style="--accent:#5b616b;--on-accent:#f4f4f2"><p class="eyebrow" style="color:var(--ink);opacity:.7">Cancelled</p><div class="yr">${s.year}</div><div class="who"><small>No Games</small>${esc(g.note||'Cancelled')}</div><p class="small" style="margin:14px 0 0;color:var(--ink);opacity:.85">The Games were called off and have no results; they count nothing in the statistics and stand in the timeline as a gap.</p></div><div class="panel"><div class="h3"><span>Where the Games would have been</span></div><p class="muted">${esc(g.note||'')}</p></div></div>`;return;}
  const sportsHere=[...new Set(s.events.map(e=>e.sport))].sort();const bySport=Object.fromEntries(sportsHere.map(sp=>[sp,s.events.filter(e=>e.sport===sp)]));
  const head=`<div class="season-head"><div class="champ-card" style="--accent:${acc};--on-accent:${onColor(acc)}"><p class="eyebrow" style="color:var(--ink);opacity:.7">The Games · ${esc(g.country)} · ${esc(lensLabel())}</p><div class="yr">${s.year}</div><div class="who"><small>${esc(g.dates||'')}</small>${esc(g.city)}</div>${lead?`<div class="team"><i></i>On top of the table · ${esc(lead)} · ${c.table[0].gold} gold</div>`:''}<div class="facts"><div><b>${s.events.length}</b>medal events</div><div><b>${fmt(s.awards.length)}</b>medals</div><div><b>${c.nations}</b>delegations on the podium</div><div><b>${fmt(c.medallists)}</b>medallists</div></div>${g.note?`<p class="small" style="margin:14px 0 0;color:var(--ink);opacity:.85">${esc(g.note)}</p>`:''}<p class="small dim" style="margin:18px 0 0">A team, pair or relay counts once for its delegation; ties are separate medals. The whole Games: ${fmt(g.athletes)} athletes${g.women?` (${fmt(g.women)} women)`:''} from ${fmt(g.delegations)} delegations, ${fmt(g.scheduled)} events on the programme.</p></div>
  <div><div class="podium">${[c.table[1],c.table[0],c.table[2]].map((n,i)=>n?`<button type="button" class="step p${c.table.indexOf(n)+1} bar" data-nation="${esc(n.id)}" style="--h:${Math.round(120+120*n.gold/Math.max(1,c.table[0].gold))}px;--team:${color(n.id)};display:flex"><span class="pos">${c.table.indexOf(n)+1}</span><span class="nm">${esc(n.id)}</span><span class="pt">${n.gold} gold · ${n.total} medals</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const map=`<div class="panel" style="margin-top:22px"><div class="h3"><span>The host</span><small>${esc(g.city)} · ${esc(g.country)} · the city on the map, not the venues</small></div><div class="course"><div class="course-map">${hostSvg(g,{minW:90,k:1,labels:true,others:true,attrs:'id="hostSvg"',color:acc})}<p class="small dim" style="margin:8px 0 0">Land: Natural Earth (public domain) · the point is the host city at approximate coordinates · grey points are the other host cities</p></div><div class="course-side"><p class="eyebrow">The Games in numbers</p><div class="kpis" style="grid-template-columns:1fr 1fr">${kpi('Athletes',fmt(g.athletes),g.women!=null?`${fmt(g.men)} men · ${fmt(g.women)} women`:'')}${kpi('Delegations',fmt(g.delegations),'')}${kpi('Programme',fmt(g.scheduled),'events scheduled')}${kpi('Sports in the lens',sportsHere.length,`${s.events.length} medal events`)}</div><div class="h3" style="margin-top:16px"><span>The programme</span><small>events by sport · click to open</small></div><div class="programme">${sportsHere.map(sp=>`<button type="button" class="chip" data-evsport="${esc(sp)}"><i style="--c:var(--accent)"></i>${esc(sp)}<span class="n">${bySport[sp].length}</span></button>`).join('')}</div></div></div></div>`;
  const tableRows=c.table;const shown=state.showAll?tableRows:tableRows.slice(0,15);
  const tab=`<div class="two" style="margin-top:22px"><div class="panel"><div class="h3"><span>The medal table</span><small>${tableRows.length} delegations · gold, then silver, then bronze</small></div>${medalTable(shown,'nation',a=>a.id,a=>color(a.id),a=>`${a.total} medals`,tableRows[0]?.total||1)}${tableRows.length>15?`<p class="small" style="margin:10px 0 0"><button type="button" class="linkbtn" id="showAll">${state.showAll?'Show the top fifteen':`Show all ${tableRows.length} delegations`}</button></p>`:''}</div>
  <div><div class="replaybox"><div class="h3" style="margin-top:0"><span>The table, event by event</span><small>a symbolic replay in the archive’s order, not the calendar · <button type="button" class="linkbtn" id="replayGo">replay</button></small></div><div class="ticker" id="ticker">—</div><div class="mtab" id="replayTable"></div><div class="prog"><i id="replayProg" style="--w:0%"></i></div></div>
  <div class="panel" style="margin-top:14px"><div class="h3"><span>Medallists of the Games</span><small>most medals here · click a name</small></div>${(()=>{const m={};for(const w of s.awards)for(const id of w.athletes){const a=m[id]||(m[id]={id,gold:0,silver:0,bronze:0,total:0,nation:w.nation});a[MEDAL[w.rank]]++;a.total++;}const top=Object.values(m).sort(medalCmp).slice(0,8);return athleteBars(top,a=>a.total,a=>`${esc(a.nation)} · ${a.gold} gold · ${a.silver} silver · ${a.bronze} bronze`,top[0]?.total||1);})()}</div></div></div>`;
  $('#view').innerHTML=head+map+tab;
  const sa=$('#showAll');if(sa)sa.onclick=()=>{state.showAll=!state.showAll;render();};
  const go=()=>runReplay(s);$('#replayGo').onclick=go;go();}
function runReplay(s){stopReplay();const table=$('#replayTable'),tick=$('#ticker'),prog=$('#replayProg');if(!table)return;const events=s.events;const n=events.length;const tot={};const order=[];const rp={raf:0,t:0,i:0};replay=rp;
  const draw=()=>{const rows=Object.values(tot).sort(medalCmp).slice(0,8);const mx=rows[0]?.total||1;table.innerHTML=rows.map((a,i)=>`<div class="mrow" style="--team:${color(a.id)}"><span class="rk">${i+1}</span><span><span class="lab"><span><i></i>${esc(a.id)}</span></span><span class="trk"><b class="g" style="width:${(100*a.gold/mx).toFixed(1)}%"></b><b class="s" style="width:${(100*a.silver/mx).toFixed(1)}%"></b><b class="b" style="width:${(100*a.bronze/mx).toFixed(1)}%"></b></span></span><span class="val"><span class="g">${a.gold}</span><small>${a.silver} · ${a.bronze}</small></span></div>`).join('');};
  const step=()=>{if(replay!==rp)return;const per=RM?n:Math.max(1,Math.round(n/220));for(let k=0;k<per&&rp.i<n;k++,rp.i++){const e=events[rp.i];for(const w of e.awards){const a=tot[w.nation]||(tot[w.nation]={id:w.nation,gold:0,silver:0,bronze:0,total:0});a[MEDAL[w.rank]]++;a.total++;}}
    const e=events[Math.min(n-1,rp.i-1)];if(e){const g=e.awards.find(w=>w.rank===1);tick.innerHTML=`<b>${rp.i} / ${n}</b> · ${esc(e.sport)} · ${esc(evLabel(e))}${g?` <i class="m g"></i>${esc(g.nation)}${g.athletes.length===1?' · '+esc(aname(g.athletes[0])):''}`:' · no gold recorded'}`;}
    prog.style.setProperty('--w',(100*rp.i/n).toFixed(1)+'%');draw();
    if(rp.i<n)rp.t=setTimeout(()=>{rp.raf=requestAnimationFrame(step);},RM?0:40);else tick.innerHTML=`<b>${n} events</b> · the table as it stood at the close of the Games`;};
  step();}
function eraView(){const ss=eraHeld();const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);const nations=nationAgg();const athletes=athleteAgg();const top=nations[0];const events=eraEvents();
  const head=`<div class="season-head"><div class="champ-card" style="${top?`--accent:${color(top.id)};--on-accent:${onColor(color(top.id))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${e?'Whole era':'All Games'} · ${esc(lensLabel())}</p><div class="yr" style="font-size:clamp(44px,6vw,84px)">${ss[0]?.year}–${ss[ss.length-1]?.year}</div>${top?`<div class="who"><small>On top of the table across the period · ${top.gold} gold · ${top.total} medals</small><a href="#" data-nation="${esc(top.id)}" style="color:inherit;text-decoration:none">${esc(top.id)}</a></div><div class="team"><i></i>${athletes[0]?esc(aname(athletes[0].id))+' · '+athletes[0].gold+' gold, the most of any athlete':''}</div>`:''}<div class="facts"><div><b>${ss.length}</b>Games held</div><div><b>${fmt(events.length)}</b>medal events</div><div><b>${fmt(events.reduce((a,x)=>a+x.awards.length,0))}</b>medals</div><div><b>${nations.length}</b>delegations on the podium</div></div></div>
  <div><div class="podium">${[nations[1],nations[0],nations[2]].map((n,i)=>n?`<button type="button" class="step p${nations.indexOf(n)+1} bar" data-nation="${esc(n.id)}" style="--h:${Math.round(120+120*n.gold/Math.max(1,nations[0].gold))}px;--team:${color(n.id)};display:flex"><span class="pos">${nations.indexOf(n)+1}</span><span class="nm">${esc(n.id)}</span><span class="pt">${n.gold} gold · ${n.total} medals</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const roll=`<div class="h3"><span>Games by Games</span><small>the delegation on top of each medal table in the lens · click a year to open it</small></div><div class="calendar">${eraSeasons().map(s=>{const l=leaderOf(s);const c=champOf(s);return `<button type="button" class="cal" data-year="${s.year}" style="--team:${l?color(l):'#5b616b'}"><div class="rd">${s.year}</div><div class="nm">${esc(s.g.city)}</div><div class="w">${s.g.cancelled?'cancelled':l?'<i class="dot" style="--c:'+color(l)+'"></i>'+esc(l)+' · '+c.table[0].gold+' gold':'—'}</div></button>`;}).join('')}</div>`;
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>The medal table across the period</span><small>gold, then silver, then bronze</small></div>${medalTable(nations.slice(0,12),'nation',a=>a.id,a=>color(a.id),a=>`${a.games} Games · ${a.total} medals`)}</div><div class="panel"><div class="h3"><span>Athletes across the period</span><small>by gold, then silver, then bronze</small></div>${athleteBars(athletes.slice(0,12),a=>a.gold,a=>`${esc(a.nation)} · ${esc(a.sport)} · ${a.total} medals · ${yspan(a)}`,athletes[0]?.gold||1)}</div></div>`;
  $('#view').innerHTML=head+roll+body;}

/* ---------- Event: one medal event of one Games — the atlas's unit, as a race is to a season ---------- */
const ordinal=n=>n+(['th','st','nd','rd'][(n%100>10&&n%100<14)?0:Math.min(n%10,4)%4]||'th');
function podiumView(){if(state.whole)return eraEventsView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No Games in this lens.</p>';return;}
  if(s.g.cancelled||!s.events.length){$('#view').innerHTML=`<p class="muted" style="margin-top:20px">${s.g.cancelled?`The ${s.year} Games were cancelled and have no events.`:'No events in this lens at these Games.'}</p>`;return;}
  let ev=evById[state.event];if(!ev||ev.y!==s.year||!inLens(ev)){const sp=state.evSport&&s.events.some(e=>e.sport===state.evSport)?state.evSport:null;ev=(sp?s.events.filter(e=>e.sport===sp):s.events)[0];}state.event=ev.id;state.evSport=ev.sport;
  const sports=[...new Set(s.events.map(e=>e.sport))].sort();const here=s.events.filter(e=>e.sport===ev.sport);
  const nav=`<div class="chiplist" style="margin-top:20px">${sports.map(sp=>`<button type="button" class="chip${sp===ev.sport?' on':''}" data-evsport="${esc(sp)}" style="${sp===ev.sport?'border-color:var(--accent);color:var(--accent)':''}"><i style="--c:${(()=>{const g=s.events.filter(e=>e.sport===sp).flatMap(e=>e.awards).filter(w=>w.rank===1);const m={};for(const w of g)m[w.nation]=(m[w.nation]||0)+1;const t=Object.entries(m).sort((a,b)=>b[1]-a[1])[0];return t?color(t[0]):'#444';})()}"></i>${esc(sp)} <span class="dim">${s.events.filter(e=>e.sport===sp).length}</span></button>`).join('')}</div><div class="eventchips" style="margin-top:10px">${here.map(e=>{const g=e.awards.find(w=>w.rank===1);return `<button type="button" class="chip${e.id===ev.id?' on':''}" data-event="${esc(e.id)}"><i style="--c:${g?color(g.nation):'#444'}"></i>${esc(evLabel(e))}</button>`;}).join('')}</div>`;
  const gold=ev.awards.filter(w=>w.rank===1);const acc=gold[0]?color(gold[0].nation):'#f2c666';
  const lin=LIN[ev.key]||[ev];const i=lin.indexOf(ev);const prevWins=lin.slice(0,i).map(e=>e.awards.filter(w=>w.rank===1));
  const same=gold[0]&&gold[0].athletes.length===1?lin.slice(0,i+1).filter(e=>e.awards.some(w=>w.rank===1&&w.athletes.includes(gold[0].athletes[0]))).length:0;
  let streak=0;if(gold[0]&&gold[0].athletes.length===1){for(let j=i;j>=0&&lin[j].awards.some(w=>w.rank===1&&w.athletes.includes(gold[0].athletes[0]));j--)streak++;}
  const natSoFar=gold[0]?lin.slice(0,i+1).filter(e=>e.awards.some(w=>w.rank===1&&w.nation===gold[0].nation)).length:0;
  const hero=`<div class="panel" style="margin-top:18px;display:flex;flex-wrap:wrap;gap:18px;align-items:flex-end;justify-content:space-between;--team:${acc}"><div><p class="eyebrow">${s.year} · ${esc(s.g.city)} · ${sl(ev.sport)}${ev.section&&!/medalists|events/i.test(ev.section)?' · '+esc(ev.section):''}</p><h2 style="margin:6px 0 0">${esc(evLabel(ev))} <span class="muted" style="font-size:.6em;font-weight:600;font-style:normal">${s.year}</span></h2><p class="small muted" style="margin:6px 0 0">${lin.length>1?`The ${ordinal(i+1)} of ${lin.length} Games with this event in the archive`:'The only Games with this event in the archive'} · <a href="${esc(ev.url)}" target="_blank" rel="noopener">the event on Wikipedia ↗</a></p></div>${gold.length?`<div class="champline" style="--team:${acc}"><span class="eyebrow">Gold${streak>1?' · '+streak+' Games in a row':''}</span><b>${gold.map(w=>alist(w.athletes)||esc(w.nation)).join(' / ')}</b><span class="small muted">${gold.map(w=>nl(w.nation)).join(' · ')}${same>1?' · '+ordinal(same)+' gold in this event':''}${natSoFar>1?' · '+esc(gold[0].nation)+'’s '+ordinal(natSoFar):''}</span></div>`:'<div class="champline"><span class="eyebrow">Gold</span><b class="muted">not awarded</b></div>'}</div>`;
  const step=r=>{const ws=ev.awards.filter(w=>w.rank===r);return `<div class="pstep p${r}"><span class="rk">${MEDALCAP[r]}</span>${ws.length?ws.map((w,k)=>`${k?'<span class="tie">tie</span>':''}<b>${w.athletes.length===1?al(w.athletes[0]):w.athletes.length?esc(w.nation):esc(w.nation)}</b>${w.athletes.length>1?`<span class="roster">${alist(w.athletes)}</span>`:''}<span class="nat"><i style="--c:${color(w.nation)}"></i>${nl(w.nation)}</span>`).join(''):'<span class="muted">not awarded</span>'}</div>`;};
  const podium=`<div class="podium3">${step(2)}${step(1)}${step(3)}</div>${ev.note?`<div class="evnote">${esc(ev.note)}${ev.status?' · '+esc(ev.status):''}</div>`:''}`;
  const hist=lin.length>1?`<div class="panel" style="margin-top:22px"><div class="h3"><span>${esc(evLabel(ev))}, Games by Games</span><small>${lin.length} Games in the archive · newest first · click a year to open its podium</small></div><div class="tablewrap" style="max-height:520px"><table><tr><th>Games</th><th>Gold</th><th>Silver</th><th>Bronze</th></tr>${[...lin].reverse().map(e=>{const at=r=>e.awards.filter(w=>w.rank===r).map(w=>`${w.athletes.length?alist(w.athletes):''} <span class="dim">${esc(w.nation)}</span>`).join(' / ')||'—';return `<tr${e.id===ev.id?' style="color:var(--accent)"':''}><td><a href="#" data-year="${e.y}" data-event="${esc(e.id)}" style="color:inherit">${e.y}</a> <span class="dim small">${esc(byYearAll[e.y]?.city||'')}</span></td><td>${at(1)}</td><td>${at(2)}</td><td>${at(3)}</td></tr>`;}).join('')}</table></div></div>`:'';
  const most=(()=>{if(lin.length<3)return '';const m={};const nm={};for(const e of lin)for(const w of e.awards){if(w.rank===1){nm[w.nation]=(nm[w.nation]||0)+1;}for(const id of w.athletes){const a=m[id]||(m[id]={id,gold:0,silver:0,bronze:0,total:0,nation:w.nation});a[MEDAL[w.rank]]++;a.total++;}}const top=Object.values(m).sort(medalCmp).slice(0,8);const tn=Object.entries(nm).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([id,n])=>({id,n}));return `<div class="two" style="margin-top:22px"><div class="panel"><div class="h3"><span>Most medals in this event</span><small>across every Games</small></div>${athleteBars(top,a=>a.total,a=>`${esc(a.nation)} · ${a.gold} gold · ${a.silver} silver · ${a.bronze} bronze`,top[0]?.total||1)}</div><div class="panel"><div class="h3"><span>Most golds by delegation</span></div>${nationBars(tn,a=>a.n,a=>`${lin.filter(e=>e.awards.some(w=>w.rank===1&&w.nation===a.id)).map(e=>e.y).join(', ')}`,tn[0]?.n||1)}</div></div>`;})();
  $('#view').innerHTML=nav+hero+podium+hist+most;}
function eraEventsView(){const list=eraEvents().slice().sort((a,b)=>b.y-a.y||a.sport.localeCompare(b.sport)||a.event.localeCompare(b.event));
  const shown=list.slice(0,600);
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Every event · ${esc(eraLabel())}</span><small>${fmt(list.length)} medal events · newest first${list.length>600?' · the first 600 shown; narrow the lens for the rest':''} · click one to open its podium</small></div><div class="tablewrap" style="max-height:640px"><table><tr><th>Games</th><th>Sport</th><th>Event</th><th>Gold</th><th>Silver</th><th>Bronze</th></tr>${shown.map(e=>{const at=r=>e.awards.filter(w=>w.rank===r).map(w=>`${w.athletes.length===1?esc(aname(w.athletes[0])):''} <span class="dim">${esc(w.nation)}</span>`).join(' / ')||'—';return `<tr><td><a href="#" data-year="${e.y}" data-event="${esc(e.id)}" style="color:inherit">${e.y}</a></td><td>${esc(e.sport)}</td><td><a href="#" data-year="${e.y}" data-event="${esc(e.id)}" style="color:inherit">${esc(evLabel(e))}</a></td><td>${at(1)}</td><td>${at(2)}</td><td>${at(3)}</td></tr>`;}).join('')}</table></div>`;}
