/* ---------- Athletes ---------- */
function athletesView(){const list=athleteAgg();const lens=state.plens;let rows=list.filter(p=>p[lens]!=null);rows.sort((a,b)=>b[lens]-a[lens]||medalCmp(a,b));rows=rows.slice(0,40);
  const max=Math.max(1,...rows.map(a=>a[lens]));const q=(state.find2||'').toLowerCase();const found=q?Object.entries(ATH).filter(([id,n])=>n.toLowerCase().includes(q)||id.toLowerCase().includes(q)).slice(0,14):[];
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Athletes · ${esc(eraLabel())}</h2></div><div class="small mono muted">${fmt(list.length)} medallists</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><input type="search" id="find2" placeholder="Search an athlete" value="${esc(state.find2||'')}" aria-label="Search"><select id="lens" aria-label="Lens">${Object.entries(PLENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(PLENSES[lens][1])}</span></div>${q?`<div class="chiplist" style="margin-bottom:14px">${found.map(([id,n])=>`<button type="button" class="chip" data-athlete="${esc(id)}">${esc(n)}</button>`).join('')||'<span class="muted small">No match.</span>'}</div>`:''}
  ${athleteBars(rows,a=>a[lens],a=>`${esc(a.nation)} · ${esc(a.sport)} · ${a.gold} gold · ${a.total} medals · ${yspan(a)}`,max)}<p class="small dim" style="margin:10px 0 0">Every member of a medal-winning team, pair or relay is a medallist here, as the source lists them; the rosters of the earliest Games are sometimes incomplete.</p></div>`;
  $('#find2').addEventListener('input',e=>{state.find2=e.target.value;athletesView();$('#find2').focus();const v=$('#find2');v.setSelectionRange(v.value.length,v.value.length);});$('#lens').addEventListener('change',e=>{state.plens=e.target.value;render();});}
function athleteView(id){if(!(id in ATH)){athletesView();return;}const all=athleteAgg();const a=all.find(x=>x.id===id);const rank=all.findIndex(x=>x.id===id)+1;
  const rows=eraAwards().filter(w=>w.athletes.includes(id)).sort((u,v)=>v.y-u.y||u.rank-v.rank);
  const byS={};for(const w of rows){const c=byS[w.sport]||(byS[w.sport]={c:w.sport,gold:0,silver:0,bronze:0,total:0});c[MEDAL[w.rank]]++;c.total++;}
  const nations=Object.entries(a?a.nations:{}).sort((u,v)=>v[1]-u[1]);const col=color(a?.nation||'?');
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${col}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Athlete${a?' · '+yspan(a):''}${a?.sport?' · '+esc(a.sport):''} · ${nations.map(([n])=>nl(n)).join(' / ')||''}</p><h2 style="margin:6px 0 0">${esc(aname(id))}</h2></div><div class="small mono muted">${rank?`#${rank} by gold, silver, bronze in ${esc(eraLabel())}`:'no medals in this lens'} · <a href="https://en.wikipedia.org/wiki/${encodeURIComponent(id)}" target="_blank" rel="noopener">Wikipedia ↗</a></div></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Gold',a?a.gold:0,'')}${kpi('Silver',a?a.silver:0,'')}${kpi('Bronze',a?a.bronze:0,'')}${kpi('Medals',a?a.total:0,a?`${a.nevents} different events`:'')}${kpi('Games',a?a.games:0,a?[...a.years].sort().join(', '):'')}${kpi('Sports',a?a.nsports:0,a?Object.keys(a.sports).join(', '):'')}</div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Every medal</span><small>${rows.length} · click a Games to open the event</small></div><div class="tablewrap" style="max-height:560px"><table><tr><th>Games</th><th>Sport</th><th>Event</th><th class="medal">Medal</th><th>For</th><th>With</th></tr>${rows.map(w=>`<tr class="${w.rank===1?'win':''}"><td><a href="#" data-year="${w.y}" data-event="${esc(w.e)}" style="color:inherit">${w.y}</a> <span class="dim small">${esc(byYearAll[w.y]?.city||'')}</span></td><td>${sl(w.sport)}</td><td>${el(w.ev)}</td><td class="medal">${mk(w.rank)}${MEDALCAP[w.rank]}</td><td>${nl(w.nation)}</td><td class="small muted wrap">${w.athletes.length>1?alist(w.athletes.filter(x=>x!==id)):'<span class="dim">individual</span>'}</td></tr>`).join('')}</table></div></div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>By sport</span></div>${bars(Object.values(byS).sort(medalCmp),f=>f.total,f=>`${f.gold} gold · ${f.silver} silver · ${f.bronze} bronze`,Math.max(1,...Object.values(byS).map(f=>f.total)),'sportv',f=>f.c,()=>col)}</div>${a&&a.games>1?`<div class="panel" style="margin-top:14px"><div class="h3"><span>Medals, Games by Games</span></div>${yearBars(eraHeld().map(s=>{const ws=rows.filter(w=>w.y===s.year);const g=ws.filter(w=>w.rank===1).length;return {y:s.year,h:ws.length?Math.round(100*Math.max(.3,ws.length/Math.max(1,...eraHeld().map(t=>rows.filter(w=>w.y===t.year).length)))):0,title:`${s.year} · ${g} gold · ${ws.length} medals`};}),()=>col)}</div>`:'<div></div>'}</div>`;}

/* ---------- Nations ---------- */
function nationsView(){const list=nationAgg();const lens=state.lens;let rows=list.filter(a=>a[lens]!=null);rows.sort((a,b)=>b[lens]-a[lens]||medalCmp(a,b));rows=rows.slice(0,40);const max=Math.max(1,...rows.map(a=>a[lens]));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Nations · ${esc(eraLabel())}</h2></div><div class="small mono muted">${list.length} delegations on the podium</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="lens" aria-label="Lens">${Object.entries(LENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(LENSES[lens][1])}</span></div>${lens==='gold'?medalTable(rows,'nation',a=>a.id,a=>color(a.id),a=>`${a.games} Games · ${yspan(a)}`):nationBars(rows,a=>a[lens],a=>`${a.gold} gold · ${a.total} medals · ${a.games} Games · ${yspan(a)}`,max)}<p class="small dim" style="margin:10px 0 0">Delegations as the source names them: the Soviet Union, the Unified Team of 1992, Russia and the ROC are separate; so are Germany, East and West Germany and the United Team of 1956–64.</p></div>`;
  $('#lens').addEventListener('change',e=>{state.lens=e.target.value;render();});}
function nationView(id){const all=nationAgg();const a=all.find(x=>x.id===id);if(!a){nationsView();return;}const rank=a.rank;
  const rows=eraAwards().filter(w=>w.nation===id);const byY=a.byYear;const maxY=Math.max(1,...Object.values(byY).map(y=>y.total));
  const sports=Object.entries(a.sports).map(([s,v])=>({id:s,...v})).sort((p,q)=>q.gold-p.gold||q.total-p.total);
  const ath={};for(const w of rows)for(const p of w.athletes){const x=ath[p]||(ath[p]={id:p,gold:0,silver:0,bronze:0,total:0,nation:id});x[MEDAL[w.rank]]++;x.total++;}const topA=Object.values(ath).sort(medalCmp).slice(0,10);
  const games=eraHeld().map(s=>{const c=champOf(s);const me=c.table.find(t=>t.id===id);return {s,me,rk:me?me.rank:null};});const bestG=games.filter(g=>g.me).sort((p,q)=>q.me.gold-p.me.gold||q.me.total-p.me.total)[0];
  const sweeps=eraEvents().filter(e=>e.awards.length>=3&&e.awards.every(w=>w.nation===id)).length;
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${color(id)}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Delegation · ${yspan(a)} · ${a.games} Games on the podium</p><h2 style="margin:6px 0 0"><i class="dot" style="--c:${color(id)};width:.5em;height:.5em;vertical-align:.1em;margin-right:8px"></i>${esc(id)}</h2></div><div class="small mono muted">#${rank} in the table of ${esc(eraLabel())}</div></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Gold',a.gold,'')}${kpi('Silver',a.silver,'')}${kpi('Bronze',a.bronze,'')}${kpi('Medals',a.total,`${a.nsports} sports`)}${kpi('Best Games',bestG?bestG.s.year:'—',bestG?`${esc(bestG.s.g.city)} · ${bestG.me.gold} gold · ${ordinal(bestG.rk)} in the table`:'')}${kpi('Podium sweeps',sweeps,'gold, silver and bronze in one event')}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Medals, Games by Games</span><small>${Object.keys(byY).length} Games · click a year</small></div>${yearBars(eraHeld().map(s=>{const y=byY[s.year];return {y:s.year,h:y?Math.round(100*y.total/maxY):0,title:`${s.year} ${s.g.city} · ${y?y.gold:0} gold · ${y?y.total:0} medals`};}),()=>color(id))}<div class="h3" style="margin-top:22px"><span>Best sports</span><small>by gold</small></div>${bars(sports.slice(0,10),x=>x.gold,x=>`${x.total} medals`,sports[0]?.gold||1,'sportv',x=>x.id,()=>color(id))}</div>
  <div class="panel"><div class="h3"><span>Most decorated</span><small>athletes of the delegation in the lens</small></div>${athleteBars(topA,x=>x.total,x=>`${x.gold} gold · ${x.silver} silver · ${x.bronze} bronze`,topA[0]?.total||1)}</div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Every Games</span><small>place in the medal table, newest first</small></div><div class="tablewrap" style="max-height:520px"><table><tr><th>Games</th><th>Host</th><th class="n">Place</th><th class="n">Gold</th><th class="n">Silver</th><th class="n">Bronze</th><th class="n">Total</th><th>On top</th></tr>${[...games].reverse().map(g=>`<tr class="${g.rk===1?'win':''}"><td>${yl(g.s.year)}</td><td class="muted small">${esc(g.s.g.city)}</td><td class="n"><b>${g.rk?ordinal(g.rk):'—'}</b></td><td class="n">${g.me?g.me.gold:''}</td><td class="n">${g.me?g.me.silver:''}</td><td class="n">${g.me?g.me.bronze:''}</td><td class="n">${g.me?g.me.total:'<span class="dim">no medal</span>'}</td><td class="small">${leaderOf(g.s)&&leaderOf(g.s)!==id?nl(leaderOf(g.s)):''}</td></tr>`).join('')}</table></div></div>`;}

/* ---------- Sports ---------- */
function sportsView(){const list=sportAgg();const lens=state.slens;let rows=list.slice().sort((a,b)=>b[lens]-a[lens]||a.id.localeCompare(b.id));const max=Math.max(1,...rows.map(a=>a[lens]));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Sports · ${esc(eraLabel())}</h2></div><div class="small mono muted">${list.length} sports · ${fmt(list.reduce((n,a)=>n+a.events,0))} medal events</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="lens" aria-label="Lens">${Object.entries(SLENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(SLENSES[lens][1])}</span></div><div class="tablewrap" style="max-height:640px"><table><tr><th>Sport</th><th class="n">${esc(SLENSES[lens][0])}</th><th>Games</th><th>Most golds</th><th>Most decorated</th></tr>${rows.map(f=>`<tr><td>${sl(f.id)}</td><td class="n"><b>${fmt(f[lens])}</b></td><td class="small">${yspan(f)} · ${f.games}</td><td>${f.topNation?nl(f.topNation[0])+' <span class="dim">'+f.topNation[1].gold+'</span>':'—'}</td><td>${f.topAthlete?al(f.topAthlete[0])+' <span class="dim">'+f.topAthlete[1].gold+' gold · '+f.topAthlete[1].total+'</span>':'—'}</td></tr>`).join('')}</table></div><p class="small dim" style="margin:10px 0 0">Sports are the source’s labels: the disciplines of aquatics and gymnastics are separate sports here (swimming, diving, artistic swimming, water polo), and cycling and canoeing each hold their track and road, sprint and slalom together.</p></div>`;
  $('#lens').addEventListener('change',e=>{state.slens=e.target.value;render();});}
function sportView(id){const a=sportAgg().find(x=>x.id===id);if(!a){sportsView();return;}const events=eraEvents().filter(e=>e.sport===id);const awards=events.flatMap(e=>e.awards);
  const nations=Object.entries(a.nations).map(([n,v])=>({id:n,gold:v.gold,silver:0,bronze:0,total:v.total})).sort((p,q)=>q.gold-p.gold||q.total-p.total);for(const n of nations){n.silver=awards.filter(w=>w.nation===n.id&&w.rank===2).length;n.bronze=awards.filter(w=>w.nation===n.id&&w.rank===3).length;}
  nations.forEach((n,i)=>n.rank=i+1);const ath=Object.entries(a.athletes).map(([p,v])=>({id:p,gold:v.gold,total:v.total,silver:0,bronze:0,nation:null}));for(const x of ath){x.nation=awards.find(w=>w.athletes.includes(x.id))?.nation;x.silver=awards.filter(w=>w.rank===2&&w.athletes.includes(x.id)).length;x.bronze=awards.filter(w=>w.rank===3&&w.athletes.includes(x.id)).length;}ath.sort(medalCmp);
  const lins={};for(const e of events){const l=lins[e.key]||(lins[e.key]={key:e.key,gender:e.gender,events:[]});l.events.push(e);}const linList=Object.values(lins).sort((p,q)=>q.events.length-p.events.length||linName(p.key).localeCompare(linName(q.key)));
  const byY={};for(const e of events)byY[e.y]=(byY[e.y]||0)+1;const maxY=Math.max(1,...Object.values(byY));const top=nations[0];
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${top?color(top.id):'var(--accent)'}"><div class="panel"><p class="eyebrow">Sport · ${yspan(a)} · ${a.games} Games</p><h2 style="margin:6px 0 0">${esc(id)}</h2></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Medal events',a.events,`${a.nlin} different events`)}${kpi('Medals',a.awards,'')}${kpi('Most golds',top?top.id:'—',top?`${top.gold} gold · ${top.total} medals`:'')}${kpi('Most decorated',ath[0]?aname(ath[0].id):'—',ath[0]?`${ath[0].gold} gold · ${ath[0].total} medals`:'')}${kpi('Games',a.games,yspan(a))}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>The medal table of the sport</span></div>${medalTable(nations.slice(0,12),'nation',n=>n.id,n=>color(n.id),n=>`${n.total} medals`)}</div><div><div class="panel"><div class="h3"><span>Most decorated</span></div>${athleteBars(ath.slice(0,10),x=>x.total,x=>`${esc(x.nation||'')} · ${x.gold} gold · ${x.silver} silver · ${x.bronze} bronze`,ath[0]?.total||1)}</div><div class="panel" style="margin-top:14px"><div class="h3"><span>Events on the programme, Games by Games</span></div>${yearBars(eraHeld().map(s=>({y:s.year,h:Math.round(100*(byY[s.year]||0)/maxY),title:`${s.year} · ${byY[s.year]||0} medal events`})),()=>top?color(top.id):'#f2c666')}</div></div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Every event</span><small>${linList.length} · the Games it was held at · click one to open its latest podium</small></div><div class="tablewrap" style="max-height:560px"><table><tr><th>Event</th><th>Category</th><th class="n">Games</th><th>Held</th><th>Latest gold</th></tr>${linList.map(l=>{const last=l.events[l.events.length-1];const g=last.awards.find(w=>w.rank===1);return `<tr><td><a href="#" data-year="${last.y}" data-event="${esc(last.id)}" style="color:inherit">${esc(evLabel(last,false))}</a></td><td class="small muted">${esc(GENDER_LABEL[l.gender]||l.gender)}</td><td class="n">${l.events.length}</td><td class="small muted">${l.events.length>6?l.events[0].y+' – '+last.y:l.events.map(e=>e.y).join(', ')}</td><td class="small">${g?(g.athletes.length===1?al(g.athletes[0])+' · ':'')+nl(g.nation):'—'}</td></tr>`;}).join('')}</table></div></div>`;}

/* ---------- Hosts ---------- */
function hostsView(){const rows=HOSTS.map(h=>({...h,games:h.years.map(y=>byYear[y]).filter(Boolean)})).filter(h=>h.games.length).sort((a,b)=>b.games.length-a.games.length||a.years[0]-b.years[0]);
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Host cities · ${esc(eraLabel())}</h2></div><div class="small mono muted">${rows.length} cities</div></div><div class="panel"><div class="worldmap" style="margin-top:0">${worldSvg()}</div><div class="tablewrap" style="max-height:560px"><table><tr><th>City</th><th>Country</th><th class="n">Games</th><th>Years</th><th>On top of the table</th></tr>${rows.map(h=>`<tr><td><a href="#" data-host="${esc(h.city)}" style="color:inherit"><b>${esc(h.city)}</b></a></td><td class="muted">${esc(h.countries.join(' / '))}</td><td class="n">${h.games.length}</td><td class="small">${h.games.map(s=>yl(s.year)).join(', ')}</td><td class="small">${[...new Set(h.games.map(s=>leaderOf(s)).filter(Boolean))].map(nl).join(' · ')}</td></tr>`).join('')}</table></div><p class="small dim" style="margin:10px 0 0">The city, at approximate coordinates, on the land as Natural Earth maps it. ${WINTER?'Milano Cortina 2026 is placed at both Milan and Cortina d’Ampezzo; outlying snow venues — Whistler for Vancouver, Zhangjiakou for Beijing, Bormio and Livigno in 2026 — are not placed.':'Melbourne and Stockholm shared 1956; satellite venues — Tahiti’s surfing in 2024, the sailing at Weymouth or Kiel — are not placed.'}</p></div>`;
  $('#view').querySelectorAll('.host').forEach(g=>g.addEventListener('click',()=>{state.host=g.dataset.host;go('hosts',false);}));}
function hostView(city){const h=hostOf(city);if(!h){hostsView();return;}const games=h.years.map(y=>byYear[y]).filter(Boolean);const fake={city:h.city,country:h.countries.join(' / '),points:[[h.city,h.lon,h.lat]]};
  const home=games.map(s=>{const c=champOf(s);const host=c.table.find(t=>s.g.country.split(' / ').some(k=>t.id===k||(k==='United Kingdom'&&t.id==='Great Britain')||(k==='West Germany'&&t.id==='West Germany')));return {s,c,host};});
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:var(--accent)"><div class="panel"><p class="eyebrow">Host city · ${esc(h.countries.join(' / '))} · ${h.years.join(', ')}</p><h2 style="margin:6px 0 0">${esc(h.city)}</h2></div></div>
  <div class="course" style="margin-top:20px"><div class="course-map">${hostSvg(fake,{minW:90,k:1,labels:true,others:true,color:'var(--accent)'})}</div><div class="course-side"><p class="eyebrow">The Games here</p><div class="calendar" style="flex-direction:column;overflow:visible">${home.map(({s,c,host})=>`<button type="button" class="cal" data-year="${s.year}" style="flex:none;--team:${c.leader?color(c.leader):'#5b616b'}"><div class="rd">${s.year} · ${esc(s.g.dates||'')}</div><div class="nm">${esc(s.g.city)}</div><div class="w">${c.leader?'<i class="dot" style="--c:'+color(c.leader)+'"></i>on top: '+esc(c.leader)+' · '+c.table[0].gold+' gold':'—'}</div>${host?`<div class="small muted" style="margin-top:4px">the host delegation ${esc(host.id)}: ${ordinal(host.rank)} · ${host.gold} gold · ${host.total} medals</div>`:''}</button>`).join('')}</div></div></div>`;}

/* ---------- Records ---------- */
function recordsView(){const ss=eraHeld();const awards=eraAwards();const events=eraEvents();const athletes=athleteAgg();const nations=nationAgg();
  const mostGames=[...athletes].sort((a,b)=>b.games-a.games||medalCmp(a,b)).slice(0,10);const multi=athletes.filter(a=>a.nsports>=2).sort((a,b)=>b.nsports-a.nsports||medalCmp(a,b)).slice(0,10);
  const single={};for(const w of awards)for(const id of w.athletes){const k=id+'|'+w.y;const a=single[k]||(single[k]={id,y:w.y,gold:0,silver:0,bronze:0,total:0,nation:w.nation});a[MEDAL[w.rank]]++;a.total++;}const bestGames=Object.values(single).sort(medalCmp).slice(0,10);
  const bestNat=[];for(const n of nations)if(n.best)bestNat.push({id:n.id,y:n.best.y,gold:n.best.gold,total:n.best.total});bestNat.sort((a,b)=>b.gold-a.gold||b.total-a.total);
  const sweeps=events.filter(e=>e.awards.length>=3&&new Set(e.awards.map(w=>w.nation)).size===1);const sweepBy={};for(const e of sweeps)sweepBy[e.awards[0].nation]=(sweepBy[e.awards[0].nation]||0)+1;const topSweep=Object.entries(sweepBy).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([id,n])=>({id,n}));
  // consecutive golds in one event by one athlete
  const streaks=[];for(const key in LIN){const lin=LIN[key].filter(e=>inEraYear(e.y)&&inLens(e));let cur={};for(const e of lin){const golds=e.awards.filter(w=>w.rank===1);const now={};for(const w of golds)for(const id of w.athletes){now[id]=(cur[id]||0)+1;}for(const id in now)if(now[id]>=2)streaks.push({id,n:now[id],key,last:e.y,first:lin.find(x=>x.y<=e.y&&x.awards.some(w=>w.rank===1&&w.athletes.includes(id)))?.y});cur=now;}}
  const best={};for(const s of streaks){const k=s.id+'|'+s.key;if(!best[k]||best[k].n<s.n)best[k]=s;}const topStreak=Object.values(best).sort((a,b)=>b.n-a.n||a.last-b.last).slice(0,10);
  const hostRows=ss.map(s=>{const c=champOf(s);const keys=s.g.country.split(' / ').map(k=>k==='United Kingdom'?'Great Britain':k);const host=c.table.find(t=>keys.includes(t.id));const prev=ss.filter(t=>t.year<s.year).slice(-1)[0];const before=prev?champOf(prev).table.find(t=>keys.includes(t.id)):null;return host?{s,host,before,gain:host.gold-(before?before.gold:0)}:null;}).filter(Boolean).sort((a,b)=>b.gain-a.gain).slice(0,10);
  const biggest=[...ss].sort((a,b)=>b.events.length-a.events.length).slice(0,8);
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Records · ${esc(eraLabel())}</h2></div><div class="small mono muted">${ss.length} Games held</div></div>
  <div class="kpis">${kpi('Games held',ss.length,`${eraSeasons().length-ss.length} cancelled`)}${kpi('Medal events',fmt(events.length),`${fmt(awards.length)} medals`)}${kpi('Medallists',fmt(athletes.length),`${fmt(athletes.filter(a=>a.gold).length)} with gold`)}${kpi('Delegations',nations.length,`${nations.filter(n=>n.gold).length} with gold`)}${kpi('Most golds',athletes[0]?aname(athletes[0].id):'—',athletes[0]?`${athletes[0].gold} · ${athletes[0].total} medals · ${yspan(athletes[0])}`:'')}</div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Most gold medals</span><small>athletes</small></div>${athleteBars(athletes.slice(0,10),a=>a.gold,a=>`${esc(a.nation)} · ${esc(a.sport)} · ${a.total} medals · ${yspan(a)}`,athletes[0]?.gold||1)}</div><div class="panel"><div class="h3"><span>Most medals</span></div>${athleteBars([...athletes].sort((a,b)=>b.total-a.total||medalCmp(a,b)).slice(0,10),a=>a.total,a=>`${a.gold} gold · ${a.silver} silver · ${a.bronze} bronze · ${yspan(a)}`,Math.max(1,...athletes.map(a=>a.total)))}</div><div class="panel"><div class="h3"><span>Most Games on the podium</span></div>${athleteBars(mostGames,a=>a.games,a=>`${esc(a.sport)} · ${a.total} medals · ${yspan(a)}`,mostGames[0]?.games||1)}</div></div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Best single Games</span><small>an athlete’s medals at one Games</small></div>${bars(bestGames,a=>a.total,a=>`${a.y} · ${esc(a.nation)} · ${a.gold} gold`,bestGames[0]?.total||1,'athlete',a=>aname(a.id),a=>color(a.nation))}</div><div class="panel"><div class="h3"><span>Same event, Games after Games</span><small>consecutive golds in one event</small></div>${topStreak.length?`<div class="board">${topStreak.map((s,i)=>`<button type="button" class="bar" data-athlete="${esc(s.id)}" style="--i:${i};--team:${color(athletes.find(a=>a.id===s.id)?.nation||'?')}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(aname(s.id))}</span><small>${esc(linName(s.key))} · ${s.first}–${s.last}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*s.n/(topStreak[0]?.n||1))}%"></span></span></span><span class="val">${s.n}</span></button>`).join('')}</div>`:'<p class="muted small">None in this lens.</p>'}</div><div class="panel"><div class="h3"><span>Medals in more than one sport</span></div>${multi.length?athleteBars(multi,a=>a.nsports,a=>`${Object.entries(a.sports).map(([s,n])=>s+' '+n).join(', ')}`,Math.max(1,...multi.map(a=>a.nsports))):'<p class="muted small">None in this lens.</p>'}</div></div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>A delegation’s best Games</span><small>gold at one Games</small></div>${nationBars(bestNat.slice(0,10),a=>a.gold,a=>`${a.y} · ${esc(byYearAll[a.y]?.city||'')} · ${a.total} medals`,bestNat[0]?.gold||1)}</div><div class="panel"><div class="h3"><span>Podium sweeps</span><small>${sweeps.length} events where one delegation took all three medals</small></div>${topSweep.length?nationBars(topSweep,a=>a.n,a=>`${sweeps.filter(e=>e.awards[0].nation===a.id).slice(-4).map(e=>e.y+' '+e.sport).join(', ')}`,topSweep[0]?.n||1):'<p class="muted small">None in this lens.</p>'}</div><div class="panel"><div class="h3"><span>The host’s lift</span><small>the host delegation’s gold at home, against the Games before</small></div><div class="board">${hostRows.map((r,i)=>`<button type="button" class="bar" data-year="${r.s.year}" style="--i:${i};--team:${color(r.host.id)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(r.host.id)}<small> ${r.s.year} · ${esc(r.s.g.city)}</small></span><small>${r.host.gold} gold at home · ${r.before?r.before.gold+' before':'none before'} · ${ordinal(r.host.rank)} in the table</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*Math.max(0,r.gain)/(Math.max(1,hostRows[0]?.gain||1)))}%"></span></span></span><span class="val">${r.gain>0?'+':''}${r.gain}</span></button>`).join('')||'<p class="muted small">None in this lens.</p>'}</div></div></div>
  <div class="panel" style="margin-top:14px"><div class="h3"><span>The biggest programmes</span><small>medal events in the lens</small></div>${bars(biggest.map(s=>({id:s.year,n:s.events.length,s})),a=>a.n,a=>`${esc(a.s.g.city)} · ${fmt(a.s.awards.length)} medals · ${champOf(a.s).nations} delegations on the podium`,biggest[0]?.events.length||1,'year',a=>String(a.id),a=>color(leaderOf(a.s)||'?'))}</div>`;}

/* ---------- Barcode ---------- */
const HEATMETRICS={gold:['Gold medals','Gold medals won at those Games.'],total:['All medals','Gold, silver and bronze at those Games.']};
function barcodeView(){const ss=eraHeld();const years=ss.map(s=>s.year);const cell={};const tot={};
  for(const s of ss)for(const w of s.awards){const n=w.nation;const c=cell[n]||(cell[n]={});const k=c[s.year]||(c[s.year]={gold:0,total:0});k.total++;if(w.rank===1)k.gold++;tot[n]=(tot[n]||0)+(w.rank===1?1:0);}
  const nations=Object.keys(cell).sort((a,b)=>tot[b]-tot[a]||a.localeCompare(b)).slice(0,30);const val=k=>k?k[state.heat]:0;const max=Math.max(1,...nations.flatMap(m=>years.map(y=>val(cell[m][y]))));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Barcode · ${esc(eraLabel())}</h2></div><div class="small mono muted">${nations.length} delegations × ${years.length} Games</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="heat" aria-label="Metric">${Object.entries(HEATMETRICS).map(([k,v])=>`<option value="${k}" ${k===state.heat?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(HEATMETRICS[state.heat][1])} Brightness is the cell’s share of the brightest cell; colour is the delegation’s. Rows ordered by gold medals; a dark cell is a Games the delegation went home from without one.</span></div>
  <div class="barcode"><div class="bc-row"><span></span><span class="cells" style="gap:2px">${years.map(y=>`<i style="background:none;height:14px;font-size:8px;color:var(--dim);text-align:center;line-height:14px">${String(y).slice(2)}</i>`).join('')}</span><span></span></div>${nations.map(m=>`<div class="bc-row"><span class="lab" data-nation="${esc(m)}">${esc(m)}</span><span class="cells">${years.map(y=>{const v=val(cell[m][y]);const a=v?Math.max(.12,v/max):0;return `<i data-year="${y}" title="${esc(m)} ${y} · ${v}" style="--c:${mixHex(color(m),'#0f1113',a)}"></i>`;}).join('')}</span><span class="tot">${fmt(tot[m])}</span></div>`).join('')}</div></div>`;
  $('#heat').addEventListener('change',e=>{state.heat=e.target.value;render();});}

/* ---------- Duel ---------- */
function swingChart(el,pts,labA,labB,cA,cB){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(180,box.height);const padL=30,padR=30,padT=16,padB=22;const n=pts.length;const max=Math.max(1,...pts.map(p=>Math.abs(p.v)));const x=i=>padL+(n>1?i*(W-padL-padR)/(n-1):(W-padL-padR)/2),y=v=>padT+(H-padT-padB)*(1-(v+max)/(2*max));
  const mid=y(0);let d='';pts.forEach((p,i)=>{d+=(i?'L':'M')+x(i).toFixed(1)+' '+y(p.v).toFixed(1);});
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Head-to-head swing"><line class="gridl" x1="${padL}" x2="${W-padR}" y1="${mid.toFixed(1)}" y2="${mid.toFixed(1)}"/><text class="lb" x="${padL}" y="${padT-4}" style="fill:${cA}">${esc(labA)} ahead</text><text class="lb" x="${padL}" y="${H-6}" style="fill:${cB}">${esc(labB)} ahead</text><path class="ser" d="${d}" style="--c:var(--muted)"/>${pts.map((p,i)=>`<circle class="pt" cx="${x(i).toFixed(1)}" cy="${y(p.v).toFixed(1)}" r="4" fill="${p.win==='A'?cA:p.win==='B'?cB:'#5b616b'}" data-year="${p.y}"><title>${esc(p.label)}</title></circle>`).join('')}</svg>`;}
function duelView(){const nations=nationAgg();const athletes=athleteAgg();
  if(state.duelBy==='a'){const ids=athletes.slice(0,200).map(p=>p.id);if(!state.dA||!(state.dA in ATH))state.dA=ids[0];if(!state.dB||!(state.dB in ATH)||state.dB===state.dA)state.dB=ids.find(i=>i!==state.dA);}
  else{const ids=nations.slice(0,60).map(m=>m.id);if(!state.dA||!ids.includes(state.dA))state.dA=ids[0];if(!state.dB||!ids.includes(state.dB)||state.dB===state.dA)state.dB=ids.find(i=>i!==state.dA);}
  const opts=sel=>state.duelBy==='a'?[...new Set([state.dA,state.dB,...athletes.slice(0,200).map(p=>p.id)])].filter(Boolean).map(id=>`<option value="${esc(id)}" ${id===sel?'selected':''}>${esc(aname(id))}</option>`).join(''):nations.slice(0,60).map(m=>`<option value="${esc(m.id)}" ${m.id===sel?'selected':''}>${esc(m.id)}</option>`).join('');
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Head to head · ${esc(eraLabel())}</h2></div><div class="small mono muted">${state.duelBy==='a'?'athletes · gold medals, and the podiums they shared':'delegations · gold medals, Games by Games'}</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="duelBy" aria-label="Compare"><option value="n" ${state.duelBy==='n'?'selected':''}>Nations</option><option value="a" ${state.duelBy==='a'?'selected':''}>Athletes</option></select><select id="dA" aria-label="First">${opts(state.dA)}</select><span class="mono small muted">vs</span><select id="dB" aria-label="Second">${opts(state.dB)}</select></div><div id="duelBody"></div></div>`;
  $('#duelBy').addEventListener('change',e=>{state.duelBy=e.target.value;state.dA=null;state.dB=null;render();});$('#dA').addEventListener('change',e=>{state.dA=e.target.value;render();});$('#dB').addEventListener('change',e=>{state.dB=e.target.value;render();});
  const a=state.dA,b=state.dB;if(!a||!b){$('#duelBody').innerHTML='<p class="muted">Pick two.</p>';return;}
  const isA=state.duelBy==='a';const has=(w,id)=>isA?w.athletes.includes(id):w.nation===id;const cA=isA?color(athletes.find(p=>p.id===a)?.nation||'?'):color(a),cB=isA?color(athletes.find(p=>p.id===b)?.nation||'?'):color(b);const nameOf=id=>isA?aname(id):id;
  const shared=[];let lead=0;const pts=[];let ga=0,gb=0,ha=0,hb=0,ta=0,tb=0;
  for(const s of eraHeld()){let ya=0,yb=0;for(const e of s.events){const wa=e.awards.find(w=>has(w,a)),wb=e.awards.find(w=>has(w,b));if(wa){ta++;if(wa.rank===1)ya++;}if(wb){tb++;if(wb.rank===1)yb++;}if(wa&&wb){shared.push({s,e,wa,wb});if(wa.rank<wb.rank)ha++;else if(wb.rank<wa.rank)hb++;}}ga+=ya;gb+=yb;lead+=ya-yb;pts.push({v:lead,win:ya>yb?'A':yb>ya?'B':'',y:s.year,label:`${s.year} · ${nameOf(a)} ${ya} · ${nameOf(b)} ${yb}`});}
  $('#duelBody').innerHTML=`<div class="duel-heads"><div class="dh" style="--team:${cA}"><span class="eyebrow">${esc(nameOf(a))}</span><b>${ga}</b><small>gold in the lens · ${ta} medals${shared.length?` · ahead in ${ha} of ${shared.length} shared podiums`:''}</small></div><div class="dh" style="--team:${cB}"><span class="eyebrow">${esc(nameOf(b))}</span><b>${gb}</b><small>gold in the lens · ${tb} medals${shared.length?` · ahead in ${hb}`:''}</small></div></div><div class="h3" style="margin-top:18px"><span>The lead in gold, Games by Games</span><small>cumulative</small></div><div class="chart" id="duelSwing" style="height:220px"></div>
  ${shared.length?`<div class="h3" style="margin-top:18px"><span>Podiums they shared</span><small>${shared.length} · same event, same Games</small></div><div class="tablewrap" style="max-height:480px"><table><tr><th>Games</th><th>Event</th><th style="color:${cA}">${esc(nameOf(a))}</th><th style="color:${cB}">${esc(nameOf(b))}</th></tr>${[...shared].reverse().slice(0,300).map(({s,e,wa,wb})=>`<tr><td><a href="#" data-year="${s.year}" data-event="${esc(e.id)}" style="color:inherit">${s.year}</a></td><td>${esc(e.sport)} · ${esc(evLabel(e))}</td><td>${mk(wa.rank)}${MEDALCAP[wa.rank]}</td><td>${mk(wb.rank)}${MEDALCAP[wb.rank]}</td></tr>`).join('')}</table></div>`:''}`;
  if(pts.length)swingChart($('#duelSwing'),pts,nameOf(a),nameOf(b),cA,cB);}

/* ---------- Sources & coverage ---------- */
function drawSources(){const cov=A.coverage||{};const src=A.sources||[];const lists=src.filter(s=>s.year&&/medal winners/i.test(s.title));const tables=src.filter(s=>s.year&&/medal table/i.test(s.title));const others=src.filter(s=>!s.year);const rev=s=>s.revision?`<a href="https://en.wikipedia.org/w/index.php?oldid=${esc(s.revision)}" target="_blank" rel="noopener">${esc(s.year||s.title)}</a>`:esc(s.year||s.title);
  $('#sourcesBody').innerHTML=`<p class="eyebrow">Games edition / ${esc(A.snapshot)}</p><h2>Every medal of every Summer Games, one archive.</h2><div class="kpis">${kpi('Games',fmt(cov.held),`${cov.cancelled} cancelled`)}${kpi('Medal events',fmt(cov.events),'')}${kpi('Medals',fmt(cov.awards),`${fmt(cov.gold)} gold`)}${kpi('Medallists',fmt(cov.medallists),'named athletes')}${kpi('Delegations',fmt(cov.nations),'')}${kpi('Sports',fmt(cov.sports),'')}${kpi('Tables reconciled',`${cov.validated}/${cov.held}`,'against the cited medal tables')}</div>
<h3>Sources</h3><ol><li>Wikipedia’s <b>list of medal winners</b> for each Games (<a href="${esc(A.licenceUrl)}" target="_blank" rel="noopener">CC BY-SA 4.0</a>, Wikipedia contributors), read at the recorded revisions on ${esc(A.retrieved)}: ${lists.map(rev).join(' · ')}<p>${esc(A.method||'')}</p></li><li>Wikipedia’s <b>medal table</b> for each Games, used only to reconcile the archive’s totals by delegation and colour: ${tables.map(rev).join(' · ')}</li>${others.length?`<li>Event and summary articles read to resolve what the lists left out or got wrong: ${others.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a>`).join(' · ')}</li>`:''}<li><a href="${esc(MAP.sourceUrl)}" target="_blank" rel="noopener">Natural Earth 1:110m land</a> (public domain)<p>The land silhouette behind every map, projected and rounded by the prototype; host cities are points at approximate coordinates, not venues.</p></li></ol>
<h3>What the atlas counts</h3>${(A.notes||[]).map(n=>`<p class="small muted">${esc(n)}</p>`).join('')}
<h3>Corrections and validation</h3><p class="small muted">All ${cov.validated} held Games reconcile by delegation and medal colour against the cited medal tables. ${(A.corrections||[]).length} events were corrected against their own articles where the lists were wrong or incomplete: ${(A.corrections||[]).map(c=>`<a href="${esc(c.source)}" target="_blank" rel="noopener">${esc(c.eventId)}</a>`).join(', ')}. ${Object.keys(A.aliases||{}).length} athlete name variants were consolidated. Events with a note carry it on their card.</p>
<h3>How to read the statistics</h3><p class="small muted">A medal is an award to a delegation in an event: a team, pair or relay counts once for its delegation and once for each named member on the athletes’ side. The medal table sorts by gold, then silver, then bronze; equal records share a place. The River shows each Games’ gold medals (or all medals) by delegation, its thickness the number of medal events in the lens. Delegations stay as the source names them across history. Cancelled Games are gaps, never zeros. The gold, silver and bronze of the earliest Games are retrospective labels.</p>`;}

/* ---------- deep links ---------- */
let routeLock=false;
function writeRoute(){if(routeLock)return;const q=[];if(state.sport!=='all')q.push('sport='+encodeURIComponent(state.sport));if(state.cat!=='all')q.push('cat='+encodeURIComponent(state.cat));if(state.era!=='all')q.push('era='+encodeURIComponent(state.era));if(state.whole)q.push('whole=1');else q.push('season='+state.year);q.push('tab='+state.tab);for(const [k,t] of [['athlete','athletes'],['nation','nations'],['sportv','sports'],['host','hosts']]){if(state.tab===t&&state[k])q.push(k+'='+encodeURIComponent(state[k]));}if(state.tab==='podium'&&!state.whole&&state.event)q.push('event='+encodeURIComponent(state.event));if(state.tab==='duel'&&state.dA&&state.dB)q.push('duel='+encodeURIComponent(state.dA+'|'+state.dB)+'&by='+state.duelBy);const h='#'+q.join('&');if(location.hash!==h){try{history[location.hash?'pushState':'replaceState'](null,'',h);}catch(e){}}}
function readRoute(){const h=location.hash.replace(/^#\/?/,'');if(!h||/^static-/.test(h))return false;const p={};for(const kv of h.split('&')){const i=kv.indexOf('=');p[i<0?kv:kv.slice(0,i)]=i<0?'1':decodeURIComponent(kv.slice(i+1));}let any=false;
  if(p.sport&&(p.sport==='all'||SPORTS.includes(p.sport))){state.sport=p.sport;any=true;}if(p.cat&&(p.cat==='all'||['Men','Women','Mixed','Open'].includes(p.cat))){state.cat=p.cat;any=true;}rebuildSeasons();
  if(p.era&&(p.era==='all'||ERAS.some(e=>e.id===p.era))){state.era=p.era;any=true;}
  if(p.season&&byYear[+p.season]){state.year=+p.season;any=true;}
  if(state.era!=='all'&&!inEraYear(state.year)){if(p.season)state.era='all';else state.year=eraHeld().slice(-1)[0]?.year||state.year;}
  state.whole=p.whole==='1';if(state.whole)any=true;
  if(p.tab&&TABS.some(t=>t[0]===p.tab)){state.tab=p.tab;any=true;}
  if(p.event&&evById[p.event]){state.event=p.event;state.year=evById[p.event].y;state.whole=false;any=true;}
  state.athlete=p.athlete&&(p.athlete in ATH)?p.athlete:null;state.nation=p.nation||null;state.sportv=p.sportv&&SPORTS.includes(p.sportv)?p.sportv:null;state.host=p.host&&hostOf(p.host)?p.host:null;
  if(p.duel){const [a,b]=p.duel.split('|');state.duelBy=p.by==='a'?'a':'n';state.dA=a;state.dB=b;any=true;}
  return any;}

/* ---------- render, navigation, events ---------- */
function render(){stopReplay();drawTabs();if(tour.stopped||!tour.timer)drawEraStrip();const v={season:seasonView,podium:podiumView,athletes:()=>state.athlete?athleteView(state.athlete):athletesView(),nations:()=>state.nation?nationView(state.nation):nationsView(),sports:()=>state.sportv?sportView(state.sportv):sportsView(),hosts:()=>state.host?hostView(state.host):hostsView(),records:recordsView,barcode:barcodeView,duel:duelView}[state.tab];try{v();}catch(e){$('#view').innerHTML=`<p class="muted">Something in this view could not be drawn: ${esc(e.message)}</p>`;console.error(e);}StageNav.draw();writeRoute();}
function go(tab,scroll=true){state.tab=tab;render();if(scroll)$('#stage').scrollIntoView({behavior:RM?'auto':'smooth',block:'start'});}
function ensureYearInLens(y){if(state.era!=='all'&&!inEraYear(y)){state.era='all';$('#eraSelect').value='all';}}
function setSeason(y,scroll){state.whole=false;ensureYearInLens(y);state.year=y;state.showAll=false;fillSeasons();applyTheme();drawRiver();if(state.tab!=='podium')state.tab='season';go(state.tab,scroll);}
function fillSeasons(){const sel=$('#season');const ss=eraSeasons();if(!ss.length){sel.innerHTML='';return;}const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);sel.innerHTML=`<option value="era">${e?'Whole era':'All Games'} · ${ss[0].year}–${ss[ss.length-1].year}</option>`+'<optgroup label="Newest first">'+ss.slice().reverse().map(s=>`<option value="${s.year}"${s.g.cancelled?' disabled':''}>${s.year} ${esc(s.g.city)}${s.g.cancelled?' · cancelled':''}</option>`).join('')+'</optgroup>';sel.value=state.whole?'era':state.year;}
function setEra(id){tourStop();state.era=id;$('#eraSelect').value=id;if(id!=='all'){if(!inEraYear(state.year)){const last=eraHeld().slice(-1)[0];state.year=last?last.year:state.year;}}fillSeasons();applyTheme();drawRiver();drawGrid();render();}
function relens(rerender=true){rebuildSeasons();if(!byYear[state.year]||byYear[state.year].g.cancelled)state.year=LAST_YEAR;state.athlete=null;state.nation=null;state.sportv=null;state.host=null;state.event=null;fillSeasons();$('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.filter(e=>e.to>=FIRST_YEAR&&e.from<=LAST_YEAR).map(e=>`<option value="${e.id}">${esc(ERA_SHORT[e.id]||e.name)} · ${e.from}–${e.to}</option>`).join('');if(![...$('#eraSelect').options].some(o=>o.value===state.era))state.era='all';$('#eraSelect').value=state.era;if(rerender){applyTheme();drawRiver();drawGrid();render();}}
function openEvent(id,scroll){const e=evById[id];if(!e)return;if(!inLens(e)){state.sport='all';state.cat='all';$('#family').value='all';$('#catSelect').value='all';rebuildSeasons();fillSeasons();}state.whole=false;ensureYearInLens(e.y);state.year=e.y;state.event=id;state.evSport=e.sport;fillSeasons();applyTheme();drawRiver();go('podium',scroll);}
function init(){
  landDefs();rebuildSeasons();
  $('#family').innerHTML=`<option value="all">All sports</option>`+SPORTS.map(f=>`<option value="${esc(f)}">${esc(f)}</option>`).join('');
  $('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.map(e=>`<option value="${e.id}">${esc(ERA_SHORT[e.id]||e.name)} · ${e.from}–${e.to}</option>`).join('');
  const topN=nationAgg().slice(0,16).map(m=>m.id);
  $('#theme').innerHTML=`<option value="champion">Nation of the Games</option>`+topN.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join('');
  fillSeasons();
  const cov=A.coverage||{};
  $('#edition').innerHTML=`<span><span class="live"></span><b>${fmt(cov.held)}</b> Games</span><span><b>${fmt(cov.events)}</b> medal events</span><span><b>${fmt(cov.awards)}</b> medals</span><span><b>${fmt(cov.medallists)}</b> medallists</span><span>through <b>${A.lastYear}</b></span>`;
  $('#reading').open=false;
  const deep=readRoute();if(deep){tourStop();$('#family').value=state.sport;$('#catSelect').value=state.cat;$('#eraSelect').value=state.era;fillSeasons();}
  drawSources();applyTheme();drawRiver();drawGrid();render();lightsOut();if(deep&&(state.tab!=='season'||state.whole||state.era!=='all'))setTimeout(()=>$('#stage').scrollIntoView({behavior:'auto',block:'start'}),60);
  addEventListener('hashchange',()=>{if(/^#static-/.test(location.hash)){$('#reading').open=true;return;}routeLock=true;try{if(readRoute()){tourStop();$('#family').value=state.sport;$('#catSelect').value=state.cat;$('#eraSelect').value=state.era;fillSeasons();applyTheme();drawRiver();drawGrid();render();}}finally{routeLock=false;}});
  $('#eraSelect').addEventListener('change',e=>setEra(e.target.value));
  $('#family').addEventListener('change',e=>{state.sport=e.target.value;relens();});
  $('#catSelect').addEventListener('change',e=>{state.cat=e.target.value;relens();});
  $('#season').addEventListener('change',e=>{if(e.target.value==='era'){state.whole=true;applyTheme();drawRiver();if(state.tab!=='podium')state.tab='season';go(state.tab,false);}else setSeason(+e.target.value,false);});
  $('#theme').addEventListener('change',applyTheme);
  $('#riverMetric').addEventListener('click',e=>{const b=e.target.closest('[data-metric]');if(!b)return;state.metric=b.dataset.metric;$$('#riverMetric button').forEach(x=>x.setAttribute('aria-pressed',x===b));riverModel=null;drawRiver();});
  $('#eraStrip').addEventListener('click',e=>{const s=e.target.closest('[data-era]');if(s)setEra(state.era===s.dataset.era?'all':s.dataset.era);});
  $('#eraStrip').addEventListener('pointerenter',()=>{tourPause();},{passive:true});$('#eraStrip').addEventListener('pointerleave',()=>{if(!tour.stopped)tourStart();},{passive:true});
  $('#eraStrip').addEventListener('mouseover',e=>{const s=e.target.closest('[data-era]');if(s&&!tour.stopped){drawEraStrip(s.dataset.era);}});
  if('IntersectionObserver' in window){new IntersectionObserver(en=>{tour.visible=en[0].isIntersecting;if(tour.visible)tourStart();else tourPause();},{threshold:.2}).observe($('#eraStrip'));}else{tour.visible=true;tourStart();}
  $('#gridSort').addEventListener('change',e=>{state.gridSort=e.target.value;drawGrid();});$('#gridFind').addEventListener('input',e=>{state.gridFind=e.target.value;drawGrid();});
  $('#circuits').addEventListener('click',e=>{const b=e.target.closest('[data-year]');if(b&&byYear[+b.dataset.year]&&!byYear[+b.dataset.year].g.cancelled)setSeason(+b.dataset.year,true);});
  $('#worldMap').addEventListener('click',e=>{const g=e.target.closest('[data-host]');if(g){state.host=g.dataset.host;go('hosts',true);}});
  const clear=t=>{if(t==='athletes')state.athlete=null;if(t==='nations')state.nation=null;if(t==='sports')state.sportv=null;if(t==='hosts')state.host=null;};
  $('#tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;clear(b.dataset.tab);go(b.dataset.tab,false);});
  $('#view').addEventListener('click',e=>{const a=e.target.closest('[data-event],[data-evsport],[data-athlete],[data-nation],[data-sportv],[data-host],[data-year],[data-tab]');if(!a)return;if(a.tagName==='A')e.preventDefault();
    if(a.dataset.event){openEvent(a.dataset.event,false);return;}
    if(a.dataset.evsport){state.evSport=a.dataset.evsport;state.event=null;go('podium',false);return;}
    if(a.dataset.tab){clear(a.dataset.tab);go(a.dataset.tab,false);return;}
    if(a.dataset.year){const y=+a.dataset.year;if(!byYear[y]||byYear[y].g.cancelled)return;setSeason(y,false);return;}
    if(a.dataset.athlete){state.athlete=a.dataset.athlete;go('athletes',false);return;}
    if(a.dataset.nation){state.nation=a.dataset.nation;go('nations',false);return;}
    if(a.dataset.sportv){state.sportv=a.dataset.sportv;go('sports',false);return;}
    if(a.dataset.host){state.host=a.dataset.host;go('hosts',false);return;}});
  addEventListener('resize',()=>{clearTimeout(window.__rz);window.__rz=setTimeout(()=>{drawRiver();if(['season','duel','records','hosts'].includes(state.tab))render();},150);});
}
StageNav.mount({seasons:()=>eraSeasons().map(s=>({year:s.year,cancelled:!!s.g.cancelled})),year:()=>state.year,whole:()=>state.whole,tab:()=>state.tab,setYear:y=>{if(byYear[y]&&!byYear[y].g.cancelled)setSeason(y,false);},unitTab:'podium',unitName:'Event',units:s=>{const t=byYear[s.year];return t?t.events.map(e=>({key:e.id,label:`${e.sport} · ${evLabel(e)}`})):[];},unit:()=>state.event,setUnit:k=>{openEvent(k,false);}});
StageSearch.mount({placeholder:'Find an athlete, a nation, a sport, an event or a Games',groups:[
  {kind:'Athletes',items:()=>{const n={};for(const w of AWARDS)for(const id of w.athletes)n[id]=(n[id]||0)+(w.rank===1?3:1);return Object.entries(ATH).map(([id,name])=>({label:name,rank:n[id]||0,keys:[id.replace(/_/g,' ')],open:()=>{state.athlete=id;go('athletes',false);}}));}},
  {kind:'Nations',items:()=>{const n={};for(const w of AWARDS)n[w.nation]=(n[w.nation]||0)+1;return NATIONS.map(m=>({label:m,rank:n[m]||0,open:()=>{state.nation=m;go('nations',false);}}));}},
  {kind:'Sports',items:()=>SPORTS.map(c=>({label:c,rank:EVENTS.filter(e=>e.sport===c).length,open:()=>{state.sportv=c;go('sports',false);}}))},
  {kind:'Events',items:()=>Object.entries(LIN).map(([k,es])=>{const e=es[es.length-1];return {label:`${evLabel(e)}`,sub:`${e.sport} · ${es.length} Games`,rank:es.length,keys:[e.sport],open:()=>openEvent(e.id,false)};})},
  {kind:'Hosts',items:()=>HOSTS.map(h=>({label:h.city,sub:h.countries.join(' / ')+' · '+h.years.join(', '),keys:['host'],open:()=>{state.host=h.city;go('hosts',false);}}))},
  {kind:'Games',items:()=>GAMES.filter(g=>!g.cancelled).map(g=>({label:`${g.year} ${g.city}`,sub:g.country,keys:['games',String(g.year)],open:()=>setSeason(g.year,false)}))}]});
init();
