/* ---------- the Grounds (the Grid): listed, in the colours of their winners ---------- */
function groundModel(){const ms=eraMatches();const m={};for(const r of ms){if(!r.v||!VENUES[r.v])continue;let c=m[r.v]||(m[r.v]={cid:r.v,count:0,first:r.year,last:r.year,wins:{},name:groundName(r.v),place:VENUES[r.v].city||'',country:'',locationOnly:!!VENUES[r.v].locationOnly});c.count++;c.first=Math.min(c.first,r.year);c.last=Math.max(c.last,r.year);if(r.winner)c.wins[r.winner]=(c.wins[r.winner]||0)+1;}
  return Object.values(m).map(c=>({...c,top:Object.entries(c.wins).sort((a,b)=>b[1]-a[1])[0]?.[0]||null}));}
function drawGrid(){const list=groundModel();const q=state.gridFind.trim().toLowerCase();const unrec=eraMatches().filter(m=>!m.v||!VENUES[m.v]).length;let shown=list.filter(c=>(q||c.count>=state.gridMin)&&(!q||(c.name+' '+c.place).toLowerCase().includes(q)));
  const sorters={count:(a,b)=>b.count-a.count||a.name.localeCompare(b.name),name:(a,b)=>a.name.localeCompare(b.name),country:(a,b)=>a.place.localeCompare(b.place)||b.count-a.count,recent:(a,b)=>b.last-a.last||b.count-a.count};shown.sort(sorters[state.gridSort]);
  const bigN=state.gridSort==='count'&&!q?6:0;const lo=list.filter(c=>c.locationOnly).length;
  $('#gridLede').textContent=`${list.length} grounds have staged an international in ${eraLabel().replace(' · ',', ')}${lo?` (${lo} recorded only as a city)`:''}${unrec?`; ${unrec.toLocaleString('en')} more matches have no ground recorded`:''}. Each carries the colour of the side that has won there most; the largest cards are the grounds the game has returned to most often.${shown.length<list.length&&!q?` Showing ${shown.length} with ${state.gridMin}+ matches.`:''}`;
  $('#circuits').innerHTML=shown.map((c,i)=>`<button type="button" class="circ flat${i<bigN?' big':''}" data-cid="${esc(c.cid)}" style="${c.top?teamVar(c.top):'--team:#8b9099'}" title="${esc(c.name)} · ${c.count} matches · ${c.first}–${c.last}${c.top?' · most wins: '+esc(c.top):''}"><span class="ct">${esc(c.place||'')}${c.locationOnly?' · city only':''}</span><span class="n">${c.count}</span><span class="nm">${esc(c.name)}</span><span class="yrs">${c.first}${c.last!==c.first?'–'+c.last:''}${c.top?' · <i style="background:var(--team)"></i>'+esc(c.top)+' '+c.wins[c.top]:''}</span></button>`).join('')||`<p class="muted">No ground matches.</p>`;}

/* ---------- Stage: tabs, era strip, era context ---------- */
const TABS=[['season','Season'],['match','Match'],['nations','Teams'],['players','Players'],['grounds','Grounds'],['records','Records'],['barcode','Barcode'],['duel','Duel']];
function drawTabs(){$('#tabs').innerHTML=TABS.map(([id,l])=>`<button type="button" role="tab" data-tab="${id}" aria-pressed="${state.tab===id}">${l}</button>`).join('');
  $('#stageStatus').textContent=(state.tab==='season'||state.tab==='match')&&!state.whole?`${state.year} · ${eraOf(state.year)?.name||''} · ${lensLabel()}`:eraLabel();}
function drawEraStrip(preview){const strip=$('#eraStrip');if(!strip.children.length)strip.innerHTML=ERAS.map(e=>`<button type="button" style="--w:${e.to-e.from+1}" data-era="${e.id}" title="${esc(e.name)} · ${e.from}–${e.to}" aria-label="${esc(e.name)} ${e.from}–${e.to}"></button>`).join('');
  for(const b of strip.children){b.classList.toggle('on',state.era===b.dataset.era);b.classList.toggle('demo',preview===b.dataset.era);}
  const e=preview?ERAS.find(x=>x.id===preview):state.era==='all'?eraOf(state.year):ERAS.find(x=>x.id===state.era);
  $('#eraCaption').innerHTML=`<span><b>${esc(e.name)}</b> · ${e.from}–${e.to}</span><span class="dim">${state.era===e.id?'Lens on · click again to release':'Click a segment to focus the whole page on that era'}</span>`;
  const ctx=$('#eraContext');ctx.innerHTML=`<div class="era-car">${e.ball.svg}</div><div><p class="eyebrow">${state.era===e.id?'Era lens':preview?'Era':'Era of the selected season'} · ${e.from}–${e.to}</p><h3>${esc(e.name)}</h3><p>${esc(e.text)}</p><div class="chips">${e.ball.features.map(f=>`<span>${esc(f)}</span>`).join('')}</div><p class="small dim" style="margin:10px 0 0">${esc(e.ball.label)} · an editorial reading of the period; the archive itself is not divided</p></div>`;}
const tour={i:-1,timer:null,visible:false,stopped:RM};
function tourStep(){if(tour.stopped||!tour.visible)return;tour.i=(tour.i+1)%ERAS.length;const ctx=$('#eraContext');ctx.classList.add('swap');setTimeout(()=>{if(tour.stopped)return;drawEraStrip(ERAS[tour.i].id);ctx.classList.remove('swap');},260);tour.timer=setTimeout(tourStep,4200);}
function tourStart(){if(tour.stopped||tour.timer)return;tour.timer=setTimeout(tourStep,1800);}
function tourPause(){clearTimeout(tour.timer);tour.timer=null;}
function tourStop(){if(tour.stopped)return;tour.stopped=true;tourPause();$('#eraContext').classList.remove('swap');drawEraStrip();}

/* ---------- shared pieces ---------- */
const scoreStr=i=>i[5]?'forfeited':`${i[1]}${i[2]<10?'/'+i[2]:''}${i[4]?'d':''}`;
const sides=(m,t)=>{const xs=(m.sc||[]).filter(i=>i[0]===t&&!i[6]);return xs.length?xs.map(scoreStr).join(' & '):'';};
const resultLine=m=>m.nr?'No result':m.result==='tie'?'Tied':m.result==='draw'?'Drawn':m.winner?`${m.winner} won${m.margin?' by '+m.margin:''}`:'—';
const compShort=m=>m.event?m.event.replace(/^ICC /,'').replace(/Men's |Men’s /,'').replace(/^Cricket World Cup$/,'World Cup')+(m.stage&&isNaN(+m.stage)?' · '+m.stage:''):m.f;
function matchCard(m,on){const w=m.winner;return `<button type="button" class="cal${on?' on':''}" data-match="${esc(m.id)}" style="${w?teamVar(w):'--team:#5b616b'}"><div class="rd">${esc(dm(m.date))} · ${esc(m.f)}${m.event?' · '+esc(compShort(m)).slice(0,22):''}</div><div class="sc"><span>${esc(code(m.home))}<small>${esc(sides(m,m.home))}</small></span><b>v</b><span>${esc(code(m.away))}<small>${esc(sides(m,m.away))}</small></span></div><div class="nm">${esc(m.home)} v ${esc(m.away)}</div><div class="w">${esc(resultLine(m))}</div></button>`;}
function natBars(rows,valOf,subOf,max,unit=''){return `<div class="board">${rows.map((a,i)=>`<button type="button" class="bar" data-nation="${esc(a.id)}" style="--i:${i};${teamVar(a.id)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(a.id)}<small> ${a.w}–${a.l}–${a.d}${a.nr?' · '+a.nr+' NR':''}</small></span><small>${subOf(a)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*valOf(a)/(max||1))}%"></span></span></span><span class="val">${valOf(a)}${unit}</span></button>`).join('')}</div>`;}
function drawChart(el,series,n,labelOf,xl){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(200,box.height);const padL=34,padR=110,padT=14,padB=26;const max=Math.max(1,...series.flatMap(s=>s.pts));const x=i=>padL+(n?i*(W-padL-padR)/n:0),y=v=>padT+(H-padT-padB)*(1-v/max);
  let g='';const step=max>200?100:max>60?25:max>20?10:max>8?5:1;for(let v=0;v<=max;v+=step)g+=`<line class="gridl" x1="${padL}" x2="${W-padR}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}"/><text class="lb" x="${padL-6}" y="${(y(v)+3).toFixed(1)}" text-anchor="end">${v}</text>`;
  for(let i=0;i<n;i++){const l=xl(i);if(l)g+=`<text class="lb" x="${x(i+1).toFixed(1)}" y="${H-8}" text-anchor="middle">${esc(l)}</text>`;}
  const paths=series.map(s=>{const d=s.pts.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1)).join('');const last=s.pts[s.pts.length-1];return `<path class="ser" d="${d}" style="--c:${color(s.id)}"><title>${esc(labelOf(s.id))} · ${fmt(last)}</title></path><text class="end" x="${(x(n)+6).toFixed(1)}" y="${(y(last)+4).toFixed(1)}" style="--c:${color(s.id)}">${esc(labelOf(s.id))} ${fmt(last)}</text>`;}).join('');
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Cumulative wins">${g}${paths}</svg>`;}

/* ---------- Season ---------- */
function seasonView(){if(state.whole)return eraView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No matches in this lens.</p>';return;}const ms=s.matches;const st=natStats(ms);const maxP=Math.max(...st.map(a=>a.p));const ranked=rankRecords(ms,3);const table=[...st].sort(recordOrder);
  const {best,cups}=champOf(s);const partial=String(s.year)===(A.lastDate||'').slice(0,4);const nations=st.length,grounds=new Set(ms.filter(m=>m.recorded).map(m=>m.v)).size;
  const podium=ranked.slice(0,3);const order=[podium[1],podium[0],podium[2]];
  const head=`<div class="season-head"><div class="champ-card" style="${best?`--accent:${color(best.id)};--on-accent:${onColor(color(best.id))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${partial?'Season in progress · results through '+esc(day(A.lastDate)):'Best record of the year'} · ${esc(lensLabel())}</p><div class="yr">${s.year}</div>${best?`<div class="who"><small>${partial?'Leads the year':'Best record'} · ${best.w}–${best.l}–${best.d}</small>${esc(best.id)}</div><div class="team"><i></i>${esc(nat(best.id).code)}</div><div class="facts"><div><b>${best.rate}%</b>win rate</div><div><b>${best.p}</b>matches</div><div><b>${ms.length}</b>matches this year</div><div><b>${nations}</b>sides</div></div>`:'<div class="who">No results yet</div>'}${cups.map(c=>`<p class="small" style="margin:14px 0 0;color:var(--ink);opacity:.85">${esc(c.label)}: <b>${esc(c.w.join(' & '))}</b>${c.runner?' · beat '+esc(c.runner):''}${c.note?' · '+esc(c.note):''}</p>`).join('')}<p class="small dim" style="margin:${cups.length?6:18}px 0 0">Ranked by wins minus losses, then win rate, among sides that played a real share of the year (${Math.min(Math.max(3,Math.round(maxP*0.4)),maxP)}+ matches).</p></div>
  <div><div class="podium">${order.map((d,i)=>d?`<button type="button" class="step p${podium.indexOf(d)+1} bar" data-nation="${esc(d.id)}" style="--h:${Math.round(120+120*d.rate/100)}px;${teamVar(d.id)};display:flex"><span class="pos">${podium.indexOf(d)+1}</span><span class="nm">${esc(d.id)}</span><span class="pt">${d.w}–${d.l}–${d.d} · ${d.rate}% · ${d.p} matches</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const cal=`<div class="h3"><span>The year’s matches</span><small>${ms.length} matches · click one to open it</small></div><div class="calendar">${ms.map(m=>matchCard(m,state.match===m.id&&state.tab==='match')).join('')}</div>`;
  const big=[...ms].filter(m=>m.marginN&&m.winner).sort((a,b)=>(b.marginN.by==='run')-(a.marginN.by==='run')||b.marginN.n-a.marginN.n).slice(0,10);
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Table of the year</span><small>every side that played · wins minus losses, then win rate</small></div>${natBars(table,a=>a.rate,a=>`${a.p} matches${a.hi?' · highest total '+a.hi:''}`,100,'%')}</div><div class="panel"><div class="h3"><span>Biggest wins of the year</span><small>by runs, then by wickets</small></div><div class="board">${big.map((m,i)=>`<button type="button" class="bar" data-match="${esc(m.id)}" style="--i:${i};${teamVar(m.winner)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(m.winner)}<small> v ${esc(m.loser)}</small></span><small>${esc(dm(m.date))} · ${esc(m.f)}${m.recorded?' · '+esc(groundName(m.v)):''}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*(m.marginN.by==='run'?m.marginN.n/(big[0].marginN.by==='run'?big[0].marginN.n:1):m.marginN.n/10))}%"></span></span></span><span class="val">${esc(m.margin)}</span></button>`).join('')||'<p class="muted small">No decided results.</p>'}</div></div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>The year, match by match</span><small>cumulative wins, top ${Math.min(8,st.length)} sides</small></div><div class="chart" id="cumChart"></div></div>`;
  $('#view').innerHTML=head+cal+body;
  const top=[...st].sort((a,b)=>b.w-a.w||b.rate-a.rate).slice(0,8);const series=top.map(a=>({id:a.id,pts:[0]}));for(const m of ms)for(const sr of series)sr.pts.push(sr.pts[sr.pts.length-1]+(m.winner===sr.id?1:0));
  let lastMon='';drawChart($('#cumChart'),series,ms.length,x=>x,i=>{const mon=ms[i].date.slice(5,7);if(mon===lastMon)return '';lastMon=mon;return new Date(ms[i].date+'T12:00:00Z').toLocaleDateString('en-GB',{month:'short',timeZone:'UTC'});});}

/* ---------- Whole era, combined ---------- */
function eraView(){const seasons=eraSeasons();const ms=eraMatches();if(!seasons.length){$('#view').innerHTML='<p class="muted">No matches in this lens.</p>';return;}const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);const label=e?e.name:'All eras';const span=`${seasons[0].year}–${seasons[seasons.length-1].year}`;
  const st=natStats(ms);const ranked=rankRecords(ms,10);const byWins=[...st].sort((a,b)=>b.w-a.w||b.rate-a.rate);
  const bests={};const roll=seasons.map(s=>{const c=champOf(s);if(c.best)bests[c.best.id]=(bests[c.best.id]||0)+1;return {year:s.year,d:c.best?.id,rec:c.best?`${c.best.w}–${c.best.l}–${c.best.d}`:'',cups:c.cups,n:s.matches.length};});
  const cups=CHAMPS.filter(c=>c.g===state.gender&&inEraYear(c.y)&&(state.fmt==='all'||c.f===state.fmt));const grounds=new Set(ms.filter(m=>m.recorded).map(m=>m.v)).size;
  const podium=ranked.slice(0,3);const order=[podium[1],podium[0],podium[2]];const top=ranked[0];
  const head=`<div class="season-head"><div class="champ-card" style="${top?`--accent:${color(top.id)};--on-accent:${onColor(color(top.id))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">Whole era, combined · ${seasons.length} seasons · ${esc(lensLabel())}</p><div class="yr" style="font-size:clamp(44px,6vw,84px)">${span}</div><div class="who"><small>${esc(label)} · best record</small>${esc(top?top.id:'—')}</div><div class="team"><i></i>${top?`${top.w}–${top.l}–${top.d} · ${top.rate}% of ${top.p} matches`:''}</div><div class="facts"><div><b>${fmt(ms.length)}</b>matches</div><div><b>${st.length}</b>sides</div><div><b>${grounds}</b>grounds</div><div><b>${cups.length}</b>ICC titles</div></div><p class="small" style="margin:18px 0 0;color:var(--ink);opacity:.85">Most wins: <b>${esc(byWins[0]?.id||'—')}</b> · ${byWins[0]?.w||0} matches won${Object.keys(bests).length?`<br><span class="dim">Best record of the year most often: ${esc(Object.entries(bests).sort((a,b)=>b[1]-a[1])[0][0])} (${Object.entries(bests).sort((a,b)=>b[1]-a[1])[0][1]} years)</span>`:''}</p></div>
  <div><div class="podium">${order.map(d=>d?`<button type="button" class="step p${podium.indexOf(d)+1} bar" data-nation="${esc(d.id)}" style="--h:${Math.round(120+120*d.rate/100)}px;${teamVar(d.id)};display:flex"><span class="pos">${podium.indexOf(d)+1}</span><span class="nm">${esc(d.id)}</span><span class="pt">${d.rate}% · ${d.w}–${d.l}–${d.d}</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const rollHtml=`<div class="h3"><span>Best record, year by year</span><small>click a year to open it</small></div><div class="calendar">${roll.map(c=>`<button type="button" class="cal" data-year="${c.year}" style="${c.d?teamVar(c.d):'--team:#5b616b'}"><div class="rd">${c.year} · ${c.n} matches</div><div class="nm" style="font-size:16px;margin-top:10px;color:var(--team)">${esc(c.d||'—')}</div><div class="w" style="color:var(--muted)">${c.rec}</div><div class="w">${c.cups.map(cp=>'⚑ '+esc(cp.w.join(' & '))).join(' ')}</div></button>`).join('')}</div>`;
  const pl=playerAgg().sort((a,b)=>b.runs-a.runs).slice(0,20);
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Sides across the era</span><small>by wins · ${st.length} sides</small></div>${natBars(byWins.slice(0,20),a=>a.w,a=>`${a.rate}% of ${a.p} matches`,byWins[0]?.w)}</div><div class="panel"><div class="h3"><span>Run-scorers across the era</span><small>recorded player-season figures</small></div><div class="board">${pl.map((p,i)=>`<button type="button" class="bar" data-player="${esc(p.id)}" style="--i:${i};${teamVar(p.team)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(p.id))}<small> ${esc(p.team)}</small></span><small>${p.games} matches · ${p.hundreds} hundreds</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*p.runs/(pl[0]?.runs||1))}%"></span></span></span><span class="val">${fmt(p.runs)}</span></button>`).join('')||'<p class="muted small">No player figures in this lens.</p>'}</div></div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Wins, season by season</span><small>cumulative wins, top ${Math.min(8,byWins.length)} by wins</small></div><div class="chart" id="cumChart"></div></div>`;
  $('#view').innerHTML=head+rollHtml+body;
  const series=byWins.slice(0,8).map(a=>({id:a.id,pts:[0]}));for(const s of seasons)for(const sr of series){let w=0;for(const m of s.matches)if(m.winner===sr.id)w++;sr.pts.push(sr.pts[sr.pts.length-1]+w);}
  drawChart($('#cumChart'),series,seasons.length,x=>x,i=>seasons.length<=20||i%Math.ceil(seasons.length/14)===0?String(seasons[i].year).slice(2):'');}
function eraMatchesView(){const ms=eraMatches();$('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Every match · ${esc(eraLabel())}</span><small>${fmt(ms.length)} matches · click one to open it</small></div><div class="tablewrap"><table><tr><th>Date</th><th>Format</th><th>Sides</th><th>Scores</th><th>Result</th><th>Ground</th></tr>${ms.slice().reverse().slice(0,1200).map(m=>`<tr><td><a href="#" data-match="${esc(m.id)}" style="color:inherit">${esc(day(m.date))}</a></td><td>${esc(m.f)}</td><td><i class="dot" style="${teamVar(m.home)}"></i>${esc(m.home)} v <i class="dot" style="${teamVar(m.away)}"></i>${esc(m.away)}</td><td>${esc(sides(m,m.home))}${sides(m,m.home)&&sides(m,m.away)?' · ':''}${esc(sides(m,m.away))}</td><td>${esc(resultLine(m))}</td><td>${m.v&&VENUES[m.v]?`<a href="#" data-ground="${esc(m.v)}" style="color:inherit">${esc(groundName(m.v))}</a>`:'<span class="dim">not recorded</span>'}</td></tr>`).join('')}</table></div>${ms.length>1200?`<p class="small dim">Showing the most recent 1,200 of ${fmt(ms.length)}; narrow the lens or open a season for the rest.</p>`:''}`;}
