/* ---------- Match: the sheet, the scorecards and the innings replay ---------- */
let replay=null;
function stopReplay(){if(replay){cancelAnimationFrame(replay.raf);replay=null;}}
const detailOf=m=>DETAILS[m.year]?.[m.id]||null;
let loading={};
function loadDetails(year){if(DETAILS[year]||!DETAIL_URL||loading[year])return Promise.resolve();loading[year]=true;return fetch(`${DETAIL_URL}${year}.json`).then(r=>r.ok?r.json():{}).then(j=>{DETAILS[year]=j||{};}).catch(()=>{DETAILS[year]={};}).finally(()=>{loading[year]=false;});}
const overs=b=>`${Math.floor(b/6)}.${b%6}`;
function dismissal(ba){const kind=ba[5],bowler=ba[6]?pname(ba[6]):'',fs=(ba[7]||[]).map(pname).join(' / ');if(kind==='caught')return 'c '+(fs||'fielder not recorded')+' b '+bowler;if(kind==='caught and bowled')return 'c & b '+bowler;if(kind==='stumped')return 'st '+(fs||'keeper not recorded')+' b '+bowler;if(kind==='bowled')return 'b '+bowler;if(kind==='lbw')return 'lbw b '+bowler;if(kind==='run out')return 'run out'+(fs?' ('+fs+')':'');if(kind==='not out')return 'not out';return kind||'—';}
function inningsCard(i,k){const os=i[10]||[];const bat=(i[8]||[]).map(b=>`<tr><td><a href="#" data-player="${esc(b[0])}" style="color:inherit">${esc(pname(b[0]))}</a></td><td class="dim">${esc(dismissal(b))}</td><td><b>${b[1]}${['not out','retired hurt','retired not out'].includes(b[5])?'*':''}</b></td><td>${b[2]}</td><td>${b[3]}</td><td>${b[4]}</td><td>${b[2]?(100*b[1]/b[2]).toFixed(0):'—'}</td></tr>`).join('');
  const bowl=(i[9]||[]).map(b=>`<tr><td><a href="#" data-player="${esc(b[0])}" style="color:inherit">${esc(pname(b[0]))}</a></td><td>${overs(b[1])}</td><td>${b[4]}</td><td>${b[2]}</td><td><b>${b[3]}</b></td><td>${b[1]?(6*b[2]/b[1]).toFixed(2):'—'}</td></tr>`).join('');
  const ex=i[7]||[0,0,0,0,0];
  return `<details class="inn"${k===0?' open':''}><summary><span class="eyebrow" style="margin:0">${i[6]?'Super Over':'Innings '+(k+1)}</span><b style="${teamVar(i[0])}"><i class="dot" style="${teamVar(i[0])}"></i>${esc(i[0])}</b><span class="tot">${esc(scoreStr(i))}</span><span class="dim">${overs(i[3])} overs${i[12]?' · target '+i[12]:''}</span></summary>
  ${os.length?`<div class="worm" data-k="${k}"><svg viewBox="0 0 900 220" class="wormsvg" role="img" aria-label="Runs by over"></svg><div class="wormscore"><b class="r">0</b><span class="dim">for</span><b class="w">0</b><span class="dim ov">over 0 of ${os.length}</span></div></div>`:''}
  <div class="sheet"><div><div class="h3"><span>Batting</span></div><div class="tablewrap" style="max-height:none"><table><tr><th>Batter</th><th></th><th>R</th><th>B</th><th>4s</th><th>6s</th><th>SR</th></tr>${bat}</table></div><p class="small dim" style="margin:6px 0 0">Extras ${ex.reduce((a,b)=>a+b,0)} · wides ${ex[0]} · no-balls ${ex[1]} · byes ${ex[2]} · leg-byes ${ex[3]}${ex[4]?' · penalties '+ex[4]:''}</p></div><div><div class="h3"><span>Bowling</span></div><div class="tablewrap" style="max-height:none"><table><tr><th>Bowler</th><th>O</th><th>M</th><th>R</th><th>W</th><th>Econ</th></tr>${bowl}</table></div>${(i[11]||[]).length?`<p class="small dim" style="margin:8px 0 0">Fall of wickets: ${i[11].map(w=>`${w[0]}/${w[1]} (${esc(pname(w[3]))}, ${esc(w[2])})`).join(' · ')}</p>`:''}</div></div></details>`;}
function matchView(){if(state.whole)return eraMatchesView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No matches in this lens.</p>';return;}let m=byId[state.match];if(!m||m.year!==s.year||!inLens(m))m=s.matches[s.matches.length-1];state.match=m.id;
  const many=s.matches.length>36;const nav=`<div class="chiplist${many?' many':''}" id="matchNav" style="margin-top:20px">${s.matches.map(x=>`<button type="button" class="chip${x.id===m.id?' on':''}" data-match="${esc(x.id)}" style="${x.id===m.id?'border-color:var(--accent);color:var(--accent)':''}"><i style="--c:${x.winner?color(x.winner):'#444'}"></i>${esc(dm(x.date))} ${esc(code(x.home))}–${esc(code(x.away))}</button>`).join('')}</div>`;
  const d=detailOf(m);const inn=d?d.inn||[]:[];
  const hero=`<div class="replay" id="replay"><div class="hud"><div><h3>${esc(m.home)} v ${esc(m.away)}</h3><div class="sub">${esc(day(m.date))}${m.end&&m.end!==m.date?' – '+esc(dm(m.end)):''} · ${esc(m.f)}${m.event?' · '+esc(m.event):''}${m.stage&&isNaN(+m.stage)?' · '+esc(m.stage):''}${m.recorded?' · '+esc(groundName(m.v)):''}</div></div><div class="whistle">${m.nr?'NR':m.draw?(m.result==='tie'?'TIE':'DRAW'):'RESULT'}</div></div>
  <div class="scoreboard">${m.teams.map(t=>`<div class="sb" style="${teamVar(t)}"><span class="tn"><i class="dot" style="${teamVar(t)}"></i>${esc(t)}</span><b>${esc(sides(m,t)||'—')}</b></div>`).join('')}</div><p class="result">${esc(resultLine(m))}${m.method?' · '+esc(m.method):''}</p>
  ${inn.length?inn.map((i,k)=>inningsCard(i,k)).join(''):d?'<p class="small dim">No scorecard is held for this match.</p>':(DETAIL_URL&&m.detail?'<p class="small dim" id="detailWait">Fetching the scorecard…</p>':'<p class="small dim">This record carries the result, date and ground; no scorecard is recorded in the source.'+(m.rawDate?' Original date listing: '+esc(m.rawDate)+'.':'')+'</p>')}
  ${inn.some(i=>(i[10]||[]).length)?'<p class="small dim" style="margin:10px 0 0">The worm builds the innings over by over from the recorded deliveries: a symbolic replay of the scoring, not a broadcast.</p>':''}</div>`;
  const hh=h2hBefore(m);const form=side=>{const prev=MATCHES.filter(x=>x.date<m.date&&x.g===m.g&&(state.fmt==='all'||x.f===state.fmt)&&x.teams.includes(side)).slice(-10);return `<div class="ribbon">${prev.map(x=>`<i class="${resClass(x,side)}" title="${esc(day(x.date))} v ${esc(x.home===side?x.away:x.home)} · ${esc(resultLine(x))}" data-match="${esc(x.id)}"></i>`).join('')}</div>`;};
  const lineups=d&&d.players&&d.players.length?`<div class="h3" style="margin-top:20px"><span>Line-ups</span></div><div class="two" style="gap:14px">${d.players.map(([t,ids])=>`<div><p class="eyebrow" style="margin:0 0 6px">${esc(t)}</p><div class="chiplist">${ids.map(id=>`<button type="button" class="chip" data-player="${esc(id)}"><i style="--c:${color(t)}"></i>${esc(pname(id))}${(m.pom||[]).includes(id)?' ★':''}</button>`).join('')}</div></div>`).join('')}</div>`:'';
  const side=`<div><div class="h3"><span>Before the toss</span><small>the record between these two, ${esc(m.f)}</small></div><div class="kpis" style="grid-template-columns:1fr 1fr"><div class="kpi" style="border-color:${color(m.home)}"><span>${esc(m.home)}</span><b>${hh.a?hh.a.w:0}</b><small>wins in ${hh.n} previous ${m.f} meetings</small>${form(m.home)}</div><div class="kpi" style="border-color:${color(m.away)}"><span>${esc(m.away)}</span><b>${hh.b?hh.b.w:0}</b><small>wins in ${hh.n} previous meetings${hh.a&&hh.a.d?' · '+hh.a.d+' drawn or tied':''}</small>${form(m.away)}</div></div><p class="small dim" style="margin:8px 0 0">Each side’s last ten matches in this lens: green won, red lost, grey drawn or tied, dark no result.</p>${lineups}
  <div class="kpis" style="margin-top:18px"><div class="kpi"><span>Toss</span><b style="font-size:20px">${m.toss&&m.toss[0]?esc(m.toss[0])+' · '+esc(m.toss[1]):'—'}</b><small>${m.toss&&m.toss[0]?'chose to '+esc(m.toss[1]):'not recorded'}</small></div><div class="kpi"><span>Player of the match</span><b style="font-size:20px">${(m.pom||[]).length?m.pom.map(id=>`<a href="#" data-player="${esc(id)}" style="color:inherit;text-decoration:none">${esc(pname(id))}</a>`).join(' / '):'—'}</b></div><div class="kpi"><span>Ground</span><b style="font-size:20px">${m.v&&VENUES[m.v]?`<a href="#" data-ground="${esc(m.v)}" style="color:inherit;text-decoration:none">${esc(groundName(m.v))}</a>`:'Not recorded'}</b><small>${esc(VENUES[m.v]?.city||'')}</small></div><div class="kpi"><span>Match no.</span><b style="font-size:20px">${m.no?esc(m.f)+' #'+m.no:'—'}</b><small>${esc(m.source==='cricsheet'?'Cricsheet scorecard':'historical results dataset')}</small></div></div></div>`;
  $('#view').innerHTML=`${nav}<div class="race">${hero}${side}</div>`;
  {const on=$('#matchNav .chip.on');if(on&&many){const nv=$('#matchNav');nv.scrollTop=Math.max(0,on.offsetTop-nv.clientHeight/2+on.offsetHeight/2);}}
  if(inn.length)runWorms();else if(DETAIL_URL&&m.detail&&!d){loadDetails(m.year).then(()=>{if(state.tab==='match'&&state.match===m.id)render();});}}
function runWorms(){stopReplay();const worms=$$('.worm');if(!worms.length)return;const m=byId[state.match];const d=detailOf(m);const rp={raf:0,t:0,last:0,dur:RM?1:9000,items:[]};replay=rp;
  for(const el of worms){const i=d.inn[+el.dataset.k];const os=i[10];const cum=[0],wk=[0];for(const o of os){cum.push(cum[cum.length-1]+o[1]);wk.push(wk[wk.length-1]+o[2]);}const max=Math.max(1,...cum);const W=900,H=220,pl=36,pr=20,pt=16,pb=30;const x=j=>pl+(W-pl-pr)*j/os.length,y=r=>pt+(H-pt-pb)*(1-r/max);
    const svg=el.querySelector('svg');const grid=[0,.25,.5,.75,1].map(f=>`<line class="gridl" x1="${pl}" x2="${W-pr}" y1="${y(max*f).toFixed(1)}" y2="${y(max*f).toFixed(1)}"/><text class="lb" x="${pl-6}" y="${(y(max*f)+3).toFixed(1)}" text-anchor="end">${Math.round(max*f)}</text>`).join('');
    const full=cum.map((r,j)=>(j?'L':'M')+x(j).toFixed(1)+' '+y(r).toFixed(1)).join('');const ovs=os.filter((o,j)=>os.length<=20||j%5===4).map(o=>`<text class="lb" x="${x(o[0]+1).toFixed(1)}" y="${H-10}" text-anchor="middle">${o[0]+1}</text>`).join('');
    svg.innerHTML=`${grid}${ovs}<path class="ghost" d="${full}"/><path class="live" d="" style="--c:${color(i[0])}"/><g class="wkts"></g><circle class="head" r="5" style="--c:${color(i[0])}"/>`;
    rp.items.push({el,i,os,cum,wk,x,y,live:svg.querySelector('.live'),head:svg.querySelector('.head'),wg:svg.querySelector('.wkts'),r:el.querySelector('.r'),w:el.querySelector('.w'),ov:el.querySelector('.ov')});}
  const place=t=>{for(const it of rp.items){const n=Math.min(it.os.length,Math.floor(t*it.os.length+1e-9));const d=it.cum.slice(0,n+1).map((r,j)=>(j?'L':'M')+it.x(j).toFixed(1)+' '+it.y(r).toFixed(1)).join('');it.live.setAttribute('d',d);it.head.setAttribute('cx',it.x(n).toFixed(1));it.head.setAttribute('cy',it.y(it.cum[n]).toFixed(1));it.r.textContent=it.cum[n];it.w.textContent=it.wk[n];it.ov.textContent=`over ${n} of ${it.os.length}`;
      let marks='';for(let j=1;j<=n;j++)if(it.os[j-1][2])marks+=`<circle cx="${it.x(j).toFixed(1)}" cy="${it.y(it.cum[j]).toFixed(1)}" r="3.5" class="wk"><title>${it.os[j-1][2]} wicket${it.os[j-1][2]>1?'s':''} in over ${j}</title></circle>`;it.wg.innerHTML=marks;}};
  const tick=now=>{if(replay!==rp)return;if(rp.last)rp.t=Math.min(1,rp.t+(now-rp.last)/rp.dur);rp.last=now;place(rp.t);if(rp.t<1)rp.raf=requestAnimationFrame(tick);else $('#replay').classList.add('done');};
  place(0);rp.raf=requestAnimationFrame(tick);
  for(const it of rp.items){it.el.onclick=()=>{rp.t=0;rp.last=0;$('#replay').classList.remove('done');if(replay!==rp){replay=rp;}cancelAnimationFrame(rp.raf);rp.raf=requestAnimationFrame(tick);};}}
function h2hBefore(m){const ms=MATCHES.filter(x=>x.date<m.date&&x.g===m.g&&x.f===m.f&&x.teams.includes(m.home)&&x.teams.includes(m.away));const st=natStats(ms);const a=st.find(x=>x.id===m.home),b=st.find(x=>x.id===m.away);return {n:ms.length,a,b};}

/* ---------- Teams (nations) ---------- */
function radar(el,axes,a,b){const W=260,H=260,cx=130,cy=130,R=96,n=axes.length;const pt=(i,v)=>{const ang=-Math.PI/2+i*2*Math.PI/n;return [cx+Math.cos(ang)*R*v,cy+Math.sin(ang)*R*v];};
  let g='';for(const k of [.25,.5,.75,1])g+=`<polygon class="ring" points="${axes.map((_,i)=>pt(i,k).map(v=>v.toFixed(1)).join(',')).join(' ')}"/>`;for(let i=0;i<n;i++){const [x,y]=pt(i,1);g+=`<line class="axis" x1="${cx}" y1="${cy}" x2="${x.toFixed(1)}" y2="${y.toFixed(1)}"/>`;const [lx,ly]=pt(i,1.24);g+=`<text class="lbl" x="${lx.toFixed(1)}" y="${(ly+3).toFixed(1)}">${esc(axes[i].label)}</text>`;}
  const poly=(vals,cls)=>`<polygon class="poly ${cls}" points="${vals.map((v,i)=>pt(i,Math.max(0,Math.min(1,v))).map(q=>q.toFixed(1)).join(',')).join(' ')}"/>`;el.innerHTML=`<svg viewBox="0 0 ${W} ${H}">${g}${poly(a,'a')}${b?poly(b,'b'):''}</svg>`;}
const AXES=[{k:'w',label:'Wins'},{k:'rate',label:'Win %'},{k:'p',label:'Matches'},{k:'hi',label:'Top total'},{k:'streak',label:'Best run'},{k:'cups',label:'Titles'}];
function normAxes(list){const max={};for(const ax of AXES)max[ax.k]=Math.max(1,...list.map(a=>a[ax.k]));return a=>AXES.map(ax=>a[ax.k]/max[ax.k]);}
function nationsView(){const ms=eraMatches();const list=natStats(ms);const lens=state.lens;const min=/rate/.test(lens)?10:0;const rows=list.filter(a=>a.p>=min).sort((a,b)=>b[lens]-a[lens]||b.w-a.w).slice(0,40);const max=Math.max(1,...rows.map(a=>a[lens]));const q=(state.find2||'').toLowerCase();const found=q?list.filter(a=>a.id.toLowerCase().includes(q)).slice(0,12):[];
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Teams · ${esc(eraLabel())}</span><small>${list.length} sides · ${fmt(ms.length)} matches</small></div><div class="panel"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:14px"><input type="search" id="find2" placeholder="Search a team" value="${esc(state.find2||'')}" aria-label="Search"><select id="lens" aria-label="Lens">${Object.entries(LENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(LENSES[lens][1])}</span></div>${q?`<div class="chiplist" style="margin-bottom:14px">${found.map(a=>`<button type="button" class="chip" data-nation="${esc(a.id)}"><i style="--c:${color(a.id)}"></i>${esc(a.id)}</button>`).join('')||'<span class="muted small">No match.</span>'}</div>`:''}
  ${natBars(rows,a=>a[lens],a=>`${a.p} matches · ${a.first}–${a.last}`,max,/rate/.test(lens)?'%':'')}</div>`;}
function seasonsTable(id){const out=[];for(const s of S){const ms=s.matches.filter(m=>m.teams.includes(id));if(!ms.length)continue;const a=natStats(ms).find(x=>x.id===id);out.push({year:s.year,...a});}return out;}
function nationView(id){const ms=eraMatches();const all=natStats(ms);const a=all.find(x=>x.id===id);const back=`<button type="button" class="btn" data-tab="nations">← All teams</button>`;const t=nat(id);
  if(!a){$('#view').innerHTML=`<div style="margin-top:22px">${back}</div><p class="muted" style="margin-top:16px">${esc(id)} played no match in ${esc(eraLabel())}. Change the lens to see them.</p>`;return;}
  const mine=ms.filter(m=>m.teams.includes(id));const norm=normAxes(all.filter(x=>x.p>=10));
  const ribbon=mine.map(m=>`<i class="${resClass(m,id)}" title="${esc(day(m.date))} v ${esc(m.home===id?m.away:m.home)} · ${esc(resultLine(m))}" data-match="${esc(m.id)}"></i>`).join('');
  const opp={};for(const m of mine){const o=m.home===id?m.away:m.home;let r=opp[o]||(opp[o]={id:o,p:0,w:0,d:0,l:0,nr:0});r.p++;const rc=resClass(m,id);if(rc==='W')r.w++;else if(rc==='L')r.l++;else if(rc==='D')r.d++;else r.nr++;}const opps=Object.values(opp).sort((a,b)=>b.p-a.p);
  const tbl=seasonsTable(id).filter(x=>inEraYear(x.year));const cups=CHAMPS.filter(c=>c.g===state.gender&&inEraYear(c.y)&&(state.fmt==='all'||c.f===state.fmt)&&(c.w.includes(id)||c.runner===id));
  const players=playerAgg().filter(p=>p.team===id).sort((a,b)=>b.runs-a.runs).slice(0,8);const bowlers=playerAgg().filter(p=>p.team===id).sort((a,b)=>b.wickets-a.wickets).slice(0,8);
  $('#view').innerHTML=`<div style="margin-top:22px;display:flex;gap:10px;flex-wrap:wrap;align-items:center">${back}<span class="small muted">${esc(eraLabel())}</span></div>
  <div class="card" style="margin-top:18px;${teamVar(id)}"><div class="panel"><div class="trace" id="trace"></div><p class="small dim" style="text-align:center;margin:8px 0 0">Form trace · each axis relative to the best side in this lens (10+ matches)</p></div>
  <div><p class="eyebrow">${t.major?'Full member':'Side'} · ${a.first}–${a.last} · ${esc(t.code)}</p><h2 class="display" style="font-size:clamp(40px,6vw,84px);margin:6px 0 0;color:var(--team);text-shadow:0 0 30px rgba(255,255,255,.18)">${esc(id)}</h2>
  <div class="kpis" style="margin-top:18px"><div class="kpi"><span>Matches</span><b>${a.p}</b><small>${a.w}–${a.l}–${a.d}${a.nr?' · '+a.nr+' no result':''}</small></div><div class="kpi"><span>Win rate</span><b>${a.rate}%</b><small>draws and no-results count as not won</small></div>${FORMATS.filter(f=>a.byF[f]).map(f=>`<div class="kpi"><span>${f}</span><b>${a.byF[f].w}–${a.byF[f].l}–${a.byF[f].d}</b><small>${a.byF[f].p} matches · ${pct(a.byF[f].w,a.byF[f].p)}%</small></div>`).join('')}<div class="kpi"><span>Best run</span><b>${a.streak}</b><small>consecutive wins</small></div><div class="kpi"><span>ICC titles</span><b>${a.cups}</b><small>${cups.filter(c=>c.w.includes(id)).map(c=>c.y).join(', ')||'in lens'}</small></div>${a.hi?`<div class="kpi"><span>Highest total</span><b>${a.hi}</b><small>recorded scorecards</small></div>`:''}</div>
  <div class="h3" style="margin-top:20px"><span>Every match</span><small>green won · red lost · grey drawn or tied · dark no result · click to open</small></div><div class="ribbon">${ribbon}</div></div></div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Record by opponent</span><small>most met first</small></div>${natBars(opps.slice(0,16),r=>r.w,r=>`${r.p} matches · ${pct(r.w,r.p)}% won`,Math.max(1,...opps.map(r=>r.w)))}</div><div class="panel">${players.length?`<div class="h3"><span>Run-scorers</span><small>recorded figures in the lens</small></div><div class="board">${players.map((p,i)=>`<button type="button" class="bar" data-player="${esc(p.id)}" style="--i:${i};${teamVar(id)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(p.id))}<small> ${p.games} matches</small></span><small>${p.hundreds} hundreds · avg ${p.batavg!=null?p.batavg.toFixed(1):'—'}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*p.runs/(players[0].runs||1))}%"></span></span></span><span class="val">${fmt(p.runs)}</span></button>`).join('')}</div><div class="h3" style="margin-top:16px"><span>Wicket-takers</span></div><div class="board">${bowlers.map((p,i)=>`<button type="button" class="bar" data-player="${esc(p.id)}" style="--i:${i};${teamVar(id)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(p.id))}<small> ${p.games} matches</small></span><small>avg ${p.bowlavg!=null?p.bowlavg.toFixed(1):'—'}${p.five?' · '+p.five+' five-fors':''}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*p.wickets/(bowlers[0].wickets||1))}%"></span></span></span><span class="val">${fmt(p.wickets)}</span></button>`).join('')}</div>`:'<p class="muted small">No recorded player figures in this lens.</p>'}${cups.length?`<div class="h3" style="margin-top:16px"><span>ICC tournaments</span></div><div class="tablewrap"><table><tr><th>Year</th><th>Tournament</th><th>Outcome</th></tr>${cups.map(c=>`<tr><td>${c.y}</td><td>${esc(c.label)}</td><td>${c.w.includes(id)?'<b style="color:var(--gold)">Champions ★</b>':'Runners-up'}${c.note?' · '+esc(c.note):''}</td></tr>`).join('')}</table></div>`:''}</div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Season by season</span></div><div class="tablewrap"><table><tr><th>Year</th><th>P</th><th>W</th><th>L</th><th>D/T</th><th>NR</th><th>Win %</th><th>Biggest win</th></tr>${tbl.slice().reverse().map(x=>`<tr><td><a href="#" data-year="${x.year}" style="color:inherit">${x.year}</a></td><td>${x.p}</td><td>${x.w}</td><td>${x.l}</td><td>${x.d}</td><td>${x.nr}</td><td>${x.rate}%</td><td>${x.big?`<a href="#" data-match="${esc(x.big.id)}" style="color:inherit">by ${esc(x.big.margin)} v ${esc(x.big.home===id?x.big.away:x.big.home)}</a>`:'—'}</td></tr>`).join('')}</table></div></div>`;
  radar($('#trace'),AXES,norm(a));}

/* ---------- Players (recorded player-season figures) ---------- */
let aggCache={};
function playerAgg(){const key=[state.gender,state.fmt,state.era].join('|');if(aggCache[key])return aggCache[key];const [y0,y1]=eraRange();const map={};
  for(const r of PS){if(r.g!==state.gender||(state.fmt!=='all'&&r.f!==state.fmt)||r.y<y0||r.y>y1)continue;let a=map[r.p]||(map[r.p]={id:r.p,teams:{},games:0,inns:0,runs:0,balls:0,outs:0,notouts:0,fours:0,sixes:0,fifties:0,hundreds:0,binns:0,bballs:0,conceded:0,wickets:0,maidens:0,five:0,catches:0,stumps:0,runouts:0,pom:0,hs:0,hsno:false,bbw:0,bbr:0,first:r.y,last:r.y});
    for(const k of ['games','inns','runs','balls','outs','notouts','fours','sixes','fifties','hundreds','binns','bballs','conceded','wickets','maidens','five','catches','stumps','runouts','pom'])a[k]+=r[k]||0;
    if(r.hs>a.hs||(r.hs===a.hs&&r.hsno)){a.hs=r.hs;a.hsno=!!r.hsno;}if(r.bbw>a.bbw||(r.bbw===a.bbw&&r.bbw&&r.bbr<a.bbr)){a.bbw=r.bbw;a.bbr=r.bbr;}
    a.teams[r.t]=(a.teams[r.t]||0)+r.games;a.first=Math.min(a.first,r.y);a.last=Math.max(a.last,r.y);}
  const out=Object.values(map).map(a=>({...a,team:Object.entries(a.teams).sort((x,y)=>y[1]-x[1])[0][0],batavg:a.outs?a.runs/a.outs:null,bowlavg:a.wickets?a.conceded/a.wickets:null,sr:a.balls?100*a.runs/a.balls:null,econ:a.bballs?6*a.conceded/a.bballs:null}));
  return aggCache[key]=out;}
function playersView(){const list=playerAgg();const lens=state.plens;let rows=list.filter(p=>p[lens]!=null);if(lens==='batavg')rows=rows.filter(p=>p.inns>=20);if(lens==='bowlavg')rows=rows.filter(p=>p.wickets>=20);rows.sort(lens==='bowlavg'?(a,b)=>a[lens]-b[lens]:(a,b)=>b[lens]-a[lens]||b.games-a.games);rows=rows.slice(0,40);const max=Math.max(1,...rows.map(p=>p[lens]));const q=(state.find2||'').toLowerCase();const found=q?Object.entries(PLAYERS).filter(([id,p])=>p.n.toLowerCase().includes(q)).slice(0,12):[];
  $('#view').innerHTML=`<div class="h3" style="margin-top:22px"><span>Players · ${esc(eraLabel())}</span><small>${fmt(list.length)} with recorded figures</small></div><div class="panel"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:14px"><input type="search" id="find2" placeholder="Search a player" value="${esc(state.find2||'')}" aria-label="Search"><select id="plens" aria-label="Lens">${Object.entries(PLENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(PLENSES[lens][1])} Figures come from recorded scorecards (from 2001 for Tests and ODIs, 2005 for T20Is) and are not complete careers.</span></div>${q?`<div class="chiplist" style="margin-bottom:14px">${found.map(([id,p])=>`<button type="button" class="chip" data-player="${esc(id)}"><i style="--c:${color((p.teams||[])[0]||'')}"></i>${esc(p.n)} <span class="dim">${esc((p.teams||[]).join(' / '))}</span></button>`).join('')||'<span class="muted small">No match.</span>'}</div>`:''}
  <div class="board">${rows.map((p,i)=>`<button type="button" class="bar" data-player="${esc(p.id)}" style="--i:${i};${teamVar(p.team)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(p.id))}<small> ${esc(p.team)}</small></span><small>${p.first}–${p.last} · ${p.games} matches · ${fmt(p.runs)} runs · ${p.wickets} wkts</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*(lens==='bowlavg'?(rows[0][lens]/p[lens]):p[lens]/max))}%"></span></span></span><span class="val">${/avg/.test(lens)?p[lens].toFixed(2):fmt(p[lens])}</span></button>`).join('')}</div></div>`;}
function playerView(id){const p=PLAYERS[id];const back=`<button type="button" class="btn" data-tab="players">← All players</button>`;if(!p){$('#view').innerHTML=`<div style="margin-top:22px">${back}</div>`;return;}
  const rows=PS.filter(r=>r.p===id).sort((a,b)=>a.y-b.y||FORMATS.indexOf(a.f)-FORMATS.indexOf(b.f));const inl=rows.filter(r=>r.g===state.gender&&(state.fmt==='all'||r.f===state.fmt)&&inEraYear(r.y));const use=inl.length?inl:rows;const a=playerAgg().find(x=>x.id===id)||aggOf(use);
  const byF=FORMATS.map(f=>{const rr=use.filter(r=>r.f===f);return rr.length?{f,...aggOf(rr)}:null;}).filter(Boolean);
  const team=(p.teams||[])[0]||a.team;const games=MATCHES.filter(m=>(m.pom||[]).includes(id));
  $('#view').innerHTML=`<div style="margin-top:22px;display:flex;gap:10px;flex-wrap:wrap;align-items:center">${back}<span class="small muted">${esc(eraLabel())}</span></div>
  <div class="card" style="margin-top:18px;grid-template-columns:1fr;${teamVar(team)}"><div><p class="eyebrow">Player · ${(p.teams||[]).map(t=>`<a href="#" data-nation="${esc(t)}" style="color:inherit">${esc(t)}</a>`).join(' / ')} · ${a.first}–${a.last}</p><h2 class="display" style="font-size:clamp(40px,6vw,84px);margin:6px 0 0;color:var(--team);text-shadow:0 0 30px rgba(255,255,255,.18)">${esc(p.n)}</h2><p class="muted" style="margin:4px 0 0">${esc(p.short||'')}${p.gender?' · '+(p.gender.includes('W')?'women’s':'men’s')+' internationals':''} · recorded figures ${inl.length?'in this lens':'across all lenses (none in the current lens)'}</p>
  <div class="kpis" style="margin-top:18px"><div class="kpi"><span>Matches</span><b>${a.games}</b><small>${a.inns} batting · ${a.binns} bowling innings</small></div><div class="kpi"><span>Runs</span><b>${fmt(a.runs)}</b><small>avg ${a.batavg!=null?a.batavg.toFixed(2):'—'} · SR ${a.sr!=null?a.sr.toFixed(1):'—'}</small></div><div class="kpi"><span>Highest</span><b>${a.hs}${a.hsno?'*':''}</b><small>${a.hundreds} hundreds · ${a.fifties} fifties</small></div><div class="kpi"><span>Wickets</span><b>${a.wickets}</b><small>avg ${a.bowlavg!=null?a.bowlavg.toFixed(2):'—'} · econ ${a.econ!=null?a.econ.toFixed(2):'—'}</small></div><div class="kpi"><span>Best bowling</span><b>${a.bbw?a.bbw+'/'+a.bbr:'—'}</b><small>${a.five} five-fors</small></div><div class="kpi"><span>Fielding</span><b>${a.catches+a.stumps}</b><small>${a.catches} catches · ${a.stumps} stumpings</small></div><div class="kpi"><span>Player of the match</span><b>${a.pom}</b></div></div>
  ${byF.length>1?`<div class="h3" style="margin-top:20px"><span>By format</span></div><div class="tablewrap"><table><tr><th>Format</th><th>M</th><th>Runs</th><th>Avg</th><th>SR</th><th>HS</th><th>100/50</th><th>Wkts</th><th>Avg</th><th>Econ</th><th>BB</th></tr>${byF.map(x=>`<tr><td>${x.f}</td><td>${x.games}</td><td>${fmt(x.runs)}</td><td>${x.batavg!=null?x.batavg.toFixed(2):'—'}</td><td>${x.sr!=null?x.sr.toFixed(1):'—'}</td><td>${x.hs}${x.hsno?'*':''}</td><td>${x.hundreds}/${x.fifties}</td><td>${x.wickets}</td><td>${x.bowlavg!=null?x.bowlavg.toFixed(2):'—'}</td><td>${x.econ!=null?x.econ.toFixed(2):'—'}</td><td>${x.bbw?x.bbw+'/'+x.bbr:'—'}</td></tr>`).join('')}</table></div>`:''}
  <div class="h3" style="margin-top:20px"><span>Season by season</span><small>${rows.length} recorded player-seasons</small></div><div class="tablewrap"><table><tr><th>Year</th><th>Format</th><th>Team</th><th>M</th><th>Runs</th><th>Avg</th><th>HS</th><th>100/50</th><th>Wkts</th><th>BB</th><th>Ct</th></tr>${rows.slice().reverse().map(r=>`<tr${inl.includes(r)?'':' class="dim"'}><td><a href="#" data-year="${r.y}" style="color:inherit">${r.y}</a></td><td>${r.f}${r.g==='W'?' (W)':''}</td><td>${esc(r.t)}</td><td>${r.games}</td><td>${r.runs}</td><td>${r.outs?(r.runs/r.outs).toFixed(1):'—'}</td><td>${r.hs}${r.hsno?'*':''}</td><td>${r.hundreds}/${r.fifties}</td><td>${r.wickets}</td><td>${r.bbw?r.bbw+'/'+r.bbr:'—'}</td><td>${r.catches}</td></tr>`).join('')}</table></div>
  ${games.length?`<div class="h3" style="margin-top:20px"><span>Player of the match</span><small>${games.length} awards</small></div><div class="ribbon">${games.map(m=>`<i class="${m.teams.includes(team)?resClass(m,team):'D'}" title="${esc(day(m.date))} · ${esc(m.home)} v ${esc(m.away)}" data-match="${esc(m.id)}"></i>`).join('')}</div>`:''}
  <p class="small dim" style="margin-top:12px">${p.espn?`<a href="https://www.espncricinfo.com/cricketers/${esc(p.espn)}" target="_blank" rel="noopener">Cricinfo profile ↗</a> · `:''}figures reconstructed from recorded deliveries; a missing season is a season without a recorded scorecard, not a blank year.</p></div></div>`;}
function aggOf(rr){const a={games:0,inns:0,runs:0,balls:0,outs:0,notouts:0,fours:0,sixes:0,fifties:0,hundreds:0,binns:0,bballs:0,conceded:0,wickets:0,maidens:0,five:0,catches:0,stumps:0,runouts:0,pom:0,hs:0,hsno:false,bbw:0,bbr:0,first:9999,last:0,team:rr[0]?.t};for(const r of rr){for(const k of ['games','inns','runs','balls','outs','notouts','fours','sixes','fifties','hundreds','binns','bballs','conceded','wickets','maidens','five','catches','stumps','runouts','pom'])a[k]+=r[k]||0;if(r.hs>a.hs||(r.hs===a.hs&&r.hsno)){a.hs=r.hs;a.hsno=!!r.hsno;}if(r.bbw>a.bbw||(r.bbw===a.bbw&&r.bbw&&r.bbr<a.bbr)){a.bbw=r.bbw;a.bbr=r.bbr;}a.first=Math.min(a.first,r.y);a.last=Math.max(a.last,r.y);}return {...a,batavg:a.outs?a.runs/a.outs:null,bowlavg:a.wickets?a.conceded/a.wickets:null,sr:a.balls?100*a.runs/a.balls:null,econ:a.bballs?6*a.conceded/a.bballs:null};}
