/* ---------- II · the Arenas: every venue the archive names, listed in the colour of its busiest division (never drawn) ---------- */
function venueModel(){const m={};for(const e of eraEvents()){const bs=e.bouts.filter(inLens);if(!bs.length)continue;const vid=e.venueId;const v=VENUES[vid]||{name:e.venue||e.city||'Unrecorded',city:e.city,country:e.country};let c=m[vid]||(m[vid]={vid,count:0,bouts:0,titles:0,first:e.year,last:e.year,divs:{},name:v.name,country:v.country||'',place:v.city||''});c.count++;c.bouts+=bs.length;c.titles+=bs.filter(b=>b.title).length;c.first=Math.min(c.first,e.year);c.last=Math.max(c.last,e.year);for(const b of bs)c.divs[b.div]=(c.divs[b.div]||0)+1;}
  return Object.values(m).map(c=>({...c,top:Object.entries(c.divs).sort((a,b)=>b[1]-a[1])[0]?.[0]||null}));}
function drawGrid(){const list=venueModel();const q=state.gridFind.trim().toLowerCase();let shown=list.filter(c=>(q||c.count>=state.gridMin)&&(!q||(c.name+' '+c.country+' '+c.place).toLowerCase().includes(q)));
  const sorters={count:(a,b)=>b.count-a.count||a.name.localeCompare(b.name),name:(a,b)=>a.name.localeCompare(b.name),country:(a,b)=>a.country.localeCompare(b.country)||b.count-a.count,recent:(a,b)=>b.last-a.last||b.count-a.count};shown.sort(sorters[state.gridSort]);
  const bigN=state.gridSort==='count'&&!q?6:0;const countries=new Set(list.map(c=>c.country).filter(Boolean));
  $('#gridLede').textContent=`${list.length} venues in ${countries.size} countries have staged a card in ${eraLabel().replace(' · ',', ')}. Each is listed as the sources name it, in the colour of the division that has fought there most; the largest cards are the arenas the promotion has returned to most often.${shown.length<list.length&&!q?` Showing ${shown.length} with ${state.gridMin}+ events.`:''}`;
  $('#circuits').innerHTML=shown.map((c,i)=>`<button type="button" class="circ flat${i<bigN?' big':''}" data-venue="${esc(c.vid)}" style="${c.top?teamVar(c.top):'--team:#8b9099'}" title="${esc(c.name)} · ${c.count} events · ${c.bouts} bouts · ${c.first}–${c.last}${c.top?' · most bouts: '+esc(divLabel(c.top)):''}"><span class="ct">${esc(c.country)}${c.place&&c.place!==c.country&&c.place!==c.name?' · '+esc(c.place):''}</span><span class="n">${c.count}</span><span class="nm">${esc(c.name)}</span><span class="yrs">${c.first}${c.last!==c.first?'–'+c.last:''} · ${c.bouts} bouts${c.titles?' · '+c.titles+' title':''}${c.top?' · <i style="background:var(--team)"></i>'+esc(divLabel(c.top)):''}</span></button>`).join('')||`<p class="muted">No venue matches.</p>`;}

/* ---------- Stage: tabs, era strip, era context ---------- */
const TABS=[['season','Season'],['event','Event'],['fighters','Fighters'],['divisions','Divisions'],['venues','Venues'],['records','Records'],['barcode','Barcode'],['duel','Duel']];
function drawTabs(){$('#tabs').innerHTML=TABS.map(([id,l])=>`<button type="button" role="tab" data-tab="${id}" aria-pressed="${state.tab===id}">${l}</button>`).join('');
  $('#stageStatus').textContent=(state.tab==='season'||state.tab==='event')&&!state.whole?`${state.year} · ${eraOf(state.year)?.name||''} · ${lensLabel()}`:eraLabel();}
function drawEraStrip(preview){const strip=$('#eraStrip');if(!strip.children.length)strip.innerHTML=ERAS.map(e=>`<button type="button" style="--w:${e.to-e.from+1}" data-era="${e.id}" title="${esc(e.name)} · ${e.from}–${e.to}" aria-label="${esc(e.name)} ${e.from}–${e.to}"></button>`).join('');
  for(const b of strip.children){b.classList.toggle('on',state.era===b.dataset.era);b.classList.toggle('demo',preview===b.dataset.era);}
  const e=preview?ERAS.find(x=>x.id===preview):state.era==='all'?eraOf(state.year):ERAS.find(x=>x.id===state.era);
  $('#eraCaption').innerHTML=`<span><b>${esc(e.name)}</b> · ${e.from}–${e.to}</span><span class="dim">${state.era===e.id?'Lens on · click again to release':'Click a segment to focus the whole page on that era'}</span>`;
  const ctx=$('#eraContext');ctx.innerHTML=`<div class="era-car">${e.ball.svg}</div><div><p class="eyebrow">${state.era===e.id?'Era lens':preview?'Era':'Era of the selected year'} · ${e.from}–${e.to}</p><h3>${esc(e.name)}</h3><p>${esc(e.text)}</p><div class="chips">${e.ball.features.map(f=>`<span>${esc(f)}</span>`).join('')}</div><p class="small dim" style="margin:10px 0 0">${esc(e.ball.label)} · an editorial reading of the period; the archive itself is not divided</p></div>`;}
const tour={i:-1,timer:null,visible:false,stopped:RM};
function tourStep(){if(tour.stopped||!tour.visible)return;tour.i=(tour.i+1)%ERAS.length;const ctx=$('#eraContext');ctx.classList.add('swap');setTimeout(()=>{if(tour.stopped)return;drawEraStrip(ERAS[tour.i].id);ctx.classList.remove('swap');},260);tour.timer=setTimeout(tourStep,4200);}
function tourStart(){if(tour.stopped||tour.timer)return;tour.timer=setTimeout(tourStep,1800);}
function tourPause(){clearTimeout(tour.timer);tour.timer=null;}
function tourStop(){if(tour.stopped)return;tour.stopped=true;tourPause();$('#eraContext').classList.remove('swap');drawEraStrip();}

/* ---------- shared pieces ---------- */
const fl=id=>`<a href="#" data-fighter="${esc(id)}" style="color:inherit">${esc(pname(id))}</a>`;
const dl=k=>`<a href="#" data-dv="${esc(k)}" style="color:inherit"><i class="dot" style="--c:${color(k)}"></i>${esc(divLabel(k))}</a>`;
const mkChip=b=>`<span class="mk" style="--c:${mkColor(b.mk)}">${esc(b.mk==='KO'?'KO/TKO':b.mk==='SUB'?'SUB':b.mk==='DEC'?'DEC':b.mk==='DQ'?'DQ':b.mk==='NC'?'NC':b.mk==='DRAW'?'DRAW':'—')}</span>`;
const titleMark=b=>b.title?`<span class="belt" title="${esc(b.notes||'Title bout')}">${b.title==='interim'?'interim title':b.title==='vacant'?'vacant title':'title'}</span>`:b.tour?`<span class="belt alt">tournament ${esc(b.tour)}</span>`:'';
const boutWho=b=>b.res==='W'?`<b>${fl(b.w)}</b> <span class="dim">def.</span> ${fl(b.w===b.a?b.b:b.a)}`:`${fl(b.a)} <span class="dim">vs.</span> ${fl(b.b)}`;
function eventCard(e,on){const m=e.main;const bs=e.bouts.filter(inLens);const d=divOfYear({bouts:bs.length?bs:e.bouts});return `<button type="button" class="cal${on?' on':''}" data-event="${esc(e.id)}" style="${teamVar(d||'catch')}"><div class="rd">${esc(dm(e.date))} · ${esc(e.city||e.country||'')}</div><div class="sc"><span>${bs.length}<small>bouts</small></span></div><div class="nm">${esc(e.name)}</div><div class="w">${m?'<i class="dot" style="--c:'+color(m.div)+'"></i>'+esc(boutLine(m))+(m.title?' · title':''):'no bouts recorded'}</div></button>`;}
function bars(rows,valOf,subOf,max,attr,nameOf,colorOf,unit=''){return `<div class="board">${rows.map((a,i)=>`<button type="button" class="bar" data-${attr}="${esc(a.id)}" style="--i:${i};--team:${colorOf(a)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(nameOf(a))}</span><small>${subOf(a)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*valOf(a)/(max||1))}%"></span></span></span><span class="val">${valOf(a)==null?'—':fmt(valOf(a))}${unit}</span></button>`).join('')}</div>`;}
const fighterBars=(rows,valOf,subOf,max,unit='')=>bars(rows,valOf,subOf,max,'fighter',a=>pname(a.id),a=>color(a.top||FIGHTERS[a.id]?.div||'catch'),unit);
const divBars=(rows,valOf,subOf,max,unit='')=>bars(rows,valOf,subOf,max,'dv',a=>divLabel(a.id),a=>color(a.id),unit);
function drawChart(el,series,n,labelOf,xl,colorOf,ylabel,unit=''){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(200,box.height);const padL=40,padR=130,padT=14,padB=26;const vals=series.flatMap(s=>s.pts.filter(v=>v!=null));const max=Math.max(1,...vals),min=Math.min(0,...vals);const x=i=>padL+(n>1?i*(W-padL-padR)/(n-1):0),y=v=>padT+(H-padT-padB)*(1-(v-min)/((max-min)||1));
  let g='';const step=max>200?50:max>60?25:max>20?10:max>8?5:1;for(let v=Math.ceil(min/step)*step;v<=max;v+=step)g+=`<line class="gridl" x1="${padL}" x2="${W-padR}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}"/><text class="lb" x="${padL-6}" y="${(y(v)+3).toFixed(1)}" text-anchor="end">${v}${unit}</text>`;
  for(let i=0;i<n;i++){const l=xl(i);if(l)g+=`<text class="lb" x="${x(i).toFixed(1)}" y="${H-8}" text-anchor="middle">${esc(l)}</text>`;}
  const paths=series.map(s=>{let d='',pen=false;s.pts.forEach((v,i)=>{if(v==null){pen=false;return;}d+=(pen?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1);pen=true;});const lastI=s.pts.map((v,i)=>v!=null?i:-1).filter(i=>i>=0).pop();const last=lastI!=null?s.pts[lastI]:null;return `<path class="ser" d="${d}" style="--c:${colorOf(s.id)}"><title>${esc(labelOf(s.id))}</title></path>${last!=null?`<text class="end" x="${(x(lastI)+6).toFixed(1)}" y="${(y(last)+4).toFixed(1)}" style="--c:${colorOf(s.id)}">${esc(labelOf(s.id))} ${fmt(last)}${unit}</text>`:''}`;}).join('');
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(ylabel||'Chart')}">${g}${paths}</svg>`;}
const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b>${s?`<small>${s}</small>`:''}</div>`;

/* ---------- Season: the year ---------- */
function seasonView(){if(state.whole)return eraView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No bouts in this lens.</p>';return;}
  const {best,ranked,titles,fastest,fins}=champOf(s);const partial=s.year===A.lastYear;
  const podium=ranked.slice(0,3);const order=[podium[1],podium[0],podium[2]];const divs={};for(const b of s.bouts)divs[b.div]=(divs[b.div]||0)+1;const drows=Object.entries(divs).sort((a,b)=>b[1]-a[1]);
  const lead=best?Object.entries(best.divs).sort((a,b)=>b[1]-a[1])[0][0]:null;
  const head=`<div class="season-head"><div class="champ-card" style="${lead?`--accent:${color(lead)};--on-accent:${onColor(color(lead))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${partial?'The year so far':'The year'} · ${esc(lensLabel())}</p><div class="yr">${s.year}</div>${best?`<div class="who"><small>Most wins of the year · ${best.wins} win${best.wins===1?'':'s'}${best.fin?' · '+best.fin+' finish'+(best.fin===1?'':'es'):''}${best.titleW?' · '+best.titleW+' title win'+(best.titleW===1?'':'s'):''}</small><a href="#" data-fighter="${esc(best.id)}" style="color:inherit;text-decoration:none">${esc(pname(best.id))}</a></div><div class="team"><i></i>${esc(divLabel(lead))}</div><div class="facts"><div><b>${s.events.length}</b>events</div><div><b>${s.bouts.length}</b>bouts</div><div><b>${titles.length}</b>title bouts</div><div><b>${pct(fins,s.bouts.length)}%</b>finishes</div></div>`:`<div class="who"><small>No results recorded</small>—</div>`}
  ${fastest?`<p class="small" style="margin:14px 0 0;color:var(--ink);opacity:.85">Fastest finish: <b>${esc(pname(fastest.w))}</b> def. ${esc(pname(fastest.w===fastest.a?fastest.b:fastest.a))} in ${clock(fastest.secs)} · ${esc(fastest.ev.name)}</p>`:''}<p class="small dim" style="margin:${fastest?6:18}px 0 0">Ranked by wins in the year, then title wins and finishes; a reading of the results, not an award.</p></div>
  <div><div class="podium">${order.map((d,i)=>d?`<button type="button" class="step p${podium.indexOf(d)+1} bar" data-fighter="${esc(d.id)}" style="--h:${Math.round(120+120*d.wins/Math.max(1,podium[0].wins))}px;--team:${color(Object.entries(d.divs).sort((a,b)=>b[1]-a[1])[0][0])};display:flex"><span class="pos">${podium.indexOf(d)+1}</span><span class="nm">${esc(pname(d.id))}</span><span class="pt">${d.wins} win${d.wins===1?'':'s'} · ${d.fin} finish${d.fin===1?'':'es'}</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const cal=`<div class="h3"><span>The year’s cards</span><small>${s.events.length} events · click one to open it</small></div><div class="calendar">${s.events.map(e=>eventCard(e,state.event===e.id&&state.tab==='event')).join('')}</div>`;
  const quick=s.bouts.filter(b=>b.fin&&b.secs!=null).sort((a,b)=>a.secs-b.secs).slice(0,10);
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Divisions of the year</span><small>by bouts</small></div>${divBars(drows.map(([id,n])=>({id,n})),a=>a.n,a=>`${s.bouts.filter(b=>b.div===a.id&&b.title).length} title bouts · ${pct(s.bouts.filter(b=>b.div===a.id&&b.fin).length,a.n)}% finishes`,drows[0]?.[1]||1)}</div><div class="panel"><div class="h3"><span>Fastest finishes of the year</span><small>elapsed time</small></div><div class="board">${quick.map((b,i)=>`<button type="button" class="bar" data-event="${esc(b.e)}" data-bout="${esc(b.id)}" style="--i:${i};--team:${color(b.div)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(b.w))}<small> def. ${esc(pname(b.w===b.a?b.b:b.a))}</small></span><small>${esc(shortMethod(b))} · ${esc(b.ev.short)} · ${esc(dm(b.date))}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*b.secs/(quick[quick.length-1]?.secs||1))}%"></span></span></span><span class="val">${clock(b.secs)}</span></button>`).join('')||'<p class="muted small">No timed finishes this year.</p>'}</div></div></div>`;
  $('#view').innerHTML=head+cal+body;}
function eraView(){const ss=eraSeasons();const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);const bouts=eraBouts();
  const fighters=fighterAgg().sort(fighterOrder);const top=fighters[0];const divs=divAgg().sort((a,b)=>b.bouts-a.bouts).slice(0,14);
  const head=`<div class="season-head"><div class="champ-card" style="${top?`--accent:${color(top.top||'catch')};--on-accent:${onColor(color(top.top||'catch'))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${e?'Whole era':'All years'} · ${esc(lensLabel())}</p><div class="yr" style="font-size:clamp(44px,6vw,84px)">${ss[0]?.year}–${ss[ss.length-1]?.year}</div>${top?`<div class="who"><small>Most wins across the period · ${top.wins} win${top.wins===1?'':'s'} · ${top.fin} finishes · ${top.titleW} title wins</small><a href="#" data-fighter="${esc(top.id)}" style="color:inherit;text-decoration:none">${esc(pname(top.id))}</a></div><div class="team"><i></i>${esc(divLabel(top.top))}</div>`:''}<div class="facts"><div><b>${fmt(bouts.length)}</b>bouts</div><div><b>${fmt(eraEvents().length)}</b>events</div><div><b>${fmt(fighters.length)}</b>fighters</div><div><b>${pct(bouts.filter(b=>b.fin).length,bouts.length)}%</b>finishes</div></div></div>
  <div><div class="podium">${[fighters[1],fighters[0],fighters[2]].map((d,i)=>d?`<button type="button" class="step p${fighters.indexOf(d)+1} bar" data-fighter="${esc(d.id)}" style="--h:${Math.round(120+120*d.wins/Math.max(1,fighters[0].wins))}px;--team:${color(d.top||'catch')};display:flex"><span class="pos">${fighters.indexOf(d)+1}</span><span class="nm">${esc(pname(d.id))}</span><span class="pt">${d.wins} wins · ${d.first}–${d.last}</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const roll=ss.map(s=>({s,c:champOf(s)}));
  const rollHtml=`<div class="h3"><span>Most wins, year by year</span><small>click a year to open it</small></div><div class="calendar">${roll.map(({s,c})=>`<button type="button" class="cal" data-year="${s.year}" style="--team:${c.best?color(Object.entries(c.best.divs).sort((a,b)=>b[1]-a[1])[0][0]):'#5b616b'}"><div class="rd">${s.year} · ${s.events.length} events · ${s.bouts.length} bouts</div><div class="nm">${c.best?esc(pname(c.best.id)):'—'}</div><div class="w">${c.best?c.best.wins+' win'+(c.best.wins===1?'':'s'):''}${c.titles.length?' · '+c.titles.length+' title bouts':''}</div></button>`).join('')}</div>`;
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Divisions across the period</span><small>by bouts</small></div>${divBars(divs,a=>a.bouts,a=>`${a.first}–${a.last} · ${a.title} title bouts · ${a.finrate}% finishes`,Math.max(1,...divs.map(a=>a.bouts)))}</div><div class="panel"><div class="h3"><span>Fighters across the period</span><small>by wins, then finishes</small></div>${fighterBars(fighters.slice(0,12),a=>a.wins,a=>`${a.fin} finishes · ${a.bouts} bouts · ${a.first}–${a.last}`,Math.max(1,...fighters.slice(0,12).map(a=>a.wins)))}</div></div>`;
  $('#view').innerHTML=head+rollHtml+body;}

/* ---------- Event: the card as the tower ---------- */
function eventView(){if(state.whole)return eraEventsView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No bouts in this lens.</p>';return;}let e=byEvent[state.event];if(!e||e.year!==s.year||!s.events.includes(e))e=s.events[s.events.length-1];state.event=e.id;
  const nav=`<div class="chiplist" style="margin-top:20px">${s.events.map(x=>`<button type="button" class="chip${x.id===e.id?' on':''}" data-event="${esc(x.id)}" style="${x.id===e.id?'border-color:var(--accent);color:var(--accent)':''}"><i style="--c:${x.main?color(x.main.div):'#444'}"></i>${esc(x.short)}${x.sub?' · '+esc(x.sub):''}</button>`).join('')}</div>`;
  const v=VENUES[e.venueId];const m=e.main;
  const hero=`<div class="card" style="margin-top:18px;grid-template-columns:1fr;${m?teamVar(m.div):''}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:18px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">${esc(day(e.date))} · ${esc([e.venue,e.city,e.country].filter(Boolean).join(' · '))}${e.att?' · '+fmt(e.att)+' attendance':''}${e.gate?' · gate $'+fmt(e.gate):''}${e.buys?' · '+fmt(e.buys)+' buys':''}</p><h2 style="margin:6px 0 0">${esc(e.short)}${e.sub?` <span class="muted" style="font-size:.6em;font-weight:600;font-style:normal">${esc(e.sub)}</span>`:''}</h2></div>${m?`<div class="champline" style="--team:${color(m.div)}"><span class="eyebrow">Main event · ${esc(divLabel(m.div))}${m.title?' · '+esc(m.title==='title'?'title bout':m.title+' title'):''}</span><b>${boutWho(m)}</b><span class="small muted">${esc(shortMethod(m))}${m.round?' · R'+m.round:''}${m.time?' '+esc(m.time):''}</span></div>`:''}${v?`<div class="small mono muted">${esc(v.n)} events at this venue · <a href="#" data-venue="${esc(e.venueId)}" style="color:var(--muted)">open</a>${e.url?` · <a href="${esc(e.url)}" target="_blank" rel="noopener" style="color:var(--muted)">Wikipedia ↗</a>`:''}</div>`:''}</div></div>`;
  const bs=e.bouts;const inL=b=>inLens(b);const maxS=Math.max(900,...bs.map(b=>b.secs||0));let card=null;
  const tower=`<div class="panel" style="margin-top:18px"><div class="h3"><span>The card</span><small>${bs.length} bout${bs.length===1?'':'s'} · main event first, as the article lists them · the bar is elapsed time</small></div><div class="tower">${bs.map((b,i)=>{const head=b.card!==card?`<div class="tw-card">${esc(b.card)}</div>`:'';card=b.card;return head+`<div class="bout${inL(b)?'':' off'}${b.title?' title':''}" data-bout="${esc(b.id)}" style="${teamVar(b.div)}"><span class="bt-n">${bs.length-i}</span><span class="bt-div"><a href="#" data-dv="${esc(b.div)}" style="color:inherit">${esc(b.div==='catch'&&b.lb?'Catchweight '+b.lb+' lb':divLabel(b.div))}</a></span><span class="bt-who">${boutWho(b)} ${titleMark(b)}${b.champ.length?` <span class="dim small">(c: ${b.champ.map(sd=>esc(pname(b[sd]))).join(', ')})</span>`:''}</span><span class="bt-how">${mkChip(b)} <span class="small">${esc(b.mk==='DEC'?(b.dk||'decision'):b.det||b.method||'')}</span></span><span class="bt-rt mono">${b.round?'R'+b.round:''}${b.time?' '+esc(b.time):''}</span><span class="bt-bar"><i style="width:${b.secs!=null?Math.round(100*b.secs/maxS):0}%;background:${mkColor(b.mk)}"></i></span>${b.notes&&!b.title?`<span class="bt-note small dim">${esc(b.notes)}</span>`:''}</div>`;}).join('')}</div></div>`;
  const bon=(e.bonuses||[]).length?`<div class="panel" style="margin-top:18px"><div class="h3"><span>Bonus awards</span><small>as the article lists them</small></div><div class="chips">${e.bonuses.map(b=>`<span class="chip"><i style="--c:var(--accent)"></i>${esc(b.t)}: ${(b.who||[]).map(w=>{const id=fighterIdOf(w);return id?fl(id):esc(w);}).join(', ')}</span>`).join('')}</div></div>`:'';
  const fins=bs.filter(b=>b.fin).length;const summary=`<div class="kpis" style="margin-top:16px">${kpi('Bouts',bs.length,'')}${kpi('Finishes',fins,`${pct(fins,bs.length)}%`)}${kpi('Title bouts',bs.filter(b=>b.title).length,'')}${kpi('Decisions',bs.filter(b=>b.mk==='DEC').length,'')}${kpi('Time in the cage',clock(bs.reduce((a,b)=>a+(b.secs||0),0)),'elapsed, all bouts')}</div>`;
  $('#view').innerHTML=nav+hero+summary+tower+bon;
  if(state.bout){const el=$(`#view [data-bout="${CSS.escape(state.bout)}"]`);if(el){el.classList.add('hl');el.scrollIntoView({block:'center',behavior:'auto'});}state.bout=null;}}
function eraEventsView(){const evs=eraEvents();const big=[...evs].sort((a,b)=>(b.att||0)-(a.att||0)).filter(e=>e.att).slice(0,20);const byV={};for(const e of evs){const k=e.venueId;(byV[k]||(byV[k]=[])).push(e);}
  const quick=eraBouts().filter(b=>b.fin&&b.secs!=null).sort((a,b)=>a.secs-b.secs).slice(0,20);
  $('#view').innerHTML=`<div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Fastest finishes across the period</span><small>elapsed time · click one to open the card</small></div><div class="board">${quick.map((b,i)=>`<button type="button" class="bar" data-event="${esc(b.e)}" data-bout="${esc(b.id)}" data-year="${b.year}" style="--i:${i};--team:${color(b.div)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(b.w))}<small> def. ${esc(pname(b.w===b.a?b.b:b.a))} · ${b.year}</small></span><small>${esc(shortMethod(b))} · ${esc(b.ev.short)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*b.secs/(quick[quick.length-1]?.secs||1))}%"></span></span></span><span class="val">${clock(b.secs)}</span></button>`).join('')||'<p class="muted small">No timed finishes in this lens.</p>'}</div></div>
  <div class="panel"><div class="h3"><span>Biggest crowds</span><small>attendance as recorded</small></div><div class="board">${big.map((e,i)=>`<button type="button" class="bar" data-event="${esc(e.id)}" data-year="${e.year}" style="--i:${i};--team:${e.main?color(e.main.div):'#5b616b'}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(e.name)}<small> ${e.year}</small></span><small>${esc([e.venue,e.city].filter(Boolean).join(' · '))}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*e.att/(big[0].att||1))}%"></span></span></span><span class="val">${fmt(e.att)}</span></button>`).join('')||'<p class="muted small">No attendances recorded in this lens.</p>'}</div></div></div>
  <div class="h3" style="margin-top:22px"><span>Every card of the period</span><small>${evs.length} events</small></div><div class="calendar">${[...evs].reverse().map(e=>eventCard(e,false)).join('')}</div>`;}
