/* ---------- Divisions ---------- */
function divisionsView(){const list=divAgg();const lens=state.lens;let rows=list.filter(a=>a[lens]!=null);rows.sort((a,b)=>b[lens]-a[lens]||b.bouts-a.bouts);const max=Math.max(1,...rows.map(a=>a[lens]));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Divisions · ${esc(eraLabel())}</h2></div><div class="small mono muted">${list.length} divisions</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="lens" aria-label="Lens">${Object.entries(LENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(LENSES[lens][1])}</span></div>${divBars(rows,a=>a[lens],a=>`${a.first}–${a.last} · ${a.bouts} bouts · ${a.title} title bouts · ${a.finrate}% finishes${a.top?' · most wins '+esc(pname(a.top[0]))+' '+a.top[1]:''}`,max,/rate/.test(lens)?'%':'')}<p class="small dim" style="margin:10px 0 0">Divisions are read from the weight class on each bout as the article gives it; the early openweight tournaments and catchweight bouts are listed as such. Women’s divisions appear from 2013.</p></div>`;
  $('#lens').addEventListener('change',e=>{state.lens=e.target.value;render();});}
function divisionView(k){const all=divAgg();const a=all.find(x=>x.id===k);if(!a){divisionsView();return;}const bouts=eraBouts().filter(b=>b.div===k);const titles=bouts.filter(b=>b.title).sort((u,v)=>u.date<v.date?-1:1);
  const wins={};const fins={};for(const b of bouts)if(b.w){wins[b.w]=(wins[b.w]||0)+1;if(b.fin)fins[b.w]=(fins[b.w]||0)+1;}const topW=Object.entries(wins).sort((u,v)=>v[1]-u[1]).slice(0,12);const topF=Object.entries(fins).sort((u,v)=>v[1]-u[1]).slice(0,12);
  const years=[...new Set(bouts.map(b=>b.year))].sort((u,v)=>u-v);const byY={};for(const b of bouts){const y=byY[b.year]||(byY[b.year]={n:0,fin:0});y.n++;if(b.fin)y.fin++;}
  const methods={};for(const b of bouts)methods[b.mk]=(methods[b.mk]||0)+1;
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${color(k)}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Division · ${a.first}–${a.last}${DIV[k]?.lb?' · '+DIV[k].lb+' lb limit':''}</p><h2 style="margin:6px 0 0"><i class="dot" style="--c:${color(k)};width:.5em;height:.5em;vertical-align:.1em;margin-right:8px"></i>${esc(divLabel(k))}</h2></div><div class="small mono muted">${esc(eraLabel())}</div></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Bouts',fmt(a.bouts),`${a.ny} years`)}${kpi('Fighters',fmt(a.nf),'')}${kpi('Title bouts',a.title,'')}${kpi('Finish rate',a.finrate+'%',`${a.ko} KO/TKO · ${a.sub} submissions`)}${kpi('Average bout',a.avg!=null?clock(a.avg):'—','elapsed, where timed')}</div>
  ${years.length>3?`<div class="h3" style="margin-top:22px"><span>Bouts and finish rate, year by year</span><small>bouts (left) · finishes as a share of bouts</small></div><div class="two"><div class="panel"><div class="chart" id="divChartN" style="height:220px"></div></div><div class="panel"><div class="chart" id="divChartF" style="height:220px"></div></div></div>`:''}
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Most wins in the division</span></div>${bars(topW.map(([id,n])=>({id,n})),x=>x.n,x=>`${fins[x.id]||0} finishes · ${bouts.filter(b=>(b.a===x.id||b.b===x.id)).length} bouts`,topW[0]?.[1]||1,'fighter',x=>pname(x.id),()=>color(k))}</div><div><div class="panel"><div class="h3"><span>Most finishes</span></div>${bars(topF.map(([id,n])=>({id,n})),x=>x.n,x=>`${wins[x.id]||0} wins`,topF[0]?.[1]||1,'fighter',x=>pname(x.id),()=>color(k))}</div><div class="panel" style="margin-top:14px"><div class="h3"><span>How bouts end</span></div><div class="chips">${Object.entries(methods).sort((u,v)=>v[1]-u[1]).map(([m,n])=>`<span class="chip"><i style="--c:${mkColor(m)}"></i>${esc(mkLabel(m))} <span style="color:var(--muted)">${n} · ${pct(n,bouts.length)}%</span></span>`).join('')}</div></div></div></div>
  ${titles.length?`<div class="panel" style="margin-top:20px"><div class="h3"><span>Title bouts, in order</span><small>${titles.length} · as the notes record them · click one to open the card</small></div><div class="tablewrap" style="max-height:560px"><table><tr><th>Date</th><th>Event</th><th>Bout</th><th>Method</th><th class="n">Round</th><th class="n">Time</th><th>Note</th></tr>${[...titles].reverse().map(b=>`<tr class="${b.title!=='title'?'':'win'}"><td class="mono"><a href="#" data-event="${esc(b.e)}" data-bout="${esc(b.id)}" data-year="${b.year}">${esc(day(b.date))}</a></td><td>${esc(b.ev.short)}</td><td>${boutWho(b)}</td><td>${mkChip(b)} <span class="small muted">${esc(b.mk==='DEC'?(b.dk||''):b.det||'')}</span></td><td class="n">${b.round??''}</td><td class="n mono">${esc(b.time||'')}</td><td class="small dim">${esc(b.title==='interim'?'interim':b.title==='vacant'?'vacant':'')}</td></tr>`).join('')}</table></div></div>`:''}`;
  if(years.length>3){drawChart($('#divChartN'),[{id:k,pts:years.map(y=>byY[y].n)}],years.length,()=>divLabel(k),i=>(years[i]%5===0&&years.length-1-i>1&&i>1)||i===0||i===years.length-1?String(years[i]):'',()=>color(k),'Bouts by year');drawChart($('#divChartF'),[{id:k,pts:years.map(y=>pct(byY[y].fin,byY[y].n))}],years.length,()=>'finish rate',i=>(years[i]%5===0&&years.length-1-i>1&&i>1)||i===0||i===years.length-1?String(years[i]):'',()=>color(k),'Finish rate by year','%');}}

/* ---------- Fighters ---------- */
function fightersView(){const list=fighterAgg();const lens=state.plens;let rows=list.filter(p=>p[lens]!=null);if(lens==='rate')rows=rows.filter(p=>p.bouts>=8);rows.sort((a,b)=>b[lens]-a[lens]||b.wins-a.wins||b.fin-a.fin);rows=rows.slice(0,40);
  const max=Math.max(1,...rows.map(a=>a[lens]));const q=(state.find2||'').toLowerCase();const found=q?Object.entries(FIGHTERS).filter(([id,p])=>p.name.toLowerCase().includes(q)).slice(0,14):[];
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Fighters · ${esc(eraLabel())}</h2></div><div class="small mono muted">${fmt(list.length)} fighters with a bout</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><input type="search" id="find2" placeholder="Search a fighter" value="${esc(state.find2||'')}" aria-label="Search"><select id="lens" aria-label="Lens">${Object.entries(PLENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(PLENSES[lens][1])}</span></div>${q?`<div class="chiplist" style="margin-bottom:14px">${found.map(([id,p])=>`<button type="button" class="chip" data-fighter="${esc(id)}">${esc(p.name)}</button>`).join('')||'<span class="muted small">No match.</span>'}</div>`:''}
  ${fighterBars(rows,a=>a[lens],a=>`${a.first}–${a.last} · ${a.wins}–${a.losses}${a.draws?'–'+a.draws:''}${a.nc?' (${a.nc} NC)'.replace('${a.nc}',a.nc):''} · ${a.fin} finishes${a.titleW?' · '+a.titleW+' title wins':''}${a.top?' · '+esc(divLabel(a.top)):''}`,max,/rate/.test(lens)?'%':'')}</div>`;
  $('#find2').addEventListener('input',e=>{state.find2=e.target.value;fightersView();$('#find2').focus();const v=$('#find2');v.setSelectionRange(v.value.length,v.value.length);});$('#lens').addEventListener('change',e=>{state.plens=e.target.value;render();});}
function fighterView(id){const p=FIGHTERS[id];if(!p){fightersView();return;}const all=fighterAgg();const a=all.find(x=>x.id===id);const rank=[...all].sort(fighterOrder).findIndex(x=>x.id===id)+1;
  const rows=eraBouts().filter(b=>b.a===id||b.b===id).sort((u,v)=>u.date<v.date?1:-1);
  const won=rows.filter(b=>b.w===id);const byD={};for(const b of rows){const d=byD[b.div]||(byD[b.div]={d:b.div,bouts:0,wins:0,fin:0});d.bouts++;if(b.w===id){d.wins++;if(b.fin)d.fin++;}}
  const how={};for(const b of won)how[b.mk]=(how[b.mk]||0)+1;const lostHow={};for(const b of rows.filter(b=>b.res==='W'&&b.w!==id))lostHow[b.mk]=(lostHow[b.mk]||0)+1;
  const rec=p.rec||[0,0,0,0];const age=p.dob?Math.floor((new Date(A.lastDate)-new Date(p.dob))/31557600000):null;
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${color(a?.top||p.div||'catch')}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Fighter${a?' · '+a.first+'–'+a.last:''}${a?.top?' · '+esc(divLabel(a.top)):''}${p.nat?' · '+esc(p.nat):''}</p><h2 style="margin:6px 0 0">${esc(p.name)}</h2></div><div class="small mono muted">${rank?`#${rank} by wins in ${esc(eraLabel())}`:''}${p.dob?` · born ${esc(day(p.dob))}`:''}${p.cm?` · ${p.cm} cm`:''}${p.url?` · <a href="${esc(p.url)}" target="_blank" rel="noopener" style="color:var(--muted)">Wikipedia ↗</a>`:''}</div></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Record in the lens',a?`${a.wins}–${a.losses}${a.draws?'–'+a.draws:''}`:'0–0',a&&a.nc?`${a.nc} no contest${a.nc===1?'':'s'}`:'')}${kpi('Finishes',a?a.fin:0,a?`${a.ko} KO/TKO · ${a.sub} submissions`:'')}${kpi('Title bouts',a?a.title:0,a?`${a.titleW} won`:'')}${kpi('Fastest finish',a&&a.fastest!=null?clock(a.fastest):'—',a&&a.fastBout?esc(byBout[a.fastBout].ev.short+' · '+pname(byBout[a.fastBout].w===id?(byBout[a.fastBout].a===id?byBout[a.fastBout].b:byBout[a.fastBout].a):'')):'')}${kpi('Whole archive',`${rec[0]}–${rec[1]}${rec[2]?'–'+rec[2]:''}`,`${p.first}–${p.last}${rec[3]?' · '+rec[3]+' NC':''}`)}${a?.bonus?kpi('Bonus awards',a.bonus,''):''}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Every bout in the lens</span><small>${rows.length} · click one to open the card</small></div><div class="tablewrap" style="max-height:560px"><table><tr><th>Date</th><th>Event</th><th></th><th>Opponent</th><th>Method</th><th class="n">R</th><th class="n">Time</th></tr>${rows.map(b=>{const opp=b.a===id?b.b:b.a;const r=b.res==='W'?(b.w===id?'W':'L'):b.res;return `<tr class="${r==='W'?'win':''}"><td class="mono"><a href="#" data-event="${esc(b.e)}" data-bout="${esc(b.id)}" data-year="${b.year}">${esc(day(b.date))}</a></td><td>${esc(b.ev.short)}${b.title?' <span class="belt">title</span>':''}</td><td><b style="color:${r==='W'?'var(--accent)':r==='L'?'var(--muted)':'var(--dim)'}">${r}</b></td><td>${fl(opp)} <span class="dim small"><i class="dot" style="--c:${color(b.div)}"></i>${esc(divLabel(b.div))}</span></td><td>${mkChip(b)} <span class="small muted">${esc(b.mk==='DEC'?(b.dk||''):b.det||'')}</span></td><td class="n">${b.round??''}</td><td class="n mono">${esc(b.time||'')}</td></tr>`;}).join('')}</table></div></div>
  <div><div class="panel"><div class="h3"><span>By division</span></div>${bars(Object.values(byD).sort((u,v)=>v.bouts-u.bouts),f=>f.wins,f=>`${f.bouts} bouts · ${f.fin} finishes`,Math.max(1,...Object.values(byD).map(f=>f.wins)),'dv',f=>divLabel(f.d),f=>color(f.d))}</div><div class="panel" style="margin-top:14px"><div class="h3"><span>How the wins came</span></div><div class="chips">${Object.entries(how).sort((u,v)=>v[1]-u[1]).map(([m,n])=>`<span class="chip"><i style="--c:${mkColor(m)}"></i>${esc(mkLabel(m))} <span style="color:var(--muted)">${n}</span></span>`).join('')||'<span class="muted small">No wins in this lens.</span>'}</div>${Object.keys(lostHow).length?`<div class="h3" style="margin-top:12px"><span>And the losses</span></div><div class="chips">${Object.entries(lostHow).sort((u,v)=>v[1]-u[1]).map(([m,n])=>`<span class="chip"><i style="--c:${mkColor(m)}"></i>${esc(mkLabel(m))} <span style="color:var(--muted)">${n}</span></span>`).join('')}</div>`:''}</div></div></div>`;}

/* ---------- Venues (the tab: the list again, with a page per venue) ---------- */
function venuesView(){const list=venueModel().sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name)).slice(0,60);
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Venues · ${esc(eraLabel())}</h2></div><div class="small mono muted">${venueModel().length} venues</div></div><div class="panel">${bars(list,v=>v.count,v=>`${esc([v.place,v.country].filter(Boolean).join(' · '))} · ${v.first}–${v.last} · ${v.bouts} bouts${v.titles?' · '+v.titles+' title bouts':''}`,list[0]?.count||1,'venue',v=>v.name,v=>color(v.top||'catch'))}<p class="small dim" style="margin:10px 0 0">Venues are listed as the sources name them, never drawn; an event whose article names no venue is listed under its city.</p></div>`;}
function venueView(vid){const v=VENUES[vid];const evs=eraEvents().filter(e=>e.venueId===vid);if(!v||!evs.length){venuesView();return;}const bouts=evs.flatMap(e=>e.bouts.filter(inLens));const divs={};for(const b of bouts)divs[b.div]=(divs[b.div]||0)+1;const top=Object.entries(divs).sort((a,b)=>b[1]-a[1])[0]?.[0]||'catch';const titles=bouts.filter(b=>b.title);const wins={};for(const b of bouts)if(b.w)wins[b.w]=(wins[b.w]||0)+1;const topW=Object.entries(wins).sort((a,b)=>b[1]-a[1]).slice(0,10);
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${color(top)}"><div class="panel"><p class="eyebrow">Venue · ${esc([v.city,v.country].filter(Boolean).join(' · '))} · ${evs[0].year}–${evs[evs.length-1].year}</p><h2 style="margin:6px 0 0">${esc(v.name)}</h2></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Events',evs.length,`${v.n} in the whole archive`)}${kpi('Bouts',bouts.length,'')}${kpi('Title bouts',titles.length,'')}${kpi('Finish rate',pct(bouts.filter(b=>b.fin).length,bouts.length)+'%','')}${kpi('Busiest division',divLabel(top),`${divs[top]} bouts`)}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Most wins here</span></div>${bars(topW.map(([id,n])=>({id,n})),x=>x.n,x=>`${bouts.filter(b=>b.w===x.id&&b.fin).length} finishes`,topW[0]?.[1]||1,'fighter',x=>pname(x.id),()=>color(top))}</div><div class="panel"><div class="h3"><span>Divisions here</span></div>${divBars(Object.entries(divs).sort((a,b)=>b[1]-a[1]).map(([id,n])=>({id,n})),a=>a.n,a=>`${bouts.filter(b=>b.div===a.id&&b.title).length} title bouts`,Object.values(divs).sort((a,b)=>b-a)[0]||1)}</div></div>
  <div class="h3" style="margin-top:22px"><span>Every card here</span><small>${evs.length}</small></div><div class="calendar">${[...evs].reverse().map(e=>eventCard(e,false)).join('')}</div>`;}

/* ---------- Records ---------- */
function recordsView(){const bouts=eraBouts();const fighters=fighterAgg().sort(fighterOrder);const divs=divAgg();const quick=bouts.filter(b=>b.fin&&b.secs!=null).sort((a,b)=>a.secs-b.secs);const long=bouts.filter(b=>b.secs!=null).sort((a,b)=>b.secs-a.secs);
  const evs=eraEvents();const big=[...evs].filter(e=>e.att).sort((a,b)=>b.att-a.att).slice(0,10);const venues=venueModel().sort((a,b)=>b.count-a.count).slice(0,10);
  const years=eraSeasons().map(s=>({s,c:champOf(s)})).filter(x=>x.c.best).sort((a,b)=>b.c.best.wins-a.c.best.wins||b.s.year-a.s.year).slice(0,10);
  const finRate=bouts.length?pct(bouts.filter(b=>b.fin).length,bouts.length):0;const ys=eraSeasons().map(s=>s.year);
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Records · ${esc(eraLabel())}</h2></div><div class="small mono muted">${fmt(bouts.length)} bouts</div></div>
  <div class="kpis">${kpi('Bouts',fmt(bouts.length),`${evs.length} events`)}${kpi('Fighters',fmt(fighters.length),`${fighters.filter(f=>f.wins).length} with a win`)}${kpi('Finish rate',finRate+'%',`${fmt(bouts.filter(b=>b.mk==='KO').length)} KO/TKO · ${fmt(bouts.filter(b=>b.mk==='SUB').length)} submissions`)}${kpi('Title bouts',fmt(bouts.filter(b=>b.title).length),'')}${kpi('Fastest finish',quick[0]?clock(quick[0].secs):'—',quick[0]?esc(pname(quick[0].w)+' · '+quick[0].ev.short+' '+quick[0].year):'')}</div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Most wins</span></div>${fighterBars(fighters.slice(0,10),a=>a.wins,a=>`${a.first}–${a.last} · ${a.fin} finishes`,fighters[0]?.wins||1)}</div><div class="panel"><div class="h3"><span>Most finishes</span></div>${fighterBars([...fighters].sort((a,b)=>b.fin-a.fin||b.wins-a.wins).slice(0,10),a=>a.fin,a=>`${a.ko} KO/TKO · ${a.sub} submissions`,Math.max(1,...fighters.map(a=>a.fin)))}</div><div class="panel"><div class="h3"><span>Most title-bout wins</span></div>${fighterBars([...fighters].sort((a,b)=>b.titleW-a.titleW||b.wins-a.wins).slice(0,10).filter(a=>a.titleW),a=>a.titleW,a=>`${a.title} title bouts · ${a.first}–${a.last}`,Math.max(1,...fighters.map(a=>a.titleW)))}</div></div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Fastest finishes</span><small>elapsed time</small></div><div class="board">${quick.slice(0,10).map((b,i)=>`<button type="button" class="bar" data-event="${esc(b.e)}" data-bout="${esc(b.id)}" data-year="${b.year}" style="--i:${i};--team:${color(b.div)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(b.w))}<small> def. ${esc(pname(b.w===b.a?b.b:b.a))} · ${b.year}</small></span><small>${esc(shortMethod(b))}</small></span></span><span class="val">${clock(b.secs)}</span></button>`).join('')}</div></div><div class="panel"><div class="h3"><span>Longest bouts</span><small>elapsed time</small></div><div class="board">${long.slice(0,10).map((b,i)=>`<button type="button" class="bar" data-event="${esc(b.e)}" data-bout="${esc(b.id)}" data-year="${b.year}" style="--i:${i};--team:${color(b.div)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(boutLine(b))}<small> ${b.year}</small></span><small>${esc(shortMethod(b))}</small></span></span><span class="val">${clock(b.secs)}</span></button>`).join('')}</div></div><div class="panel"><div class="h3"><span>Most wins in one year</span></div><div class="board">${years.map(({s,c},i)=>`<button type="button" class="bar" data-year="${s.year}" style="--i:${i};--team:${color(Object.entries(c.best.divs).sort((a,b)=>b[1]-a[1])[0][0])}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(c.best.id))}<small> ${s.year}</small></span><small>${c.best.fin} finishes · ${c.best.titleW} title wins</small></span></span><span class="val">${c.best.wins}</span></button>`).join('')}</div></div></div>
  <div class="three" style="margin-top:14px"><div class="panel"><div class="h3"><span>Busiest venues</span><small>events</small></div>${bars(venues,v=>v.count,v=>`${esc([v.place,v.country].filter(Boolean).join(' · '))} · ${v.first}–${v.last}`,venues[0]?.count||1,'venue',v=>v.name,v=>color(v.top||'catch'))}</div><div class="panel"><div class="h3"><span>Biggest crowds</span><small>attendance as recorded</small></div><div class="board">${big.map((e,i)=>`<button type="button" class="bar" data-event="${esc(e.id)}" data-year="${e.year}" style="--i:${i};--team:${e.main?color(e.main.div):'#5b616b'}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(e.short)}<small> ${e.year}</small></span><small>${esc([e.venue,e.city].filter(Boolean).join(' · '))}</small></span></span><span class="val">${fmt(e.att)}</span></button>`).join('')||'<p class="muted small">No attendances recorded.</p>'}</div></div><div class="panel"><div class="h3"><span>Divisions by finish rate</span><small>minimum 30 bouts</small></div>${divBars(divs.filter(d=>d.bouts>=30).sort((a,b)=>b.finrate-a.finrate),a=>a.finrate,a=>`${a.bouts} bouts`,100,'%')}</div></div>
  ${ys.length>3?`<div class="h3" style="margin-top:22px"><span>Finish rate, year by year</span><small>knockouts and submissions as a share of bouts</small></div><div class="panel"><div class="chart" id="finChart" style="height:240px"></div></div>`:''}`;
  if(ys.length>3){const pts=eraSeasons().map(s=>pct(s.bouts.filter(b=>b.fin).length,s.bouts.length));drawChart($('#finChart'),[{id:'fin',pts}],ys.length,()=>'finish rate',i=>(ys[i]%5===0&&ys.length-1-i>1&&i>1)||i===0||i===ys.length-1?String(ys[i]):'',()=>'var(--accent)','Finish rate by year','%');}}

/* ---------- Barcode ---------- */
const HEATMETRICS={bouts:['Bouts','Bouts in the division that year.'],fin:['Finishes','Bouts ended inside the distance that year.'],title:['Title bouts','Championship bouts that year.']};
function barcodeView(){const ss=eraSeasons();const years=ss.map(s=>s.year);const cell={};const tot={};
  for(const s of ss)for(const b of s.bouts){const d=b.div;const c=cell[d]||(cell[d]={});const k=c[s.year]||(c[s.year]={bouts:0,fin:0,title:0});k.bouts++;if(b.fin)k.fin++;if(b.title)k.title++;tot[d]=(tot[d]||0)+1;}
  const divs=Object.keys(cell).sort((a,b)=>(DIV[a]?.order??99)-(DIV[b]?.order??99));const val=k=>k?k[state.heat]:0;const max=Math.max(1,...divs.flatMap(d=>years.map(y=>val(cell[d][y]))));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Barcode · ${esc(eraLabel())}</h2></div><div class="small mono muted">${divs.length} divisions × ${years.length} years</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="heat" aria-label="Metric">${Object.entries(HEATMETRICS).map(([k,v])=>`<option value="${k}" ${k===state.heat?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(HEATMETRICS[state.heat][1])} Brightness is the cell’s share of the brightest cell; colour is the division’s. Rows in weight order.</span></div>
  <div class="barcode"><div class="bc-row"><span></span><span class="cells" style="gap:2px">${years.map(y=>`<i style="background:none;height:14px;font-size:8px;color:var(--dim);text-align:center;line-height:14px">${years.length<=30||y%5===0?String(y).slice(2):''}</i>`).join('')}</span><span></span></div>${divs.map(d=>`<div class="bc-row"><span class="lab" data-dv="${esc(d)}">${esc(divLabel(d))}</span><span class="cells">${years.map(y=>{const v=val(cell[d][y]);const a=v?Math.max(.12,v/max):0;return `<i data-year="${y}" title="${esc(divLabel(d))} ${y} · ${v}" style="--c:${mixHex(color(d),'#0f1113',a)}"></i>`;}).join('')}</span><span class="tot">${fmt(tot[d])}</span></div>`).join('')}</div></div>`;
  $('#heat').addEventListener('change',e=>{state.heat=e.target.value;render();});}

/* ---------- Duel ---------- */
function swingChart(el,pts,labA,labB,cA,cB){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(180,box.height);const padL=30,padR=30,padT=16,padB=22;const n=pts.length;const max=Math.max(1,...pts.map(p=>Math.abs(p.v)));const x=i=>padL+(n>1?i*(W-padL-padR)/(n-1):(W-padL-padR)/2),y=v=>padT+(H-padT-padB)*(1-(v+max)/(2*max));
  const mid=y(0);let d='';pts.forEach((p,i)=>{d+=(i?'L':'M')+x(i).toFixed(1)+' '+y(p.v).toFixed(1);});
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Head-to-head swing"><line class="gridl" x1="${padL}" x2="${W-padR}" y1="${mid.toFixed(1)}" y2="${mid.toFixed(1)}"/><text class="lb" x="${padL}" y="${padT-4}" style="fill:${cA}">${esc(labA)} ahead</text><text class="lb" x="${padL}" y="${H-6}" style="fill:${cB}">${esc(labB)} ahead</text><path class="ser" d="${d}" style="--c:var(--muted)"/>${pts.map((p,i)=>`<circle class="pt" cx="${x(i).toFixed(1)}" cy="${y(p.v).toFixed(1)}" r="4" fill="${p.win==='A'?cA:p.win==='B'?cB:'#5b616b'}" data-year="${p.y}"><title>${esc(p.label)}</title></circle>`).join('')}</svg>`;}
function duelView(){const fighters=fighterAgg().sort(fighterOrder);const ids=fighters.slice(0,200).map(p=>p.id);if(!state.dA||!FIGHTERS[state.dA])state.dA=ids[0];if(!state.dB||!FIGHTERS[state.dB]||state.dB===state.dA)state.dB=ids.find(i=>i!==state.dA);
  const opts=sel=>[...new Set([state.dA,state.dB,...ids])].filter(Boolean).map(id=>`<option value="${esc(id)}" ${id===sel?'selected':''}>${esc(pname(id))}</option>`).join('');
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Head to head · ${esc(eraLabel())}</h2></div><div class="small mono muted">two fighters · their records, the bouts they shared, the opponents they shared</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="dA" aria-label="First">${opts(state.dA)}</select><span class="mono small muted">vs</span><select id="dB" aria-label="Second">${opts(state.dB)}</select></div><div id="duelBody"></div></div>`;
  $('#dA').addEventListener('change',e=>{state.dA=e.target.value;render();});$('#dB').addEventListener('change',e=>{state.dB=e.target.value;render();});
  const a=state.dA,b=state.dB;if(!a||!b){$('#duelBody').innerHTML='<p class="muted">Pick two.</p>';return;}
  const fa=fighters.find(p=>p.id===a),fb=fighters.find(p=>p.id===b);const cA=color(fa?.top||FIGHTERS[a].div||'catch'),cB=color(fb?.top||FIGHTERS[b].div||'catch');
  const shared=eraBouts().filter(x=>(x.a===a&&x.b===b)||(x.a===b&&x.b===a));const oppOf=(x,id)=>x.a===id?x.b:x.a;const oppsA={},oppsB={};for(const x of eraBouts()){if(x.a===a||x.b===a)oppsA[oppOf(x,a)]=x;if(x.a===b||x.b===b)oppsB[oppOf(x,b)]=x;}const common=Object.keys(oppsA).filter(o=>oppsB[o]&&o!==a&&o!==b);
  let lead=0;const pts=[];let wa=0,wb=0;for(const s of eraSeasons()){let ya=0,yb=0;for(const x of s.bouts){if(x.w===a)ya++;if(x.w===b)yb++;}wa+=ya;wb+=yb;lead+=ya-yb;pts.push({v:lead,win:ya>yb?'A':yb>ya?'B':'',y:s.year,label:`${s.year} · ${pname(a)} ${ya} · ${pname(b)} ${yb}`});}
  const rec=f=>f?`${f.wins}–${f.losses}${f.draws?'–'+f.draws:''}`:'0–0';const resOf=(x,id)=>x.res==='W'?(x.w===id?'W':'L'):x.res;
  $('#duelBody').innerHTML=`<div class="duel-heads"><div class="dh" style="--team:${cA}"><span class="eyebrow">${esc(pname(a))}</span><b>${rec(fa)}</b><small>${fa?fa.fin+' finishes · '+fa.titleW+' title wins':''}${shared.length?` · ${shared.filter(x=>x.w===a).length} of ${shared.length} shared bouts won`:''}</small></div><div class="dh" style="--team:${cB}"><span class="eyebrow">${esc(pname(b))}</span><b>${rec(fb)}</b><small>${fb?fb.fin+' finishes · '+fb.titleW+' title wins':''}${shared.length?` · ${shared.filter(x=>x.w===b).length} won`:''}</small></div></div><div class="h3" style="margin-top:18px"><span>The lead in wins, year by year</span><small>cumulative</small></div><div class="chart" id="duelSwing" style="height:220px"></div>
  ${shared.length?`<div class="h3" style="margin-top:18px"><span>Bouts they shared</span><small>${shared.length}</small></div><div class="tablewrap"><table><tr><th>Date</th><th>Event</th><th>Result</th><th>Method</th><th class="n">R</th><th class="n">Time</th></tr>${[...shared].reverse().map(x=>`<tr><td class="mono"><a href="#" data-event="${esc(x.e)}" data-bout="${esc(x.id)}" data-year="${x.year}">${esc(day(x.date))}</a></td><td>${esc(x.ev.short)}${x.title?' <span class="belt">title</span>':''}</td><td>${boutWho(x)}</td><td>${mkChip(x)} <span class="small muted">${esc(x.mk==='DEC'?(x.dk||''):x.det||'')}</span></td><td class="n">${x.round??''}</td><td class="n mono">${esc(x.time||'')}</td></tr>`).join('')}</table></div>`:''}
  ${common.length?`<div class="h3" style="margin-top:18px"><span>Opponents they shared</span><small>${common.length} · the most recent bout against each</small></div><div class="tablewrap" style="max-height:420px"><table><tr><th>Opponent</th><th style="color:${cA}">${esc(pname(a))}</th><th style="color:${cB}">${esc(pname(b))}</th></tr>${common.map(o=>`<tr><td>${fl(o)}</td><td>${resOf(oppsA[o],a)} · ${esc(shortMethod(oppsA[o]))} · <a href="#" data-event="${esc(oppsA[o].e)}" data-bout="${esc(oppsA[o].id)}" data-year="${oppsA[o].year}">${oppsA[o].year}</a></td><td>${resOf(oppsB[o],b)} · ${esc(shortMethod(oppsB[o]))} · <a href="#" data-event="${esc(oppsB[o].e)}" data-bout="${esc(oppsB[o].id)}" data-year="${oppsB[o].year}">${oppsB[o].year}</a></td></tr>`).join('')}</table></div>`:''}`;
  if(pts.length)swingChart($('#duelSwing'),pts,pname(a),pname(b),cA,cB);}

/* ---------- Sources & coverage ---------- */
function drawSources(){const cov=A.coverage||{};const src=A.sources||[];
  $('#sourcesBody').innerHTML=`<p class="eyebrow">Cage edition / ${esc(day(A.snapshot))}</p><h2>Every UFC bout since 1993, one archive.</h2><div class="kpis">${kpi('Events',fmt(cov.events||EVENTS.length),`${S.length} years`)}${kpi('Bouts',fmt(cov.bouts||BOUTS.length),`${fmt(cov.titleBouts)} title bouts`)}${kpi('Fighters',fmt(Object.keys(FIGHTERS).length),`${fmt(cov.fightersWithArticle)} with an article`)}${kpi('Venues',fmt(cov.venues),'listed, never drawn')}${kpi('Without an elapsed time',fmt(cov.withoutTime),'no round or time recorded')}</div>
<h3>Sources</h3><ol>${src.map(s=>`<li>${s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.name)}</a>`:esc(s.name)}${s.licence?` (<a href="${esc(s.licenceUrl||'#')}" target="_blank" rel="noopener">${esc(s.licence)}</a>)`:''}</li>`).join('')}</ol><p>${esc(A.method||'')} ${(A.issues||[]).length?`${(A.issues||[]).length} events whose results table could not be read are listed in the data file.`:''} Every event links to the article it came from.</p>
<h3>How to read the statistics</h3><p class="small muted">A win is the result as the article records it, in the order the article lists the bouts (the main event first). A finish is a knockout, technical knockout or submission; decisions, disqualifications, draws and no contests are not finishes. A title bout is one the article’s notes describe as being for a championship — undisputed, interim or vacant — and tournament bouts of the early years are marked as such. Elapsed time adds five-minute rounds from UFC 21 in July 1999; before that only a first-round time is taken as elapsed, so the early tournaments’ overtime rounds are not timed. Records are counted from the bouts in the archive and the lens, not the fighters’ careers elsewhere. Venues and cities are as the articles name them; an event whose article names no venue is listed under its city. Nothing on this page is affiliated with the promotion; its names are used only to identify the events.</p>`;}

/* ---------- deep links ---------- */
let routeLock=false;
function writeRoute(){if(routeLock)return;const q=[];if(state.div!=='all')q.push('division='+encodeURIComponent(state.div));if(state.era!=='all')q.push('era='+encodeURIComponent(state.era));if(state.whole)q.push('whole=1');else q.push('season='+state.year);q.push('tab='+state.tab);if(state.tab==='event'&&!state.whole&&state.event)q.push('event='+encodeURIComponent(state.event));for(const [k,t] of [['fighter','fighters'],['dv','divisions'],['venue','venues']]){if(state.tab===t&&state[k])q.push(k+'='+encodeURIComponent(state[k]));}if(state.tab==='duel'&&state.dA&&state.dB)q.push('duel='+encodeURIComponent(state.dA+'|'+state.dB));const h='#'+q.join('&');if(location.hash!==h){try{history.replaceState(null,'',h);}catch(e){}}}
const DIV_LENSES=()=>['all','M','W',...DIVS.map(d=>d.key)];
function readRoute(){const h=location.hash.replace(/^#\/?/,'');if(!h||/^static-/.test(h))return false;const p={};for(const kv of h.split('&')){const i=kv.indexOf('=');p[i<0?kv:kv.slice(0,i)]=i<0?'1':decodeURIComponent(kv.slice(i+1));}let any=false;
  if(p.division&&DIV_LENSES().includes(p.division)){state.div=p.division;any=true;}rebuildSeasons();
  if(p.era&&(p.era==='all'||ERAS.some(e=>e.id===p.era))){state.era=p.era;any=true;}
  if(p.event&&byEvent[p.event]){const e=byEvent[p.event];if(!e.bouts.some(inLens)){state.div='all';rebuildSeasons();}state.event=p.event;state.year=e.year;any=true;}else if(p.season&&byYear[+p.season]){state.year=+p.season;any=true;}
  if(p.bout&&byBout[p.bout])state.bout=p.bout;
  if(state.era!=='all'&&!inEraYear(state.year)){if(p.season||p.event)state.era='all';else state.year=eraSeasons().slice(-1)[0]?.year||state.year;}
  state.whole=p.whole==='1';if(state.whole)any=true;
  if(p.tab&&TABS.some(t=>t[0]===p.tab)){state.tab=p.tab;any=true;}
  state.fighter=p.fighter&&FIGHTERS[p.fighter]?p.fighter:null;state.dv=p.dv&&DIV[p.dv]?p.dv:null;state.venue=p.venue&&VENUES[p.venue]?p.venue:null;
  if(p.duel){const [a,b]=p.duel.split('|');state.dA=a;state.dB=b;any=true;}
  return any;}

/* ---------- render, navigation, events ---------- */
function render(){drawTabs();if(tour.stopped||!tour.timer)drawEraStrip();const v={season:seasonView,event:eventView,divisions:()=>state.dv?divisionView(state.dv):divisionsView(),fighters:()=>state.fighter?fighterView(state.fighter):fightersView(),venues:()=>state.venue?venueView(state.venue):venuesView(),records:recordsView,barcode:barcodeView,duel:duelView}[state.tab];try{v();}catch(e){$('#view').innerHTML=`<p class="muted">Something in this view could not be drawn: ${esc(e.message)}</p>`;console.error(e);}writeRoute();}
function go(tab,scroll=true){state.tab=tab;render();if(scroll)$('#stage').scrollIntoView({behavior:RM?'auto':'smooth',block:'start'});}
function ensureYearInLens(y){if(state.era!=='all'&&!inEraYear(y)){state.era='all';$('#eraSelect').value='all';}}
function setSeason(y,scroll){state.whole=false;ensureYearInLens(y);state.year=y;state.event=null;fillSeasons();applyTheme();drawRiver();if(state.tab!=='season'&&state.tab!=='event')state.tab='season';go(state.tab,scroll);}
function openEvent(id,scroll,bout){const e=byEvent[id];if(!e)return;state.whole=false;if(!e.bouts.some(inLens)){state.div='all';$('#division').value='all';relens(false);}ensureYearInLens(e.year);state.year=e.year;state.event=id;state.bout=bout||null;fillSeasons();applyTheme();drawRiver();go('event',scroll);}
function fillSeasons(){const sel=$('#season');const ss=eraSeasons();if(!ss.length){sel.innerHTML='';return;}const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);sel.innerHTML=`<option value="era">${e?'Whole era':'All years'} · ${ss[0].year}–${ss[ss.length-1].year}</option>`+ss.slice().reverse().map(s=>`<option value="${s.year}">${s.year}</option>`).join('');sel.value=state.whole?'era':state.year;}
function setEra(id){tourStop();state.era=id;$('#eraSelect').value=id;if(id!=='all'){if(!inEraYear(state.year)){const last=eraSeasons().slice(-1)[0];state.year=last?last.year:state.year;state.event=null;}}fillSeasons();applyTheme();drawRiver();drawGrid();render();}
function relens(rerender=true){rebuildSeasons();if(!byYear[state.year])state.year=LAST_YEAR;state.event=null;state.fighter=null;state.dv=null;state.venue=null;fillSeasons();$('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.filter(e=>e.to>=FIRST_YEAR).map(e=>`<option value="${e.id}">${esc(ERA_SHORT[e.id]||e.name)} · ${e.from}–${e.to}</option>`).join('');$('#eraSelect').value=state.era;if(rerender){applyTheme();drawRiver();drawGrid();render();}}
function init(){
  rebuildSeasons();
  $('#division').innerHTML=`<option value="all">All divisions</option><option value="M">Men’s divisions</option><option value="W">Women’s divisions</option>`+DIVS.map(d=>`<option value="${esc(d.key)}">${esc(d.label)}</option>`).join('');
  $('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.map(e=>`<option value="${e.id}">${esc(ERA_SHORT[e.id]||e.name)} · ${e.from}–${e.to}</option>`).join('');
  $('#theme').innerHTML=`<option value="champion">Division of the year</option>`+DIVS.map(d=>`<option value="${esc(d.key)}">${esc(d.label)}</option>`).join('');
  fillSeasons();
  const cov=A.coverage||{};
  $('#edition').innerHTML=`<span><span class="live"></span><b>${fmt(EVENTS.length)}</b> events</span><span><b>${fmt(BOUTS.length)}</b> bouts</span><span><b>${fmt(Object.keys(FIGHTERS).length)}</b> fighters</span><span><b>${fmt(cov.venues||Object.keys(VENUES).length)}</b> venues</span><span>through <b>${esc(day(A.lastDate))}</b></span>`;
  $('#reading').open=false;
  const deep=readRoute();if(deep){tourStop();$('#division').value=state.div;$('#eraSelect').value=state.era;fillSeasons();}
  drawSources();applyTheme();drawRiver();drawGrid();render();lightsOut();if(deep&&(state.tab!=='season'||state.whole||state.era!=='all'))setTimeout(()=>$('#stage').scrollIntoView({behavior:'auto',block:'start'}),60);
  addEventListener('hashchange',()=>{if(/^#static-/.test(location.hash)){$('#reading').open=true;return;}routeLock=true;try{if(readRoute()){tourStop();$('#division').value=state.div;$('#eraSelect').value=state.era;fillSeasons();applyTheme();drawRiver();drawGrid();render();}}finally{routeLock=false;}});
  $('#eraSelect').addEventListener('change',e=>setEra(e.target.value));
  $('#division').addEventListener('change',e=>{state.div=e.target.value;relens();});
  $('#season').addEventListener('change',e=>{if(e.target.value==='era'){state.whole=true;applyTheme();drawRiver();if(state.tab!=='season'&&state.tab!=='event')state.tab='season';go(state.tab,false);}else setSeason(+e.target.value,false);});
  $('#theme').addEventListener('change',applyTheme);
  $('#eraStrip').addEventListener('click',e=>{const s=e.target.closest('[data-era]');if(s)setEra(state.era===s.dataset.era?'all':s.dataset.era);});
  $('#eraStrip').addEventListener('pointerenter',()=>{tourPause();},{passive:true});$('#eraStrip').addEventListener('pointerleave',()=>{if(!tour.stopped)tourStart();},{passive:true});
  $('#eraStrip').addEventListener('mouseover',e=>{const s=e.target.closest('[data-era]');if(s&&!tour.stopped){drawEraStrip(s.dataset.era);}});
  if('IntersectionObserver' in window){new IntersectionObserver(en=>{tour.visible=en[0].isIntersecting;if(tour.visible)tourStart();else tourPause();},{threshold:.2}).observe($('#eraStrip'));}else{tour.visible=true;tourStart();}
  $('#gridSort').addEventListener('change',e=>{state.gridSort=e.target.value;drawGrid();});$('#gridMin').addEventListener('change',e=>{state.gridMin=+e.target.value;drawGrid();});$('#gridFind').addEventListener('input',e=>{state.gridFind=e.target.value;drawGrid();});
  $('#circuits').addEventListener('click',e=>{const b=e.target.closest('[data-venue]');if(b){state.venue=b.dataset.venue;go('venues',true);}});
  const clear=t=>{if(t==='fighters')state.fighter=null;if(t==='divisions')state.dv=null;if(t==='venues')state.venue=null;};
  $('#tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;clear(b.dataset.tab);go(b.dataset.tab,false);});
  $('#view').addEventListener('click',e=>{const a=e.target.closest('[data-event],[data-fighter],[data-dv],[data-venue],[data-year],[data-tab],[data-bout]');if(!a)return;if(a.tagName==='A')e.preventDefault();
    if(a.dataset.tab){clear(a.dataset.tab);go(a.dataset.tab,false);return;}
    if(a.dataset.event){openEvent(a.dataset.event,false,a.dataset.bout);return;}
    if(a.dataset.bout&&!a.dataset.event){const b=byBout[a.dataset.bout];if(b&&state.tab!=='event')openEvent(b.e,false,b.id);return;}
    if(a.dataset.year){const y=+a.dataset.year;if(!byYear[y])return;ensureYearInLens(y);state.whole=false;state.year=y;state.event=null;fillSeasons();applyTheme();drawRiver();go('season',false);return;}
    if(a.dataset.fighter){state.fighter=a.dataset.fighter;go('fighters',false);return;}
    if(a.dataset.dv){state.dv=a.dataset.dv;go('divisions',false);return;}
    if(a.dataset.venue){state.venue=a.dataset.venue;go('venues',false);return;}});
  addEventListener('resize',()=>{clearTimeout(window.__rz);window.__rz=setTimeout(()=>{drawRiver();if(['season','duel','records','divisions'].includes(state.tab))render();},150);});
}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
