// Headless smoke over docs/: every page loads without errors, every tab/era/season renders, phone width has no horizontal scroll.
// Usage: node tools/check_site.js [f1|rugby|cricket|tennis|motogp|sbk|hub]
const { chromium } = require('playwright'); const path = require('path');
const DOCS = path.resolve(__dirname, '..', 'docs'); const PORT = 8765 + Math.floor(Math.random() * 200); const BASE = `http://127.0.0.1:${PORT}/`;
const url = k => BASE + (k === 'hub' ? '' : k + '/');
// the production shells fetch their archive, so docs/ is served over http (python's stdlib server)
const { spawn } = require('child_process'); const server = spawn('python3', ['-m', 'http.server', String(PORT), '--bind', '127.0.0.1', '--directory', DOCS], { stdio: 'ignore' });
const wait = ms => new Promise(r => setTimeout(r, ms));
const SHOTS = path.join(__dirname, 'shots');
async function open(b, k, vp, hash = '') { const ctx = await b.newContext(vp); const p = await ctx.newPage(); const errs = []; p.on('pageerror', e => errs.push(e.message + ' @ ' + (e.stack || '').split('\n')[1])); p.on('console', m => { if (m.type() === 'error' && !/fonts\.g|net::ERR/.test(m.text())) errs.push('console: ' + m.text()); }); const t0 = Date.now(); await p.goto(url(k) + hash, { waitUntil: 'load', timeout: 180000 }); if (k !== 'hub') await p.waitForFunction(() => typeof state !== 'undefined' && document.querySelectorAll('#tabs button').length > 0, null, { timeout: 120000 }); const ms = Date.now() - t0; await p.waitForTimeout(400); await p.click('#skipLights').catch(() => {}); await p.waitForTimeout(1200); return { p, errs, ms, ctx }; }
const motor = { f1: { tabs: ['race', 'drivers', 'teams', 'circuits', 'records', 'barcode', 'duel'], who: 'drivers' }, motogp: { tabs: ['race', 'riders', 'teams', 'circuits', 'records', 'barcode', 'duel'], who: 'riders' }, sbk: { tabs: ['race', 'riders', 'teams', 'circuits', 'records', 'barcode', 'duel'], who: 'riders' } };
(async () => { await wait(800); const b = await chromium.launch(); const fs = require('fs'); const keys = process.argv[2] ? [process.argv[2]] : ['hub', 'f1', 'rugby', 'cricket', 'tennis', 'tt', 'motogp', 'sbk', 'ufc', 'dakar'].filter(k => k === 'hub' || fs.existsSync(path.join(DOCS, k, 'index.html'))); console.log('checking', keys.join(', ')); let bad = 0;
  // deep links, as the static pages use them
  const DEEP = { f1: ['#tab=drivers&driver=senna', () => state.driver === 'senna' && /Senna/.test(document.querySelector('#view h2')?.textContent || '')], rugby: ['#tab=nations&nation=South%20Africa&era=pro', () => state.nation === 'South Africa' && state.era === 'pro'], tt: ['#tab=riders&rider=joey-dunlop', () => state.rider === 'joey-dunlop' && /Dunlop/.test(document.querySelector('#view h2')?.textContent || '')], tennis: ['#tour=W&tab=players&player=W200033', () => state.player === 'W200033' && state.tour === 'W' && /Williams/.test(document.querySelector('#view h2')?.textContent || '')], cricket: ['#gender=W&format=T20I&tab=nations&nation=Australia', () => state.nation === 'Australia' && state.gender === 'W' && state.fmt === 'T20I' && /Australia/.test(document.querySelector('#view h2')?.textContent || '')], motogp: ['#tab=riders&rider=valentino-rossi', () => state.rider === 'valentino-rossi' && /Rossi/.test(document.querySelector('#view h2')?.textContent || '')], sbk: ['#season=2001&tab=race', () => state.year === 2001 && state.tab === 'race'], ufc: ['#tab=fighters&fighter=royce-gracie', () => state.fighter === 'royce-gracie' && /Gracie/.test(document.querySelector('#view h2')?.textContent || '')], dakar: ['#tab=drivers&driver=stephane-peterhansel', () => state.driver === 'stephane-peterhansel' && /Peterhansel/.test(document.querySelector('#view h2')?.textContent || '')] };
  for (const k of keys) { if (!DEEP[k]) continue; const { p, errs, ctx } = await open(b, k, { viewport: { width: 1440, height: 900 } }, DEEP[k][0]); const ok = await p.evaluate(DEEP[k][1]); const back = await p.evaluate(() => location.hash); if (!ok || errs.length) { bad++; console.log(k, 'DEEP LINK FAILED', DEEP[k][0], back, errs.slice(0, 2)); } else console.log(k, 'deep link ok', back); await ctx.close(); }
  for (const k of keys) { const { p, errs, ms, ctx } = await open(b, k, { viewport: { width: 1440, height: 900 } }); let info = {}, smoke = [];
    if (k === 'hub') { info = await p.evaluate(() => ({ links: [...document.querySelectorAll('a.sport')].map(a => a.getAttribute('href')), title: document.title })); await p.screenshot({ path: `${SHOTS}/hub.png`, fullPage: true }); }
    else if (motor[k]) { const m = motor[k];
      info = await p.evaluate(() => ({ title: document.title, brand: document.querySelector('.brand')?.textContent.trim().slice(0, 40), bands: document.querySelectorAll('#riverSvg .band').length, circuits: document.querySelectorAll('#circuits .circ').length, seasons: DATA.seasons.length, races: DATA.seasons.reduce((a, s) => a + s.races.length, 0), rows: DATA.seasons.reduce((a, s) => a + s.races.reduce((b, r) => b + r.rows.length, 0), 0), readingOpen: document.querySelector('#reading').open, canonical: document.querySelector('link[rel=canonical]')?.href }));
      await p.screenshot({ path: `${SHOTS}/${k}-river.png` });
      for (const t of m.tabs) { await p.click(`#tabs [data-tab="${t}"]`); await p.waitForTimeout(t === 'race' ? 1200 : 350); } await p.evaluate(() => document.querySelector('#stage').scrollIntoView()); await p.waitForTimeout(300); await p.screenshot({ path: `${SHOTS}/${k}-stage.png` });
      smoke = await p.evaluate((who) => { const out = []; for (const s of DATA.seasons) { state.year = s.year; state.era = 'all'; state.whole = false; for (const tab of ['season', 'race']) { state.tab = tab; state.race = 1; try { render(); } catch (e) { out.push(s.year + ' ' + tab + ': ' + e.message); } } stopReplay(); }
        for (const e of DATA.eras.map(e => e.id).concat(['all'])) { state.era = e; state.driver = null; state.rider = null; state.team = null; state.circuit = null; fillSeasons(); for (const tab of [who, 'teams', 'circuits', 'records', 'barcode', 'duel']) { state.tab = tab; try { render(); } catch (x) { out.push(e + ' ' + tab + ': ' + x.message); } } state.whole = true; for (const tab of ['season', 'race']) { state.tab = tab; try { render(); } catch (x) { out.push(e + ' whole ' + tab + ': ' + x.message); } } state.whole = false; }
        state.era = 'all'; fillSeasons(); for (const c of Object.keys(DATA.circuits)) { state.circuit = c; state.tab = 'circuits'; try { render(); } catch (x) { out.push('circuit ' + c + ': ' + x.message); } } state.circuit = null; state.tab = 'season'; render(); return out; }, m.who);
    } else if (k === 'tt') {
      info = await p.evaluate(() => ({ title: document.title, brand: document.querySelector('.brand')?.textContent.trim().slice(0, 40), bands: document.querySelectorAll('#riverSvg .band').length, places: document.querySelectorAll('#courseSvg .lm').length, courseLen: Math.round(document.querySelector('#courseLine').getTotalLength()), seasons: S.length, races: RACES.length, riders: Object.keys(RIDERS).length, readingOpen: document.querySelector('#reading').open, canonical: document.querySelector('link[rel=canonical]')?.href }));
      if (!info.places || !info.courseLen) { bad++; console.log(k, 'COURSE NOT DRAWN', info); }
      await p.screenshot({ path: `${SHOTS}/tt-river.png` });
      for (const t of ['race', 'riders', 'marques', 'classes', 'records', 'barcode', 'duel']) { await p.click(`#tabs [data-tab="${t}"]`); await p.waitForTimeout(t === 'race' ? 1500 : 350); } await p.evaluate(() => document.querySelector('#stage').scrollIntoView()); await p.waitForTimeout(300); await p.screenshot({ path: `${SHOTS}/tt-stage.png` });
      smoke = await p.evaluate(() => { const out = []; const T = (label, fn) => { try { fn(); } catch (x) { out.push(label + ': ' + x.message); } };
        for (const f of ['all', ...FAMILIES]) { state.family = f; document.querySelector('#family').value = f; state.era = 'all'; T(f + ' relens', () => relens(false)); T(f + ' river', () => { applyTheme(); drawRiver(); });
          for (const s of S.filter((s, i) => f === 'all' || i % 3 === 0)) { state.year = s.year; state.whole = false; state.race = null; for (const tab of ['season', 'race']) { state.tab = tab; T(f + ' ' + s.year + ' ' + tab, render); } stopReplay(); }
          for (const e of ERAS.map(e => e.id).concat(['all'])) { state.era = e; state.rider = null; state.marque = null; state.cls = null; fillSeasons(); for (const tab of ['riders', 'marques', 'classes', 'records', 'barcode', 'duel']) { state.tab = tab; T(f + ' ' + e + ' ' + tab, render); } state.duelBy = 'm'; state.dA = state.dB = null; T(f + ' ' + e + ' duel marques', render); state.duelBy = 'r'; state.dA = state.dB = null; state.whole = true; for (const tab of ['season', 'race']) { state.tab = tab; T(f + ' ' + e + ' whole ' + tab, render); } state.whole = false; }
          state.era = 'all'; fillSeasons(); }
        state.family = 'all'; document.querySelector('#family').value = 'all'; relens(false); state.era = 'all'; fillSeasons();
        for (const r of RACES.filter((r, i) => i % 7 === 0)) { T('race ' + r.id, () => openRace(r.id, false)); stopReplay(); }
        for (const id of Object.keys(RIDERS).filter((v, i) => i % 15 === 0)) { state.rider = id; state.tab = 'riders'; T('rider ' + id, render); } state.rider = null;
        for (const m of marqueAgg().map(m => m.id)) { state.marque = m; state.tab = 'marques'; T('marque ' + m, render); } state.marque = null;
        for (const c of FAMILIES) { state.cls = c; state.tab = 'classes'; T('class ' + c, render); } state.cls = null;
        for (const k of Object.keys(LENSES)) { state.lens = k; state.tab = 'marques'; T('lens ' + k, render); } for (const k of Object.keys(PLENSES)) { state.plens = k; state.tab = 'riders'; T('plens ' + k, render); } for (const k of Object.keys(HEATMETRICS)) { state.heat = k; state.tab = 'barcode'; T('heat ' + k, render); }
        state.tab = 'season'; render(); return out; });
    } else if (k === 'ufc') {
      info = await p.evaluate(() => ({ title: document.title, brand: document.querySelector('.brand')?.textContent.trim().slice(0, 40), bands: document.querySelectorAll('#riverSvg .band').length, venues: document.querySelectorAll('#circuits .circ').length, seasons: S.length, events: EVENTS.length, bouts: BOUTS.length, fighters: Object.keys(FIGHTERS).length, readingOpen: document.querySelector('#reading').open, canonical: document.querySelector('link[rel=canonical]')?.href }));
      if (!info.venues || !info.bands) { bad++; console.log(k, 'ARENAS OR RIVER NOT DRAWN', info); }
      await p.screenshot({ path: `${SHOTS}/ufc-river.png` });
      for (const t of ['event', 'divisions', 'fighters', 'venues', 'records', 'barcode', 'duel']) { await p.click(`#tabs [data-tab="${t}"]`); await p.waitForTimeout(350); } await p.evaluate(() => document.querySelector('#stage').scrollIntoView()); await p.waitForTimeout(300); await p.screenshot({ path: `${SHOTS}/ufc-stage.png` });
      smoke = await p.evaluate(() => { const out = []; const T = (label, fn) => { try { fn(); } catch (x) { out.push(label + ': ' + x.message); } };
        for (const f of ['all', 'M', 'W', ...DIVS.map(d => d.key)]) { state.div = f; document.querySelector('#division').value = f; state.era = 'all'; T(f + ' relens', () => relens(false)); T(f + ' river', () => { applyTheme(); drawRiver(); drawGrid(); });
          for (const s of S.filter((s, i) => f === 'all' || i % 4 === 0)) { state.year = s.year; state.whole = false; state.event = null; for (const tab of ['season', 'event']) { state.tab = tab; T(f + ' ' + s.year + ' ' + tab, render); } }
          for (const e of ERAS.map(e => e.id).concat(['all'])) { state.era = e; state.fighter = null; state.dv = null; state.venue = null; fillSeasons(); for (const tab of ['divisions', 'fighters', 'venues', 'records', 'barcode', 'duel']) { state.tab = tab; T(f + ' ' + e + ' ' + tab, render); } state.dA = state.dB = null; state.whole = true; for (const tab of ['season', 'event']) { state.tab = tab; T(f + ' ' + e + ' whole ' + tab, render); } state.whole = false; }
          state.era = 'all'; fillSeasons(); }
        state.div = 'all'; document.querySelector('#division').value = 'all'; relens(false); state.era = 'all'; fillSeasons();
        for (const e of EVENTS.filter((e, i) => i % 9 === 0)) { T('event ' + e.id, () => openEvent(e.id, false)); }
        for (const id of Object.keys(FIGHTERS).filter((v, i) => i % 25 === 0)) { state.fighter = id; state.tab = 'fighters'; T('fighter ' + id, render); } state.fighter = null;
        for (const d of DIVS.map(d => d.key)) { state.dv = d; state.tab = 'divisions'; T('division ' + d, render); } state.dv = null;
        for (const v of Object.keys(VENUES).filter((v, i) => i % 6 === 0)) { state.venue = v; state.tab = 'venues'; T('venue ' + v, render); } state.venue = null;
        for (const k of Object.keys(LENSES)) { state.lens = k; state.tab = 'divisions'; T('lens ' + k, render); } for (const k of Object.keys(PLENSES)) { state.plens = k; state.tab = 'fighters'; T('plens ' + k, render); } for (const k of Object.keys(HEATMETRICS)) { state.heat = k; state.tab = 'barcode'; T('heat ' + k, render); }
        state.tab = 'season'; render(); return out; });
    } else if (k === 'dakar') {
      info = await p.evaluate(() => ({ title: document.title, brand: document.querySelector('.brand')?.textContent.trim().slice(0, 40), bands: document.querySelectorAll('#riverSvg .band').length, routes: document.querySelectorAll('#circuits .circ').length, seasons: S.length, editions: EDS.length, people: Object.keys(PEOPLE).length, routeMap: !!document.querySelector('#routeSvg'), readingOpen: document.querySelector('#reading').open, canonical: document.querySelector('link[rel=canonical]')?.href }));
      if (!info.routes || !info.bands) { bad++; console.log(k, 'ROUTES OR RIVER NOT DRAWN', info); }
      await p.screenshot({ path: `${SHOTS}/dakar-river.png` });
      for (const t of ['drivers', 'marques', 'classes', 'records', 'barcode', 'duel', 'season']) { await p.click(`#tabs [data-tab="${t}"]`); await p.waitForTimeout(350); } await p.evaluate(() => document.querySelector('#stage').scrollIntoView()); await p.waitForTimeout(300); await p.screenshot({ path: `${SHOTS}/dakar-stage.png` });
      smoke = await p.evaluate(() => { const out = []; const T = (label, fn) => { try { fn(); } catch (x) { out.push(label + ': ' + x.message); } };
        for (const f of ['all', ...CATS]) { state.cat = f; document.querySelector('#family').value = f; state.era = 'all'; T(f + ' relens', () => relens(false)); T(f + ' river', () => { applyTheme(); drawRiver(); drawGrid(); });
          for (const s of S.filter((s, i) => f === 'all' || i % 3 === 0)) { state.year = s.year; state.whole = false; state.tab = 'season'; T(f + ' ' + s.year + ' season', render); }
          for (const e of ERAS.map(e => e.id).concat(['all'])) { state.era = e; state.driver = null; state.marque = null; state.cls = null; fillSeasons(); for (const tab of ['drivers', 'marques', 'classes', 'records', 'barcode', 'duel']) { state.tab = tab; T(f + ' ' + e + ' ' + tab, render); } state.dA = state.dB = null; state.whole = true; state.tab = 'season'; T(f + ' ' + e + ' whole season', render); state.whole = false; }
          state.era = 'all'; fillSeasons(); }
        state.cat = 'all'; document.querySelector('#family').value = 'all'; relens(false); state.era = 'all'; fillSeasons();
        for (const id of Object.keys(PEOPLE).filter((v, i) => i % 12 === 0)) { state.driver = id; state.tab = 'drivers'; T('driver ' + id, render); } state.driver = null;
        for (const m of marqueAgg().map(m => m.id)) { state.marque = m; state.tab = 'marques'; T('marque ' + m, render); } state.marque = null;
        for (const c of CATS) { state.cls = c; state.tab = 'classes'; T('class ' + c, render); } state.cls = null;
        for (const k of Object.keys(LENSES)) { state.lens = k; state.tab = 'marques'; T('lens ' + k, render); } for (const k of Object.keys(PLENSES)) { state.plens = k; state.tab = 'drivers'; T('plens ' + k, render); } for (const k of Object.keys(HEATMETRICS)) { state.heat = k; state.tab = 'barcode'; T('heat ' + k, render); }
        for (const by of ['d', 'm']) { state.duelBy = by; state.dA = state.dB = null; state.tab = 'duel'; T('duel ' + by, render); }
        state.tab = 'season'; render(); return out; });
    } else if (k === 'tennis') {
      info = await p.evaluate(() => ({ title: document.title, brand: document.querySelector('.brand')?.textContent.trim().slice(0, 40), bands: document.querySelectorAll('#riverSvg .band').length, courts: document.querySelectorAll('#circuits .circ').length, seasons: S.length, titles: CHAMPS.length, editions: Object.keys(EDS).length, players: Object.keys(PLAYERS).length, readingOpen: document.querySelector('#reading').open, canonical: document.querySelector('link[rel=canonical]')?.href }));
      await p.screenshot({ path: `${SHOTS}/tennis-river.png` });
      for (const t of ['draw', 'players', 'nations', 'tournaments', 'records', 'barcode', 'duel']) { await p.click(`#tabs [data-tab="${t}"]`); await p.waitForTimeout(t === 'draw' || t === 'duel' ? 3000 : 350); } await p.evaluate(() => document.querySelector('#stage').scrollIntoView()); await p.waitForTimeout(300); await p.screenshot({ path: `${SHOTS}/tennis-stage.png` });
      await p.click('#tabs [data-tab="draw"]'); await p.waitForTimeout(3000); await p.evaluate(() => document.querySelector('#stage').scrollIntoView()); await p.screenshot({ path: `${SHOTS}/tennis-draw.png` });
      const shard = await p.evaluate(() => ({ loaded: Object.keys(DETAILS).length, bracket: document.querySelectorAll('.bm').length, sheet: document.querySelectorAll('.sheet').length })); console.log(k, 'draw', JSON.stringify(shard)); if (!shard.bracket) { bad++; console.log(k, 'NO BRACKET RENDERED for the default edition'); }
      smoke = await p.evaluate(() => { const out = []; const T = (label, fn) => { try { fn(); } catch (x) { out.push(label + ': ' + x.message); } };
        for (const g of ['M', 'W', 'all']) for (const f of ['S', 'D']) { state.tour = g; state.disc = f; document.querySelector('#tour').value = g; document.querySelector('#disc').value = f; state.era = 'all'; T(g + f + ' relens', () => relens(false)); T(g + f + ' river', () => { applyTheme(); drawRiver(); drawGrid(); });
          for (const s of S.filter((s, i) => i % (f === 'S' && g !== 'all' ? 1 : 4) === 0)) { state.year = s.year; state.whole = false; state.edition = null; state.match = null; for (const tab of ['season', 'draw']) { state.tab = tab; T(g + f + ' ' + s.year + ' ' + tab, render); } stopReplay(); }
          for (const e of ERAS.map(e => e.id).concat(['all'])) { state.era = e; state.nation = null; state.player = null; state.tourn = null; fillSeasons(); for (const tab of ['players', 'nations', 'tournaments', 'records', 'barcode', 'duel']) { state.tab = tab; T(g + f + ' ' + e + ' ' + tab, render); } state.duelBy = 'n'; state.dA = state.dB = null; T(g + f + ' ' + e + ' duel nations', render); state.duelBy = 'p'; state.dA = state.dB = null; state.whole = true; for (const tab of ['season', 'draw']) { state.tab = tab; T(g + f + ' ' + e + ' whole ' + tab, render); } state.whole = false; }
          state.era = 'all'; fillSeasons(); }
        state.tour = 'M'; state.disc = 'S'; document.querySelector('#tour').value = 'M'; document.querySelector('#disc').value = 'S'; relens(false); state.era = 'all'; fillSeasons();
        for (const t of Object.keys(TOURN).filter((v, i) => i % 25 === 0)) { state.tourn = t; state.tab = 'tournaments'; T('tourn ' + t, render); } state.tourn = null;
        for (const n of Object.keys(IOC).filter((v, i) => i % 3 === 0)) { state.nation = n; state.tab = 'nations'; T('nation ' + n, render); } state.nation = null;
        for (const pl of Object.keys(PLAYERS).filter((p, i) => i % 60 === 0)) { state.player = pl; state.tab = 'players'; T('player ' + pl, render); } state.player = null;
        for (const e of Object.keys(EDS).filter((e, i) => i % 400 === 0)) { T('edition ' + e, () => openEdition(e, false)); stopReplay(); }
        for (const k of Object.keys(LENSES)) { state.lens = k; state.tab = 'nations'; T('lens ' + k, render); } for (const k of Object.keys(PLENSES)) { state.plens = k; state.tab = 'players'; T('plens ' + k, render); } for (const k of Object.keys(HEATMETRICS)) { state.heat = k; state.tab = 'barcode'; T('heat ' + k, render); }
        state.tab = 'season'; render(); return out; });
    } else if (k === 'cricket') {
      info = await p.evaluate(() => ({ title: document.title, brand: document.querySelector('.brand')?.textContent.trim().slice(0, 40), bands: document.querySelectorAll('#riverSvg .band').length, grounds: document.querySelectorAll('#circuits .circ').length, seasons: S.length, matches: MATCHES.length, players: Object.keys(PLAYERS).length, detailed: MATCHES.filter(m => m.detail).length, readingOpen: document.querySelector('#reading').open, canonical: document.querySelector('link[rel=canonical]')?.href }));
      await p.screenshot({ path: `${SHOTS}/cricket-river.png` });
      for (const t of ['match', 'nations', 'players', 'grounds', 'records', 'barcode', 'duel']) { await p.click(`#tabs [data-tab="${t}"]`); await p.waitForTimeout(t === 'match' ? 2500 : 350); } await p.evaluate(() => document.querySelector('#stage').scrollIntoView()); await p.waitForTimeout(300); await p.screenshot({ path: `${SHOTS}/cricket-stage.png` });
      await p.click('#tabs [data-tab="match"]'); await p.waitForTimeout(2500); await p.evaluate(() => document.querySelector('#stage').scrollIntoView()); await p.screenshot({ path: `${SHOTS}/cricket-match.png` });
      const shard = await p.evaluate(() => ({ loaded: Object.keys(DETAILS).length, scorecard: document.querySelectorAll('details.inn').length, worms: document.querySelectorAll('.worm').length })); console.log(k, 'match sheet', JSON.stringify(shard)); if (!shard.scorecard) { bad++; console.log(k, 'NO SCORECARD RENDERED for the latest match'); }
      smoke = await p.evaluate(() => { const out = []; const T = (label, fn) => { try { fn(); } catch (x) { out.push(label + ': ' + x.message); } };
        for (const g of ['M', 'W']) for (const f of ['all', 'Test', 'ODI', 'T20I']) { state.gender = g; state.fmt = f; document.querySelector('#gender').value = g; document.querySelector('#format').value = f; state.era = 'all'; T(g + f + ' relens', () => relens(false)); T(g + f + ' river', () => { applyTheme(); drawRiver(); drawGrid(); });
          for (const s of S.filter((s, i) => i % (f === 'all' ? 1 : 3) === 0)) { state.year = s.year; state.whole = false; state.match = s.matches[0].id; for (const tab of ['season', 'match']) { state.tab = tab; T(g + f + ' ' + s.year + ' ' + tab, render); } stopReplay(); }
          for (const e of ERAS.map(e => e.id).concat(['all'])) { state.era = e; state.nation = null; state.player = null; state.ground = null; fillSeasons(); for (const tab of ['nations', 'players', 'grounds', 'records', 'barcode', 'duel']) { state.tab = tab; T(g + f + ' ' + e + ' ' + tab, render); } state.duelBy = 'p'; T(g + f + ' ' + e + ' duel players', render); state.duelBy = 'n'; state.whole = true; for (const tab of ['season', 'match']) { state.tab = tab; T(g + f + ' ' + e + ' whole ' + tab, render); } state.whole = false; }
          state.era = 'all'; fillSeasons(); }
        state.gender = 'M'; state.fmt = 'all'; document.querySelector('#gender').value = 'M'; document.querySelector('#format').value = 'all'; relens(false); state.era = 'all'; fillSeasons();
        for (const v of Object.keys(VENUES).filter((v, i) => i % 4 === 0)) { state.ground = v; state.tab = 'grounds'; T('ground ' + v, render); } state.ground = null;
        for (const n of Object.keys(TEAMS)) { state.nation = n; state.tab = 'nations'; T('nation ' + n, render); } state.nation = null;
        for (const pl of Object.keys(PLAYERS).filter((p, i) => i % 40 === 0)) { state.player = pl; state.tab = 'players'; T('player ' + pl, render); } state.player = null;
        for (const m of MATCHES.filter((m, i) => i % 150 === 0)) { T('match ' + m.id, () => openMatch(m.id, false)); stopReplay(); }
        for (const k of Object.keys(LENSES)) { state.lens = k; state.tab = 'nations'; T('lens ' + k, render); } for (const k of Object.keys(PLENSES)) { state.plens = k; state.tab = 'players'; T('plens ' + k, render); } for (const k of Object.keys(HEATMETRICS)) { state.heat = k; state.tab = 'barcode'; T('heat ' + k, render); }
        state.tab = 'season'; render(); return out; });
    } else { // rugby, same grammar as the motorsport pages
      info = await p.evaluate(() => ({ title: document.title, brand: document.querySelector('.brand')?.textContent.trim().slice(0, 40), bands: document.querySelectorAll('#riverSvg .band').length, grounds: document.querySelectorAll('#circuits .circ').length, seasons: S.length, matches: MATCHES.length, players: PLAYERS.length, coaches: COACHES.length, readingOpen: document.querySelector('#reading').open, canonical: document.querySelector('link[rel=canonical]')?.href }));
      await p.screenshot({ path: `${SHOTS}/rugby-river.png` });
      for (const t of ['match', 'nations', 'players', 'grounds', 'coaches', 'records', 'barcode', 'duel']) { await p.click(`#tabs [data-tab="${t}"]`); await p.waitForTimeout(t === 'match' ? 1200 : 350); } await p.evaluate(() => document.querySelector('#stage').scrollIntoView()); await p.waitForTimeout(300); await p.screenshot({ path: `${SHOTS}/rugby-stage.png` });
      await p.click('#tabs [data-tab="match"]'); await p.waitForTimeout(800); await p.evaluate(() => document.querySelector('#stage').scrollIntoView()); await p.screenshot({ path: `${SHOTS}/rugby-match.png` });
      smoke = await p.evaluate(() => { const out = []; const T = (label, fn) => { try { fn(); } catch (x) { out.push(label + ': ' + x.message); } };
        for (const s of S) { state.year = s.year; state.era = 'all'; state.whole = false; state.match = s.matches[0].id; for (const tab of ['season', 'match']) { state.tab = tab; T(s.year + ' ' + tab, render); } stopReplay(); }
        for (const e of ERAS.map(e => e.id).concat(['all'])) { state.era = e; state.nation = null; state.player = null; state.ground = null; state.coach = null; fillSeasons(); for (const tab of ['nations', 'players', 'grounds', 'coaches', 'records', 'barcode', 'duel']) { state.tab = tab; T(e + ' ' + tab, render); } state.duelBy = 'p'; T(e + ' duel players', render); state.duelBy = 'n'; state.whole = true; for (const tab of ['season', 'match']) { state.tab = tab; T(e + ' whole ' + tab, render); } state.whole = false; drawRiver(); drawGrid(); }
        state.era = 'all'; fillSeasons(); for (const g of Object.keys(GROUNDS)) { state.ground = g; state.tab = 'grounds'; T('ground ' + g, render); } state.ground = null;
        for (const n of new Set(MATCHES.flatMap(m => [m.home, m.away]))) { state.nation = n; state.tab = 'nations'; T('nation ' + n, render); } state.nation = null;
        for (const pl of PLAYERS.filter((p, i) => i % 5 === 0)) { state.player = pl.id; state.tab = 'players'; T('player ' + pl.id, render); } state.player = null;
        for (const c of COACHES) { state.coach = c.id; state.tab = 'coaches'; T('coach ' + c.id, render); } state.coach = null;
        for (const m of MATCHES.filter((m, i) => i % 40 === 0)) { T('match ' + m.id, () => openMatch(m.id, false)); stopReplay(); }
        for (const k of Object.keys(LENSES)) { state.lens = k; state.tab = 'nations'; T('lens ' + k, render); } for (const k of Object.keys(HEATMETRICS)) { state.heat = k; state.tab = 'barcode'; T('heat ' + k, render); }
        state.tab = 'season'; render(); return out; });
    }
    console.log(k, 'load', ms + 'ms', JSON.stringify(info)); if (smoke.length || errs.length) { bad++; console.log(k, 'SMOKE', JSON.stringify(smoke.slice(0, 8)), 'ERRORS', JSON.stringify(errs.slice(0, 5))); } else console.log(k, 'smoke clean, no errors');
    await ctx.close();
    // phone
    const m = await open(b, k, { viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
    const mob = await m.p.evaluate(() => [document.documentElement.scrollWidth, innerWidth]); await m.p.screenshot({ path: `${SHOTS}/${k}-phone.png` }); if (mob[0] > mob[1] + 1 || mob[1] > 391 || m.errs.length) { bad++; console.log(k, 'PHONE overflow/errors', mob, m.errs.slice(0, 3)); } else console.log(k, 'phone ok', mob); await m.ctx.close();
  }
  // the offline editions still open from disk
  for (const f of require('fs').readdirSync(path.join(DOCS, 'downloads')).filter(f => f.endsWith('.html') && f !== 'index.html')) { const ctx = await b.newContext({ viewport: { width: 1200, height: 800 } }); const p = await ctx.newPage(); const errs = []; p.on('pageerror', e => errs.push(e.message)); await p.goto('file://' + path.join(DOCS, 'downloads', f), { waitUntil: 'load', timeout: 180000 }); await p.waitForTimeout(800); const ok = await p.evaluate(() => typeof state !== 'undefined' && document.querySelectorAll('#riverSvg .band').length > 0); if (!ok || errs.length) { bad++; console.log(f, 'OFFLINE FAILED', errs.slice(0, 2)); } else console.log(f, 'offline edition ok'); await ctx.close(); }
  await b.close(); server.kill(); console.log(bad ? `FAIL (${bad})` : 'ALL CLEAN'); process.exit(bad ? 1 : 0); })();
