/* ---------- the Courts (the Grid): tournaments listed, in the colour of their surface ---------- */
function courtModel(){const eds=eraEditions().filter(e=>!e.team&&e.level!=='D');const m={};
  const mk=(t,y)=>m[t]||(m[t]={cid:t,years:new Set(),first:y,last:y,surf:{},name:TOURN[t]?.n||t,place:(TOURN[t]?.city||'').split(' · ')[0],major:!!TOURN[t]?.major,level:{}});
  for(const e of eds){const c=mk(e.t,e.y);c.years.add(e.y);c.first=Math.min(c.first,e.y);c.last=Math.max(c.last,e.y);c.surf[e.surface]=(c.surf[e.surface]||0)+1;c.level[e.level]=(c.level[e.level]||0)+1;}
  const [y0,y1]=eraRange();const wins={};for(const c of CHAMPS){if(!inLens(c.c)||c.y<y0||c.y>y1)continue;if(!m[c.t]&&!(TOURN[c.t]?.major||EDS[c.id]))continue;const t=mk(c.t,c.y);t.years.add(c.y);t.first=Math.min(t.first,c.y);t.last=Math.max(t.last,c.y);if(!EDS[c.id]&&TOURN[c.t]?.s)t.surf[TOURN[c.t].s]=(t.surf[TOURN[c.t].s]||0)+1;const w=wins[c.t]||(wins[c.t]={});for(const p of c.w)w[p]=(w[p]||0)+1;}
  return Object.values(m).map(c=>{const s=Object.entries(c.surf).sort((a,b)=>b[1]-a[1])[0]?.[0]||TOURN[c.cid]?.s||'Unknown';const top=Object.entries(wins[c.cid]||{}).sort((a,b)=>b[1]-a[1])[0]||null;const lv=Object.entries(c.level).sort((a,b)=>b[1]-a[1])[0]?.[0]||(c.major?'G':'A');return {...c,count:c.years.size,surface:s,top:top?top[0]:null,topN:top?top[1]:0,lv,rank:LEVEL_RANK[lv]||0};});}
function drawGrid(){const list=courtModel();const q=state.gridFind.trim().toLowerCase();const team=eraEditions().filter(e=>e.team||e.level==='D').length;let shown=list.filter(c=>(q||c.count>=state.gridMin||c.major)&&(!q||(c.name+' '+c.place).toLowerCase().includes(q)));
  const sorters={count:(a,b)=>(b.major-a.major)||b.count-a.count||b.rank-a.rank||a.name.localeCompare(b.name),name:(a,b)=>a.name.localeCompare(b.name),surface:(a,b)=>a.surface.localeCompare(b.surface)||b.count-a.count,recent:(a,b)=>b.last-a.last||b.count-a.count,level:(a,b)=>b.rank-a.rank||b.count-a.count};shown.sort(sorters[state.gridSort]);
  const bigN=state.gridSort==='count'&&!q?Math.min(6,shown.filter(c=>c.major).length||4):0;
  $('#gridLede').textContent=`${list.length} tournaments in ${eraLabel().replace(' · ',', ')}${team?` (plus ${team.toLocaleString('en')} team ties, kept off the grid)`:''}. Each carries the colour of its surface and names the player who has won it most; the majors lead, then the events the tour has returned to most often.${shown.length<list.length&&!q?` Showing ${shown.length} with ${state.gridMin}+ editions.`:''}`;
  $('#circuits').innerHTML=shown.map((c,i)=>`<button type="button" class="circ flat${i<bigN?' big':''}" data-cid="${esc(c.cid)}" style="--team:${surfColor(c.surface)}" title="${esc(c.name)} · ${c.count} editions · ${c.first}–${c.last}${c.top?' · most titles: '+esc(pname(c.top))+' '+c.topN:''}"><span class="ct">${esc(c.place||'')}${c.place?' · ':''}${esc(c.surface)}${c.major?' · major':''}</span><span class="n">${c.count}</span><span class="nm">${esc(c.name)}</span><span class="yrs">${c.first}${c.last!==c.first?'–'+c.last:''}${c.top?' · <i style="background:'+pcolor(c.top)+'"></i>'+esc(pname(c.top))+' '+c.topN:''}</span></button>`).join('')||`<p class="muted">No tournament matches.</p>`;}

/* ---------- Stage: tabs, era strip, era context ---------- */
const TABS=[['season','Season'],['draw','Draw'],['players','Players'],['nations','Nations'],['tournaments','Tournaments'],['records','Records'],['barcode','Barcode'],['duel','Duel']];
function drawTabs(){$('#tabs').innerHTML=TABS.map(([id,l])=>`<button type="button" role="tab" data-tab="${id}" aria-pressed="${state.tab===id}">${l}</button>`).join('');
  $('#stageStatus').textContent=(state.tab==='season'||state.tab==='draw')&&!state.whole?`${state.year} · ${eraOf(state.year)?.name||''} · ${lensLabel()}`:eraLabel();}
function drawEraStrip(preview){const strip=$('#eraStrip');if(!strip.children.length)strip.innerHTML=ERAS.map(e=>`<button type="button" style="--w:${e.to-e.from+1}" data-era="${e.id}" title="${esc(e.name)} · ${e.from}–${e.to}" aria-label="${esc(e.name)} ${e.from}–${e.to}"></button>`).join('');
  for(const b of strip.children){b.classList.toggle('on',state.era===b.dataset.era);b.classList.toggle('demo',preview===b.dataset.era);}
  const e=preview?ERAS.find(x=>x.id===preview):state.era==='all'?eraOf(state.year):ERAS.find(x=>x.id===state.era);
  $('#eraCaption').innerHTML=`<span><b>${esc(e.name)}</b> · ${e.from}–${e.to}</span><span class="dim">${state.era===e.id?'Lens on · click again to release':'Click a segment to focus the whole page on that era'}</span>`;
  const ctx=$('#eraContext');ctx.innerHTML=`<div class="era-car">${e.ball.svg}</div><div><p class="eyebrow">${state.era===e.id?'Era lens':preview?'Era':'Era of the selected season'} · ${e.from}–${e.to}</p><h3>${esc(e.name)}</h3><p>${esc(e.text)}</p><div class="chips">${e.ball.features.map(f=>`<span>${esc(f)}</span>`).join('')}</div><p class="small dim" style="margin:10px 0 0">${esc(e.ball.label)} · an editorial reading of the period; the archive itself is not divided</p></div>`;}
const tour={i:-1,timer:null,visible:false,stopped:RM};
function tourStep(){if(tour.stopped||!tour.visible)return;tour.i=(tour.i+1)%ERAS.length;const ctx=$('#eraContext');ctx.classList.add('swap');setTimeout(()=>{if(tour.stopped)return;drawEraStrip(ERAS[tour.i].id);ctx.classList.remove('swap');},260);tour.timer=setTimeout(tourStep,4200);}
function tourStart(){if(tour.stopped||tour.timer)return;tour.timer=setTimeout(tourStep,1800);}
function tourPause(){clearTimeout(tour.timer);tour.timer=null;}
function tourStop(){if(tour.stopped)return;tour.stopped=true;tourPause();$('#eraContext').classList.remove('swap');drawEraStrip();}

/* ---------- shared pieces ---------- */
const champOfEd=id=>CHAMPS.find(c=>c.id===id||c.m===id);
const edName=e=>TOURN[e.t]?.n||e.name;
const pl=id=>`<a href="#" data-player="${esc(id)}" style="color:inherit">${esc(pname(id))}</a>`;
const pls=ids=>(ids||[]).map(pl).join(' / ');
const flag=id=>`<i class="dot" style="--c:${pcolor(id)}"></i>`;
function edCard(e,on){const c=champOfEd(e.id);const w=c?c.w[0]:null;return `<button type="button" class="cal${on?' on':''}" data-edition="${esc(e.id)}" style="--team:${surfColor(e.surface)}"><div class="rd">${esc(dm(e.date))} · ${esc(levelName(e.level))}${e.draw?' · '+e.draw:''}</div><div class="sc"><span>${esc(e.surface)}</span></div><div class="nm">${esc(edName(e))}</div><div class="w">${c?'<i class="dot" style="--c:'+pcolor(w)+'"></i>'+esc(pnames(c.w))+(c.l.length?' d. '+esc(pnames(c.l)):''):e.n?e.n+' matches':'no result recorded'}</div></button>`;}
function natBars(rows,valOf,subOf,max,unit=''){return `<div class="board">${rows.map((a,i)=>`<button type="button" class="bar" data-nation="${esc(a.id)}" style="--i:${i};${teamVar(a.id)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(natName(a.id))}<small> ${a.t} titles · ${a.mj} majors</small></span><small>${subOf(a)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*valOf(a)/(max||1))}%"></span></span></span><span class="val">${valOf(a)}${unit}</span></button>`).join('')}</div>`;}
function playerBars(rows,valOf,subOf,max,unit=''){return `<div class="board">${rows.map((a,i)=>`<button type="button" class="bar" data-player="${esc(a.id)}" style="--i:${i};--team:${pcolor(a.id)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(a.id))}<small> ${esc(natName(pnat(a.id)))}</small></span><small>${subOf(a)}</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*valOf(a)/(max||1))}%"></span></span></span><span class="val">${valOf(a)}${unit}</span></button>`).join('')}</div>`;}
function drawChart(el,series,n,labelOf,xl,colorOf){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(200,box.height);const padL=34,padR=130,padT=14,padB=26;const max=Math.max(1,...series.flatMap(s=>s.pts));const x=i=>padL+(n?i*(W-padL-padR)/n:0),y=v=>padT+(H-padT-padB)*(1-v/max);
  let g='';const step=max>200?100:max>60?25:max>20?10:max>8?5:1;for(let v=0;v<=max;v+=step)g+=`<line class="gridl" x1="${padL}" x2="${W-padR}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}"/><text class="lb" x="${padL-6}" y="${(y(v)+3).toFixed(1)}" text-anchor="end">${v}</text>`;
  for(let i=0;i<n;i++){const l=xl(i);if(l)g+=`<text class="lb" x="${x(i+1).toFixed(1)}" y="${H-8}" text-anchor="middle">${esc(l)}</text>`;}
  const paths=series.map(s=>{const d=s.pts.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1)).join('');const last=s.pts[s.pts.length-1];return `<path class="ser" d="${d}" style="--c:${colorOf(s.id)}"><title>${esc(labelOf(s.id))} · ${fmt(last)}</title></path><text class="end" x="${(x(n)+6).toFixed(1)}" y="${(y(last)+4).toFixed(1)}" style="--c:${colorOf(s.id)}">${esc(labelOf(s.id))} ${fmt(last)}</text>`;}).join('');
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Cumulative chart">${g}${paths}</svg>`;}
const age=(dob,date)=>{if(!dob||!date||dob.length<8)return null;const y=+dob.slice(0,4),m=+dob.slice(4,6),d=+dob.slice(6,8);const Y=+date.slice(0,4),M=+date.slice(5,7),D=+date.slice(8,10);let a=Y-y;if(M<m||(M===m&&D<d))a--;return a;};

/* ---------- Season ---------- */
function seasonView(){if(state.whole)return eraView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No season in this lens.</p>';return;}
  const {best,ranked,majors}=champOf(s);const partial=String(s.year)===(A.lastDate||'').slice(0,4);const eds=s.editions.filter(e=>!e.team&&e.level!=='D');const team=s.editions.length-eds.length;
  const podium=ranked.slice(0,3);const order=[podium[1],podium[0],podium[2]];
  const head=`<div class="season-head"><div class="champ-card" style="${best?`--accent:${pcolor(best.id)};--on-accent:${onColor(pcolor(best.id))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${partial?'Season in progress · results through '+esc(day(A.lastDate)):'Most titles of the year'} · ${esc(lensLabel())}</p><div class="yr">${s.year}</div>${best?`<div class="who"><small>${partial?'Leads the year':'Most titles'} · ${best.t} title${best.t===1?'':'s'}${best.mj?' · '+best.mj+' major'+(best.mj===1?'':'s'):''}</small><a href="#" data-player="${esc(best.id)}" style="color:inherit;text-decoration:none">${esc(pname(best.id))}</a></div><div class="team"><i></i>${esc(natName(pnat(best.id)))}</div><div class="facts"><div><b>${best.w}–${best.l||0}</b>matches</div><div><b>${best.f}</b>finals</div><div><b>${s.titles.length}</b>titles this year</div><div><b>${eds.length}</b>tournaments</div></div>`:`<div class="who"><small>No titles recorded</small>—</div>`}
  ${majors.map(m=>`<p class="small" style="margin:14px 0 0;color:var(--ink);opacity:.85">${esc(TOURN[m.t]?.n||m.t)}: <b>${esc(pnames(m.w))}</b>${m.l.length?' d. '+esc(pnames(m.l)):''}${m.s?' · '+esc(m.s):''}</p>`).join('')}<p class="small dim" style="margin:${majors.length?6:18}px 0 0">Ranked by titles, then majors, then finals, then match wins; a reading of the roll of honour, not an official award.</p></div>
  <div><div class="podium">${order.map((d,i)=>d?`<button type="button" class="step p${podium.indexOf(d)+1} bar" data-player="${esc(d.id)}" style="--h:${Math.round(120+120*Math.min(1,d.t/Math.max(1,podium[0].t)))}px;--team:${pcolor(d.id)};display:flex"><span class="pos">${podium.indexOf(d)+1}</span><span class="nm">${esc(pname(d.id))}</span><span class="pt">${d.t} title${d.t===1?'':'s'} · ${d.mj} major${d.mj===1?'':'s'} · ${d.w}–${d.l||0}</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const cal=eds.length?`<div class="h3"><span>The year’s tournaments</span><small>${eds.length} events${team?' · '+team+' team ties not shown':''} · click one to open its draw</small></div><div class="calendar">${eds.map(e=>edCard(e,state.edition===e.id&&state.tab==='draw')).join('')}</div>`:`<div class="h3"><span>The year’s titles</span><small>from Wimbledon’s own records · full draws from 1968</small></div><div class="calendar">${s.titles.map(c=>`<button type="button" class="cal" data-tourn="${esc(c.t)}" style="--team:${surfColor(TOURN[c.t]?.s||'Unknown')}"><div class="rd">${c.y} · ${esc(c.c)}</div><div class="sc"><span>${esc(TOURN[c.t]?.s||'')}</span></div><div class="nm">${esc(TOURN[c.t]?.n||c.t)}</div><div class="w"><i class="dot" style="--c:${pcolor(c.w[0])}"></i>${esc(pnames(c.w))}${c.l.length?' d. '+esc(pnames(c.l)):''}</div></button>`).join('')}</div>`;
  // table of the year by nation, and the race for titles among the top players
  const nat={};for(const c of s.titles){for(const p of c.w){const n=pnat(p);const a=nat[n]||(nat[n]={id:n,t:0,mj:0,f:0,w:0,l:0});a.t+=1/c.w.length;if(MAJORS.includes(c.t))a.mj+=1/c.w.length;}}
  for(const r of PS){if(r.y!==s.year||!inLens(r.c))continue;const n=pnat(r.p);const a=nat[n]||(nat[n]={id:n,t:0,mj:0,f:0,w:0,l:0});a.w+=r.w;a.l+=r.l;}
  const table=Object.values(nat).map(a=>({...a,t:Math.round(a.t),mj:Math.round(a.mj)})).sort((a,b)=>b.t-a.t||b.mj-a.mj||b.w-a.w).slice(0,20);
  const top6=ranked.slice(0,6).map(p=>p.id);const dated=s.titles.filter(c=>EDS[c.id]).map(c=>({d:EDS[c.id].date,w:c.w}));dated.sort((a,b)=>a.d<b.d?-1:1);
  const race=top6.length&&dated.length?`<div class="h3" style="margin-top:26px"><span>The race for titles</span><small>cumulative titles of the year’s top six, by tournament date</small></div><div class="chart" id="seasonChart"></div>`:'';
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Table of the year</span><small>nations by titles, then majors</small></div>${natBars(table,a=>a.t,a=>`${a.w}–${a.l} in matches`,Math.max(1,...table.map(a=>a.t)))}</div><div class="panel"><div class="h3"><span>Finals of the year</span><small>${s.titles.length} titles · the biggest first</small></div><div class="board">${[...s.titles].sort((a,b)=>(LEVEL_RANK[EDS[b.id]?.level||'G']||0)-(LEVEL_RANK[EDS[a.id]?.level||'G']||0)||((EDS[a.id]?.date||'')<(EDS[b.id]?.date||'')?-1:1)).slice(0,14).map((c,i)=>`<button type="button" class="bar" data-edition="${esc(c.id)}" style="--i:${i};--team:${pcolor(c.w[0])}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pnames(c.w))}<small> d. ${esc(pnames(c.l))||'—'}</small></span><small>${esc(TOURN[c.t]?.n||c.t)} · ${esc(EDS[c.id]?.surface||TOURN[c.t]?.s||'')}${c.s?' · '+esc(c.s):''}</small></span></span><span class="val" style="font-size:12px">${esc(levelName(EDS[c.id]?.level||'G'))}</span></button>`).join('')}</div></div></div>`;
  $('#view').innerHTML=head+cal+race+body;
  if(race){const n=dated.length;const series=top6.map(id=>{let c=0;const pts=[0];for(const d of dated){if(d.w.includes(id))c++;pts.push(c);}return {id,pts};});const months=dated.map(d=>d.d.slice(5,7));drawChart($('#seasonChart'),series,n,pname,i=>{const m=months[i];return i===0||months[i-1]!==m?new Date(2000,+m-1,1).toLocaleDateString('en-GB',{month:'short'}):'';},pcolor);}}
function eraView(){const ss=eraSeasons();const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);const titles=eraTitles();const eds=eraEditions().filter(x=>!x.team&&x.level!=='D');
  const players=playerAgg().sort(playerOrder);const top=players[0];const nations=natAgg().sort((a,b)=>b.t-a.t||b.mj-a.mj).slice(0,12);
  const head=`<div class="season-head"><div class="champ-card" style="${top?`--accent:${pcolor(top.id)};--on-accent:${onColor(pcolor(top.id))}`:''}"><p class="eyebrow" style="color:var(--ink);opacity:.7">${e?'Whole era':'All seasons'} · ${esc(lensLabel())}</p><div class="yr" style="font-size:clamp(44px,6vw,84px)">${ss[0]?.year}–${ss[ss.length-1]?.year}</div>${top?`<div class="who"><small>Most titles across the period · ${top.t} titles · ${top.mj} majors</small><a href="#" data-player="${esc(top.id)}" style="color:inherit;text-decoration:none">${esc(pname(top.id))}</a></div><div class="team"><i></i>${esc(natName(pnat(top.id)))}</div>`:''}<div class="facts"><div><b>${fmt(titles.length)}</b>titles</div><div><b>${fmt(eds.length)}</b>tournaments</div><div><b>${ss.length}</b>seasons</div><div><b>${fmt(players.length)}</b>players</div></div></div>
  <div><div class="podium">${[players[1],players[0],players[2]].map((d,i)=>d?`<button type="button" class="step p${players.indexOf(d)+1} bar" data-player="${esc(d.id)}" style="--h:${Math.round(120+120*d.t/Math.max(1,players[0].t))}px;--team:${pcolor(d.id)};display:flex"><span class="pos">${players.indexOf(d)+1}</span><span class="nm">${esc(pname(d.id))}</span><span class="pt">${d.t} titles · ${d.mj} majors</span></button>`:'<div></div>').join('')}<div class="base"></div></div></div></div>`;
  const roll=ss.map(s=>({s,c:champOf(s)}));
  const rollHtml=`<div class="h3"><span>Most titles, year by year</span><small>click a year to open it</small></div><div class="calendar">${roll.map(({s,c})=>`<button type="button" class="cal" data-year="${s.year}" style="--team:${c.best?pcolor(c.best.id):'#5b616b'}"><div class="rd">${s.year}</div><div class="nm">${c.best?esc(pname(c.best.id)):'—'}</div><div class="w">${c.best?c.best.t+' title'+(c.best.t===1?'':'s')+(c.best.mj?' · '+c.best.mj+' major'+(c.best.mj===1?'':'s'):''):''}</div></button>`).join('')}</div>`;
  const body=`<div class="two" style="margin-top:26px"><div class="panel"><div class="h3"><span>Nations across the period</span><small>by titles</small></div>${natBars(nations,a=>a.t,a=>`${a.np} players · ${a.nw} title winners`,Math.max(1,...nations.map(a=>a.t)))}</div><div class="panel"><div class="h3"><span>Players across the period</span><small>by titles, then majors</small></div>${playerBars(players.slice(0,12),a=>a.t,a=>`${a.mj} majors · ${a.f} finals · ${a.w}–${a.l}`,Math.max(1,...players.slice(0,12).map(a=>a.t)))}</div></div>`;
  $('#view').innerHTML=head+rollHtml+body;}
