/* ---------- the matches of a season: embedded offline, fetched per year on the site ---------- */
let replay=null;
function stopReplay(){if(replay){clearTimeout(replay.timer);replay=null;}}
let loading={};
function loadDetails(year){if(DETAILS[year])return Promise.resolve(DETAILS[year]);if(!DETAIL_URL)return Promise.resolve(null);if(loading[year])return loading[year];
  return loading[year]=fetch(DETAIL_URL+year+'.json').then(r=>r.ok?r.json():null).then(d=>{if(d)DETAILS[year]=d;delete loading[year];return d;}).catch(()=>{delete loading[year];return null;});}
const matchRows=(year,eid)=>(DETAILS[year]?.[eid]||[]).map(r=>unpack(MF,r));
const ROUNDS=['R128','R64','R32','R16','QF','SF','F','RR','BR','ER'];
const roundName={R128:'First round · 128',R64:'Round of 64',R32:'Round of 32',R16:'Round of 16',QF:'Quarter-finals',SF:'Semi-finals',F:'Final',RR:'Round robin',BR:'Bronze match',ER:'Early round'};
const seedOf=s=>s?String(s).replace(/^(\d+)$/,'[$1]'):'';
function defaultEdition(s){const eds=s.editions.filter(e=>!e.team&&e.level!=='D');if(!eds.length)return null;const mj=eds.filter(e=>MAJORS.includes(e.t));if(mj.length)return mj[mj.length-1].id;return [...eds].sort((a,b)=>(LEVEL_RANK[b.level]||0)-(LEVEL_RANK[a.level]||0)||(a.date<b.date?1:-1))[0].id;}
function matchLine(m,champ){const w=m.w,l=m.l;const on=state.match===m.id;const path=champ&&w.some(p=>champ.includes(p));return `<button type="button" class="bm${on?' on':''}${path?' path':''}" data-match="${esc(m.id)}"><span class="p w"><i class="dot" style="--c:${pcolor(w[0])}"></i><span>${esc(pnames(w))}</span><small>${esc(seedOf(m.ws))}</small></span><span class="p l"><i class="dot" style="--c:${pcolor(l[0])}"></i><span>${esc(pnames(l))}</span><small>${esc(seedOf(m.ls))}</small></span><span class="s">${esc(m.s||'—')}</span></button>`;}
function drawView(){if(state.whole)return eraDrawsView();const s=byYear[state.year];if(!s){$('#view').innerHTML='<p class="muted">No season in this lens.</p>';return;}
  const eds=s.editions.filter(e=>!e.team&&e.level!=='D');let e=EDS[state.edition];if(!e||e.y!==s.year||!inLens(e.c)||e.team){state.edition=defaultEdition(s);e=EDS[state.edition];}
  if(!e){const titles=s.titles;$('#view').innerHTML=`<div class="panel"><div class="h3"><span>${s.year} · the roll of honour</span><small>full draws exist from 1968; before that Wimbledon’s own records give the champions</small></div><div class="board">${titles.map((c,i)=>`<button type="button" class="bar" data-tourn="${esc(c.t)}" style="--i:${i};--team:${pcolor(c.w[0])}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pnames(c.w))}<small> d. ${esc(pnames(c.l))||'—'}</small></span><small>${esc(TOURN[c.t]?.n||c.t)} · ${esc(c.c)}${c.s?' · '+esc(c.s):''}</small></span></span></button>`).join('')||'<p class="muted">No titles in this lens.</p>'}</div></div>`;return;}
  const many=eds.length>36;const nav=`<div class="chiplist${many?' many':''}" id="matchNav" style="margin-top:20px">${eds.map(x=>`<button type="button" class="chip${x.id===e.id?' on':''}" data-edition="${esc(x.id)}" style="${x.id===e.id?'border-color:var(--accent);color:var(--accent)':''}"><i style="--c:${surfColor(x.surface)}"></i>${esc(dm(x.date))} ${esc(edName(x)).slice(0,26)}${MAJORS.includes(x.t)?' ★':''}</button>`).join('')}</div>`;
  const c=champOfEd(e.id);const t=TOURN[e.t]||{};const rows=matchRows(s.year,e.id);const champ=c?c.w:null;
  const head=`<div class="card" style="margin-top:18px;grid-template-columns:1fr;--team:${surfColor(e.surface)}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:18px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">${esc(levelName(e.level))} · ${esc(e.surface)} · ${esc(day(e.date))}${e.draw?' · draw of '+e.draw:''} · ${esc(e.c==='MS'?'ATP singles':e.c==='WS'?'WTA singles':e.c==='MD'?'ATP doubles':'WTA doubles')}</p><h2 style="margin:6px 0 0"><a href="#" data-tourn="${esc(e.t)}" style="color:inherit;text-decoration:none">${esc(edName(e))}</a> <span class="muted" style="font-size:.6em;font-weight:600;font-style:normal">${esc((t.city||'').split(' · ')[0])}</span></h2></div>${c?`<div class="champline" style="--team:${pcolor(c.w[0])}"><span class="eyebrow">Champion</span><b>${pls(c.w)}</b><span class="small muted">d. ${pls(c.l)||'—'}${c.s?' · '+esc(c.s):''}</span></div>`:'<div class="champline"><span class="eyebrow">Champion</span><b class="muted">not recorded</b></div>'}</div></div>`;
  let bracket='';
  if(!rows.length){bracket=`<p class="muted" style="margin-top:18px">${DETAIL_URL&&!DETAILS[s.year]?'Loading the matches of '+s.year+'…':'No match records for this edition; the roll of honour above is what the archive holds.'}</p>`;}
  else{const byR={};for(const m of rows)(byR[m.r]||(byR[m.r]=[])).push(m);for(const r in byR)byR[r].sort((a,b)=>(a.n||0)-(b.n||0));
    const present=ROUNDS.filter(r=>byR[r]);const cols=present.filter(r=>!['RR','BR','ER'].includes(r)&&byR[r].length<=16);const early=present.filter(r=>!cols.includes(r)&&!['RR','BR','ER'].includes(r));
    const rr=byR.RR?`<details class="round" open><summary>${roundName.RR} · ${byR.RR.length} matches</summary><div class="bmlist">${byR.RR.map(m=>matchLine(m,champ)).join('')}</div></details>`:'';
    const earlyHtml=early.map(r=>`<details class="round"><summary>${roundName[r]||r} · ${byR[r].length} matches${champ&&byR[r].some(m=>m.w.some(p=>champ.includes(p)))?' · <span style="color:var(--accent)">the champion’s match is marked</span>':''}</summary><div class="bmlist">${byR[r].map(m=>matchLine(m,champ)).join('')}</div></details>`).join('');
    const colsHtml=cols.length?`<div class="bracket" id="bracket" style="--cols:${cols.length}">${cols.map((r,k)=>`<div class="bcol" style="--i:${k}"><div class="bhead">${esc(roundName[r]||r)}<small>${byR[r].length}</small></div>${byR[r].map(m=>matchLine(m,champ)).join('')}</div>`).join('')}${byR.BR?`<div class="bcol" style="--i:${cols.length}"><div class="bhead">${roundName.BR}</div>${byR.BR.map(m=>matchLine(m,champ)).join('')}</div>`:''}</div>`:'';
    bracket=`<div class="h3" style="margin-top:22px"><span>The draw</span><small>${rows.length} matches · the champion’s path is lit · <button type="button" class="linkbtn" id="replayDraw">replay the build</button></small></div>${rr}${earlyHtml}${colsHtml}`;}
  let sheet='';const m=rows.find(x=>x.id===state.match)||(rows.length?byR_final(rows):null);if(m){state.match=m.id;sheet=matchSheet(m,e);}
  $('#view').innerHTML=nav+head+bracket+sheet;
  {const on=$('#matchNav .chip.on');if(on&&many){const nv=$('#matchNav');nv.scrollTop=Math.max(0,on.offsetTop-nv.clientHeight/2+on.offsetHeight/2);}}
  const rb=$('#replayDraw');if(rb)rb.onclick=()=>{const b=$('#bracket');if(!b)return;b.classList.remove('build');void b.offsetWidth;b.classList.add('build');};
  if($('#bracket')&&!RM)$('#bracket').classList.add('build');
  if(!rows.length&&DETAIL_URL&&!DETAILS[s.year]){loadDetails(s.year).then(()=>{if(state.tab==='draw'&&state.year===s.year)render();});}}
function byR_final(rows){return rows.find(x=>x.r==='F')||rows[rows.length-1];}
const statRow=(l,a,b,fa,fb)=>`<tr><td class="n">${a==null?'—':esc(fa??a)}</td><td class="lab">${l}</td><td class="n">${b==null?'—':esc(fb??b)}</td></tr>`;
function matchSheet(m,e){const w=m.w,l=m.l;const st=m.st;const S=A.statFields||[];const get=(row,k)=>{if(!st||!st[row])return null;const i=S.indexOf(k);return i<0?null:st[row][i];};
  const pc=(a,b)=>a!=null&&b?Math.round(100*a/b)+'%':null;
  const rows=st?[statRow('Aces',get(0,'ace'),get(1,'ace')),statRow('Double faults',get(0,'df'),get(1,'df')),statRow('Service points',get(0,'svpt'),get(1,'svpt')),statRow('First serves in',pc(get(0,'1stIn'),get(0,'svpt')),pc(get(1,'1stIn'),get(1,'svpt'))),statRow('First-serve points won',pc(get(0,'1stWon'),get(0,'1stIn')),pc(get(1,'1stWon'),get(1,'1stIn'))),statRow('Second-serve points won',pc(get(0,'2ndWon'),get(0,'svpt')!=null&&get(0,'1stIn')!=null?get(0,'svpt')-get(0,'1stIn'):null),pc(get(1,'2ndWon'),get(1,'svpt')!=null&&get(1,'1stIn')!=null?get(1,'svpt')-get(1,'1stIn'):null)),statRow('Service games',get(0,'SvGms'),get(1,'SvGms')),statRow('Break points saved',get(0,'bpSaved')!=null?`${get(0,'bpSaved')}/${get(0,'bpFaced')}`:null,get(1,'bpSaved')!=null?`${get(1,'bpSaved')}/${get(1,'bpFaced')}`:null),statRow('Break points converted',get(1,'bpFaced')!=null?`${get(1,'bpFaced')-get(1,'bpSaved')}/${get(1,'bpFaced')}`:null,get(0,'bpFaced')!=null?`${get(0,'bpFaced')-get(0,'bpSaved')}/${get(0,'bpFaced')}`:null)].join(''):'';
  const sets=(m.s||'').split(' ').filter(x=>/\d/.test(x));const setsHtml=sets.map(x=>{const mm=/^(\d+)-(\d+)(?:\((\d+)\))?/.exec(x);if(!mm)return `<span class="set"><b>${esc(x)}</b></span>`;const a=+mm[1],b=+mm[2];return `<span class="set${a>b?' won':' lost'}"><b>${a}</b><b>${b}</b>${mm[3]?`<small>${mm[3]}</small>`:''}</span>`;}).join('');
  return `<div class="card sheet" style="margin-top:22px;grid-template-columns:1fr;--team:${pcolor(w[0])}"><div class="panel"><p class="eyebrow">${esc(roundName[m.r]||m.r)} · ${esc(edName(e))} ${e.y} · ${esc(e.surface)}${m.bo?' · best of '+m.bo:''}${m.mins?' · '+m.mins+' minutes':''}${/RET|W\/O|DEF/i.test(m.s||'')?' · '+(/W\/O/i.test(m.s)?'walkover':/DEF/i.test(m.s)?'default':'retirement'):''}</p>
  <div class="sheet-heads"><div class="who w" style="--team:${pcolor(w[0])}"><small>${esc(natName(pnat(w[0])))}${m.wr?' · rank '+m.wr:''}${m.ws?' · seed '+esc(m.ws):''}</small><b>${pls(w)}</b></div><div class="score">${setsHtml||'<b>'+esc(m.s||'—')+'</b>'}</div><div class="who l" style="--team:${pcolor(l[0])}"><small>${esc(natName(pnat(l[0])))}${m.lr?' · rank '+m.lr:''}${m.ls?' · seed '+esc(m.ls):''}</small><b>${pls(l)}</b></div></div>
  ${rows?`<div class="tablewrap" style="max-height:none;margin-top:14px"><table class="stats"><tr><th class="n">${esc(pname(w[0]))}</th><th></th><th class="n">${esc(pname(l[0]))}</th></tr>${rows}</table></div>`:'<p class="small dim" style="margin:12px 0 0">No serve statistics recorded for this match; the tour’s match statistics begin in 1991 and are patchy before the 2000s.</p>'}
  ${w.length===1&&l.length===1?`<p class="small muted" style="margin:12px 0 0"><a href="#" data-duel="${esc(w[0])}|${esc(l[0])}">Open the head-to-head →</a></p>`:''}</div></div>`;}
function eraDrawsView(){const ss=eraSeasons();const titles=eraTitles().filter(c=>MAJORS.includes(c.t)||LEVEL_RANK[EDS[c.id]?.level||'G']>=5);const byT={};for(const c of titles)(byT[c.t]||(byT[c.t]=[])).push(c);
  const order=Object.keys(byT).sort((a,b)=>(TOURN[b]?.major?1:0)-(TOURN[a]?.major?1:0)||byT[b].length-byT[a].length);
  $('#view').innerHTML=`<div class="h3" style="margin-top:20px"><span>The biggest titles across the period</span><small>majors, Tour Finals and the Olympic tournament · click a year to open its draw</small></div>${order.map(t=>`<div class="panel" style="margin-top:14px"><div class="h3"><span>${esc(TOURN[t]?.n||t)}</span><small>${byT[t].length} editions · ${esc(TOURN[t]?.s||'')}</small></div><div class="chiplist">${byT[t].map(c=>`<button type="button" class="chip" data-edition="${esc(c.id)}" data-year="${c.y}"><i style="--c:${pcolor(c.w[0])}"></i>${c.y} ${esc(pnames(c.w))}</button>`).join('')}</div></div>`).join('')||'<p class="muted">No titles in this lens.</p>'}`;}

/* ---------- Players ---------- */
function playersView(){const list=playerAgg();const lens=state.plens;let rows=list.filter(p=>p[lens]!=null);if(lens==='rate')rows=rows.filter(p=>p.p>=100);rows.sort((a,b)=>b[lens]-a[lens]||b.t-a.t||b.w-a.w);rows=rows.slice(0,40);
  const max=Math.max(1,...rows.map(a=>a[lens]));const q=(state.find2||'').toLowerCase();const found=q?Object.entries(PLAYERS).filter(([id,p])=>p.n.toLowerCase().includes(q)).slice(0,14):[];
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Players · ${esc(eraLabel())}</h2></div><div class="small mono muted">${fmt(list.length)} players</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><input type="search" id="find2" placeholder="Search a player" value="${esc(state.find2||'')}" aria-label="Search"><select id="lens" aria-label="Lens">${Object.entries(PLENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(PLENSES[lens][1])}</span></div>${q?`<div class="chiplist" style="margin-bottom:14px">${found.map(([id,p])=>`<button type="button" class="chip" data-player="${esc(id)}"><i style="--c:${pcolor(id)}"></i>${esc(p.n)} <span class="dim">${esc(p.ioc||'')}</span></button>`).join('')||'<span class="muted small">No match.</span>'}</div>`:''}
  ${playerBars(rows,a=>a[lens],a=>`${a.first}–${a.last} · ${a.t} titles · ${a.mj} majors · ${a.w}–${a.l}`,max,/rate/.test(lens)?'%':'')}</div>`;
  $('#find2').addEventListener('input',e=>{state.find2=e.target.value;playersView();$('#find2').focus();const v=$('#find2');v.setSelectionRange(v.value.length,v.value.length);});$('#lens').addEventListener('change',e=>{state.plens=e.target.value;render();});}
function playerView(id){const p=PLAYERS[id];if(!p){playersView();return;}const all=playerAgg();const a=all.find(x=>x.id===id)||{id,w:0,l:0,t:0,f:0,mj:0,hw:0,hl:0,cw:0,cl:0,gw:0,gl:0,iw:0,il:0,first:null,last:null,p:0,rate:0};
  const rank=[...all].sort(playerOrder).findIndex(x=>x.id===id)+1;const [y0,y1]=eraRange();
  const titles=CHAMPS.filter(c=>c.w.includes(id)&&inLens(c.c)&&c.y>=y0&&c.y<=y1).sort((a,b)=>b.y-a.y||((EDS[a.id]?.date||'')<(EDS[b.id]?.date||'')?1:-1));const finalsLost=CHAMPS.filter(c=>c.l.includes(id)&&inLens(c.c)&&c.y>=y0&&c.y<=y1);
  const rows=psRows().filter(r=>r.p===id).sort((a,b)=>b.y-a.y||a.c.localeCompare(b.c));
  const majorsBy={};for(const c of titles)if(MAJORS.includes(c.t))majorsBy[c.t]=(majorsBy[c.t]||0)+1;
  const rivals=(RIVALS[id]||[]).slice(0,6);
  const surf=[['Hard',a.hw,a.hl],['Clay',a.cw,a.cl],['Grass',a.gw,a.gl],['Carpet & other',a.iw,a.il]].filter(x=>x[1]+x[2]>0);
  const born=p.dob&&p.dob.length>=8?`${p.dob.slice(6,8)}/${p.dob.slice(4,6)}/${p.dob.slice(0,4)}`:p.dob&&p.dob.length>=4?p.dob.slice(0,4):null;
  const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b>${s?`<small>${s}</small>`:''}</div>`;
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${pcolor(id)}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Player · ${esc(natName(p.ioc))}${p.hand?' · '+(p.hand==='L'?'left-handed':p.hand==='R'?'right-handed':'')+'':''}${p.height?' · '+p.height+' cm':''}${born?' · born '+esc(born):''}${a.first?' · '+a.first+'–'+a.last:''}</p><h2 style="margin:6px 0 0"><i class="dot" style="--c:${pcolor(id)};width:.5em;height:.5em;vertical-align:.1em;margin-right:8px"></i>${esc(p.n)}</h2></div>${rank?`<div class="small mono muted">#${rank} by titles in ${esc(eraLabel())}</div>`:''}</div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Titles',a.t,titles.length!==a.t?'':'in the lens')}${kpi('Majors',a.mj,Object.keys(majorsBy).length?Object.entries(majorsBy).map(([t,n])=>`${TOURN[t]?.n} ${n}`).join(' · '):'')}${kpi('Finals',a.f,`${finalsLost.length} lost`)}${kpi('Matches',`${a.w}–${a.l}`,a.p?a.rate+'% won':'no match records before 1968')}${kpi('Best year',a.bestY||'—',a.best?a.best+' titles':'')}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Titles</span><small>${titles.length} in the lens · click one to open its draw</small></div><div class="board">${titles.slice(0,60).map((c,i)=>`<button type="button" class="bar" data-edition="${esc(c.id)}" data-year="${c.y}" style="--i:${i};--team:${surfColor(EDS[c.id]?.surface||TOURN[c.t]?.s||'Unknown')}"><span class="rk">${titles.length-i}</span><span><span class="lab"><span>${esc(TOURN[c.t]?.n||c.t)}<small> ${c.y}${MAJORS.includes(c.t)?' · major':''}</small></span><small>d. ${esc(pnames(c.l))||'—'}${c.s?' · '+esc(c.s):''}${c.w.length>1?' · with '+esc(pnames(c.w.filter(x=>x!==id))):''}</small></span></span><span class="val" style="font-size:12px">${esc(EDS[c.id]?.surface||TOURN[c.t]?.s||'')}</span></button>`).join('')||'<p class="muted small">No titles in this lens.</p>'}${titles.length>60?`<p class="small dim">…and ${titles.length-60} more.</p>`:''}</div></div>
  <div><div class="panel"><div class="h3"><span>Rivals</span><small>most meetings, all years · head to head</small></div><div class="board">${rivals.map(([o,w,l],i)=>`<button type="button" class="bar" data-duel="${esc(id)}|${esc(o)}" style="--i:${i};--team:${pcolor(o)}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(o))}<small> ${esc(natName(pnat(o)))}</small></span><small>${w+l} meetings</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*w/Math.max(1,w+l))}%"></span></span></span><span class="val">${w}–${l}</span></button>`).join('')||'<p class="muted small">Fewer than three meetings with anyone on record.</p>'}</div></div>
  ${surf.length?`<div class="panel" style="margin-top:14px"><div class="h3"><span>By surface</span><small>matches won–lost</small></div><div class="board">${surf.map(([s,w,l],i)=>`<div class="bar" style="--i:${i};--team:${surfColor(s.split(' ')[0])}"><span class="rk"></span><span><span class="lab"><span>${s}</span><small>${pct(w,w+l)}% won</small></span><span class="trk"><span class="fill" style="--w:${Math.round(100*w/Math.max(1,w+l))}%"></span></span></span><span class="val">${w}–${l}</span></div>`).join('')}</div></div>`:''}</div></div>
  <div class="panel" style="margin-top:20px"><div class="h3"><span>Season by season</span><small>${rows.length} player-seasons in the lens</small></div><div class="tablewrap"><table><tr><th>Year</th><th>Draw</th><th class="n">W</th><th class="n">L</th><th class="n">Win %</th><th class="n">Titles</th><th class="n">Finals</th><th class="n">Majors</th><th class="n">Hard</th><th class="n">Clay</th><th class="n">Grass</th></tr>${rows.map(r=>`<tr><td><a href="#" data-year="${r.y}">${r.y}</a></td><td>${esc(r.c==='MS'?'ATP':r.c==='WS'?'WTA':r.c==='MD'?'ATP doubles':'WTA doubles')}</td><td class="n">${r.w}</td><td class="n">${r.l}</td><td class="n">${r.w+r.l?pct(r.w,r.w+r.l):'—'}</td><td class="n"><b>${r.t}</b></td><td class="n">${r.f}</td><td class="n">${r.mj}</td><td class="n">${r.hw}–${r.hl}</td><td class="n">${r.cw}–${r.cl}</td><td class="n">${r.gw}–${r.gl}</td></tr>`).join('')}</table></div></div>`;}
