/* ---------- Nations ---------- */
function nationsView(){const list=natAgg();const lens=state.lens;let rows=list.filter(a=>a.id&&a.id!=='UNK');if(lens==='rate')rows=rows.filter(a=>a.p>=200);rows.sort((a,b)=>b[lens]-a[lens]||b.t-a.t||b.w-a.w);rows=rows.slice(0,40);const max=Math.max(1,...rows.map(a=>a[lens]));
  const q=(state.find2||'').toLowerCase();const found=q?list.filter(a=>natName(a.id).toLowerCase().includes(q)||a.id.toLowerCase()===q).slice(0,12):[];
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Nations · ${esc(eraLabel())}</h2></div><div class="small mono muted">${list.length} nations</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><input type="search" id="find2" placeholder="Search a nation" value="${esc(state.find2||'')}" aria-label="Search"><select id="lens" aria-label="Lens">${Object.entries(LENSES).map(([k,v])=>`<option value="${k}" ${k===lens?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(LENSES[lens][1])}</span></div>${q?`<div class="chiplist" style="margin-bottom:14px">${found.map(a=>`<button type="button" class="chip" data-nation="${esc(a.id)}"><i style="--c:${natColor(a.id)}"></i>${esc(natName(a.id))}</button>`).join('')||'<span class="muted small">No match.</span>'}</div>`:''}
  ${natBars(rows,a=>a[lens],a=>`${a.np} players · ${a.first}–${a.last}`,max,/rate/.test(lens)?'%':'')}</div>`;
  $('#find2').addEventListener('input',e=>{state.find2=e.target.value;nationsView();$('#find2').focus();const v=$('#find2');v.setSelectionRange(v.value.length,v.value.length);});$('#lens').addEventListener('change',e=>{state.lens=e.target.value;render();});}
function nationView(id){const all=natAgg();const a=all.find(x=>x.id===id);if(!a){nationsView();return;}const rank=[...all].sort((x,y)=>y.t-x.t||y.mj-x.mj).findIndex(x=>x.id===id)+1;
  const players=playerAgg().filter(p=>p.nat===id).sort(playerOrder);const [y0,y1]=eraRange();const majors=CHAMPS.filter(c=>inLens(c.c)&&c.y>=y0&&c.y<=y1&&MAJORS.includes(c.t)&&c.w.some(p=>pnat(p)===id)).sort((x,y)=>y.y-x.y);
  const byYearT={};for(const r of psRows()){if(pnat(r.p)!==id)continue;const b=byYearT[r.y]||(byYearT[r.y]={y:r.y,t:0,w:0,l:0,mj:0});b.t+=r.t;b.w+=r.w;b.l+=r.l;b.mj+=r.mj;}
  const years=Object.values(byYearT).sort((x,y)=>x.y-y.y);const maxT=Math.max(1,...years.map(x=>x.t));
  const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b>${s?`<small>${s}</small>`:''}</div>`;
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${natColor(id)}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Nation · ${esc(id)} · ${a.first}–${a.last}</p><h2 style="margin:6px 0 0"><i class="dot" style="--c:${natColor(id)};width:.5em;height:.5em;vertical-align:.1em;margin-right:8px"></i>${esc(natName(id))}</h2></div><div class="small mono muted">#${rank} by titles in ${esc(eraLabel())}</div></div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Titles',fmt(a.t),`${a.nw} different winners`)}${kpi('Majors',a.mj,'')}${kpi('Finals',fmt(a.f),'')}${kpi('Matches',`${fmt(a.w)}–${fmt(a.l)}`,a.p?a.rate+'% won':'')}${kpi('Players',fmt(a.np),'in the lens')}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Players</span><small>by titles, then majors</small></div>${playerBars(players.slice(0,15),p=>p.t,p=>`${p.mj} majors · ${p.f} finals · ${p.w}–${p.l} · ${p.first}–${p.last}`,Math.max(1,...players.slice(0,15).map(p=>p.t)))}</div>
  <div><div class="panel"><div class="h3"><span>Titles by year</span><small>${years.length} seasons</small></div><div class="yearbars">${years.map(x=>`<button type="button" data-year="${x.y}" title="${x.y} · ${x.t} titles · ${x.w}–${x.l}" style="--h:${Math.round(100*x.t/maxT)}%;--team:${natColor(id)}"><i></i><span>${x.y%10===0?x.y:''}</span></button>`).join('')}</div></div>
  <div class="panel" style="margin-top:14px"><div class="h3"><span>Majors</span><small>${majors.length} titles</small></div><div class="board">${majors.slice(0,30).map((c,i)=>`<button type="button" class="bar" data-edition="${esc(c.id)}" data-year="${c.y}" style="--i:${i};--team:${pcolor(c.w[0])}"><span class="rk">${majors.length-i}</span><span><span class="lab"><span>${esc(pnames(c.w))}<small> ${esc(TOURN[c.t]?.n||c.t)} ${c.y}</small></span><small>d. ${esc(pnames(c.l))||'—'}${c.s?' · '+esc(c.s):''}</small></span></span></button>`).join('')||'<p class="muted small">No major titles in this lens.</p>'}</div></div></div></div>`;}

/* ---------- Tournaments ---------- */
function tournamentsView(){const list=courtModel().sort((a,b)=>(b.major-a.major)||b.count-a.count||a.name.localeCompare(b.name));const q=(state.find2||'').toLowerCase();const rows=q?list.filter(c=>(c.name+' '+c.place).toLowerCase().includes(q)):list;
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Tournaments · ${esc(eraLabel())}</h2></div><div class="small mono muted">${list.length} events</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><input type="search" id="find2" placeholder="Search a tournament or city" value="${esc(state.find2||'')}" aria-label="Search"></div><div class="tablewrap" style="max-height:640px"><table><tr><th>Tournament</th><th>City</th><th>Surface</th><th>Level</th><th class="n">Editions</th><th>Years</th><th>Most titles</th></tr>${rows.slice(0,400).map(c=>`<tr><td><a href="#" data-tourn="${esc(c.cid)}">${esc(c.name)}</a>${c.major?' <span class="dim">★</span>':''}</td><td>${esc(c.place)}</td><td><i class="dot" style="--c:${surfColor(c.surface)}"></i>${esc(c.surface)}</td><td>${esc(levelName(c.lv))}</td><td class="n">${c.count}</td><td>${c.first}–${c.last}</td><td>${c.top?flag(c.top)+' '+pl(c.top)+' <span class="dim">'+c.topN+'</span>':'—'}</td></tr>`).join('')}</table></div>${rows.length>400?`<p class="small dim">Showing 400 of ${rows.length}; search to narrow.</p>`:''}</div>`;
  $('#find2').addEventListener('input',e=>{state.find2=e.target.value;tournamentsView();$('#find2').focus();const v=$('#find2');v.setSelectionRange(v.value.length,v.value.length);});}
function tournamentView(id){const t=TOURN[id];if(!t){tournamentsView();return;}const [y0,y1]=eraRange();const eds=Object.values(EDS).filter(e=>e.t===id&&inLens(e.c)&&e.y>=y0&&e.y<=y1).sort((a,b)=>b.y-a.y||(a.date<b.date?1:-1));
  const roll=CHAMPS.filter(c=>c.t===id&&inLens(c.c)&&c.y>=y0&&c.y<=y1).sort((a,b)=>b.y-a.y||a.c.localeCompare(b.c));const wins={};for(const c of roll)for(const p of c.w)wins[p]=(wins[p]||0)+1;const top=Object.entries(wins).sort((a,b)=>b[1]-a[1]).slice(0,10);
  const surfs={};for(const e of eds)surfs[e.surface]=(surfs[e.surface]||0)+1;const surf=Object.entries(surfs).sort((a,b)=>b[1]-a[1]);const kpi=(k,v,s)=>`<div class="kpi"><span>${k}</span><b>${v}</b>${s?`<small>${s}</small>`:''}</div>`;
  const first=Math.min(...roll.map(c=>c.y),...eds.map(e=>e.y)),last=Math.max(...roll.map(c=>c.y),...eds.map(e=>e.y));
  $('#view').innerHTML=`<div class="card" style="margin-top:20px;grid-template-columns:1fr;--team:${surfColor(surf[0]?.[0]||t.s||'Unknown')}"><div class="panel" style="display:flex;flex-wrap:wrap;gap:20px;align-items:flex-end;justify-content:space-between"><div><p class="eyebrow">Tournament${t.major?' · major':''} · ${esc((t.city||'').split(' · ').join(', '))}${surf.length?' · '+surf.map(([s,n])=>esc(s)+(surf.length>1?' '+n:'')).join(', '):t.s?' · '+esc(t.s):''}</p><h2 style="margin:6px 0 0">${esc(t.n)}</h2></div>${t.url?`<a class="small mono" href="${esc(t.url)}" target="_blank" rel="noopener" style="color:var(--muted)">official site ↗</a>`:''}</div></div>
  <div class="kpis" style="margin-top:16px">${kpi('Editions',eds.length||roll.length,isFinite(first)?`${first}–${last}`:'')}${kpi('Titles recorded',roll.length,'in the lens')}${kpi('Most titles',top[0]?pname(top[0][0]):'—',top[0]?top[0][1]+' titles':'')}${kpi('Different champions',Object.keys(wins).length,'')}</div>
  <div class="two" style="margin-top:20px"><div class="panel"><div class="h3"><span>Roll of honour</span><small>${roll.length} titles · click a year to open its draw</small></div><div class="tablewrap" style="max-height:640px"><table><tr><th>Year</th><th>Draw</th><th>Champion</th><th>Runner-up</th><th>Score</th></tr>${roll.map(c=>`<tr><td>${EDS[c.id]?`<a href="#" data-edition="${esc(c.id)}" data-year="${c.y}">${c.y}</a>`:c.y}</td><td>${esc(c.c==='MS'?'ATP':c.c==='WS'?'WTA':c.c==='MD'?'ATP doubles':c.c==='WD'?'WTA doubles':c.c)}</td><td>${(c.w||[]).map(p=>flag(p)+' '+pl(p)).join(' / ')}</td><td>${(c.l||[]).map(p=>pl(p)).join(' / ')||'—'}</td><td class="mono small">${esc(c.s||'')}</td></tr>`).join('')}</table></div></div>
  <div class="panel"><div class="h3"><span>Most titles here</span></div>${playerBars(top.map(([id,n])=>({id,n})),a=>a.n,a=>`${roll.filter(c=>c.w.includes(a.id)).map(c=>c.y).sort().join(', ')}`,top[0]?top[0][1]:1)}</div></div>`;}

/* ---------- Records ---------- */
function recordsView(){const players=playerAgg();const nations=natAgg().filter(a=>a.id&&a.id!=='UNK');const [y0,y1]=eraRange();const titles=eraTitles();const eds=eraEditions().filter(e=>!e.team&&e.level!=='D');const matches=eraSeasons().reduce((a,s)=>a+s.matches,0);
  const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b><small>${s}</small></div>`;const rc=(k,l)=>[...players].filter(p=>k==='rate'?p.p>=100:true).sort((a,b)=>b[k]-a[k]||b.t-a.t).slice(0,10);
  const board=(title,rows,k,unit='')=>`<div class="panel"><div class="h3"><span>${title}</span></div>${playerBars(rows,a=>a[k],a=>`${a.first}–${a.last} · ${a.t} titles · ${a.mj} majors`,Math.max(1,...rows.map(a=>a[k])),unit)}</div>`;
  const recs=[];for(const c of circs()){const R=RECORDS[c]||{};for(const k in R)for(const r of R[k])if(r[2]>=y0&&r[2]<=y1)recs.push({k,c,r});}
  const rlist=(k,title,valOf,unit)=>{const rows=recs.filter(x=>x.k===k).sort((a,b)=>b.r[0]-a.r[0]).slice(0,8);return rows.length?`<div class="panel"><div class="h3"><span>${title}</span><small>${unit}</small></div><div class="board">${rows.map(({r},i)=>{const eid=r[1].replace(/:\d+$/,'');const e=EDS[eid];return `<button type="button" class="bar" data-edition="${esc(eid)}" data-match="${esc(r[1])}" data-year="${r[2]}" style="--i:${i};--team:${pcolor(k==='aces'?r[7]:r[3])}"><span class="rk">${i+1}</span><span><span class="lab"><span>${k==='aces'?esc(pname(r[7])):esc(pname(r[3]))+'<small> d. '+esc(pname(r[4]))+'</small>'}${k==='aces'?'<small> v '+esc(pname(r[7]===r[3]?r[4]:r[3]))+'</small>':''}</span><small>${esc(e?edName(e):eid)} ${r[2]} · ${esc(roundName[r[6]]||r[6])}${k==='upsets'?' · rank '+r[7]+' beat rank '+r[8]:''} · ${esc(r[5])}</small></span></span><span class="val">${valOf(r)}</span></button>`;}).join('')}</div></div>`:'';};
  const mj=CHAMPS.filter(c=>inLens(c.c)&&c.y>=y0&&c.y<=y1&&MAJORS.includes(c.t)&&c.w.length===1&&PLAYERS[c.w[0]]?.dob).map(c=>({c,a:age(PLAYERS[c.w[0]].dob,EDS[c.id]?.date||c.y+'-07-01')})).filter(x=>x.a!=null);const young=[...mj].sort((a,b)=>a.a-b.a).slice(0,6),old=[...mj].sort((a,b)=>b.a-a.a).slice(0,6);
  const ages=(title,rows)=>rows.length?`<div class="panel"><div class="h3"><span>${title}</span><small>at the final, from recorded birth dates</small></div><div class="board">${rows.map(({c,a},i)=>`<button type="button" class="bar" data-edition="${esc(c.id)}" data-year="${c.y}" style="--i:${i};--team:${pcolor(c.w[0])}"><span class="rk">${i+1}</span><span><span class="lab"><span>${esc(pname(c.w[0]))}<small> ${esc(TOURN[c.t]?.n||c.t)} ${c.y}</small></span></span></span><span class="val">${a}</span></button>`).join('')}</div></div>`:'';
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Records · ${esc(eraLabel())}</h2></div><div class="small mono muted">${fmt(titles.length)} titles</div></div>
  <div class="kpis">${kpi('Titles',fmt(titles.length),`${fmt(eds.length)} tournaments`)}${kpi('Matches',fmt(matches),matches?'recorded from 1968':'no match records before 1968')}${kpi('Players',fmt(players.length),`${fmt(players.filter(p=>p.t).length)} won a title`)}${kpi('Nations',nations.length,`${nations.filter(n=>n.t).length} with a title`)}${kpi('Majors',fmt(titles.filter(c=>MAJORS.includes(c.t)).length),'')}</div>
  <div class="three" style="margin-top:20px">${board('Titles',rc('t'),'t')}${board('Majors',rc('mj'),'mj')}${board('Finals',rc('f'),'f')}</div>
  <div class="three" style="margin-top:14px">${board('Match wins',rc('w'),'w')}${board('Win rate · 100+ matches',rc('rate'),'rate','%')}<div class="panel"><div class="h3"><span>Nations by titles</span></div>${natBars([...nations].sort((a,b)=>b.t-a.t).slice(0,10),a=>a.t,a=>`${a.np} players`,Math.max(1,...nations.map(a=>a.t)))}</div></div>
  <div class="three" style="margin-top:14px">${rlist('longest','Longest matches',r=>Math.floor(r[0]/60)+'h '+String(r[0]%60).padStart(2,'0'),'recorded duration')}${rlist('aces','Most aces in a match',r=>r[0],'serve statistics from 1991')}${rlist('games','Most games in a match',r=>r[0],'games played')}</div>
  <div class="three" style="margin-top:14px">${rlist('upsets','Biggest upsets by ranking',r=>r[7],'winner’s rank · top-three seeds beaten')}${ages('Youngest major champions',young)}${ages('Oldest major champions',old)}</div>`;}

/* ---------- Barcode ---------- */
const HEATMETRICS={t:['Titles','Titles won by the nation’s players that year.'],mj:['Majors','Grand Slam titles that year.'],w:['Match wins','Matches won that year (from 1968).'],rate:['Win rate %','Wins divided by matches that year; blank below 20 matches.']};
function barcodeView(){const ss=eraSeasons();const years=ss.map(s=>s.year);const cell={};const tot={};
  for(const r of psRows()){const n=pnat(r.p);if(!n||n==='UNK')continue;const c=cell[n]||(cell[n]={});const k=c[r.y]||(c[r.y]={t:0,mj:0,w:0,l:0});k.t+=r.t;k.mj+=r.mj;k.w+=r.w;k.l+=r.l;tot[n]=(tot[n]||0)+(state.heat==='w'||state.heat==='rate'?r.w:state.heat==='mj'?r.mj:r.t);}
  const nations=Object.keys(cell).sort((a,b)=>tot[b]-tot[a]).slice(0,28);const val=k=>!k?0:state.heat==='rate'?(k.w+k.l>=20?pct(k.w,k.w+k.l):0):k[state.heat];const max=Math.max(1,...nations.flatMap(n=>years.map(y=>val(cell[n][y]))));
  $('#view').innerHTML=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Season barcode · ${esc(eraLabel())}</h2></div><div class="small mono muted">${nations.length} nations × ${years.length} seasons</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="heat" aria-label="Metric">${Object.entries(HEATMETRICS).map(([k,v])=>`<option value="${k}" ${k===state.heat?'selected':''}>${v[0]}</option>`).join('')}</select><span class="small muted">${esc(HEATMETRICS[state.heat][1])} Brightness is the cell’s share of the brightest cell; colour is the nation’s. Rows ordered by total.</span></div>
  <div class="barcode"><div class="bc-row"><span></span><span class="cells" style="gap:2px">${years.map(y=>`<i style="background:none;height:14px;font-size:8px;color:var(--dim);text-align:center;line-height:14px">${years.length<=30||y%10===0?String(y).slice(2):''}</i>`).join('')}</span><span></span></div>${nations.map(n=>`<div class="bc-row"><span class="lab" data-nation="${esc(n)}">${esc(natName(n))}</span><span class="cells">${years.map(y=>{const v=val(cell[n][y]);const a=v?Math.max(.12,v/max):0;return `<i data-year="${y}" title="${esc(natName(n))} ${y} · ${v}${state.heat==='rate'?'%':''}" style="--c:${mixHex(natColor(n),'#0f1113',a)}"></i>`;}).join('')}</span><span class="tot">${fmt(Math.round(tot[n]))}</span></div>`).join('')}</div></div>`;
  $('#heat').addEventListener('change',e=>{state.heat=e.target.value;render();});}

/* ---------- Duel ---------- */
function swingChart(el,pts,labA,labB,cA,cB){const box=el.getBoundingClientRect(),W=Math.max(300,box.width),H=Math.max(180,box.height);const padL=30,padR=30,padT=16,padB=22;const n=pts.length;const max=Math.max(1,...pts.map(p=>Math.abs(p.v)));const x=i=>padL+(n>1?i*(W-padL-padR)/(n-1):(W-padL-padR)/2),y=v=>padT+(H-padT-padB)*(1-(v+max)/(2*max));
  const mid=y(0);let d='';pts.forEach((p,i)=>{d+=(i?'L':'M')+x(i).toFixed(1)+' '+y(p.v).toFixed(1);});
  const dots=pts.map((p,i)=>`<circle class="pt" cx="${x(i).toFixed(1)}" cy="${y(p.v).toFixed(1)}" r="4" fill="${p.win==='A'?cA:cB}" data-edition="${esc(p.e||'')}" data-year="${p.y||''}" data-match="${esc(p.m||'')}"><title>${esc(p.label)}</title></circle>`).join('');
  el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Head-to-head swing"><line class="gridl" x1="${padL}" x2="${W-padR}" y1="${mid.toFixed(1)}" y2="${mid.toFixed(1)}"/><text class="lb" x="${padL}" y="${padT-4}" style="fill:${cA}">${esc(labA)} ahead</text><text class="lb" x="${padL}" y="${H-6}" style="fill:${cB}">${esc(labB)} ahead</text><path class="ser" d="${d}" style="--c:var(--muted)"/>${dots}</svg>`;}
let duelLoad=null;
function duelView(){const players=playerAgg().sort(playerOrder);const nations=natAgg().filter(a=>a.id&&a.id!=='UNK').sort((a,b)=>b.t-a.t);
  if(state.duelBy==='p'){const ids=players.slice(0,120).map(p=>p.id);if(!state.dA||!PLAYERS[state.dA]){let best=null;for(const id of ids.slice(0,20))for(const [o,w,l] of RIVALS[id]||[]){if(ids.includes(o)&&(!best||w+l>best.n))best={a:id,b:o,n:w+l};}state.dA=best?best.a:ids[0];state.dB=best?best.b:null;}if(!state.dB||!PLAYERS[state.dB]||state.dB===state.dA){const r=(RIVALS[state.dA]||[]).find(x=>PLAYERS[x[0]]);state.dB=r?r[0]:ids.find(i=>i!==state.dA);}}
  else{const ids=nations.slice(0,60).map(n=>n.id);if(!state.dA||!ids.includes(state.dA))state.dA=ids[0];if(!state.dB||!ids.includes(state.dB)||state.dB===state.dA)state.dB=ids.find(i=>i!==state.dA);}
  const opts=(sel)=>state.duelBy==='p'?[...new Set([state.dA,state.dB,...players.slice(0,120).map(p=>p.id)])].filter(Boolean).map(id=>`<option value="${esc(id)}" ${id===sel?'selected':''}>${esc(pname(id))}</option>`).join(''):nations.slice(0,60).map(n=>`<option value="${esc(n.id)}" ${n.id===sel?'selected':''}>${esc(natName(n.id))}</option>`).join('');
  const head=`<div class="sect-head" style="margin-top:22px"><div><h2 style="font-size:24px;margin:0">Head to head · ${esc(eraLabel())}</h2></div><div class="small mono muted">${state.duelBy==='p'?'players · every meeting on record':'nations · titles and wins in the lens'}</div></div><div class="panel"><div class="tools" style="margin-bottom:14px"><select id="duelBy" aria-label="Compare"><option value="p" ${state.duelBy==='p'?'selected':''}>Players</option><option value="n" ${state.duelBy==='n'?'selected':''}>Nations</option></select><select id="dA" aria-label="First">${opts(state.dA)}</select><span class="mono small muted">vs</span><select id="dB" aria-label="Second">${opts(state.dB)}</select></div><div id="duelBody"></div></div>`;
  $('#view').innerHTML=head;$('#duelBy').addEventListener('change',e=>{state.duelBy=e.target.value;state.dA=null;state.dB=null;render();});$('#dA').addEventListener('change',e=>{state.dA=e.target.value;render();});$('#dB').addEventListener('change',e=>{state.dB=e.target.value;render();});
  if(state.duelBy==='n')duelNations(nations);else duelPlayers();}
function duelNations(nations){const NA=nations.find(n=>n.id===state.dA),NB=nations.find(n=>n.id===state.dB);if(!NA||!NB){$('#duelBody').innerHTML='<p class="muted">Pick two nations.</p>';return;}const cA=natColor(NA.id),cB=natColor(NB.id);
  const by={};for(const r of psRows()){const n=pnat(r.p);if(n!==NA.id&&n!==NB.id)continue;const b=by[r.y]||(by[r.y]={y:r.y,a:0,b:0,aw:0,bw:0});if(n===NA.id){b.a+=r.t;b.aw+=r.w;}else{b.b+=r.t;b.bw+=r.w;}}
  const years=Object.values(by).sort((x,y)=>x.y-y.y);let lead=0;const pts=years.map(x=>{lead+=x.a-x.b;return {v:lead,win:x.a>=x.b?'A':'B',y:x.y,label:`${x.y} · ${natName(NA.id)} ${x.a} titles · ${natName(NB.id)} ${x.b} titles`};});
  const rowsK=[['Titles','t'],['Majors','mj'],['Finals','f'],['Match wins','w'],['Win rate %','rate'],['Players','np'],['Title winners','nw']];
  $('#duelBody').innerHTML=`<div class="duel-heads"><div class="dh" style="--team:${cA}"><span class="eyebrow">${esc(natName(NA.id))}</span><b>${fmt(NA.t)}</b><small>titles · ${NA.mj} majors</small></div><div class="dh" style="--team:${cB}"><span class="eyebrow">${esc(natName(NB.id))}</span><b>${fmt(NB.t)}</b><small>titles · ${NB.mj} majors</small></div></div><div class="h3" style="margin-top:18px"><span>The lead in titles, year by year</span><small>cumulative</small></div><div class="chart" id="duelSwing" style="height:220px"></div>
  <div class="tablewrap" style="margin-top:14px"><table><tr><th style="text-align:right;color:${cA}">${esc(natName(NA.id))}</th><th style="text-align:center"></th><th style="color:${cB}">${esc(natName(NB.id))}</th></tr>${rowsK.map(([l,k])=>{const va=NA[k],vb=NB[k];const m=Math.max(va,vb,1);return `<tr><td style="text-align:right"><span style="display:inline-block;height:8px;width:${Math.round(120*va/m)}px;background:${cA};border-radius:2px;vertical-align:middle;margin-right:8px"></span><b>${fmt(va)}${/rate/.test(k)?'%':''}</b></td><td style="text-align:center;color:var(--muted);font-size:10.5px;letter-spacing:.14em;text-transform:uppercase">${l}</td><td><b>${fmt(vb)}${/rate/.test(k)?'%':''}</b><span style="display:inline-block;height:8px;width:${Math.round(120*vb/m)}px;background:${cB};border-radius:2px;vertical-align:middle;margin-left:8px"></span></td></tr>`;}).join('')}</table></div>`;
  if(pts.length)swingChart($('#duelSwing'),pts,natName(NA.id),natName(NB.id),cA,cB);}
function duelPlayers(){const a=state.dA,b=state.dB;if(!a||!b){$('#duelBody').innerHTML='<p class="muted">Pick two players.</p>';return;}const cA=pcolor(a),cB=pcolor(b);
  const yearsA=new Set(PS.filter(r=>r.p===a).map(r=>r.y)),yearsB=new Set(PS.filter(r=>r.p===b).map(r=>r.y));const years=(A.matchYears||[]).filter(y=>yearsA.has(y)&&yearsB.has(y));const missing=years.filter(y=>!DETAILS[y]);
  const meetings=[];for(const y of years){const d=DETAILS[y];if(!d)continue;for(const eid in d){const e=EDS[eid];if(!e||!['MS','WS'].includes(e.c))continue;for(const row of d[eid]){const m=unpack(MF,row);if(m.w.length!==1||m.l.length!==1)continue;if((m.w[0]===a&&m.l[0]===b)||(m.w[0]===b&&m.l[0]===a))meetings.push({m,e});}}}
  meetings.sort((x,y)=>x.e.date<y.e.date?-1:x.e.date>y.e.date?1:(x.m.n||0)-(y.m.n||0));
  const wa=meetings.filter(x=>x.m.w[0]===a).length,wb=meetings.length-wa;const surf={};for(const x of meetings){const s=surf[x.e.surface]||(surf[x.e.surface]={a:0,b:0});if(x.m.w[0]===a)s.a++;else s.b++;}
  let lead=0;const pts=meetings.map(x=>{lead+=x.m.w[0]===a?1:-1;return {v:lead,win:x.m.w[0]===a?'A':'B',e:x.e.id,y:x.e.y,m:x.m.id,label:`${edName(x.e)} ${x.e.y} · ${roundName[x.m.r]||x.m.r} · ${pname(x.m.w[0])} ${x.m.s}`};});
  const status=missing.length?`<p class="small muted" id="duelStatus">Loading the seasons the two shared · ${years.length-missing.length} of ${years.length}…</p>`:'';
  $('#duelBody').innerHTML=`<div class="duel-heads"><div class="dh" style="--team:${cA}"><span class="eyebrow">${esc(natName(pnat(a)))}</span><b>${wa}</b><small>${pl(a)} · wins in ${meetings.length} meetings</small></div><div class="dh" style="--team:${cB}"><span class="eyebrow">${esc(natName(pnat(b)))}</span><b>${wb}</b><small>${pl(b)}</small></div></div>${status}
  ${meetings.length?`<div class="h3" style="margin-top:18px"><span>The rivalry, match by match</span><small>cumulative lead · click a point to open the match</small></div><div class="chart" id="duelSwing" style="height:220px"></div><div class="chiplist" style="margin-top:12px">${Object.entries(surf).map(([s,v])=>`<span class="chip" style="cursor:default"><i style="--c:${surfColor(s)}"></i>${esc(s)} ${v.a}–${v.b}</span>`).join('')}</div>
  <div class="tablewrap" style="margin-top:14px;max-height:520px"><table><tr><th>Year</th><th>Tournament</th><th>Round</th><th>Surface</th><th>Winner</th><th>Score</th></tr>${[...meetings].reverse().map(({m,e})=>`<tr><td><a href="#" data-edition="${esc(e.id)}" data-year="${e.y}" data-match="${esc(m.id)}">${e.y}</a></td><td>${esc(edName(e))}</td><td>${esc(roundName[m.r]||m.r)}</td><td><i class="dot" style="--c:${surfColor(e.surface)}"></i>${esc(e.surface)}</td><td style="color:${m.w[0]===a?cA:cB}"><b>${esc(pname(m.w[0]))}</b></td><td class="mono small">${esc(m.s||'')}</td></tr>`).join('')}</table></div>`:missing.length?'':'<p class="muted small" style="margin-top:14px">No tour-level meetings on record between these two.</p>'}`;
  if(pts.length)swingChart($('#duelSwing'),pts,pname(a),pname(b),cA,cB);
  if(missing.length&&DETAIL_URL){const token=duelLoad={a,b};(async()=>{let k=years.length-missing.length;for(const y of missing){if(duelLoad!==token||state.tab!=='duel')return;await loadDetails(y);k++;const st=$('#duelStatus');if(st)st.textContent=`Loading the seasons the two shared · ${k} of ${years.length}…`;}if(duelLoad===token&&state.tab==='duel'&&state.dA===a&&state.dB===b)duelPlayers();})();}}

/* ---------- Sources & coverage ---------- */
function drawSources(){const kpi=(t,v,s)=>`<div class="kpi"><span>${t}</span><b>${v}</b><small>${s}</small></div>`;const cov=A.coverage||{};const scope=cov.scope||[];
  $('#sourcesBody').innerHTML=`<p class="eyebrow">Tour edition / ${esc(day(A.snapshot))}</p><h2>Every title, every match of the Open era, one archive.</h2><div class="kpis">${kpi('Matches',fmt(cov.matches),'tour-level, 1968 on')}${kpi('Titles',fmt(cov.titles),'majors from 1877')}${kpi('Players',fmt(cov.players),'')}${kpi('Tournaments',fmt(cov.tournaments),`${fmt(cov.editions)} editions`)}${kpi('With statistics',fmt(cov.statistics),'serve statistics, 1991 on')}${kpi('Latest event',esc(day(A.lastDate)),'snapshot '+esc(day(A.snapshot)))}</div>
<h3>Sources</h3><ol><li><a href="https://github.com/JeffSackmann" target="_blank" rel="noopener">Jeff Sackmann / Tennis Abstract</a> (<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>)<p>The tour-level match results of the ATP and WTA from 1968 (${scope.map(s=>`${s.c==='MS'?'ATP singles':s.c==='WS'?'WTA singles':s.c==='MD'?'ATP doubles':s.c==='WD'?'WTA doubles':s.c} ${s.start||'—'}–${s.end||'—'}, ${fmt(s.matches)} matches`).join('; ')}), with seedings, rankings, durations and serve statistics where recorded. Source commit ${esc((A.sourceCommit||'').slice(0,10))}. This atlas is non-commercial and shares alike.</p></li><li>Wimbledon’s own records<p>Champions and finalists before 1968 from the Wimbledon Compendium, the club’s published roll of honour from 1877 (singles from 1877 and 1884, doubles from 1884 and 1913), used as facts. The other majors’ rolls begin with the Open era in this archive.</p></li></ol>
<h3>How to read the statistics</h3><p class="small muted">A title is a tournament won at tour level as the source records it; team ties (Davis Cup, Billie Jean King Cup) are kept off the grid and out of the title counts. The River shares each year’s titles among the winners’ nations, a doubles title split between partners. “Most titles of the year” ranks by titles, then majors, then finals, then match wins; it is a reading of the roll of honour, not a ranking or an award. Match records begin with the Open era, so wins, win rates and head-to-heads are 1968 onward; serve statistics exist from 1991 and thinly before the 2000s. Win rate needs 100 matches for a player and 200 for a nation. Nationalities are as the source lists them today, so historical nations (the Soviet Union, Czechoslovakia, West Germany) appear only where the source keeps them. Ages are computed from recorded birth dates.</p>`;}

/* ---------- deep links ---------- */
let routeLock=false;
function writeRoute(){if(routeLock)return;const q=[];if(state.tour!=='M')q.push('tour='+state.tour);if(state.disc!=='S')q.push('draw=D');if(state.era!=='all')q.push('era='+encodeURIComponent(state.era));if(state.whole)q.push('whole=1');else q.push('season='+state.year);q.push('tab='+state.tab);if(state.tab==='draw'&&!state.whole&&state.edition)q.push('edition='+encodeURIComponent(state.edition));if(state.tab==='draw'&&!state.whole&&state.match)q.push('match='+encodeURIComponent(state.match));for(const k of ['nation','player','tourn']){if(state.tab===(k==='tourn'?'tournaments':k+'s')&&state[k])q.push(k+'='+encodeURIComponent(state[k]));}if(state.tab==='duel'&&state.dA&&state.dB)q.push('duel='+encodeURIComponent(state.dA+'|'+state.dB)+'&by='+state.duelBy);const h='#'+q.join('&');if(location.hash!==h){try{history.replaceState(null,'',h);}catch(e){}}}
function readRoute(){const h=location.hash.replace(/^#\/?/,'');if(!h||/^static-/.test(h))return false;const p={};for(const kv of h.split('&')){const i=kv.indexOf('=');p[i<0?kv:kv.slice(0,i)]=i<0?'1':decodeURIComponent(kv.slice(i+1));}let any=false;
  if(['M','W','all'].includes(p.tour)){state.tour=p.tour;any=true;}if(p.draw==='D'||p.draw==='S'){state.disc=p.draw;any=true;}rebuildSeasons();
  if(p.era&&(p.era==='all'||ERAS.some(e=>e.id===p.era))){state.era=p.era;any=true;}
  if(p.edition&&EDS[p.edition]){const e=EDS[p.edition];if(!inLens(e.c)){state.tour=e.c[0];state.disc=e.c[1];rebuildSeasons();}state.edition=p.edition;state.year=e.y;any=true;}else if(p.season&&byYear[+p.season]){state.year=+p.season;any=true;}
  if(p.match)state.match=p.match;
  if(state.era!=='all'&&!inEraYear(state.year)){if(p.season||p.edition)state.era='all';else state.year=eraSeasons().slice(-1)[0]?.year||state.year;}
  state.whole=p.whole==='1';if(state.whole)any=true;
  if(p.tab&&TABS.some(t=>t[0]===p.tab)){state.tab=p.tab;any=true;}
  state.nation=p.nation&&IOC[p.nation]!==undefined?p.nation:null;state.player=p.player&&PLAYERS[p.player]?p.player:null;state.tourn=p.tourn&&TOURN[p.tourn]?p.tourn:null;
  if(p.duel){const [a,b]=p.duel.split('|');state.duelBy=p.by==='n'?'n':'p';state.dA=a;state.dB=b;any=true;}
  return any;}

/* ---------- render, navigation, events ---------- */
function render(){stopReplay();drawTabs();if(tour.stopped||!tour.timer)drawEraStrip();const v={season:seasonView,draw:drawView,players:()=>state.player?playerView(state.player):playersView(),nations:()=>state.nation?nationView(state.nation):nationsView(),tournaments:()=>state.tourn?tournamentView(state.tourn):tournamentsView(),records:recordsView,barcode:barcodeView,duel:duelView}[state.tab];try{v();}catch(e){$('#view').innerHTML=`<p class="muted">Something in this view could not be drawn: ${esc(e.message)}</p>`;console.error(e);}writeRoute();}
function go(tab,scroll=true){state.tab=tab;render();if(scroll)$('#stage').scrollIntoView({behavior:RM?'auto':'smooth',block:'start'});}
function ensureYearInLens(y){if(state.era!=='all'&&!inEraYear(y)){state.era='all';$('#eraSelect').value='all';drawGrid();}}
function setSeason(y,scroll){state.whole=false;ensureYearInLens(y);state.year=y;state.edition=null;state.match=null;fillSeasons();applyTheme();drawRiver();if(state.tab!=='season'&&state.tab!=='draw')state.tab='season';go(state.tab,scroll);}
function openEdition(id,scroll,match){const e=EDS[id];if(!e)return;state.whole=false;if(!inLens(e.c)){state.tour=e.c[0];state.disc=e.c[1];$('#tour').value=state.tour;$('#disc').value=state.disc;relens(false);}ensureYearInLens(e.y);state.year=e.y;state.edition=id;state.match=match||null;fillSeasons();applyTheme();drawRiver();go('draw',scroll);}
function fillSeasons(){const sel=$('#season');const ss=eraSeasons();if(!ss.length){sel.innerHTML='';return;}const e=state.era==='all'?null:ERAS.find(x=>x.id===state.era);sel.innerHTML=`<option value="era">${e?'Whole era':'All seasons'} · ${ss[0].year}–${ss[ss.length-1].year}</option>`+ss.slice().reverse().map(s=>`<option value="${s.year}">${s.year}</option>`).join('');sel.value=state.whole?'era':state.year;}
function setEra(id){tourStop();state.era=id;$('#eraSelect').value=id;if(id!=='all'){if(!inEraYear(state.year)){const last=eraSeasons().slice(-1)[0];state.year=last?last.year:state.year;state.edition=null;state.match=null;}}fillSeasons();applyTheme();drawRiver();drawGrid();render();}
function relens(rerender=true){rebuildSeasons();if(!byYear[state.year])state.year=LAST_YEAR;state.edition=null;state.match=null;state.nation=null;state.player=null;state.tourn=null;fillSeasons();$('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.filter(e=>e.to>=FIRST_YEAR).map(e=>`<option value="${e.id}">${esc(ERA_SHORT[e.id]||e.name)} · ${e.from}–${e.to}</option>`).join('');$('#eraSelect').value=state.era;if(rerender){applyTheme();drawRiver();drawGrid();render();}}
function init(){
  rebuildSeasons();
  $('#eraSelect').innerHTML=`<option value="all">All eras · ${FIRST_YEAR}–${LAST_YEAR}</option>`+ERAS.map(e=>`<option value="${e.id}">${esc(ERA_SHORT[e.id]||e.name)} · ${e.from}–${e.to}</option>`).join('');
  const topNat=natAgg().sort((a,b)=>b.t-a.t).slice(0,16).map(n=>n.id);
  $('#theme').innerHTML=`<option value="champion">Champion’s colours</option><optgroup label="Surfaces">${Object.keys(SURF).filter(s=>s!=='Unknown').map(s=>`<option value="${s}">${s}</option>`).join('')}</optgroup><optgroup label="Nations">${topNat.map(n=>`<option value="${esc(n)}">${esc(natName(n))}</option>`).join('')}</optgroup>`;
  fillSeasons();
  const cov=A.coverage||{};
  $('#edition').innerHTML=`<span><span class="live"></span><b>${fmt(cov.titles||CHAMPS.length)}</b> titles through <b>${Math.max(...CHAMPS.map(c=>c.y))}</b></span><span><b>${fmt(cov.matches)}</b> matches through <b>${esc(day(A.lastDate))}</b></span><span><b>${fmt(cov.players)}</b> players</span><span><b>${fmt(cov.tournaments)}</b> tournaments</span>`;
  $('#reading').open=false;
  const deep=readRoute();if(deep){tourStop();$('#tour').value=state.tour;$('#disc').value=state.disc;$('#eraSelect').value=state.era;fillSeasons();}
  drawSources();applyTheme();drawRiver();drawGrid();render();lightsOut();if(deep&&(state.tab!=='season'||state.whole||state.era!=='all'))setTimeout(()=>$('#stage').scrollIntoView({behavior:'auto',block:'start'}),60);
  addEventListener('hashchange',()=>{if(/^#static-/.test(location.hash)){$('#reading').open=true;return;}routeLock=true;try{if(readRoute()){tourStop();$('#tour').value=state.tour;$('#disc').value=state.disc;$('#eraSelect').value=state.era;fillSeasons();applyTheme();drawRiver();drawGrid();render();}}finally{routeLock=false;}});
  $('#eraSelect').addEventListener('change',e=>setEra(e.target.value));
  $('#tour').addEventListener('change',e=>{state.tour=e.target.value;relens();});
  $('#disc').addEventListener('change',e=>{state.disc=e.target.value;relens();});
  $('#season').addEventListener('change',e=>{if(e.target.value==='era'){state.whole=true;applyTheme();drawRiver();if(state.tab!=='season'&&state.tab!=='draw')state.tab='season';go(state.tab,false);}else setSeason(+e.target.value,false);});
  $('#theme').addEventListener('change',applyTheme);
  $('#gridSort').addEventListener('change',e=>{state.gridSort=e.target.value;drawGrid();});
  $('#gridMin').addEventListener('change',e=>{state.gridMin=+e.target.value;drawGrid();});
  $('#gridFind').addEventListener('input',e=>{state.gridFind=e.target.value;drawGrid();});
  $('#eraStrip').addEventListener('click',e=>{const s=e.target.closest('[data-era]');if(s)setEra(state.era===s.dataset.era?'all':s.dataset.era);});
  $('#eraStrip').addEventListener('pointerenter',()=>{tourPause();},{passive:true});$('#eraStrip').addEventListener('pointerleave',()=>{if(!tour.stopped)tourStart();},{passive:true});
  $('#eraStrip').addEventListener('mouseover',e=>{const s=e.target.closest('[data-era]');if(s&&!tour.stopped){drawEraStrip(s.dataset.era);}});
  if('IntersectionObserver' in window){new IntersectionObserver(en=>{tour.visible=en[0].isIntersecting;if(tour.visible)tourStart();else tourPause();},{threshold:.2}).observe($('#eraStrip'));}else{tour.visible=true;tourStart();}
  $('#circuits').addEventListener('click',e=>{const b=e.target.closest('[data-cid]');if(b){state.tourn=b.dataset.cid;go('tournaments');}});
  const clear=t=>{if(t==='nations')state.nation=null;if(t==='players')state.player=null;if(t==='tournaments')state.tourn=null;};
  $('#tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;clear(b.dataset.tab);go(b.dataset.tab,false);});
  $('#view').addEventListener('click',e=>{const a=e.target.closest('[data-duel],[data-edition],[data-match],[data-nation],[data-player],[data-tourn],[data-year],[data-tab]');if(!a)return;if(a.tagName==='A')e.preventDefault();
    if(a.dataset.tab){clear(a.dataset.tab);go(a.dataset.tab,false);return;}
    if(a.dataset.duel){const [x,y]=a.dataset.duel.split('|');state.duelBy='p';state.dA=x;state.dB=y;go('duel',false);return;}
    if(a.dataset.edition&&EDS[a.dataset.edition]){openEdition(a.dataset.edition,false,a.dataset.match||null);return;}
    if(a.dataset.match&&state.tab==='draw'){state.match=a.dataset.match;render();return;}
    if(a.dataset.year){const y=+a.dataset.year;if(!byYear[y])return;ensureYearInLens(y);state.whole=false;state.year=y;state.edition=null;state.match=null;fillSeasons();applyTheme();drawRiver();go('season',false);return;}
    if(a.dataset.nation){state.nation=a.dataset.nation;go('nations',false);return;}
    if(a.dataset.player){state.player=a.dataset.player;go('players',false);return;}
    if(a.dataset.tourn){state.tourn=a.dataset.tourn;go('tournaments',false);return;}});
  addEventListener('resize',()=>{clearTimeout(window.__rz);window.__rz=setTimeout(()=>{drawRiver();if(['season','duel'].includes(state.tab))render();},150);});
}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
